### ISSUE TITLE
make sure Attester lookup failure doesn't affect WKD in task group

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1003]
As implemented now, if Attester call fails (server down), I think it would throw even if WKD call was successfully returning a key. For now that's not bothering me since primary customer has Attester disabled using the `disallow_attester_search_for_domains=[*]` rule. But it's something that should be addressed later.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1002#issuecomment-966950340_

**Comment by tomholub** [comment]
If a public key was found through any of the other methods (I suppose on iOS we only support WKD and Attester, so the other method here is WKD) then that error should be ignored.

If no public key was found on WKD, and there was an error looking up public key on Attester (other than 404), then that error should be surfaced to the user. I think we used to do it in the form of a red colored bubble for the recipient and a retry icon next to it, which should be already implemented.

**Comment by tomholub** [comment]
The logic used to be:

1) look up on WKD, and if there is any result, return it
2) (if nothing on wkd) look up on attester

Then we changed it to something like:
1) do the following two actions at the same time:
  - lookup on wkd
  - lookup on Attester
2) evaluate the results

It got faster with the refactor, but suddently if there was an error looking up on Attester, it started affecting otherwise successful lookips on WKD, which is a bug.

**Comment by ioanmo226** [comment]
Previous logic looks okay to me

**Comment by tomholub** [comment]
The problem is that the user has to wait too long with the previous logic. Most users don't run WKD, and it can sometimes take 8 seconds or more just to get a negative result from WKD, and another 7 seconds or so to get a negative result from Attester. That's 15 seconds of waiting instead of 8 if you parallelize.

**Comment by ioanmo226** [comment]
Ohh, i see
i thought lookup process takes about 1-2 seconds.

**Comment by tomholub** [comment]
These can be slow in some situations, unfortunately. Because we are calling a domain that may or may not be there (in case of WKD) depending on recipient, and sometimes the connection just hangs. We have a 4 (or 10?) second timeout. You can't tell these apart from just a slow connection.

For attester, a non-succesful search ends up searching several external servers which also takes a while.
