### ISSUE TITLE
highlight mixed or partial signatures

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1004]
Just realized - there is more than one kind of `.good` :-) TypeScript code for reference:

```ts
  if (verifyRes && verifyRes.match) {
    if (mixedSignatures) {
      verifyRes.mixed = true;
    }
    if (signedBlockCount > 0 && signedBlockCount != contentBlocks.length) {
      verifyRes.partial = true;
    }
  }
```

That means `VerifyRes` needs to be updated to also include `mixed: Bool?` and `partial: Bool?`. Plus this logic here, too. But that's for another issue, needs more thought. It won't be a difficult change once thought through.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/998#discussion_r748181487_

**Comment by tomholub** [comment]
Will need two more signature result statuses: `.partial` and `.goodMixed`

Then instead of `return .good`, do the following:

```swift
guard verifyRes.partial != true else { return .partial } // orange "Only partially signed"
guard verifyRes.mixed != true else { return .goodMixed }  // green "Signed with mixed keys"
return .good
```

**Comment by tomholub** [comment]
to reproduce `partial`: send inline-signed message but before the `-----BEGIN` header, add a few empty lines and some plain text

No need to reproduce / test mixed.

**Comment by ivan-ushakov** [comment]
> to reproduce `partial`: send inline-signed message but before the `-----BEGIN` header, add a few empty lines and some plain text

Does not work with browser extension. I tried this sample:
```
Received: from 717284730244
	named unknown
	by gmailapi.google.com
	with HTTPREST;
	Mon, 29 Nov 2021 10:28:55 -0800
Content-Type: multipart/mixed;
 boundary="----sinikael-?=_1-16382105347330.20105288288687007"
Openpgp: id=A54D82BE1521D20E
From: e2e enterprise test at FlowCrypt <EMAIL>
To: e2e enterprise test at FlowCrypt <EMAIL>
Subject: Partially signed only message
Date: Mon, 29 Nov 2021 10:28:55 -0800
Message-Id: <CAGKkJUZph_YDg1x4ZO9a=WHmdmZqAwzbVmhUk4=ne-kgPnCtBA@mail.gmail.com>
MIME-Version: 1.0

------sinikael-?=_1-16382105347330.20105288288687007
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Partially signed only message
-----BEGIN PGP SIGNATURE-----
Version: FlowCrypt Email Encryption 8.2.0
Comment: Seamlessly send and receive encrypted email

wnUEARYKAAYFAmGlG+YAIQkQpU2CvhUh0g4WIQQ4EA0h8XMm5EeGnaelTYK+
FSHSDmOWAP9D99Y1lOlNu0T4u5dlX5BRJBNnUozVfnOkhCcCEaLcrwD+Jbi6
fstza+lL18hSd7dftMf7PScM+4wRnDzL0Eb41Q0=3D
=3DJZeV
-----END PGP SIGNATURE-----

------sinikael-?=_1-16382105347330.20105288288687007--
```

When I add any text before `-----BEGIN PGP SIGNED MESSAGE-----` it still shows green signature.

**Comment by ivan-ushakov** [comment]
OK, looks like in iOS app it works right:

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-29 at 21 46 47](https://user-images.githubusercontent.com/1408366/143925173-93cd042c-033d-45ba-a2e8-c5db987456b0.png)

**Comment by tomholub** [comment]
On browser extension, it's different. There, the unsigned part will be outside of the green border. But on iOS, it's all lumped as one text, so we need a different badge on iOS. Looks good as I see it above.
