### ISSUE TITLE
optionally send API requests to a mock URL

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1012]
I understand we could probably do another build, to have eg enterprise/consumer/debug/mock builds where the mock build would have different URLs to call.

But that would mean we would have to build too apps for UI testing: both debug and mock if we want to test live as well as mocked version (which we do).

Is there a way to build one app but somehow toggle if it should use mock or live APIs? One idea is that the splash screen would have an actual toggle there, but that may make app code too complicated. Is there some way to run an app with parameters to one time tell it to use mock apis and other times not? (something like unix command line arguments)

**Comment by tomholub** [comment]
related to #1006

**Comment by sosnovsky** [comment]
We can send command-line arguments to iOS app using Appium `processArguments` capability:
```
app: join(process.cwd(), './FlowCrypt.app'),
processArguments: {'args': ['--mock']},
```

And then in the app it's possible to check which arguments were set there:
```swift
if CommandLine.arguments.contains("--mock") {
// use mock API
} else {
// use real API
}
```

**Comment by tomholub** [comment]
That's exactly it. Looks very doable. Thanks!

**Comment by tomholub** [comment]
@fcvakintos I can see `processArguments` mentioned here https://appium.io/docs/en/writing-running-appium/caps/

Can they be set to be different for each test spec? Can they be dynamic, generated during test runtime for a particular spec?
