### ISSUE TITLE
[needs confirmation] passphrase session is shared after logout

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#1013]
Please correct me if I'm wrong, this is all based on my testing case. (May needs confirmation)

Description:
I have tested out the FlowCrypt ios version and it seems like the passphrase session is persistent after a logout. This means that the app continues to show the message without any passphrase requirement for the other user who login next after the other.

FlowCrypt iOS version 0.4.0

Steps to reproduce:
User 1 - first user (first@gmail.com)
User 2 - second user (second@gmail.com)

Device 1 - a device where user 1 and user 2 log in.

1. Login on FlowCrypt ios app as user 1 => choose save passphrase **[not temporarily]**
2. Read an encrypted message => passphrase prompt will appear 
3. Enter passphrase for user 1
4. Go Back and Logout as user 1
5. Login as user 2 => choose to save passphrase **[temporarily]**
6. Read an encrypted message => passphrase will not be prompted (in my testing case; from which it should be prompted for a passphrase since it was the first attempt for user 2 to read/interact with an encrypted message)
7. user 2 is able to read encrypted messages without the initial passphrase requirement.

Conclusion:
Is it possible that user 1 passphrase session was used by user 2 causing the app to think the passphrase sessions are valid?

*Things are working properly if the app was closed in between Step #4.

**Comment by tomholub** [comment]
Even when you have no previous users on fresh new app, setting up with temporary pass phrase should cause messages to be readable without pass phrase prompt for up to 4 hours for that user (as entering pass phrase during setup also causes pass phrase to be remembered for now).

Can you confirm that?

**Comment by martgil** [comment]
Yes, @tomholub, I can confirm that. Thanks!

**Comment by martgil** [comment]
Thank you for your clarification. I'll be closing this one. Thanks again!
