### ISSUE TITLE
signed-only messages not recognized as signed + ui tests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1020]
> I want to test it with `flowcrypt.compatibility` account, as you mentioned there is an issue with signed but not encrypted messages. But as it's quite rare case we can leave it for another issue, is it okay?

I'll file another issue for it, not necessary to do now.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/998#issuecomment-969305108_

**Comment by tomholub** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/6306961/141853076-51325e35-d286-4572-b81f-400ff7e72005.png">

**Comment by tomholub** [comment]
This will also need ui tests for displaying:
1) signed+encrypted message
2) singed only message
3) signed only message with detached signature
4) plain message
5) signed-only message where the pubkey is not available
6) signed-only message that was tempered during transit

For this, please add six emails in e2e account with appropriate subject names, and test against that using Appium.

**Comment by tomholub** [comment]
Ivan - I'll give this to you so you can get familiar with message signing / verification. To create messages for ui tests, you should use the browser extension. The chevron next to the send button allows you to choose what kind of message to send.

**Comment by ivan-ushakov** [comment]
> 3. signed only message with detached signature
Can we do this in browser extension?

**Comment by tomholub** [comment]
Or you could copy them from `flowcrypt.compatiblity` account (do you have access?) into e2e account.

**Comment by ivan-ushakov** [comment]
> I think possibly not (or at least not spec complying ones), but you can send it that way from Thunderbird.

Will try this one

**Comment by ivan-ushakov** [comment]
How signed but not encrypted message looks like now:

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-23 at 20 45 35](https://user-images.githubusercontent.com/1408366/143077067-55256640-016a-4c9c-bd7a-450cd71b4f7b.png)

**Comment by ivan-ushakov** [comment]
Some other example, just to check that we are rendering them correctly:

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-23 at 20 52 12](https://user-images.githubusercontent.com/1408366/143078931-c31c2a4b-2b71-409e-a419-6b743c44475f.png)
![Simulator Screen Shot - iPhone 11 Pro - 2021-11-23 at 20 57 13](https://user-images.githubusercontent.com/1408366/143078939-c5b6fdfc-be3b-4c5d-9b74-1dc5e4956ae0.png)
![Simulator Screen Shot - iPhone 11 Pro - 2021-11-23 at 20 57 40](https://user-images.githubusercontent.com/1408366/143078947-d50d0201-b02b-4004-a16d-7c66e882702c.png)
![Simulator Screen Shot - iPhone 11 Pro - 2021-11-23 at 20 57 51](https://user-images.githubusercontent.com/1408366/143078951-fbee4f81-c183-4edb-837f-19cdfc9a7658.png)
![Simulator Screen Shot - iPhone 11 Pro - 2021-11-23 at 20 58 09](https://user-images.githubusercontent.com/1408366/143078954-fe1b68fd-6716-453a-8f27-1b29442aef5a.png)

**Comment by ivan-ushakov** [comment]
Looks like only this one is epson:

> 3. signed only message with detached signature

Unfortunately I can not setup Thunderbird mail client with my Gmail account.

**Comment by ivan-ushakov** [comment]
@tomholub do you want to have separate UI test for each case?

**Comment by tomholub** [comment]
> How signed but not encrypted message looks like now:
> 
> ![Simulator Screen Shot - iPhone 11 Pro - 2021-11-23 at 20 45 35](https://user-images.githubusercontent.com/1408366/143077067-55256640-016a-4c9c-bd7a-450cd71b4f7b.png)

This one is the most wrong. When it's "not signed" it's supposed to be red. When it's signed, it's supposed to be green. But here it's showing "not signed" in green - why the inconsistency? How come the text is not tightly tied to the color?

(plus, of course, it's supposed to be recognized as signed)

**Comment by tomholub** [comment]
The other screenshots look good.

**Comment by tomholub** [comment]
> Looks like only this one is epson:
> 
> > 3. signed only message with detached signature
> 
> Unfortunately I can not setup Thunderbird mail client with my Gmail account.

Can you be more specific - is it giving you any error?

**Comment by tomholub** [comment]
> @tomholub do you want to have separate UI test for each case?

Since we cannot parallelize tests yet (#1069) I think it takes less time overall to have fewer "large" tests than many small ones.

So please test all signature verification scenarios in one test.

And then in a separate test, you'll test all message decryption errors (in another issue/PR).

**Comment by ivan-ushakov** [comment]
> This one is the most wrong. When it's "not signed" it's supposed to be red. When it's signed, it's supposed to be green. But here it's showing "not signed" in green - why the inconsistency? How come the text is not tightly tied to the color?

If we have plain text message we need to mark it in red anyway?

**Comment by ivan-ushakov** [comment]
Also found that there is no way to check background color in Appium.

**Comment by ivan-ushakov** [comment]
> > Unfortunately I can not setup Thunderbird mail client with my Gmail account.
> 
> Can you be more specific - is it giving you any error?

Yes, it does not allow to login with third party email client until you change security setting in Google Account.

**Comment by ivan-ushakov** [comment]
I want to use `gpg` util for this cases:

1. signed only message with detached signature
2. signed-only message where the pubkey is not available
3. signed-only message that was tempered during transit

Should work.

**Comment by tomholub** [comment]
> Also found that there is no way to check background color in Appium.

I see. So we can't test by that, only test content.

**Comment by tomholub** [comment]
> > This one is the most wrong. When it's "not signed" it's supposed to be red. When it's signed, it's supposed to be green. But here it's showing "not signed" in green - why the inconsistency? How come the text is not tightly tied to the color?
> 
> If we have plain text message we need to mark it in red anyway?

Yes, plain text (not signed) message should always show "not signed" and red badge for signature.

**Comment by tomholub** [comment]
> > > Unfortunately I can not setup Thunderbird mail client with my Gmail account.
> > 
> > 
> > Can you be more specific - is it giving you any error?
> 
> Yes, it does not allow to login with third party email client until you change security setting in Google Account.

You're using some very old version of Thunderbird. New versions use oauth, which will allow you to sign in with Google just like FlowCrypt iOS app does.

**Comment by tomholub** [comment]
> Also found this useful example - `FlowCrypt/flowcrypt-ios/Core/source/assets/compat/mime-email-plain-signed-detached.txt`

You can actually use these samples directly. Just save them with `.eml` extension, then drag them from desktop to Thunderbird inbox, and it will get saved on Gmail.

**Comment by ivan-ushakov** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2021-11-24 at 21 11 13](https://user-images.githubusercontent.com/1408366/143292525-ea04e6f6-93eb-4d6f-88d0-6df03076bf9b.png)

Got this for `FlowCrypt/flowcrypt-ios/Core/source/assets/compat/mime-email-plain-signed-detached.txt`. Signature error looks too long.

**Comment by ivan-ushakov** [comment]
Interesting that browser extension does not process signature while mobile app does.

**Comment by tomholub** [comment]
> Got this for FlowCrypt/flowcrypt-ios/Core/source/assets/compat/mime-email-plain-signed-detached.txt. Signature error looks too long.

The error is not necessarily too long, but he visual should be fixed so that the badge flows on multiple lines. I'll file a separate issue for that.

**Comment by tomholub** [comment]
> Interesting that browser extension does not process signature while mobile app does.

Could you share a screenshot of what happens on browser extension?

**Comment by ivan-ushakov** [comment]
> > Interesting that browser extension does not process signature while mobile app does.
> 
> Could you share a screenshot of what happens on browser extension?

Browser extension just shows detached signature as attachment

<img width="512" alt="Screenshot 2021-11-24 at 21 45 18" src="https://user-images.githubusercontent.com/1408366/143296669-598e3668-9970-4241-a657-43520098928c.png">
.

**Comment by tomholub** [comment]
It doesn't recognize this one because of the unexpected name. Normally, these are nameless or named `signature.asc` or `signature` or similar.

**Comment by ivan-ushakov** [comment]
> It doesn't recognize this one because of the unexpected name. Normally, these are nameless or named `signature.asc` or `signature` or similar.

Tried with `signature` but result is the same:
<img width="614" alt="Screenshot 2021-11-25 at 19 08 55" src="https://user-images.githubusercontent.com/1408366/143473784-f501b688-6880-4372-a036-8c736d3619e5.png">

**Comment by tomholub** [comment]
Try `signature.asc`

**Comment by tomholub** [comment]
And give it a mime-type of `application/pgp-signature` if it doesn't have

**Comment by ivan-ushakov** [comment]
@tomholub 

Maybe you have ideas with this one produce message digest error in browser extension?

```
import emailjs = require('emailjs');
const openpgp = require('openpgp');

console.log('starting...');

const publicKey = '-----BEGIN PGP PUBLIC KEY BLOCK-----\r\nVersion: FlowCrypt iOS 0.2 Gmail Encryption\r\nComment: Seamlessly send and receive encrypted email\r\n\r\nxjMEYUsiUhYJKwYBBAHaRw8BAQdAWssVJKjkDqTo78c6oRUWQzBU5EeM1jyt\r\nsIYX7PzZh9bNOGUyZSBlbnRlcnByaXNlIHRlc3RzIDxlMmUuZW50ZXJwcmlz\r\nZS50ZXN0QGZsb3djcnlwdC5jb20+wngEExYKACAFAmFLIlICGwMFFgIDAQAE\r\nCwkIBwUVCgkICwIeAQIZAQAKCRClTYK+FSHSDrWUAQDGmiilgW1Q97JzZ8eN\r\nyevvnYl7FTNTGBiX+O9pFGaSdAEAukBYMV5fMXQihUdOQ8dL6Tfp7QQ4tuKo\r\nI52QCvp1bQTOOARhSyJSEgorBgEEAZdVAQUBAQdApW7iwSvECJCJqHXevZCN\r\nPt3xHiaWNLd/gKeMyFuhYU0DAQgHwnUEGBYKAB0FAmFLIlICGwwFFgIDAQAE\r\nCwkIBwUVCgkICwIeAQAKCRClTYK+FSHSDsUNAP9+YFUHDOCxJLmv6HZI6y2o\r\n3HWm193CuAoB2mWLEg6cnAEAoiq3T6s5r5X880Yx+VdJSHposEtzbQtBrzl8\r\n9//SbQE=\r\n=n4ak\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n';
const privateKey = 'PRIVATE_KEY';

const messageText = 'Signed only message with detached signature';

const main = async () => {
	const key = await openpgp.decryptKey({
		privateKey: await openpgp.readKey({ armoredKey: privateKey }),
		passphrase: '<PASS_PHRASE>'
	});

	const signed = await openpgp.sign({
		message: await openpgp.createMessage({ text: messageText }),
		signingKeys: key,
		detached: true
	});

	const message = new emailjs.Message({
		subject: 'Signed only message with detached signature',
		from: 'EMAIL',
		to: 'EMAIL',
		text: messageText,
		attachment: {
			type: 'application/pgp-signature',
			name: 'signature.asc',
			data: signed
		} as emailjs.MessageAttachment,
	});

	const stream = message.stream();
	stream.on('data', (data) => console.log(data));

};

main();

```

**Comment by ivan-ushakov** [comment]
I'm still trying to create a tool to easy generate all requires emails for this (and maybe future) tasks but since I'm trying to learn TS and MIME and PGP at the same time, it could be time consuming.

**Comment by tomholub** [comment]
You went too deep in this rabbit hole :-) as you are re-implementing functionality of a pgp email client.

The problem is likely here:

```ts
	const message = new emailjs.Message({
		subject: 'Signed only message with detached signature',
		from: 'EMAIL',
		to: 'EMAIL',
		text: messageText,
		attachment: {
			type: 'application/pgp-signature',
			name: 'signature.asc',
			data: signed
		} as emailjs.MessageAttachment,
	});
```

That is not what a signed message looks like. Sure, it has the elements: there's the text and then there's the signature. But you are guessing the structure, when the structure is governed by specification here https://datatracker.ietf.org/doc/html/rfc3156 specifically here https://datatracker.ietf.org/doc/html/rfc3156#section-5

I'm only quoting that for education purposes, what you are doing now is not needed / too difficult to be worthwhile for our current needs.

Use Thunderbird instead.

**Comment by tomholub** [comment]
It's not wasted time - you learned something useful while looking into it, and the knowledge will come handy later. But for this issue, it's better to use a message produced by a real, battle-tested email client.
