### ISSUE TITLE
add mark unread, move to trash, delete to a sending test

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1029]
In another issue:

It would be good, since we already sent a new message we don't need to also test message actions on it and delete it in the same test. 

- before opening the message, verify it's marked as unread in inbox
- after opening the message, run `checkOpenedEmail` as before
- after that, go back to sent (can use the back icon) and verify it's marked as read
- open the message again and tap "mark as read". Back to sent list - verify it's unread (this checks that we cleverly re-rendered the message after the action without need to refresh)
- refresh the sent message by pulling down on the list, then verify it's still unread (this checks that it was updated as unread on the mail server)
- open the message again and tap "Trash" icon
- go back using back icon, and verify that the message is gone from the list without refreshing
- refresh the list, make sure it's still gone
- using Menu, go to Trash folder, find the message, open it, and tap Trash again (this completely deletes the message)
- using back button, go back to Trash, see that message is not there
- refresh Trash by pulling down, see that message is not there

Then finally, change the test name by adding `+ mark unread, move to trash, delete`

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1027#discussion_r751474066_

**Comment by tomholub** [comment]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/6306961/142252737-244e2c40-83c8-4edd-ab0e-0e31f7ba3457.png">

**Comment by fcvakintos** [comment]
@tomholub is it for Sent message or Inbox?
`before opening the message, verify it's marked as unread in inbox`

**Comment by fcvakintos** [comment]
and we cant to check unread email or read

**Comment by tomholub** [comment]
> and we cant to check unread email or read

Because not implemented I suppose? In that case we could only implement moving to trash and deleting for now.

**Comment by tomholub** [comment]
> @tomholub is it for Sent message or Inbox? `before opening the message, verify it's marked as unread in inbox`

I forgot it was a sent message. For now can skip the unread/read tests.

**Comment by tomholub** [comment]
> @tomholub is it for Sent message or Inbox?

to clarify - in this test, we'd be using the sent folder

**Comment by fcvakintos** [comment]
ok, thanks
