### ISSUE TITLE
[User Feedback] Passphrase prompt occurs every time a user attempt to send a message during an active passphrase session

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#1032]
Description from original feedback:
>I have my password set to temporary.  After sending a message and then when I attempt to send a second email during the same session, it again asked for my password even though I had not logged off.  The app should retain my temporary password until I log off.

I can confirm this with FlowCrypt iOS 0.4.0 (via TestFlight)

Steps to reproduce:
1. Log in to your account with the FlowCrypt iOS app
2. Enter your passphrase and **choose the remember passphrase temporarily option**
3. Write a message and send it for the first time (a pop-up prompt will appear asking for a passphrase) - enter your passphrase
4. For the second time around, write a message once again and try to send it (another pop-up prompt asking again for a passphrase)

The user doesn't need to close the app or even put the phone to sleep. I believe the passphrase session can take up to 4 hours per session.

Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGlksJFsgDbFTfpQkRLZMBRdvzl

**Comment by tomholub** [comment]
@martgil can you reproduce this on master as well?

**Comment by martgil** [comment]
Yes, sir, @tomholub. I am able to reproduce this issue on the master branch build last night.

**Comment by martgil** [comment]
I check the passphrase session for reading emails and it works fine. The passphrase was only asked by the app once.
