### ISSUE TITLE
mart can't build master

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1033]
But seems like it only happens for a specified PR as I can't build the project from the master branch at the moment.

_Originally posted by @martgil in https://github.com/FlowCrypt/flowcrypt-ios/issues/668#issuecomment-972621062_

What is the issue it's giving you?

**Comment by martgil** [comment]
I'm getting all these errors when building the master branch. While I was recently able to install the flowcrypt 1.6.x version today.

Here is how I prepared in building the project (master)
1. git clone flowcrypt-ios repo
2. install dependencies with: 
```
make dependencies
bundle exec pod install
```
3. open the `.xcodeworkspace` to Xcode and let it perform indexing
4. It appears after trying to build the project.

Error in XCode workspace:
<img width="1440" alt="Screen Shot 2021-11-18 at 5 18 19 PM" src="https://user-images.githubusercontent.com/46025304/142386966-1606ab01-8a6d-4c1c-a9dd-afec5972befd.png">
Error in XCode Project: 
<img width="1440" alt="Screen Shot 2021-11-18 at 5 18 34 PM" src="https://user-images.githubusercontent.com/46025304/142386994-0e86e62b-527c-4ca4-9afb-d7c66cb66840.png">

**Comment by sosnovsky** [comment]
@martgil can you try to perform `File -> Packages -> Reset Package Caches` and then `File -> Packages -> Update to Latest Packages Versions`?

**Comment by martgil** [comment]
I do `Reset Package Caches` and then `Update to Latest Packages Versions` but unfortunately it doesn't work.

**Comment by martgil** [comment]
I can also see this error description which I think fails to clone a repository.

<img width="829" alt="Screen Shot 2021-11-18 at 5 52 36 PM" src="https://user-images.githubusercontent.com/46025304/142392435-d646c66e-1350-4c33-873c-b13acc7036f0.png">

**Comment by sosnovsky** [comment]
Does `git clone git@github.com:Marketcircle/libetpan` works for you if you try to run it manually from terminal?

**Comment by sosnovsky** [comment]
I just tried to clone `flowcrypt-ios` repository and build it from scratch - worked well for me, no issue with fetching packages

**Comment by martgil** [comment]
Hello, @sosnovsky I tried to connect my Github account to Xcode as it seems necessary. However, Xcode asks doesn't ask for my ssh key password on the contrary the `git clone git@github.com:Marketcircle/libetpan` asks for an ssh password. Am I doing it correctly?

**Comment by sosnovsky** [comment]
You can also try to add your ssh key to ssh-agent with this terminal command
```bash
ssh-add -K ~/.ssh/YOUR_SSH_KEY.pub
```

**Comment by martgil** [comment]
Hello @sosnovsky, `ssh-add` completed this puzzle. I am now running the debug build version on my device as well. 

Thanks for the helping hand!
Mart Gil

**Comment by sosnovsky** [comment]
Perfect!
