### ISSUE TITLE
use actor for Gmail/IMAP/SMTP

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1057]
Then I'll merge this, and we make sure that we use actor for Gmail/IMAP/SMTP in another issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1055#issuecomment-975395117_

**Comment by ivan-ushakov** [comment]
Since `GTLRService` is has async functions and we use them, there is no need to have `GmailService` as actor.

**Comment by tomholub** [comment]
Got it. I assume same for IMAP/SMTP. Closing
