### ISSUE TITLE
bad public key selector in apium - Expected 'e2e' to contain '-----BEGIN PGP PUBLIC KEY BLOCK-----'

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1068]
```
    // todo - fixme
    //     [0-11] Error in "SETTINGS:  user should see public key and should not see private key"
    // Error: Expected 'e2e' to contain '-----BEGIN PGP PUBLIC KEY BLOCK-----'.
    //     at <Jasmine>
    //     at PublicKeyScreen.checkPublicKey (/Users/tom/git/flowcrypt-ios/appium/tests/screenobjects/public-key.screen.ts:32:31)
    //     at processTicksAndRejections (node:internal/process/task_queues:96:5)
    //     at async UserContext.<anonymous> (/Users/tom/git/flowcrypt-ios/appium/tests/specs/settings/CheckSettingsForLoggedUser.spec.ts:34:5)``
    // await expect(pubkeyValue).toContain("-----BEGIN PGP PUBLIC KEY BLOCK-----");
```

**Comment by tomholub** [comment]
I commented out this code until fixed - please take a look

**Comment by fcvakintos** [comment]
@tomholub, I tried to add accesibilityId for public key, but no results
maybe devs can help me?
now accessibilityId for publicKey is full publicKey value(check screen)
we need to add accesibilityId like "publicKey" then I will fix a test 
<img width="1266" alt="Screenshot 2021-12-02 at 12 31 50" src="https://user-images.githubusercontent.com/91205853/144405571-77abf6ab-deaf-4dba-bc3a-a9add16648f2.png">

**Comment by tomholub** [comment]
Please make it `encryptedPrivateKey`. @Kharchevskyi should be able to help

**Comment by fcvakintos** [comment]
@Kharchevskyi can you check this one?
and add accessibility id in PR for this ticket?
https://github.com/FlowCrypt/flowcrypt-ios/issues/1187

**Comment by fcvakintos** [comment]
it is fixed in https://github.com/FlowCrypt/flowcrypt-ios/pull/1198
