### ISSUE TITLE
parallelize appium builds

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1069]
tests are starting to take an hour to run. Please try setting tests to run concurrently - up to 2 tests at a time.

**Comment by fcvakintos** [comment]
You mean to create queue on semaphore?

**Comment by tomholub** [comment]
I mean when I run `npm run-script only.test.all` on CI, it will start two simulators to run tests in parallel / get done faster. Could add a sysarg like 'npm run-script only.test.all --parallel'. When present, appium will start two simulators instead of one, and test in parallel.

**Comment by fcvakintos** [comment]
I know how to run same tests but for multiple devices, but don't know how to do that if we want to split them. Need to google

**Comment by tomholub** [comment]
For example on browser extension we parallelize most tests to run 10 in parallel (except for the particularly flaky ones which we run sequentially). For iOS, we can start with 2.

**Comment by fcvakintos** [comment]
mobile part is much more complicated if compare with browser

**Comment by tomholub** [comment]
I know

**Comment by fcvakintos** [comment]
@tomholub I have idea, we could use semaphore blocks to run separate list of tests so in that case they will be devided and faster. What do you think based on your exp with this CI system?

**Comment by tomholub** [comment]
does appium not already provide any mechanism for this?

**Comment by fcvakintos** [comment]
no, what I saw is just running same tests on diff devices but it's not what we need

**Comment by tomholub** [comment]
ok. Let's leave this for later

**Comment by ioanmo226** [comment]
@sosnovsky I think this issue seems outdated as we already run appium tests in multiple jobs.
What do you think?

**Comment by sosnovsky** [comment]
Yes, we can close this issue as tests are already running in parallel.
