### ISSUE TITLE
tests that open emails in inbox should search for them first

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1071]
For example `Error: element ("~Test 1") still not displayed after 15000ms` is because the desired email is too low on the screen now, and the test doesn't see it.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1070#issuecomment-976469472_

**Comment by tomholub** [comment]
As we add more test emails into the inbox, some inbox become out of view.

To find the right email to test with, going forward, we have to search for the email and then open it that way.

**Comment by tomholub** [comment]
Or categorize emails using labels in Gmail, and then open a particular label in left menu to open the email.

**Comment by tomholub** [comment]
@fcvakintos after finalizing open PRs, please do this one next - it's still creating some friction as it is now.

**Comment by fcvakintos** [comment]
@tomholub I will add ScrollToElement method

**Comment by tomholub** [comment]
no, please absolutely do not do that :-) use the search functionality.

**Comment by tomholub** [comment]
Eg for sent emails that we specifically want to see in sent folder, sure - use ScrollToElement. But for general tests that open one of the inbox emails and check contents etc, use search.
