### ISSUE TITLE
wait until loader gone before interacting with menu items

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1072]
```
  clickInboxButton = async () => {
    await ElementHelper.waitAndClick(await this.inboxButton, 500); // todo - instead wait until loader gone
  }

  clickSentButton = async () => {
    await ElementHelper.waitAndClick(await this.sentButton, 500); // todo - instead wait until loader gone
  }

  clickTrashButton = async () => {
    await ElementHelper.waitAndClick(await this.trashButton, 500); // todo - instead wait until loader gone
  }
```

The menu shows loader briefly. When the test tries to tap a menu item before loader is gone, test breaks.

**Comment by fcvakintos** [comment]
I tried to find selector for spinner, but it is not displayed in DOM if check by appium, 
I can add method which check some of items in menu (elements display), and after that we will click on some menu element

**Comment by tomholub** [comment]
@Kharchevskyi do you know how this loader is constructed and if it could maybe get an `accessibilityIdentifier`?

**Comment by Kharchevskyi** [comment]
you can try to add `accessibilityIdentifier` for spinner here
```
func showSpinner(_ message: String = "loading_title".localized, isUserInteractionEnabled: Bool = false) {
        guard self.view.subviews.first(where: { $0 is MBProgressHUD }) == nil else {
            // hud is already shown
            return
        }
        self.view.isUserInteractionEnabled = isUserInteractionEnabled

        let spinner = MBProgressHUD.showAdded(to: self.view, animated: true)
        spinner.label.text = message
        spinner.isUserInteractionEnabled = isUserInteractionEnabled
    }
```

**Comment by fcvakintos** [comment]
@Kharchevskyi is it ok?
<img width="700" alt="Screenshot 2021-11-29 at 12 49 47" src="https://user-images.githubusercontent.com/91205853/143854925-e7a95711-20c5-4d57-a368-60630167d1e2.png">

**Comment by Kharchevskyi** [comment]
Sure. Or You can pass optional argument to function with default value = nil. And use it as accessibility identifier or default value if passed value nil. 
Or you can keep it as in your implementation if this enough for you.

**Comment by fcvakintos** [comment]
@tomholub i added fixes for this
added spinner element, and wait until spinner invisible - but i added it to clickMenuButton and checkMenu methods.
I think it should work, and I removed delay for click on menu Item
<img width="810" alt="Screenshot 2021-11-29 at 14 11 36" src="https://user-images.githubusercontent.com/91205853/143866082-8d34e9ef-05d0-46ce-8cb2-0a761973e61c.png">

**Comment by fcvakintos** [comment]
for spinner I checked and it's not visible by appium at all... I can't expect or wait it

**Comment by fcvakintos** [comment]
@tomholub^

**Comment by tomholub** [comment]
Probably because you are testing too early.

So the execution is:
1) tap menu
2) you check that loader is not there, which it's not (yet). so you proceed with testing, tap something else
3) loader appears
4) loader disappears
5) test fails because something was tapped too fast

It's just a guess. You can confirm it visually - loader only appears a few hundred ms after I tap menu.

You can confirm this by doing:

```ts
// but you have to use a custom method to give up "successfully" after 1000ms
// in case spinner both shows and disappears before it noticed, or never shows which is also ok
await this.waitElementVisible(await this.loadingSpinner);
// now wait for it to go away
await this.waitElementInvisible(await this.loadingSpinner);
```

**Comment by fcvakintos** [comment]
and I tried and it fails on visible waiting

**Comment by tomholub** [comment]
I see. Could this be appium/wdio bug? Could you report it to them?

**Comment by fcvakintos** [comment]
it could be on appium side, need to research that more

**Comment by tomholub** [comment]
until then - yes - please try making the menu more robust by waiting for some specific items, and then a bit longer.

**Comment by fcvakintos** [comment]
@tomholub ok, sure, i think it helps
