### ISSUE TITLE
fix appium tests on master

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1073]
Not sure what broke them - it could be a combination of https://github.com/FlowCrypt/flowcrypt-ios/issues/1071 caused by #1041 or something else. Can't merge PRs until resolved, in particular this one is blocked #1043

**Comment by fcvakintos** [comment]
fixes in this run
https://flowcrypt.semaphoreci.com/workflows/85ac9bc7-47bd-42a2-830e-f0f3c35f6085?pipeline_id=3a254918-5270-4221-9907-f73ee6e8b74f

**Comment by tomholub** [comment]
Thank you - this is better.
