### ISSUE TITLE
crash when moving email to trash

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1076]
![image](https://user-images.githubusercontent.com/6306961/143063062-b68d013f-7f18-44bb-91b0-a2049189f6a5.png)

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/143063296-8386a41d-edb6-4f0a-b960-40e6152e56e9.png)

![image](https://user-images.githubusercontent.com/6306961/143063369-5b85cc9a-0236-4dd2-900c-bdef97bed736.png)

**Comment by tomholub** [comment]
```
      [NSException raise:ASCollectionInvalidUpdateException format:@"%@: %@", [responsibleDataSource class], e.reason];
```

**Comment by ivan-ushakov** [comment]
> It's in a catch block but wasn't caught - is that because it's an ObjC exception?

Yes, same thing as Realm exceptions. We can not catch them with `do - catch`. Only with objc code and `@try`.

**Comment by tomholub** [comment]
It would be good to use this: https://stackoverflow.com/questions/32758811/catching-nsexception-in-swift everywhere.

**Comment by tomholub** [comment]
Could call it `ObjC.catch` to be used as follows:

```
do {
    try ObjC.catch {
       /* calls that might throw an NSException */
    }
} catch {
    print("An error ocurred: \(error)")
}
```

But don't know if it can interface with async/await calls inside? One way or another, we should find a way to do this, for sanity.

**Comment by ivan-ushakov** [comment]
> It would be good to use this: https://stackoverflow.com/questions/32758811/catching-nsexception-in-swift everywhere.

Having this everywhere will make code looks verbose. We could use it in potential dangerous places but wrapping each objc function/method is too much.

**Comment by tomholub** [comment]
That would be verbose, yes. The issue is that almost anything can potentially throw ObjC exception. MailCore - ObjC. Gmail API - ObjC. Texture - ObjC.

Do we necessarily have to catch it exactly on the first boundary from ObjC to Swift? Or could it be later? Best would be if we only had to do it once per `Task` - then it's not verbose.

```swift
fun handle() {
  Task {
    do {
      try ObjC.catch {
        try await thisCanThrowSwift()
        try await thisCallsMethodThatCallsMethodThatCanThrowObjc()
        thisCanTrhowObjC()
        someOtherCode()
      }
    } catch {
      handle(error)
    }
  }
}
```

**Comment by tomholub** [comment]
I see it won't be so easy - let's discuss general ObjC catching separately in #1077. I'll hide the comments here.

**Comment by tomholub** [comment]
@ivan-ushakov can you look into handling the objc exception just for this one case?

**Comment by ivan-ushakov** [comment]
> @ivan-ushakov can you look into handling the objc exception just for this one case?

Sure. Does it still happen?

**Comment by tomholub** [comment]
I don't know. It happened once, it may happen again.
