### ISSUE TITLE
more generalized in-memory storage + remember id_token

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1091]
for #955 we will need a way to retain id_token longer.

Currently, we retrieve it during setup and then use it to authenticate with EKM, then forget it.

I'd like it instead be remembered, same like in-memory pass phrase (but always only in memory - regardless how pass phrase is remembered).

You can use the same mechanism/even same class and object that is used for in memory pass phrase storage, as long as you give it a more general name like `InMemoryStorage`. Or you can have a separate instance of that same class to be used for id tokens, or you can have two different classes, based on what you think makes sense.

Either way, whenever we wipe in-memory pass phrases (eg logout), id tokens should get wiped too.

This is a preparation for #955 where soon, we'll have to be calling FlowCrypt Enterprise Server (FES) and authenticate ourselves while doing that.

**Comment by sosnovsky** [comment]
@tomholub I found that we can fetch user's `idToken` at any time by using `GoogleUserService(currentUserEmail: "CURRENT_EMAIL", appDelegateGoogleSessionContainer: nil).idToken` (like here https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Functionality/Services/Remote%20Private%20Key%20Services/EmailKeyManagerApi.swift#L59)

It's already stored in `GTMAppAuthFetcherAuthorization`, probably it should be enough for our needs or we need to store it in another place too?

**Comment by tomholub** [comment]
That would be good news. On other platforms we always had to re-authenticate.

Does it always give you a fresh new idToken when you use `GoogleUserService(currentUserEmail: "CURRENT_EMAIL", appDelegateGoogleSessionContainer: nil).idToken` ? Or it gives you the cached one, and then re-fetches a new one when it expires? 

`GTMAppAuthFetcherAuthorization` caches it automatically? For how long and where (memory / storage)

**Comment by sosnovsky** [comment]
Value is cached only in memory, but it doesn't automatically re-fetched - I just tested it:
- `idToken` is valid for 1 hour
- but even when it's expired `GTMAppAuthFetcherAuthorization` still returns cached value
- old value is returned even after app restart

So we'll need to implement manual `idToken` refresh on expiration, currently working on it

**Comment by tomholub** [comment]
> So we'll need to implement manual idToken refresh on expiration, currently working on it

This will be using `GoogleUserService(currentUserEmail: "CURRENT_EMAIL", appDelegateGoogleSessionContainer: nil).idToken` which doesn't require any interaction from the user? If yes, could you find out which Google API is it using?

**Comment by sosnovsky** [comment]
Yes, I'll try to find which API we can use to make this process invisible for users

**Comment by tomholub** [comment]
When doing this on browser extension, I didn't find any API that allows that - it was necessary to re-authenticate. But if you can find it, it would be great - we could reuse it on browser extension too.
