### ISSUE TITLE
Add accessibility ID for headers

### ISSUE THREAD

**Issue by fcvakintos** [FlowCrypt/flowcrypt-ios#1094]
Looks good - less duplication.

When you encounter any `ios class chain` kind of selector, use accessibility identifiers instead.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1092#pullrequestreview-816005153_

**Comment by fcvakintos** [comment]
@ivan-ushakov can you help me with accessibility IDs for headers?
I dont know how to add it, i need to add it to all screens(sent/inbox/trash)
i think it should be here for inbox screen
how can i add it?
<img width="692" alt="Screenshot 2021-11-26 at 15 21 10" src="https://user-images.githubusercontent.com/91205853/143587494-405ca5b0-9a38-4626-a8d9-bd6554b22d7c.png">
<img width="393" alt="Screenshot 2021-11-26 at 15 19 25" src="https://user-images.githubusercontent.com/91205853/143587508-8576a7fc-dee8-42d6-a747-fe6f600ece4e.png">

**Comment by fcvakintos** [comment]
will add accessibilityid for search icon and help icon
`  CREATE_EMAIL_BUTTON: '-ios class chain:**/XCUIElementTypeButton[`label == "+"`]',
  INBOX_HEADER: '-ios class chain:**/XCUIElementTypeStaticText[`label == "INBOX"`]',
  SEARCH_ICON: '~search icn',
  HELP_ICON: '~help icn'
  HELP_ICON: '~help icn',
  SEARCH_FIELD: '~Search All Mail'`

**Comment by fcvakintos** [comment]
@tomholub how from devs can help me?

**Comment by tomholub** [comment]
@Kharchevskyi please take a look when you have a chance

**Comment by ivan-ushakov** [comment]
> @ivan-ushakov can you help me with accessibility IDs for headers?
> I dont know how to add it, i need to add it to all screens(sent/inbox/trash)

Try this one:

```
    private func setupUI() {
        title = inboxTitle
        view.accessibilityIdentifier = inboxTitle

        tableNode.do {
            $0.delegate = self
            $0.dataSource = self
            $0.leadingScreensForBatching = 1
            $0.view.refreshControl = refreshControl
            node.addSubnode($0)
        }

        node.addSubnode(composeButton)
        refreshControl.addTarget(self, action: #selector(refresh), for: .valueChanged)
    }
```

**Comment by Kharchevskyi** [comment]
or better to add them to `navigationController?.navigationItem.titleView?.accessibilityIdentifier = inboxTitle` instead of ` view.accessibilityIdentifier = inboxTitle`. Please check if this works for you

**Comment by fcvakintos** [comment]
`view.accessibilityIdentifier = inboxTitle`  didnt help me too
