### ISSUE TITLE
ui tests for message processing errors

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1095]
Test badge and text content for the following:

https://github.com/FlowCrypt/flowcrypt-ios/issues/1041

The email samples are already prepared in e2e account.

**Comment by tomholub** [comment]
emails:
 - encrypted - MDC hash mismatch - modification detected - should fail
 - message encrypted for another public key (only one pubkey used)
 - wrong checksum
 - not integrity protected - should show a warning and not decrypt automatically

Please write one test `decrypt errors render properly` that opens these four messages, and test the error messages in body contents, and also contents of encryption badge and signing badge for all 4 messages.

Also please take screenshots of how each of these is rendered, so I can make sure it's what I wanted.

**Comment by fcvakintos** [comment]
1st: 
<img width="400" alt="Screenshot 2021-12-02 at 15 09 09" src="https://user-images.githubusercontent.com/91205853/144428249-b3263dea-04cf-4735-ac7e-f69025b7e427.png">

2nd:
<img width="385" alt="Screenshot 2021-12-02 at 15 10 18" src="https://user-images.githubusercontent.com/91205853/144428347-87ff5365-95aa-4c89-a220-4786ca23564d.png">

3rd:
<img width="403" alt="Screenshot 2021-12-02 at 15 11 01" src="https://user-images.githubusercontent.com/91205853/144428491-44870871-0265-417b-9d0d-26400229a969.png">

4th:
<img width="400" alt="Screenshot 2021-12-02 at 15 12 16" src="https://user-images.githubusercontent.com/91205853/144428665-a607417c-f7d0-4ba9-8c51-43842e00b99e.png">

@tomholub is it correct?

**Comment by tomholub** [comment]
Only the 3rd is correct, because of wrong settings on my end. I will adjust them and ask you to retest.

**Comment by fcvakintos** [comment]
I will start to add new test for this

**Comment by tomholub** [comment]
Updated. Please log out and go through setup again, and provide new screenshots. It should not be showing key_mismatch everywhere anymore.

**Comment by fcvakintos** [comment]
@tomholub pls check

<img width="381" alt="Screenshot 2021-12-02 at 17 09 22" src="https://user-images.githubusercontent.com/91205853/144448597-2cf767d4-b0ac-430a-bab2-05c1025ff6f9.png">

**Comment by tomholub** [comment]
This one has always been good. How about the other three?

**Comment by tomholub** [comment]
Also, please double check that the existing tests didn't break because I added another key in the settings -> keys (in case they expected exactly one key - that would have to get fixed in the tests)

**Comment by fcvakintos** [comment]
for 1st  and 4th messages I need to set pass phrase
is it correct?
<img width="382" alt="Screenshot 2021-12-02 at 17 20 32" src="https://user-images.githubusercontent.com/91205853/144450840-2f835535-2dac-4960-b159-74b7a59f3172.png">
 for 2nd and 3rd - no set pass phrase
 2nd email error:
 
<img width="396" alt="Screenshot 2021-12-02 at 17 21 27" src="https://user-images.githubusercontent.com/91205853/144451041-a3716d71-a3b9-45a7-a9de-cddbbead3ed6.png">

**Comment by tomholub** [comment]
> for 1st and 4th messages I need to set pass phrase

Is this right after you've re-set up the e2e account?

**Comment by fcvakintos** [comment]
yes

**Comment by tomholub** [comment]
> > for 1st and 4th messages I need to set pass phrase
> 
> Is this right after you've re-set up the e2e account?

I've just tested this. It's a bug. I'll file an issue for this right now. You can write the test so that it gives it the pass phrase, but add a comment that that's because of a bug and should be removed once the github issue is fixed. Link that issue in the comment.

**Comment by fcvakintos** [comment]
after setting pass phrase the email text is not displayed
<img width="387" alt="Screenshot 2021-12-02 at 17 33 57" src="https://user-images.githubusercontent.com/91205853/144452908-83592c8f-a926-4105-82ca-442704fd7ca4.png">

**Comment by tomholub** [comment]
> after setting pass phrase the email text is not displayed

This particular is caused by #1144 - please do the same - add comments in the tests that the implementation is wrong and link the issue.

**Comment by tomholub** [comment]
this looks good

![image](https://user-images.githubusercontent.com/6306961/144454954-46383ead-20f1-4d53-aef1-4ffcbb8f4fd6.png)

**Comment by fcvakintos** [comment]
@tomholub yes, after pass phrase error is displayed

**Comment by fcvakintos** [comment]
@tomholub 
for 4th email  no error
<img width="388" alt="Screenshot 2021-12-03 at 10 27 53" src="https://user-images.githubusercontent.com/91205853/144570270-fcd12497-f62b-471b-a68e-6875fbf8bce4.png">

**Comment by tomholub** [comment]
You keep showing me the other email.

I mean this one:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/6306961/144579701-b956ead1-7162-45f8-88d8-de15ad5406a4.png">

**Comment by fcvakintos** [comment]
@tomholub `encrypted - MDC hash mismatch - modification detected - should fail` - after pass phrase has this error 
check pls?
correct or no?
<img width="390" alt="Screenshot 2021-12-03 at 12 44 48" src="https://user-images.githubusercontent.com/91205853/144589687-ed010fb3-7fe1-4dc0-a6d6-00b9ada133e4.png">

**Comment by tomholub** [comment]
That one is correct

**Comment by fcvakintos** [comment]
what expected result for this?
not integrity protected - should show a warning and not decrypt automatically

**Comment by fcvakintos** [comment]
@tomholub now i set pass phrase for 4th email and get this screen, is it correct?
<img width="405" alt="Screenshot 2021-12-03 at 13 34 40" src="https://user-images.githubusercontent.com/91205853/144596018-3a624e18-ecf3-4455-9840-d01b47bbfd65.png">

**Comment by tomholub** [comment]
> @tomholub now i set pass phrase for 4th email and get this screen, is it correct?

It's wrong, but test it anyway, with a code comment pointing to the underlying bug #1144
