### ISSUE TITLE
improve sending progress status to debug customer issue

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1096]
We have a customer which is sending an email without attachments and it takes 70 seconds to send. Then it succeeds.

I'm not sure where to start debugging, it could be their environment. But something we could do to make progress more obvious:

1) differentiate different states in the loader. For example, `Encrypting`, `Sending`, `Deleting draft` or whatever it may be.
2) show a percentage even though we are not uploading any attachments. Is this possible and meaningful? Let's say the request has 1kb of data, maybe we could still show a percentage progress.

I received a video of the issue and it's really just a simple message and then send and then a spinner for 70 seconds like this:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/6306961/143491234-13b7825a-0e2e-4cb2-9bb6-e21bd3c46db8.png">

I'll file another issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/695#issuecomment-979428783_

**Comment by Kharchevskyi** [comment]
As an improvement for the future - would suggest to add some mechanism for debugging for users
As an example we can have some debug logger, which would save user logs to file system or elsewhere and then this logs can be shared with us.
