### ISSUE TITLE
reply-to header not honored

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1099]
on `flowcrypt.compatibility` account there is a test message `Honor reply-to address - encrypted`

When you open on iOS and hit reply, you will notice the `to:` shows `flowcrypt.compatibility` when it should show another email per the reply-to header. Compare with browser extension.

Copy the message to e2e account to also write a ui test for this, which will tap on the reply button and check the recipient field.

**Comment by martgil** [comment]
the test message is now present in the e2e account.

**Comment by tomholub** [comment]
Thank you!
