### ISSUE TITLE
context.folderPath nil/empty string improvements

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1101]
Not sure what is an `""`  (empty string) path. Doesn't lead anywhere - it's as bad as a nil. 

Any good reason why `context.folderPath` should ever be nil? I mean, why is `folderPath` nilable in the first place?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1087#discussion_r757146582_

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/143572321-cd2eda96-1be9-4c5b-89a0-482a3d5bcf47.png)

**Comment by ioanmo226** [comment]
@tomholub we set context.folderPath to nil when we want to search for all folders.
Like in search screen when user searches something, we have to show all search results despite of current selected folder.

**Comment by tomholub** [comment]
Got it. Could add a comment above the init for clarity, and also replace `context.folderPath ?? ""` with `context.folderPath` so that it's `value or nil`, not `value or empty value`.

**Comment by ioanmo226** [comment]
ok
