### ISSUE TITLE
message signed by unknown key should have a different badge

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1112]
This one is not right - signed only message that is missing pubkey should have encryption badge of `not encrypted` and a signature badge that says it cannot be verified due to missing pubkey.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1088#discussion_r758616826_

**Comment by tomholub** [comment]
To clarify, if that was an encrypted message, then it should say "encrypted". If it was plain, then "not encrypted". Either way not "decrypt error".

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/143922323-8d876920-a0be-452b-8bc1-f1b56849c7ed.png)

**Comment by ivan-ushakov** [comment]
I think this happens because message was generated with TS code and OpenPGP library:
```
Message-Id: <ID>
Date: Fri, 26 Nov 2021 21:08:29 +0300
Subject: =?UTF-8?Q?Signed_only_message_where_the_pubkey_is_not_availabl?= =?UTF-8?Q?e?=
From: EMAIL
To: EMAIL
Content-Type:text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

-----BEGIN PGP MESSAGE-----

xA0DAQgB4zmJwUJwzCMByzt1AGGhIp1TaWduZWQgb25seSBtZXNzYWdlIHdo
ZXJlIHRoZSBwdWJrZXkgaXMgbm90IGF2YWlsYWJsZcLBcwQBAQgABgUCYaEi
nQAhCRDjOYnBQnDMIxYhBFifPYHspaLad5u5E+M5icFCcMwjVYQP/Rj0Ca94
Up4bzEtLsaNqorJAKa9bAilvG7xBIANOQvc+aMch/2B17lSKwagoiOlG6Y37
/DzDtx2RiZlehaFU1EVmqrXaK/v6+WvzO0ckMvb09LUoiy+hj+5pIN9F7zem
KQYPmuyqGvMl+OIz8MIp/2EbZKhy6KEBU/QeLP1AXIp3z/L28fgBjXLJxsG7
LIobmL7++7Cs9wKxrmMvSTaJhew1sFfbzeDTodCN98wy7VAQGm96txdthIEG
z2sWEd0h7o5PQEPs2EE/zYhTTNCriaNllcR/HDcb9AIM2jJsdSX0uXBatVN+
6WrOhwf57LJ8Qqu0+dWa15mjFERXgyCH+tW8Gx5niwiIluBdJSRbfw7DZAKw
OHkbiOrsIzhT9uYj03wn2Q7HdjE9s74vPYLIKsItl1Xnjm9F0HZ5R5F04owo
CTj5iyxDH6J34t3cEcZQSyLlEIYWeUQq/3XaDscdUHXWofqKlwPFXKyV3c/f
5A4XxqrbPkMnW0FN9k4jG0z2MGGtvyZRdHiL6MbB35DejUsqYdt/575Hf+BE
IHGg1fCkZ9P2IXkRVrI3DrEfPtTuggtW2LFSPlB9U+GEz6Onj9EIQvoA+lCQ
RVVly+1Tuh7FEabadZbJ3akS7oaEy3eoVj/uRSkk9EDtbrLBJMJgtS1rzZQ7
yOYjZy8j4Q4hONiR
=+ltZ
-----END PGP MESSAGE-----
```

Unfortunately I don't know how to create is other way.

**Comment by tomholub** [comment]
I'll give you another message.

**Comment by tomholub** [comment]
Here's how you can make one: take any validly signed message, open the mime, and change `from: ` header to `from: unknown@sender.test`. That will cause it to not find the right public key (since none can be found for that email) which will in turn produce unknown signature badge.
