### ISSUE TITLE
switch to SearchScreen.searchAndClickEmailBySubject

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#1116]
I moved search logic to separate screen object `SearchScreen`. Let's refactor current tests to use this object instead of `MailFolderScreen`.

**Comment by tomholub** [comment]
Just to be sure - is search screen significantly different from other folder screens?

If yes, then the refactor should be in the app first. I think it's this issue [#search thre](https://github.com/FlowCrypt/flowcrypt-ios/issues/669)

After that, the search screen should resemble regular inbox screen and we should be able to use `MailFolderScreen`, maybe. Unless all of the test code is different, in which case it would make sense to have a separate ts class.

**Comment by ivan-ushakov** [comment]
> Just to be sure - is search screen significantly different from other folder screens?

I was thinking that if we have separate view controller then it should be separate screen object.

**Comment by ivan-ushakov** [comment]
With new Xcode 13.2.1 something broken with appium and I can not run tests on my machine.
```
[0-0] 2021-12-19T10:57:51.914Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Could not create simulator with name 'appiumTest-D9F8AED7-A385-454E-8176-8D3544C0C182-iPhone 11 Pro Simulator (15.2)', device type id 'iPhone 11 Pro Simulator (15.2)', with runtime ids 'com.apple.CoreSimulator.SimRuntime.iOS-15-2'
```

**Comment by sosnovsky** [comment]
> With new Xcode 13.2.1 something broken with appium and I can not run tests on my machine.
> 
> ```
> [0-0] 2021-12-19T10:57:51.914Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Could not create simulator with name 'appiumTest-D9F8AED7-A385-454E-8176-8D3544C0C182-iPhone 11 Pro Simulator (15.2)', device type id 'iPhone 11 Pro Simulator (15.2)', with runtime ids 'com.apple.CoreSimulator.SimRuntime.iOS-15-2'
> ```

Tests work well for me on Xcode 13.2 after changing `15.0` to `15.2` here https://github.com/FlowCrypt/flowcrypt-ios/blob/master/appium/config/wdio.live.conf.js#L29
Looks like you got some issue with simulator ids, as simulators are reset after Xcode update.
Were you able to fix it?
