### ISSUE TITLE
when and why does app reset through arguments?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1124]
```swift
    if ProcessInfo().arguments.contains(AppReset.reset.rawValue) {
        AppReset.resetKeychain()
        AppReset.resetUserDefaults()
    }
```

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1111#issuecomment-981540910_

**Comment by tomholub** [comment]
I wonder what is the purpose of the code above. It's clear what it does, but when and why?

**Comment by ivan-ushakov** [comment]
> I wonder what is the purpose of the code above. It's clear what it does, but when and why?

Maybe this is used for UI tests?

**Comment by tomholub** [comment]
It does look like it's for tests. But I believe UI tests were added without it. Let's see git blame

**Comment by tomholub** [comment]
Good call, it was used for now deprecated UI tests that were written in swift.

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/6306961/144116504-3a040c70-259a-45bd-bd7d-9c821adf97d8.png">

**Comment by tomholub** [comment]
I'll remove it
