### ISSUE TITLE
user / cloud contacts provider - inconsistent naming

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1129]
```
        let cloudContactProvider = cloudContactProvider ?? UserContactsProvider(
            userService: GoogleUserService(
                currentUserEmail: email,
                appDelegateGoogleSessionContainer: UIApplication.shared.delegate as? AppDelegate
            )
        )
```

should name it `CloudContactProvider` instead of `UserContactsProvider`

`userService` should be called `googleUserService`

**Comment by ioanmo226** [comment]
@tomholub `UserContactsProvider` is inherited from `CloudContactsProvider` and `GoogleUserService` is inherited from `UserService`.  
I guess previous devs implemented this way because there might be `OutlookUserService` or `ICloudUserService` which would be inherited from `UserService`?
Please confirm

**Comment by ioanmo226** [comment]
@tomholub Please check

**Comment by tomholub** [comment]
I suppose, since Outlook is planned sometime in the future.

But what is the difference between `UserContactsProvider` and `CloudContactsProvider` and `UserService`? It sounds to me like it should all be one class? And then from there, we could have children like `GoogleUserService` and `OutlookUserService` ?

**Comment by tomholub** [comment]
Also there seems to be two things somewhat co-mixed: "user service" and "cloud contacts". It all just seems like one big mess, as implemented. Could you propose possible ways to simplify and clean up?
