### ISSUE TITLE
inbox pagination is broken - doesn't load more items

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#1132]

**Comment by tomholub** [comment]
could you provide more details?

**Comment by Kharchevskyi** [comment]
https://user-images.githubusercontent.com/13693255/144274008-d03cb94f-e796-4d1a-9aa5-bf65d23616d2.mp4

**Comment by Kharchevskyi** [comment]
@tomholub can you please check as well?

**Comment by tomholub** [comment]
If the brokenness is that it doesn't give more emails when I scroll all the way down, then yes - that is currently broken for me.

**Comment by tomholub** [comment]
That means this needs to be covered by an appium test as well.
