### ISSUE TITLE
sending email to users without valid keys should fail with appropriate modal

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1138]
attempt to send email to accounts
 - `expired` at flowcrypt.com
 - `revoked` at flowcrypt.com

in both cases it should show an error modal - test for contents of that modal.

Both in one test called `will not send email to recipients that only have revoked or expired keys`

**Comment by fcvakintos** [comment]
@tomholub what are the emails?
expired@flowcrypt.com?
revoked@flowcrypt.com?

**Comment by fcvakintos** [comment]
is it a correct error for revoked account?
<img width="354" alt="Screenshot 2021-12-02 at 12 39 58" src="https://user-images.githubusercontent.com/91205853/144406437-00797953-1907-40f3-affa-51576986d5b4.png">

**Comment by fcvakintos** [comment]
the same error for expired account

**Comment by tomholub** [comment]
Revoked looks good.

The expired one should look similar but should say expired in the modal.

**Comment by fcvakintos** [comment]
thanks
