### ISSUE TITLE
A server with the specified hostname could not be found

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1139]
Please see where exactly this error is coming from, and add the server URL to the error message so that we know which one it is.

<img width="235" alt="image" src="https://user-images.githubusercontent.com/6306961/144330410-9daa3c53-bf62-41e3-9fef-3ca7f645668a.png">

**Comment by ivan-ushakov** [comment]
@tomholub 
What was the tag for this version?

**Comment by tomholub** [comment]
Happened on both 0.4.0 (1x) and 0.5.0 (2x)

**Comment by tomholub** [comment]
My suspicion is that this was calling `fes.somecustomuserdomain.com` for user `@somecustomuserdomain.com`

**Comment by ivan-ushakov** [comment]
Yes, I found this to be the only possible source but we have following logic:
```
try await getUserOrgRulesIfNeeded()
|
try await appContext.clientConfigurationService.fetch(for: currentUser)
|
try await server.getClientConfiguration(for: user.email)
```

And inside `getClientConfiguration`:
```
let request = ApiCall.Request(
    apiName: Constants.apiName,
    url: "https://fes.\(userDomain)/api/v1/client-configuration?domain=\(userDomain)"
)
let safeReponse = try await ApiCall.call(request)
```
so we don't handle error code like in `getActiveFesUrl`. Maybe we need to use `getToleratedNSErrorCodes`.

**Comment by tomholub** [comment]
But don't we call `getActiveFesUrl` first? That one should have failed, and then we would never call `getUserOrgRulesIfNeeded` ?

**Comment by tomholub** [comment]
`getClientConfiguration` should indeed fail if called and there's no FES, but it should not be called at all if `getActiveFesUrl` decides there is no FES running there.

**Comment by ivan-ushakov** [comment]
> But don't we call `getActiveFesUrl` first? That one should have failed, and then we would never call `getUserOrgRulesIfNeeded` ?

No, we have this sequence:
```
do {
    await setupCore()
    try await appContext.dataService.performMigrationIfNeeded()
    try await setupSession()
    try await getUserOrgRulesIfNeeded()
    chooseView(for: window)
} catch {
    showErrorAlert(of: error, on: window)
}
```

**Comment by tomholub** [comment]
I may need to take a look. Is `getActiveFesUrl` ever used?

**Comment by ivan-ushakov** [comment]
> I may need to take a look. Is `getActiveFesUrl` ever used?

My bad. We call it inside `getClientConfoguration`. So you are right:
```
guard try await getActiveFesUrl(for: email) != nil else {
    return .empty
}
```

**Comment by tomholub** [comment]
My guess is, maybe `getActiveFesUrl` still fails for some type of errors.

**Comment by tomholub** [comment]
Plus, it produces modals that lack information about what went wrong

**Comment by ivan-ushakov** [comment]
Yes, we need at least error code

**Comment by ivan-ushakov** [comment]
OK, I found problem: `ApiCall.call()` throws `ApiError` but we expect `HttpErr` here:
```
  if let httpError = error as? HttpErr,
     let nsError = httpError.error as NSError?,
     Constants.getToleratedNSErrorCodes.contains(nsError.code) {
      return nil
  }
```
Looks like my mistake during `async` refactoring. Will fix it.

**Comment by ivan-ushakov** [comment]
We also have this logic:
```
  guard let raw = local.load(for: user.email) else {
      throw error
  }
  return ClientConfiguration(raw: raw)
```
We throw error and show that alert only if we don't have local configuration

**Comment by tomholub** [comment]
> We also have this logic:
> 
> ```
>   guard let raw = local.load(for: user.email) else {
>       throw error
>   }
>   return ClientConfiguration(raw: raw)
> ```
> 
> We throw error and show that alert only if we don't have local configuration

This is correct. If we already have one locally, it's ok to keep using the local when we fail to re-fetch it.
