### ISSUE TITLE
unexpected modal for some key mismatch situations

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1143]
Hi @tomholub,

I just noticed that the first key mismatch reported above was actually an error for a public key mismatch (I think)

In case you are wondering, here is what it looks like for mismatch (private key) which might be related to https://github.com/FlowCrypt/flowcrypt-ios/issues/1140
![image](https://user-images.githubusercontent.com/46025304/144388763-ee7a0f12-ed11-441b-b475-754b3ef210fa.png)

_Originally posted by @martgil in https://github.com/FlowCrypt/flowcrypt-ios/issues/704#issuecomment-984417298_

There is no difference between a public key mismatch and a private key mismatch - it's always a mismatch between a public key that encrypted the message and private key that is trying to open it. It's always both.

So there is something else going on. Could you please copy this message into e2e account and reproduce it there? But please use subject `key mismatch unexpectedly produces a modal`

**Comment by martgil** [comment]
>There is no difference between a public key mismatch and a private key mismatch - it's always a mismatch between a public key that encrypted the message and private key that is trying to open it. It's always both.

Thank you, sir! I understood it clearly now. 

I have moved the message with an appropriate subject on e2e account and I'm getting the same results.
<img width="305" alt="Screen Shot 2021-12-03 at 12 30 20 PM" src="https://user-images.githubusercontent.com/46025304/144545514-47b07f2c-df70-46ad-a93c-c76fd6100ada.png">

**Comment by tomholub** [comment]
Thanks. Instead of the modal, it should render the key mismatch like we're already usually rendering it.
