### ISSUE TITLE
crash when reading a message on Outlook

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1145]
1) log in with outlook
2) set up (in my case with pass phrase saved to device)
3) open any email in inbox
4) crash

This is likely caused by my async/await refactor, didn't check IMAP that time

**Comment by Kharchevskyi** [comment]
@tomholub @sosnovsky 
It looks like `MessageViewController` is removed in scope of this pr https://github.com/FlowCrypt/flowcrypt-ios/pull/1017 which was used for opening messages.

"Other email provider option" does not support message threads functionality.

**Comment by sosnovsky** [comment]
Yes, `MessageViewController` was removed, but `ThreadDetailsViewController` should support single messages too - `Thread` with 1 message is created for this case https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Controllers/MessageList%20Extension/MsgListViewController.swift#L40

**Comment by Kharchevskyi** [comment]
Looks like it doesn't support operations with messages (archive/delete/mark as unread) and it can't resolve dependency for this controller
```
Fatal error: Email Provider should support this functionality. Can't resolve dependency for Optional<MessagesThreadOperationsProvider>
```

**Comment by sosnovsky** [comment]
Yes, seems like we've missed this functionality there, as it was tested mostly with Google accounts, while IMAP accounts functionality wasn't high priority. We still has some issues for it - like https://github.com/FlowCrypt/flowcrypt-ios/issues/989 and https://github.com/FlowCrypt/flowcrypt-ios/issues/484

**Comment by Kharchevskyi** [comment]
Should we revert those changes? 
Or add support for message operations? Which can take some time

**Comment by sosnovsky** [comment]
Reverting changes will need re-duplicating of all code which was added to `ThreadDetailsViewController` since then, which will take some time too.

We already have `messageOperationsProvider` in `ThreadDetailsViewController`, it can be used for performing operations when there is a single message instead of thread. Just need to identify which message type we have - `message` or `thread` and then use `messageOperationsProvider` or `threadOperationsProvider` accordingly.

**Comment by tomholub** [comment]
We should definitely not revert the changes - `MessageViewController` was removed purposefully, since `ThreadDetailsViewController` can be used to render a thread containing 1 message as well.

We don't have to fix message operations in this issue. I'll file another issue for that. Just viewing the message.
