### ISSUE TITLE
appium test for migrations from older app to newer app?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1148]
We should ideally have a test for upgrading from earlier app. For this, I suppose we would pre-build an app and check it into the repo. It would forever stay the same until it can no longer run the current iOS version we test on.

The test would:
 - open the app
 - set up an account
 - open the most recent app build
 - verify that basic functionality remains functional (eg no missed or bad migrations)

Not sure if realistic - worth a try.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1133#discussion_r761365292_

**Comment by tomholub** [comment]
@fcvakintos is this realistic? Appium would have to reuse storage between running the older app and the newer app, for this to work.

**Comment by fcvakintos** [comment]
@tomholub I did that before, so it could be done I guess. I will investigate next week

**Comment by fcvakintos** [comment]
@tomholub  I have a question
if i update the app from old version to new, should I login again?

**Comment by tomholub** [comment]
I think the old version should be already logged in. Therefore, after updating, we should confirm that it remains logged in and functional.

That means we'll have to maybe pack up the older app's storage and include it as a semaphore secret.

**Comment by fcvakintos** [comment]
@tomholub, ok, it works for me

**Comment by tomholub** [comment]
1) open one encrypted message
2) open settings screen -> keys
3) open settings screen -> contacts

**Comment by fcvakintos** [comment]
@tomholub ok, on old app version should I do the same steps??
and is it in 1 scenario?

**Comment by tomholub** [comment]
I originally thought you wouldn't test anything on the old version of the app, and already have storage from old app pre-made.

But now I see you want to test both. That's also fine. In that case, yes - do the above tests on both apps.

**Comment by tomholub** [comment]
You also need to make sure that the original app load at least one contact that you can check later. You can do that eg by opening an encrypted+signed message.

**Comment by fcvakintos** [comment]
@tomholub is it on old app?

**Comment by tomholub** [comment]
You want to check that the contact information is preserved. So yes - it needs to be generated in old app, and checked in new app.

**Comment by fcvakintos** [comment]
ok

**Comment by fcvakintos** [comment]
@tomholub we have some problem, we need to push old app for running on semaphore CI, but it has 168MB.
Is is ok if we will push it every time?

**Comment by tomholub** [comment]
What do you mean by "push it every time"? Please explain all steps that you expect will be needed in order to test this.

**Comment by fcvakintos** [comment]
So:
1. install old app
2. check 1 encrypted email on old app
3. check 1 contact on old app
4. remove old app
5. install new app
6. verification on new app(checking email, contact and pubkey)

**Comment by tomholub** [comment]
Be more specific! Push it where? How? Where exactly will it be? How will it be downloaded? I can't give any advice from your half-statements.

**Comment by fcvakintos** [comment]
So for testing such scenario I need old application file which has size 150 Mb, in our ci configuration we are building new app so as result we need both. Old app is static and should be stored somewhere, for example in repository but it quite big and github is rejecting my push because of the size. I am checking if we have option to store this old app on CI side

**Comment by tomholub** [comment]
I could upload it to S3 so that you can download it during CI run using wget or similar. If you could zip it and deliver it to me somehow (eg through google drive), then I'll upload it publicly for you. Would that work?

**Comment by fcvakintos** [comment]
Great, will send you tomorrow!

**Comment by fcvakintos** [comment]
@tomholub I sent you

**Comment by tomholub** [comment]
https://flowcrypt.s3.eu-central-1.amazonaws.com/dev/flowcrypt-ios-2021-12-17-v060-for-ci-migration-test.zip

**Comment by fcvakintos** [comment]
@tomholub Can you create new zip with new app? 
some selectors are updated and the tests will fail on this version

**Comment by tomholub** [comment]
I could, but isn't that an issue we'll have over time either way? Surely the selectors on the new app will continue to evolve, plus the new app functionality will continue to evolve. We can't keep updating the old app every time when that happens.

**Comment by fcvakintos** [comment]
@tomholub ok, we can create new methods and add new selectors for old app which will work only on old app

**Comment by fcvakintos** [comment]
we can create new screen object file and add these methods there

**Comment by fcvakintos** [comment]
@tomholub is it good way? I need your approval

**Comment by tomholub** [comment]
I think so, I don't see a way around that. Just one limited screen like `OldVersionAppScreens` or similar, maybe.

**Comment by fcvakintos** [comment]
@tomholub , yes, i think we can add there only methods which different on the current version, not all
ok?
and we will update this file when something changed

**Comment by tomholub** [comment]
> @tomholub , yes, i think we can add there only methods which different on the current version, not all
>  and we will update this file when something changed

I guess so. Over time, we will need to add more, as the new and old app will diverge, as you say.

**Comment by fcvakintos** [comment]
@tomholub I think we can close this issue, PR is merged already
