### ISSUE TITLE
primary key for saving private keys should be email+fingerprint

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1150]
Realm has following limitation:
> You can define only one primary key per object schema.

So we need to think how to get that index with fingerprint and email.

_Originally posted by @ivan-ushakov in https://github.com/FlowCrypt/flowcrypt-ios/pull/1133#discussion_r761394522_

**Comment by tomholub** [comment]
currently this

```
final class KeyInfoRealmObject: Object {
    @Persisted(primaryKey: true) var primaryFingerprint: String
    @Persisted var `private`: String
    @Persisted var `public`: String
    @Persisted var passphrase: String?
    @Persisted var source: String
    @Persisted var user: UserRealmObject?
    @Persisted var allFingerprints: List<String>
    @Persisted var allLongids: List<String>

    var primaryLongid: String {
        allLongids[0]
    }

    override var description: String {
        "account = \(user?.email ?? "N/A") ####### longid = \(primaryLongid)"
    }
}
```

Let's instead call it `KeypairRealmObject`

primary key should be a composition of email+fingerprint like this: `\(primaryFingerprint),\(userEmail.toBase64String())`

then `email` and `primaryFingerprint` should be two more separate fields

**Comment by ivan-ushakov** [comment]
We also need new schema version and migration script

**Comment by tomholub** [comment]
yup

**Comment by ivan-ushakov** [comment]
@tomholub
Why we use `userEmail.toBase64String()`, not just `email`?

**Comment by tomholub** [comment]
I'm worried when I join sequences that together have some meaning, of characters that I have no control over. It's probably excessive, but it just doesn't feel right.

It's true that while email can contain all sorts of weird characters, it's not allowed to contain a comma. But if we do get an email address that contains a comma from some weird email provider, maybe that could cause some mess. I don't know. It's just a reflex, if I'm combining items into an index, I want more control over them. Base64-encoding it is a way to give it some order. Likely not needed, but will let me sleep a little better at night.

**Comment by tomholub** [comment]
We could always hash it like `id = sha256(fingerprint + "," + email)` if you prefer that over the base64.
