### ISSUE TITLE
appium test for inbox pagination

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1156]
That means this needs to be covered by an appium test as well.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1132#issuecomment-985638671_

pre-setup: ensure there is some email in inbox which is old enough that scrolling down to it requires pagination (mening - it's not loaded in inbox unless you scroll down and see more items load)

test case:
1) load inbox
2) ensure the email is not there
3) could the amount of emails rendered in inbox - even the ones that are out of screen (is this possible?)
4) scroll all the way down
5) more items should be added to inbox. Count them again to ensure it's more now
6) scroll down until you find the right email. tap on it, and verify contents

**Comment by tomholub** [comment]
Currently this functionality is broken, therefore not actionable to write test yet.

**Comment by tomholub** [comment]
it's fixed now, can be tested

**Comment by fcvakintos** [comment]
@tomholub can we use for testing account "e2e.enterprise.test@flowcrypt.com"?
or you have some another account for testing?
if it is a 'e2e' account we need to send more email to this and it can effect our tests

**Comment by tomholub** [comment]
Didn't we already have loads of emails in inbox on this account to test with? Or do you mean emails sent in the future?

**Comment by fcvakintos** [comment]
@tomholub yes, we have but it is not enough for check this test case because pagination is not available

**Comment by fcvakintos** [comment]
@tomholub pls check this issue
https://github.com/FlowCrypt/flowcrypt-ios/issues/1284
it is actual only for e2e account, on my account it works correct

**Comment by tomholub** [comment]
#1284 hopefully settled now, let me know if you are still blocked

**Comment by tomholub** [comment]
#1288 is the same issue
