### ISSUE TITLE
enable calling local mock without https on debug build

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1159]
Only on debug bundle id, I'd like to be able to call `http://127.0.0.1:8001/` without https. Please help me add an exception.

**Comment by tomholub** [comment]
related: #1012

**Comment by sosnovsky** [comment]
I tried to open local url `http://127.0.0.1:8080/` and it worked well, without any added exception, possibly iOS allows to load local resources without HTTPS. Did you receive any error when trying to load local URL?

**Comment by tomholub** [comment]
yup - I got a "network is not reachable" or similar from the app. I'll try again then. Thanks!

**Comment by tomholub** [comment]
I'm getting this but it turns out it's my fault - the mocks are not starting properly.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/6306961/144676959-539eeff9-4d52-4394-a513-57e8b0832257.png">

**Comment by tomholub** [comment]
all good - thanks!
