### ISSUE TITLE
proceedAfterLogout rename 

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#116]
`proceedAfterLogout` is not the best name considering how we use it. Maybe `GlobalRouter().reloadApp()` ?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/115_

**Comment by Kharchevskyi** [comment]
Totally right! Will fix it together with navigation issue that I mentioned

**Comment by tomholub** [comment]
Yes I think I saw the side menu just show a spinner and never finish at some point, without showing any folders. Is that what you meant?

**Comment by Kharchevskyi** [comment]
Yes. thats also a bug. 
but I'm about ENSideMenuNavigationController. ENSideMenuNavigationController is already NabigationController and UInavigationController can't be pushed inside UInavigationController.
