### ISSUE TITLE
use accessibility identifier for error modal

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1162]
```
  checkError = async (errorText: string) => {
    const message = '-ios class chain:**/XCUIElementTypeAlert/XCUIElementTypeOther/XCUIElementTypeOther/' +
      'XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]';//it works only with this selector
    await expect(await this.errorHeader).toBeDisplayed();
    await expect(await $(message)).toHaveAttribute('value', `${errorText}`);
    await expect(await this.okButton).toBeDisplayed();
  }
```

I'd like this to be renamed to `checkErrorModal` and be moved to `BaseScreen`, so that it's reusable across the app.

We use the same code to render error modals everywhere, so we can use same code to check for it everywhere.

**Comment by tomholub** [comment]
In the same issue, use this general method to look for this modal:

```ts
  it('app setup fails with bad EKM URL', async () => {
    const mockApi = new MockApi();
    mockApi.fesConfig = { clientConfiguration: { key_manager_url: 'INTENTIONAL BAD URL' } };
    await mockApi.withMockedApis(async () => {
      await SplashScreen.login();
      // todo - replace the following pause with wait for modal error
      //   that says "Please check if key manager url set correctly"
      await browser.pause(5000);
    });
  });
```

I'm merging it in https://github.com/FlowCrypt/flowcrypt-ios/pull/1158 unfinished like this.

**Comment by tomholub** [comment]
And this one 

```ts
  it('setup shows meaningful error when FES returns 400', async () => {
    const mockApi = new MockApi();
    mockApi.fesConfig = { returnError: { code: 400, message: "some client err" } };
    await mockApi.withMockedApis(async () => {
      await SplashScreen.login();
      // todo - replace the following pause with wait for modal error
      await browser.pause(5000);
    });
  });
zzz

**Comment by fcvakintos** [comment]
@tomholub What the expected error for this 'setup shows meaningful error when FES returns 400'?
now I get this error, is it correct?
if yes, i need to create new method for this
and I cant to add accessibility Id for error message, maybe Devs can help me?
![Simulator Screen Shot - iPhone 13 - 2021-12-06 at 11 38 03](https://user-images.githubusercontent.com/91205853/144823086-68a7a744-c365-4725-8e6c-6d670126c08e.png)

**Comment by tomholub** [comment]
This is a good error, at least for now

**Comment by tomholub** [comment]
>  and I cant to add accessibility Id for error message, maybe Devs can help me?

What have you tried?

**Comment by fcvakintos** [comment]
@tomholub now it has accessibility id = full error message(check screen), we can use it, but better if we will user unique accessibility id for all errors( like "errorMessage")
<img width="1273" alt="Screenshot 2021-12-06 at 13 12 01" src="https://user-images.githubusercontent.com/91205853/144836594-8b167c60-8cf0-47e3-a4b2-ad9b58465e58.png">

**Comment by tomholub** [comment]
Yes, that's what the issue is about. Have you tried to add the accessibilityId?

**Comment by fcvakintos** [comment]
to this method
<img width="811" alt="Screenshot 2021-12-06 at 13 37 16" src="https://user-images.githubusercontent.com/91205853/144839521-9ce33e77-2e48-4cbb-b9da-bb8e56447fb1.png">
but i dont know how to add it
