### ISSUE TITLE
write appium test that returns FES mock error with wrong error format

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1163]
currently the app gets confused

should still show that it was a 400 from FES url

**Comment by tomholub** [comment]
Something like

```
  it('setup shows meaningful error when FES returns 400 with bad format', async () => {
    const mockApi = new MockApi();
    mockApi.fesConfig = { returnError: { code: 400, message: "this one has bad format", useWrongFormat: true } };
    await mockApi.withMockedApis(async () => {
      await SplashScreen.login();
      // todo - replace the following pause with wait for modal error
      await browser.pause(5000);
    });
  });
```

**Comment by tomholub** [comment]
First please check if we already have similar test. There may already be one

**Comment by fcvakintos** [comment]
@tomholub we have similar test
`it('setup shows meaningful error when FES returns 400', async () => {
    const mockApi = new MockApi();
    mockApi.fesConfig = {
      returnError: {
        code: 400,
        message: "some client err"
      }
    };
    await mockApi.withMockedApis(async () => {
      await SplashScreen.login();
      await BaseScreen.checkModalMessage('Login Error\n' +
          'EnterpriseServerApi 400 message:some client err get http://127.0.0.1:8001/fes/api/');
    });
  });`
But we dont have "useWrongFormat" in this

**Comment by tomholub** [comment]
Thanks for mentioning the similar test.

I guess we need a something like: `returnError: { code: 400, message: "wrong format", formatWrongly: true }`

In which case the Api would return, as an example: `{"wrongFieldError": {"wrongFieldCode": 400, "wrongFieldMessage": "wrong format"}}`

Then we'll see how the app handles that

**Comment by fcvakintos** [comment]
ok, will try

**Comment by fcvakintos** [comment]
for firts case:
<img width="436" alt="Screenshot 2022-05-03 at 17 32 40" src="https://user-images.githubusercontent.com/91205853/166473972-a70433ff-7f17-405c-80ca-5073856ae985.png">
` 400 GET /fes/api/ | {"code":400,"message":"message:wrong format","details":"details:wrong format"}`

**Comment by fcvakintos** [comment]
with "wrong-text" - the same error

**Comment by tomholub** [comment]
You haven't edited the FES mock to actually change the error respomnses based on the new `format` input. Of course it still behaves as before.

**Comment by fcvakintos** [comment]
@tomholub check this pls
is it correct?
`export type FesConfig = {
  returnError?: { code: number, message: string, format?: 'wrong-json' | 'wrong-text'},
  clientConfiguration?: Fes$ClientConfiguration
};`

**Comment by fcvakintos** [comment]
@tomholub what do you mean about implementation in fes config?

**Comment by tomholub** [comment]
Changing just the type definition of the `FesConfig`, and then changing the config in the test, changes nothing.

Some code in the FES mock implementation has to actually look at the updated config and return a modified HTTP response accordingly, no? I shouldn't have to explain this.

I worry that as we will be needing to test more complex scenarios over time (all the simple ones are already tested), you will be not up to the task anymore. You have set up the initial test cases well and got well functioning initial test setup with appium, but your lack of software experience is really showing: when we started working with async/await, when I asked you to update your dependencies, whenever mocks have to be implemented, and also now when mocks have to be modified. It may be that this project has outgrown your current skill. You'll have to make a choice as to whether you want to proactively improve your programming skills to be able to work on more complicated tests here, or if you should be looking to work on simpler test scenarios on another project.
