### ISSUE TITLE
error handling in file/photo manager

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1167]
Here in `takePhoto` we should distinguish the exact "missing access" photo before running `showNoAccessToCameraAlert`. Else a regular error modal.

`selectPhoto` and `selectFromFilesApp` should have errors handled with a modal?

Let's look at this in the future.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1166#discussion_r762467991_

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/144725125-0ff57745-3822-4bbb-9767-4e09ae630fb4.png)

**Comment by tomholub** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/6306961/144741903-026bf3fa-d56d-4bac-879a-544d2756b4af.png">

Yes - error handling should ideally always be at task level, for consistency.

**Comment by ioanmo226** [comment]
> Here in takePhoto we should distinguish the exact "missing access" photo before running showNoAccessToCameraAlert. Else a regular error modal.

Only missing access error is thrown and it's correct to display missing access dialog (as it's currently implemented)
![image](https://user-images.githubusercontent.com/77344191/160585305-f956fe39-f8e5-4a4a-987e-47db71629502.png)

> selectPhoto and selectFromFilesApp should have errors handled with a modal?

SelectPhoto and selectFromFilesApp doesn't throw any errors

**Comment by tomholub** [comment]
I suppose it changed. Thanks
