### ISSUE TITLE
appium paste pass phrase during + into modals setup instead of typing

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1170]
Typing the long pass phrases is too slow (setup 2x and also into pass phrase prompts)

Can we paste them instead?

**Comment by tomholub** [comment]
same thing for searching in emails - to slow to type all the subjects

**Comment by fcvakintos** [comment]
we cant paste text in appium, but we can try use sendKeys method instead setValue

**Comment by fcvakintos** [comment]
@tomholub tried using sendKeys, but it works the same as setValue
i think it is appium problem

**Comment by tomholub** [comment]
This doesn't help? https://appiumpro.com/editions/16-automating-the-clipboard-on-ios-and-android

**Comment by fcvakintos** [comment]
will check

**Comment by fcvakintos** [comment]
it didnt help

**Comment by tomholub** [comment]
Can you be more specific? What have you tried, what didn't work and why?

**Comment by fcvakintos** [comment]
I tried setValue method, tried sendKeys method, tried setClipboard/getClipboard value, tried setValueImmediate method
but it didnt help
 setValue, sendKeys and setValueImmediate works to slow, I think it is Appium or wdio issue

**Comment by tomholub** [comment]
Ok, I'm setting this for later
