### ISSUE TITLE
related db calls should be put into a storage method that has a tx

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1171]
This should be made a transaction in storage (can be another PR later) else it produces inconsistent results.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1165#discussion_r762539199_

**Comment by tomholub** [comment]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/6306961/144742936-4a3eabfe-ce26-4e74-9722-2ea73beaf272.png">

**Comment by tomholub** [comment]
applies to any place that we are doing more than one db write call within some method. Whether that is done in a loop or updating two tables etc.

That way we will not end up with unpredictable database states if one operation succeeds but next one fails.

**Comment by ioanmo226** [comment]
@tomholub Could you describe in more details?
Currently not sure what to do.

**Comment by tomholub** [comment]
@sosnovsky maybe you'd be able to give an example

**Comment by sosnovsky** [comment]
@ioanmo226 we can use `removePubKey` method from task description as example (https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Functionality/Services/Local%20Contacts%20Service/LocalContactsProvider.swift#L121)

```swift
// current version
for key in keys {
    try storage.write {
        storage.delete(key)
    }
}

// transaction version
try storage.write {
    for key in keys {
        storage.delete(key)
    }
}
```

Then all key deletion operations will be executed as 1 transaction, and if any operation fails - full transaction will be cancelled.

**Comment by tomholub** [comment]
And similarly for any other operations that happen either in a loop, or where two database operations happen inside one method.

**Comment by ioanmo226** [comment]
Got it. Thanks for your explanation.
