### ISSUE TITLE
replace forEach with for in

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1172]
I'd like to ban `.forEach` in this codebase. Let's instead use`for thing in things {`, in this case `for newKeyToAdd in newKeysToAdd {`. I'll make another issue, to do this across the codebase.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1165#discussion_r762539544_

**Comment by tomholub** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/6306961/144742955-c8f12b5c-54a9-4ecb-b258-5dfac447b416.png">

**Comment by ioanmo226** [comment]
@tomholub Specific reason for ban forEach?
forEach has its advantage that it simplifies codes.

**Comment by tomholub** [comment]
It's for consistency with our other codebases, on other platforms.

Also to ensure there is always "one obvious way to do a thing". When you have an array and you want to iterate over it and return, then it's `.map` and friends. If you want to iterate without returning, then it's `for x of y`. It makes the intention clear. No need for yet-another-way to do a loop with forEach.

**Comment by tomholub** [comment]
The more the code looks like code on our other platforms, the easier is to do code reviews - which I have to do in 3 different languages. This was one of the reasons we embraced async/await here even though it meant dropping support for iOS < 15.

**Comment by ioanmo226** [comment]
> there is always "one obvious way to do a thing". When you have an array and you want to iterate over it and return, then it's `.map` and friends. If you want to iterate without returning, then it's `for x of y`. It makes the intention clear. No need for yet-another-way to

Ok, Got it

**Comment by ioanmo226** [comment]
@tomholub I still think `forEach` is useful and `forEach` is in every language.
And it makes code a bit long if we completely remove forEach.

Let's take this for an example.
```
keys
  .compactMap { try? PubKeyRealmObject($0) }
  .forEach { self.pubKeys.append($0) }
```

If we refactor this, it would look like this.
```
let realmKeys = keys
    .compactMap { try? PubKeyRealmObject($0) }
for realmKey in realmKeys {
    self.pubKeys.append(realmKey)
}
```

Let me know your thought

**Comment by tomholub** [comment]
Your second version is good. You can (though don't have to) still shorten it as follows:

```swift
for realmKey in keys.compactMap { try? PubKeyRealmObject($0) } {
    self.pubKeys.append(realmKey)
}
```

**Comment by ioanmo226** [comment]
You mean you still want to get rid of `forEach`?

**Comment by tomholub** [comment]
Absolutely

**Comment by ioanmo226** [comment]
Ok
