### ISSUE TITLE
use XCUIElementTypeAlert for appium tests of modals

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1179]
to this method
<img width="811" alt="Screenshot 2021-12-06 at 13 37 16" src="https://user-images.githubusercontent.com/91205853/144839521-9ce33e77-2e48-4cbb-b9da-bb8e56447fb1.png">
but i dont know how to add it

_Originally posted by @fcvakintos in https://github.com/FlowCrypt/flowcrypt-ios/issues/1162#issuecomment-986694763_

**Comment by Kharchevskyi** [comment]
<img width="600" alt="Screenshot 2021-12-12 at 15 27 17" src="https://user-images.githubusercontent.com/13693255/145714490-f5a27326-2a57-4da4-a46c-5193a23d68e5.png">
@fcvakintos @tomholub for what elements do you need accessibility id? would it be enough to add to buttons/titles only? or you need id for view of alert as well?

**Comment by tomholub** [comment]
we'll need it for:
 - title (bolded)
 - message
 - each button

**Comment by Kharchevskyi** [comment]
For now I couldn't find a correct way how to add **custom** accessibility identifiers to UIAlertControllers.
After some investigations I found next issues:

* in case we add aid to controller's view `alert.view.accessibilityIdentifier = "aid-pass-phrase-alert"` all other elements, like buttons became not accessible. Please check screenshot.

<img width="600" alt="Screenshot 2021-12-21 at 18 23 49" src="https://user-images.githubusercontent.com/13693255/146964048-421928f4-84dc-48c1-bac7-798369766d25.png">

* it is possible to add via Apple's private APIs. But this solution is fragile and actually not recommended by Apple.
https://stackoverflow.com/questions/38117410/how-can-i-set-accessibilityidentifier-to-uialertcontroller

* It looks like it is possible to get elements (title, message, buttons) by their default ids. 
@fcvakintos correct me if I wrong, but I think it would be enough for tests?
<img width="600" alt="Screenshot 2021-12-12 at 15 27 27" src="https://user-images.githubusercontent.com/13693255/146966690-68dec1b6-20ef-4f66-87c4-77d472a933e4.png">
<img width="600" alt="Screenshot 2021-12-21 at 17 24 27" src="https://user-images.githubusercontent.com/13693255/146966825-0daef214-4222-4291-8f01-1d118a640ee2.png">

**Comment by tomholub** [comment]
Not good to use private apis.

In this particular case, we'll have to go with the default accessibility ids like `ok` and `cancel`.

What is the default accessibility id of the title and message? Would it be `Pass Phrase` and `Confirm Pass Phrase` respectively?

**Comment by sosnovsky** [comment]
I also found `driver.getAlertText()` function which gives full text of current alert, so it'll return `Pass Phrase\nConfirm Pass Phrase`
And for checking if alert is shown I use `-ios predicate string:type == 'XCUIElementTypeAlert'` selector.

Checking alert text looks like this:
```js
get currentModal() {
  return $("-ios predicate string:type == 'XCUIElementTypeAlert'");
}

checkModalText = async (message: string) => 
  await ElementHelper.waitElementVisible(await this.currentModal);
  const alertText = await driver.getAlertText();
  expect(alertText).toEqual(message);
}
```

Maybe this findings will be useful for this issue too.

**Comment by tomholub** [comment]
I like Roman's approach, clear and straight forward.

**Comment by tomholub** [comment]
That means, for this issue, @fcvakintos please update the tests to use that approach.

@Kharchevskyi thanks for looking into this.
