### ISSUE TITLE
crash when loading IMAP inbox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1181]
[FlowCrypt_2021-12-06-145538_Dmitrys-MacBook-Pro-2.crash.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/7660798/FlowCrypt_2021-12-06-145538_Dmitrys-MacBook-Pro-2.crash.zip)

_Originally posted by @fcvakintos in https://github.com/FlowCrypt/flowcrypt-ios/issues/484#issuecomment-986749718_

**Comment by Kharchevskyi** [comment]
@tomholub is it possible for you to share credentials which was used?

**Comment by tomholub** [comment]
shared over email
