### ISSUE TITLE
update appium/README.md with how to install/use/configure appium inspector

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1182]
@Kharchevskyi later please add to appium/README.md how to install and use the above tool and how to configure it so that others can also do it. I'm filing a separate issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1127#issuecomment-986772870_

**Comment by Kharchevskyi** [comment]
@tomholub please check https://github.com/FlowCrypt/flowcrypt-ios/blob/master/appium/README.md
is it ok? or need to add smth more?

**Comment by tomholub** [comment]
yes this helps
