### ISSUE TITLE
unify fatal error screens, either with an abstract VC or make both one VC

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1184]
This is very similar to the other error screen we have. It should be the same screen and same VC, with a boolean init parameter to offer to reset storage or not.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1165#discussion_r762541537_

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/144875437-f6f8e578-c289-4800-8038-6f552f90a47f.png)

**Comment by ioanmo226** [comment]
I don't think so.
This issue seems outdated. I can't even find FatalErrorViewController
