### ISSUE TITLE
appium test for canceling login

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1186]
Thanks! I'll file a separate issue for an appium tests, to do separately after the code fix.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1185#issuecomment-987154727_

**Comment by fcvakintos** [comment]
@tomholub I will add this steps to settings spec, ok?

**Comment by fcvakintos** [comment]
@tomholub or i should create new spec?

**Comment by tomholub** [comment]
Actually, was the login spec that I deleted the only one that contained log-out? If yes then it could be brought back and renamed as "cancel login + log in + log out"

**Comment by fcvakintos** [comment]
ok, will create new spec
