### ISSUE TITLE
menu bar items accessibility ids

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1187]
@Kharchevskyi @tomholub I found new issue after this fix, now we dont have accesibility id for menu bar items
it is after this fix i think, because now accessibility id = "INBOX" is not unique
<img width="1288" alt="Screenshot 2021-12-07 at 10 26 21" src="https://user-images.githubusercontent.com/91205853/144993756-aa5cc612-085e-466b-b281-2401667d7938.png">

can we add accessibility id for menu bar items?
something like this - menubarIteminbox, menubaritemchat and etc

_Originally posted by @fcvakintos in https://github.com/FlowCrypt/flowcrypt-ios/issues/1127#issuecomment-987685871_

**Comment by Kharchevskyi** [comment]
@fcvakintos as far as I see the problem is only with the first cell?

<img width="1244" alt="Screenshot 2021-12-07 at 13 53 35" src="https://user-images.githubusercontent.com/13693255/145026599-bf38b6ba-83e5-4563-8ac9-8cb0a5edf07f.png">

**Comment by fcvakintos** [comment]
@Kharchevskyi, yes, if you open chat screen and open the menu - accessibility id for chat on menu bar will not displayed

**Comment by tomholub** [comment]
Would be good to have something like `menuItemINBOX` for the accessibilityIds as Dmitry suggested

**Comment by Kharchevskyi** [comment]
@fcvakintos can you please confirm that this is what you need? 
Also for the future what are the requirements for accessibility id for you? 
Does it matter if the id is capitalized/lowercased/camelized?



<img width="600" alt="Screenshot 2021-12-08 at 17 29 03" src="https://user-images.githubusercontent.com/13693255/145236068-ddf0f013-28d1-463c-b8e4-fb466650d63b.png">

<img width="600" alt="Screenshot 2021-12-08 at 17 38 12" src="https://user-images.githubusercontent.com/13693255/145237113-e03938a2-ec10-46e4-b6da-5710ea6fbb43.png">

<img width="600" alt="Screenshot 2021-12-08 at 17 38 05" src="https://user-images.githubusercontent.com/13693255/145237165-61bcefb3-a4c2-4de2-a26e-30da1fb63400.png">

**Comment by fcvakintos** [comment]
@Kharchevskyi yes, it is cool
