### ISSUE TITLE
index-based accessibilityIds for recipient bubbles/badges in compose

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1197]
Ok, then we need updated accessibility identifiers to include the color for the recipient bubbles.

`to1orange` - first recipient has orange color (or `to1green` - first recipient has green color, etc)
`to2red` - second recipient has red color

And so on.

so its `"to" + index + color`, where color can be `gray|orange|red|green`

Once you have these, you will be checking that for example `to1gray` text contains `available.on@attester.test`

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/736#issuecomment-988832107_

**Comment by tomholub** [comment]
We did something similar with attachments before, I think. I think it may have been zero-indexed.

**Comment by Kharchevskyi** [comment]
@fcvakintos can you please help with next error when running `npm run-script test.mock.all`?

```
[0-0] Force-quitting node process because unhandled rejection at: Promise {
  <rejected> /Users/antonkharchevskyi/git/flowcrypt-ios/appium/tests/specs/mock/setup/SetupFailsWithInconsistentClientConfiguration.spec.ts:1
  import { MockApi } from 'api-mocks/mock';
  ^^^^^^
 ```

**Comment by fcvakintos** [comment]
I had this error yesterday, I fixed it "npm install", it helped me
what is the branch or run?

**Comment by Kharchevskyi** [comment]
Current master

**Comment by fcvakintos** [comment]
let me try

**Comment by fcvakintos** [comment]
it works for me on current master
try remove node_modules and npm install

**Comment by Kharchevskyi** [comment]
Thanks. Will try

**Comment by fcvakintos** [comment]
@tomholub let me know if its help

**Comment by Kharchevskyi** [comment]
yes, works for me, thank you
