### ISSUE TITLE
format of accessibility ids

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1199]
> Also for the future what are the requirements for accessibility id for you? 
> Does it matter if the id is capitalized/lowercased/camelized?

_Originally posted by @Kharchevskyi in https://github.com/FlowCrypt/flowcrypt-ios/issues/1187#issuecomment-988924329_

Good question. I would actually most prefer a dash. And I would like to always prepend it with "aid" (differentiate from value content which is queried the same way) to become  `aid-menu-item-INBOX`

**Comment by tomholub** [comment]
@fcvakintos does appium have any problem with dashes in accessibility ids?

**Comment by Kharchevskyi** [comment]
The easiest solution would be just to have one lowercased word. Is it possible?

**Comment by Kharchevskyi** [comment]
so ideally is one camelized word I think?

**Comment by tomholub** [comment]
ideal are dashes. `aid-menu-item-INBOX`, `aid-navigation-title-INBOX`, `aid-to-1-red`, `aid-attachment-1` etc. Then it would be the same as we have it on browser extension. Just need to be sure that appium can support it. It should.

**Comment by ioanmo226** [comment]
Possible duplicate of #1449 and should be closed once #1449 is implemented.

**Comment by tomholub** [comment]
closing as a duplicate
