### ISSUE TITLE
compose: body text improvements

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#12]
- [x]  Remove msg placeholder when focused
- [x] make typed text show in black
- [x]  use standard size for composed text: 17
- [x] make compose field scrollable (currently cannot see text if I write too many lines)

**Comment by tomholub** [comment]
here example of too much text / cannot scroll:

![image](https://user-images.githubusercontent.com/6306961/61993338-f9921d00-b09c-11e9-86ae-3d7ab110ca07.png)

**Comment by RomanKovalchuk2019** [comment]
Fixed in pr #32
