### ISSUE TITLE
mock ui test with --enterprise flag: FES offline (shows error)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1208]

**Comment by ioanmo226** [comment]
![image](https://user-images.githubusercontent.com/77344191/209650134-5febf5de-8a85-48e3-9bf2-079ad8747a0b.png)

Should app return error for --enterprise flag and FES returns 404?
If so, then what's this test? (This test doesn't pass --enterprise flag though. Even if we pass --enterprise flag, app currently doesn't show any error too)

**Comment by tomholub** [comment]
enterprise build + 404 = allow setup workout fes. no error.

**Comment by ioanmo226** [comment]
Then what does this issue title mean (mock ui test with --enterprise flag: FES offline (shows error))?

**Comment by tomholub** [comment]
wrongly worded issue i think. can close
