### ISSUE TITLE
mock ui test with --enterprise flag: FES returns 404 (allows setup without FES)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1209]

**Comment by tomholub** [comment]
1) do a mock test of setup
2) set up fes API to return error code 404 with message "on error 404 app should act like there is no FES"
3) go through initial stage of setup (login) and check the resulting setup screen. It should be different than the regular setup screen. Please share screenshot. Then we'll settle exactly what to test on it.

**Comment by tomholub** [comment]
Test should be called `enterprise app allows setup without FES when FES returns 404`

**Comment by fcvakintos** [comment]
@tomholub I get this screen 
<img width="415" alt="Screenshot 2022-03-28 at 12 37 44" src="https://user-images.githubusercontent.com/91205853/160370695-b763dff0-d49f-4dc4-a545-ae0c1c2e740e.png">

after 
` mockApi.fesConfig = {
      returnError: {
        code: 404,
        message: "on error 404 app should act like there is no FES"
      }
    };`

**Comment by fcvakintos** [comment]
@tomholub Is it correct?

**Comment by tomholub** [comment]
That looks good

**Comment by tomholub** [comment]
You can just test that you find this particular screen, with that text and those buttons.

**Comment by fcvakintos** [comment]
@tomholub thanks, cool will finish today
