### ISSUE TITLE
Configure Test Reports in Semaphore

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#1215]
Semaphore has ability to render easy-to-use UI from `.xml` test report (https://flowcrypt.semaphoreci.com/workflows/e0b03549-9198-4e88-8b4b-20093c51a526/summary)
I think it should be useful for us and give better insight on app test results.

<img width="1251" alt="Screenshot 2021-12-13 at 10 17 43" src="https://user-images.githubusercontent.com/1062093/145776228-c1f83df4-dc21-43e0-8e5c-1b2b4a90809a.png">

**Comment by tomholub** [comment]
There seems to be a formatter for it https://webdriver.io/docs/junit-reporter/

**Comment by sosnovsky** [comment]
It'll also make finding failed tests much easier, as with current `info` log level it's quite difficult to see which tests haven't passed.

<img width="1392" alt="Screenshot 2021-12-20 at 22 04 26" src="https://user-images.githubusercontent.com/1062093/146825953-75096c0d-3b2a-40b3-ab64-b74c8d66aa7d.png">

**Comment by tomholub** [comment]
Agree, the logs got more verbose with the change, making the reporter more useful.

If it bothers you and doesn't look too difficult, you can add it.

**Comment by sosnovsky** [comment]
Okay, I'll check it today-tomorrow.

By the way, how do you currently check screenshots of failed tests - by connecting to ssh and opening screenshots folder or there is another way? As I thought they'll be available on `Artifacts` tab https://flowcrypt.semaphoreci.com/artifacts/workflows/892a3732-c7d7-4309-a12c-780fe59d3090

**Comment by tomholub** [comment]
They are in artifacts, but not where you're looking.

Have to click on the `Appium UI tests` job which takes you here https://flowcrypt.semaphoreci.com/jobs/f1901355-712a-4684-9293-bce59f86463d and only then the artifacts which takes you here https://flowcrypt.semaphoreci.com/artifacts/jobs/f1901355-712a-4684-9293-bce59f86463d?project=9bd38bf4-4a38-4cb3-b551-38302af1eb07

So it's a job artifact, not workflow artifact. I guess you could, with a change, make it a workflow artifact too, to be more accessible.

**Comment by sosnovsky** [comment]
Ah, now I see them, thanks. Should be okay to have them on job level
