### ISSUE TITLE
test emails clogging e2e account

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1230]
Could we be sending these elsewhere eg robot@flowcrypt.com?

![image](https://user-images.githubusercontent.com/6306961/146420792-51dd6cee-addb-40b6-aa9d-8808c4ca6d58.png)

And delete the existing ones.

**Comment by tomholub** [comment]
The above screenshot is in inbox, which should be only consisting of messages that are there permanently for tests.

**Comment by fcvakintos** [comment]
@tomholub hey, what should I do?

**Comment by tomholub** [comment]
See why are messages sent there during test, and if we can send them to robot@flowcrypt.com instead.

**Comment by fcvakintos** [comment]
@tomholub 
it is old emails, new emails are sent to robot@flowcrypt.com
we don't send the emails to e2e account now

**Comment by tomholub** [comment]
In that case, please delete them from e2e inbox.

**Comment by fcvakintos** [comment]
@tomholub I don't see these emails in e2e inbox
<img width="1339" alt="Screenshot 2021-12-24 at 12 41 17" src="https://user-images.githubusercontent.com/91205853/147345879-25fe50fd-0da3-422e-aaa1-ef86cc483da8.png">

**Comment by tomholub** [comment]
someone may have deleted them since
