### ISSUE TITLE
API class for calling FES endpoints to upload message to web portal

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1231]
part of #955 

same as https://github.com/FlowCrypt/flowcrypt-android/issues/1615

**Comment by sosnovsky** [comment]
@IvanPizhenko I'm trying to upload message to FES server using `POST /api/v1/message` endpoint, but receive the same `Uploaded file doesn't contain a valid PGP message` error as in Android task https://github.com/FlowCrypt/flowcrypt-android/issues/1615#issuecomment-997987123

Here is body of POST request (I added new line after `-----END PGP MESSAGE-----` as you advised in mentioned task)
```
--13F50D63-2F56-4239-8B32-7C60DBE7CF87
Content-Disposition: form-data; name="details"
Content-Type: application/json; charset=utf-8
{"associateReplyToken":"reply token","cc":[],"to":["test@flowcrypt.com"],"bcc":[],"from":"test@flowcrypt.com"}
--13F50D63-2F56-4239-8B32-7C60DBE7CF87
Content-Disposition: form-data; name="content"; filename="content"
Content-Type: application/octet-stream
-----BEGIN PGP MESSAGE-----
Version: FlowCrypt iOS 0.2 Gmail Encryption
Comment: Seamlessly send and receive encrypted email

wV4DZQdhGPK/uXASAQdA7yRB0t1jOq3VykCoTpyh3cxEd3uxi+WNPXrbDYiW
PnMwXQV0Cq8iwTCjsvA9N+T7KlaM4QzYOdPzdQpU+23332ZvQLzmcU6lJJhD
kGtyOkmFwV4DZQdhGPK/uXASAQdA95bWrjI1FGhFRRcnI/UeHLk8FAMU9Siy
8S7lOObw8jIw0kKP8r20zU2KJVhWFkhHXTZ7OyodE6T9yM/2BMjDVFQbPfKn
tApuSvZPrVECdHqu0qoBFU6pUb8v3ztV8siAUHOnzxsuq0C0XBtmAXrViB4J
bXgR/3C7Gm+t89dVVoFeLQl6nmGS6qQsIpBKNAb0YMJbh593EzXTWcbp7iXQ
nW+sSJdtiKiebcJ6ZShswmC8JERQhBgK/vzqOrjjBnLiKO73l8mcbH2TQB2J
+SlPLl0TPCF726YWOoRethHj1SzqGAHaN7wgO1ZZlZw/ZtKpFmPkv6Oj4H4P
kmZfWQ=3D=3D
=3DFfLd
-----END PGP MESSAGE-----

--13F50D63-2F56-4239-8B32-7C60DBE7CF87--
```

Is anything else should be added there? Thanks

**Comment by IvanPizhenko** [comment]
@sosnovsky You must send only part starting with `-----BEGIN PGP MESSAGE-----` and ending with `-----END PGP MESSAGE-----` (with newline in the end), please make sure you don't add that leading and trailing email related stuff.

**Comment by tomholub** [comment]
The data as Roman printed it above is the whole `form-multipart` data. On a casual look, it looks correct to me, and as far as I can see, the pgp part only contains an armored pgp message.

**Comment by tomholub** [comment]
@sosnovsky you could send a password-encrypted message from the browser extension with the network tab open for debugging. Then right-click the request to FES and choose "export as cURL". Print the export here (with id token redacted), then we can compare the contents.

**Comment by tomholub** [comment]
@sosnovsky also, what is the error id that you got back?

**Comment by sosnovsky** [comment]
I was able to make successful request using Postman, but still trying to make it work on iOS - currently receiving such error:
```json
{
  "code" : 400,
  "message" : "Uploaded file doesn\'t contain a valid PGP message",
  "details" : "For more details, see FlowCrypt Enterprise Server logs."
}
```

**Comment by sosnovsky** [comment]
It finally works! Thanks for your advices guys
The issue was with missing additional line-break after `Content-Type: ..`, so instead of
```
Content-Type: application/octet-stream
-----BEGIN PGP MESSAGE-----
...
```

it should be 
```
Content-Type: application/octet-stream

-----BEGIN PGP MESSAGE-----
...
```
