### ISSUE TITLE
update decrypt error tests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1234]
This will need appium tests added and updated:
 - update test of subject "encrypted - MDC hash mismatch - modification detected - should fail" to check for the error message
 - update test of subject "not integrity protected - should show a warning and not decrypt automatically" to check for the error message
 - add another email to verify: "key mismatch unexpectedly produces a modal" where you should now be able to successfully view email body

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1219#issuecomment-997022897_

**Comment by fcvakintos** [comment]
@tomholub hey, i have a question
In "key mismatch unexpectedly produces a modal" email we have 2 attachments, should i check all or only the first is enough?
if we need to check all i need to update check attachments method

**Comment by tomholub** [comment]
You don't need to check the attachments in that email. We'll have a specific test for that later, after #1233 . Just test the message body is present.
