### ISSUE TITLE
add error handling approach to repo docs / readme

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1244]
We have extension with `errorMessage` property for `Error` - https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Extensions/Error%2BExtension.swift#L12

It checks if `Error` has some custom message using `CustomStringConvertible` protocol, otherwise it uses `localizedDescription` property.

Here is example of error with custom messages - https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Functionality/Services/Compose%20Message%20Service/ComposeMessageError.swift

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-ios/issues/1241#issuecomment-999489160_

**Comment by tomholub** [comment]
Should also add that there should generally be only one "grand" try/catch inside each `Task` and that there should be generally a single `Task` right in each handler. And then all errors downstream should generally be re-thrown.

**Comment by ioanmo226** [comment]
Sorry, I'm a bit confused...
Do I have to modify readme or update code here?

**Comment by tomholub** [comment]
update the readme, to document our approach to error handling. It could be a new document like `code-design.md` that you link from the main readme. Over time, it will collect similar decisions to make them clear to less frequent contributors.
