### ISSUE TITLE
UI tests processing fails on Semaphore

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#1245]
Currently all UI tests are failing with error
```
ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Could not create simulator with name 'appiumTest-D8A59CC9-56F8-4E2A-B76E-015403E84D37-iPhone 13', device type id 'iPhone 13', with runtime ids 'com.apple.CoreSimulator.SimRuntime.iOS-15-0', '15.0'
```

**Comment by tomholub** [comment]
Could this be an environment change on Semaphore? I know recently you mentioned upgrading to 15.2 to fix some issues, worth a try.

**Comment by sosnovsky** [comment]
Yes, looks like the same issue, updating to `15.2` fixed tests running - https://flowcrypt.semaphoreci.com/jobs/98f4b5a3-4fec-490e-a5e5-6e46423af4a4
