### ISSUE TITLE
iPad - Fix layout for setup screens

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#1273]
Verify screens for ipad
- [x] SetupBackupsViewController
- [x] SetupManuallyEnterPassPhraseViewController

SetupGenerateKeyViewController
<img src="https://user-images.githubusercontent.com/13693255/148206349-53d97ea1-b3b9-4ba5-a71d-1302ae5c4576.png" width="300">

**Comment by tomholub** [comment]
yup - these should be better aligned
