### ISSUE TITLE
'Couldn't get active FES url' error on startup

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#1275]
@tomholub I tried to login to outlook account and get the error
<img width="433" alt="Screenshot 2022-01-05 at 16 26 49" src="https://user-images.githubusercontent.com/91205853/148233876-72fa68e5-7900-4bc8-93ed-f198bc3bce26.png">
can you check pls?

_Originally posted by @fcvakintos in https://github.com/FlowCrypt/flowcrypt-ios/issues/484#issuecomment-1005732008_

**Comment by Kharchevskyi** [comment]
#1267
