### ISSUE TITLE
on consumer release, tolerate FES errors 4xx, 5xx and SSL errors when calling opportunistically

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1277]
I think, on cosumer release, we should also tolerate 4xx and 5xx errors when opportunistically calling FES. I'll file another issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1207#discussion_r767203747_

**Comment by tomholub** [comment]
Currently only tolerated "404" and all network errors. But if we get a 400 or 500, currently it will fail.

**Comment by tomholub** [comment]
This above only applies to calling FES "opportunistically", when the app doesn't know know if customer is running FES or not.

**Comment by tomholub** [comment]
Currently SSL error on email domain on the consumer app domain can cause the following:

![image](https://user-images.githubusercontent.com/6306961/177740987-3f868fe4-3504-4751-ba76-2c00e874bef8.png)

**Comment by tomholub** [comment]
Calling a server opportunistically means a call is attempted without knowing whether any server is actually there or not. If a server is there and responds, we do one thing, if a server is not there, we do another thing.

It's what we do when calling the WKD on recipient domain. Maybe there is openpgpkey.recipient.com server running, maybe not - we just try.

And that's the same thing we are doing when setting up the consumer version of the iOS app when calling FES. If fes.user.com server is there, then we use it and consider it an "enterprise environment", and if not, we consider it a "consumer environment".

Currently, if fes.user.com is returning 4xx or 5xx errors or if there is SSL error, (which could be caused simply by the user domain server setup that didn't expect that any app will call that subdomain), the consumer app will refuse to finish set up, which is not desirable.

On enterprise app though, it's correct to refuse to set up because FES is expected to be running.

**Comment by ioanmo226** [comment]
@tomholub Thank you for your explanation.
Now I have a better understanding of above issue.
But still not sure how to reproduce this issue.
Could you tell me how to reproduce above ssl error?

> Currently SSL error on email domain on the consumer app domain can cause the following:

**Comment by tomholub** [comment]
To reproduce it, temporarily, you could maybe add `<some ip> fes.flowcrypt.com` into your hosts file. Like, maybe you put the ip address of google.com or some other website. That should send requests their way during setup, which would hopefully produce an SSL error.

It will mimic someone signing up who's domain at fes.domain.com returns SSL error.

**Comment by ioanmo226** [comment]
Got it. thanks
