### ISSUE TITLE
cannot log out if error happens during app startup

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1279]
> Also it looks that it's impossible to log out if any error occurs during app startup. Please check #1267 There is no other way than delete app if it happens

I'll track that as a separate issue

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1276#issuecomment-1005995217_

**Comment by tomholub** [comment]
@Kharchevskyi did you mean app startup on an already set up account?

Or simply if the error happens after authentication?

**Comment by Kharchevskyi** [comment]
Looks like if any error occurs during `AppStartup.initializeApp`.

But in my case it was during `getUserOrgRulesIfNeeded`
```
Task {
    window.rootViewController = BootstrapViewController()
    window.makeKeyAndVisible()

    do {
        await setupCore()
        try await appContext.dataService.performMigrationIfNeeded()
        try await setupSession()
        try await getUserOrgRulesIfNeeded()
        chooseView(for: window)
    } catch {
        showErrorAlert(of: error, on: window)
    }
}
```

error alert has only one button
```
private func showErrorAlert(of error: Error, on window: UIWindow) {
    let alert = UIAlertController(title: "Startup Error", message: "\(error.localizedDescription)", preferredStyle: .alert)
    let retry = UIAlertAction(title: "Retry", style: .default) { _ in
        self.initializeApp(window: window)
    }
    alert.addAction(retry)
    window.rootViewController?.present(alert, animated: true, completion: nil)
}
```
I think we should add `use another account button` or smth like that

**Comment by tomholub** [comment]
There should be a retry + log out + user another account, as you say.

If there isn't another account, tapping it should show the splash screen as if when adding a secondary account.

**Comment by ioanmo226** [comment]
@tomholub I can't reproduce this issue.
Could you tell me how to reproduce this issue?

**Comment by tomholub** [comment]
Try setting up an account, then replacing `try await getUserOrgRulesIfNeeded()` with `throw AppError.general('test')` and rebuild the app.

Then observe what happens during app startup

**Comment by ioanmo226** [comment]
Sorry. I don't get you. why do we need to replace that code?
It will return error in that place. Further code will not proceed I think.

![image](https://user-images.githubusercontent.com/77344191/157492718-094a372a-c6d8-4d11-896b-04c8aae5a716.png)

**Comment by tomholub** [comment]
replacing that line, temporarily, allows you to simulate the situation when one of those lines throw an error.

When this happens, the current result is what you see on the screen.

The intended result should be that the modal should have both `Retry` and `Log out` options, so that user could log out and go through setup again.

**Comment by ioanmo226** [comment]
Aha, got it
