### ISSUE TITLE
BUG: Inbox screen displays only 20 emails after updating inbox screen on e2e account

### ISSUE THREAD

**Issue by fcvakintos** [FlowCrypt/flowcrypt-ios#1284]
Steps:

1. Login to e2e account
2. Observe Inbox screen - 36 emails are displayed
3. Pull down for refresh
4. Observe screen

**Actual:** Only 20 emails are displayed on Inbox screen
**Expected:** All items should be displayed

Uploading Screen Recording 2022-01-10 at 15.45.26.mov…

**Comment by tomholub** [comment]
@sosnovsky can you please later see if you can triage it on the e2e account?

**Comment by sosnovsky** [comment]
> @sosnovsky can you please later see if you can triage it on the e2e account?

For sure, I'll check it

**Comment by fcvakintos** [comment]
@sosnovsky how many email should be displayed on inbox screen with pagination?

**Comment by sosnovsky** [comment]
> @sosnovsky how many email should be displayed on inbox screen with pagination?

I created separate issue for ui test - https://github.com/FlowCrypt/flowcrypt-ios/issues/1288
