### ISSUE TITLE
Inbox emails disappear when going back from email detail screen

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#1289]
Steps to reproduce:
1. Scroll down inbox to load page 2 of emails
2. Open any email
3. Go back to inbox

**Expected**: 2 pages of emails are shown
**Actual**: only page 1 is shown, emails from page 2 were removed (noticed in https://github.com/FlowCrypt/flowcrypt-ios/issues/1288#issuecomment-1010006530)

**Comment by tomholub** [comment]
What should be the appropriate fix for this? Will we keep the emails in memory, or re-fetch them more appropriately when going back?

**Comment by sosnovsky** [comment]
It happens because app refreshes messages list after marking thread as `read` (https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Controllers/Inbox/InboxViewController.swift#L428)
This `refresh` loads only first page of messages and sets it as inbox messages list (replacing previously loaded emails).

Probably it's not necessary to refresh full messages list when marking 1 thread as `read`, so we can just reload cell with opened thread. But need to check why `refresh` was initially needed there.

**Comment by tomholub** [comment]
The refresh was probably so that it reloads the data after the change - the message could have moved (trash), moved (archive), got read (mark as read), got unread (mark as unread), etc.

I guess not strictly necessary to do the reload, if we know what action we just made.

**Comment by sosnovsky** [comment]
Agree, I think in this case we should implement callback with `action` param and then refresh messages list accordingly.
As currently `refresh` loads only first page of messages, so changes to messages from second page are not loaded.
