### ISSUE TITLE
searching email by recipient name doesn't find any result

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1291]
I have an email from "Joe" both in the inbox and in all mail (archived).

I'm currently in inbox and tap on the search field, and enter "Joe".

It doesn't find any email. The person's email address is eg `Joe Doe <joe.doe@example.test>`

**Comment by ioanmo226** [comment]
@tomholub Please confirm if this issue is still reproducible.
For me, searching email by recipient name works fine.

**Comment by tomholub** [comment]
looks ok now
