### ISSUE TITLE
auto-select export option for distribution

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1292]
I'm always manually choosing "export" here, is it possible to tell it to always use that option?

<img width="313" alt="image" src="https://user-images.githubusercontent.com/6306961/149129968-f9edd3e6-c00d-4ea6-b123-a28ce3ba7558.png">

Also, is it possible to similarly pre-select "manage signing automatically" so it doesn't ask me?

**Comment by sosnovsky** [comment]
I think there is no way to pre-select these options on Xcode. But we can use `fastlane` to make export process automatic and faster.
We just need to create fastlane actions for different build types, so you'll just need to execute `fastlane export` or `fastlane export_enterprise` for generating build and (optionally) uploading it to App Store Connect.

**Comment by tomholub** [comment]
understood - thank you. That would be for another time.
