### ISSUE TITLE
check which of these ui tests are already implemented and where - compose

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1299]
as part of https://github.com/FlowCrypt/flowcrypt-ios/issues/1294, here is a list of browser extension ui tests that may or may not be already implemented in Appium.

 - `compose - nogpg and revoked recipients trigger both warnings`
 - `compose - freshly loaded pubkey`
 - `compose - list of pubkeys gets refetched in compose`
 - `compose - can load contact based on name`
 - `compose - signed with entered pass phrase + will remember pass phrase in session`
 - `compose - can load contact based on name different from email`
 - `compose - nogpg and non-revoked recipients trigger nopgp warning only`

To proceed with this and similar lists, clone the codebase at https://github.com/FlowCrypt/flowcrypt-browser, npm install, then search the codebase for the above test titles. Then understand what the test does from the source, and see if we have equivalent test on iOS. For each of the items, either write the name of the iOS test, or write that a test is missing.

Don't start implementing the tests yet, only check if they are missing or not.

**Comment by fcvakintos** [comment]
@tomholub checked
1. `compose - nogpg and revoked recipients trigger both warnings` - we have tests for revoked and expired pubkey, and we have for no public key user. is it the same?
2. `compose - freshly loaded pubkey` - I think we have this case
3. `compose - list of pubkeys gets refetched in compose` -  not covered
4. `compose - can load contact based on name` -  covered
5. `compose - signed with entered pass phrase + will remember pass phrase in session` - covered
6. `compose - can load contact based on name different from email` - covered
7.  `compose - nogpg and non-revoked recipients trigger nopgp warning only` - I think this case is not covered but im not sure

**Comment by tomholub** [comment]
For the covered ones - also include the name of equivalent test on iOS. Read issue description carefully, it was written above.

**Comment by fcvakintos** [comment]
1. `compose - nogpg and revoked recipients trigger both warnings` - `sending message to user with expired/revoked public key produces modal`
`2. `compose - freshly loaded pubkey`  - `check filled compose email after reopening app and text autoscroll`
3. `compose - list of pubkeys gets refetched in compose` - not covered
4. `compose - can load contact based on name` - `user is able to select recipient from contact list using contact name`
5. `compose - signed with entered pass phrase + will remember pass phrase in session` - `user is able to send encrypted email when pass phrase session ended + move to trash, delete`
6. `compose - can load contact based on name different from email` - `user is able to select recipient from contact list using contact name`
7. `compose - nogpg and non-revoked recipients trigger nopgp warning only` - `sending message to user without public key produces password modal`

can you check is it correct?

**Comment by tomholub** [comment]
Thank you. The issue `compose - list of pubkeys gets refetched in compose` - not covered - will be covered in https://github.com/FlowCrypt/flowcrypt-ios/pull/1321 so I can close this issue.

**Comment by fcvakintos** [comment]
yes
