### ISSUE TITLE
killing app mid-setup of second user will show splash-screen on next start (instead of first user inbox)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1300]
Once in a while, I open the app and it greets me with a splash screen "Continue with Gmail" even though I'm logged in. I think when I tapped on continue, then tapped "cancel", it may have even "realized" that there is some user logged in and showed me inbox. Or maybe I killed the app and then it showed inbox normally. I'm not sure, I'll continue to observe it.

@sosnovsky have you observed something similar? I've been observing something like this on 0.6.0 but I don't know exactly what is the issue or how to reproduce.

**Comment by sosnovsky** [comment]
No, I haven't observed such issue. Does it happen on simulator or on the real device?

**Comment by tomholub** [comment]
Real device. I'll pay more attention next time I use the app, and will add more details.

**Comment by tomholub** [comment]
I wonder if trying to log into IMAP/SMTP earlier could have affected this. Will try

**Comment by tomholub** [comment]
To reproduce:
1) log into account 1 and set up until you see inbox
2) log into account 2 but don't finish set up (I tried this with IMAP/SMTP login, but could also work with Gmail login where setup is not finished)
3) kill the app (or wait a long time :-) )
4) open the app

expected: 
 - either I should see the half-setup user 2 and continue where I left off (or abort setup)
 - or I should see my previously setup user 1 inbox (I think current implementation was meant to do this, which would be fine)

actual:
 - splash screen

To recover from the above state, currently I have to `Continue with Gmail` -> choose user 1, which will send me to inbox without going through setup.

**Comment by tomholub** [comment]
Given that this is a bit of a special scenario, and our main customer didn't mention multi-account situations, I'm moving this to later milestone.
