### ISSUE TITLE
ui test: app updates older public keys to newer but not vice versa

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1301]
These two tests can be searched on browser extension test suite by name: 
 - `do not auto-refresh key if older version of the same key available on attester`
 - `auto-refresh expired key if newer version of the same key available`

The iOS test will be similar, except instead of manual key import, all keys will be imported from attester (iOS doesn't support manually importing public keys into the app).

Setup: add two more public keys in `attesterPublicKeySamples`:

`keyOlderVersion`:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEYd8pKhYJKwYBBAHaRw8BAQdAXQ9bBzlYPwy3mQD5MIQSkuOyEomESHHo
AAiUi0enB77NKFVwZGF0aW5nIGtleSA8dXBkYXRpbmcua2V5QGV4YW1wbGUu
dGVzdD7CeAQQFgoAIAUCYd8pKgYLCQcIAwIEFQgKAgQWAgEAAhkBAhsDAh4B
AAoJEMfJkMGi6njd9HUA/0ZdZaaOFy0hM+GpEnzK+A/G3bLe9Kulh4jT8+4j
JqcKAP0V+pga+B1v98aeF8cRlgQPEyWtYUqZLcDLBQ6r3BEfDM44BGHfKSoS
CisGAQQBl1UBBQEBB0BPkVSyVsZ+vsF4e4NbVsq/YNjqL0JQI+t6OHc5YxJS
SgMBCAfCYQQYFggACQUCYd8pKgIbDAAKCRDHyZDBoup43Y+gAQDSVD/EDqCE
dSL33ptMlhwRCKHGiKcVmKwucxYkk6apFQEA018565fZcvtb339L2s/IIxLs
4621FX8Sy6kpR7mAzQo=
=3UnZ
-----END PGP PUBLIC KEY BLOCK-----
```

`keyNewerVersion`:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEYd8pKhYJKwYBBAHaRw8BAQdAXQ9bBzlYPwy3mQD5MIQSkuOyEomESHHo
AAiUi0enB77NKFVwZGF0aW5nIGtleSA8dXBkYXRpbmcua2V5QGV4YW1wbGUu
dGVzdD7CeAQQFgoAIAUCYd8pKgYLCQcIAwIEFQgKAgQWAgEAAhkBAhsDAh4B
AAoJEMfJkMGi6njd9HUA/0ZdZaaOFy0hM+GpEnzK+A/G3bLe9Kulh4jT8+4j
JqcKAP0V+pga+B1v98aeF8cRlgQPEyWtYUqZLcDLBQ6r3BEfDM44BGHfKSoS
CisGAQQBl1UBBQEBB0BPkVSyVsZ+vsF4e4NbVsq/YNjqL0JQI+t6OHc5YxJS
SgMBCAfCYQQYFggACQUCYd8pKgIbDAAKCRDHyZDBoup43Y+gAQDSVD/EDqCE
dSL33ptMlhwRCKHGiKcVmKwucxYkk6apFQEA018565fZcvtb339L2s/IIxLs
4621FX8Sy6kpR7mAzQrOOARh3yuYEgorBgEEAZdVAQUBAQdAglzBCJCRj29J
THYvVGaNESiiVKmyrTEnXonGUS58TwMDAQgHwmEEGBYIAAkFAmHfK5gCGwwA
CgkQx8mQwaLqeN3PWwD9ErvC+ufnX0O2AmZDz67QfFH6tA1t1/wUEHgzBXEe
gc8BAMaYm3AlSGbX1rJYgUtCWukkLuURdECIzerG2UuP87ID
=dQen
-----END PGP PUBLIC KEY BLOCK-----
```

Both can be written as single test called `app updates older public keys to newer but not vice versa` as follows:

stage 1

1) serve `keyOlderVersion` on attester mock for email `updating.key@example.test`
2) compose new email, enter `updating.key@example.test`, wait for it to load
3) go to Settings -> Contacts -> `updating.key@example.test` -> public keys (tap the first one)
  - Check the date of the "signature" - expect that exact string.
  - check "last fetched" and remember it to compare in below steps
  - check fingerprints - there should be exactly two of them - expect exactly these two

stage 2 

4) change attester mock settings to serve `keyNewerVersion` for `updating.key@example.test`
5) compose new email, enter `updating.key@example.test`, wait for it to load
6) go to Settings -> Contacts -> `updating.key@example.test` -> public keys (tap the first one)
  - Check the date of the "signature" - this should now be different, more recent time than in stage 1. Expect this exact (different then before) string in the test
  - check "last fetched" and confirm that it's a more recent time than stage 1
  - check fingerprints - there should be exactly three of them - expect exactly these three at this stage 2

stage 3

7) change attester mock settings to serve `keyOlderVersion` for `updating.key@example.test` again
8) compose new email, enter `updating.key@example.test`, wait for it to load
9) go to Settings -> Contacts -> `updating.key@example.test` -> public keys (tap the first one)
  - Check the date of the "signature" - this should remain the same as stage 2
  - check "last fetched" and confirm that it's a more recent time, even more recent than stage 2
  - check fingerprints - there should be exactly three of them - expect exactly these three at this step

stage 4:

10) delete the public key by tapping the trash icon on that screen
11) compose new email, enter `updating.key@example.test`, wait for it to load
12) go to Settings -> Contacts -> `updating.key@example.test` -> public keys (tap the first one)
  - Check the date of the "signature" - expect exactly the same as in stage 1
  - check "last fetched" - the date/time should be later than all previous stages
  - check fingerprints - expect exactly the same as stage 1

**Comment by fcvakintos** [comment]
@Kharchevskyi could you help me with aid for Public key screen?
I need add for all values from this screen
like `signatureValue` for date of signature
I tried to add but get strange ids
<img width="1277" alt="Screenshot 2022-01-17 at 17 57 50" src="https://user-images.githubusercontent.com/91205853/149802283-375d23f4-370e-44cb-8d1f-1a5951cd229e.png">
<img width="537" alt="Screenshot 2022-01-17 at 17 58 01" src="https://user-images.githubusercontent.com/91205853/149802295-2169cbff-c474-4ce3-a8ef-d7637105b9c5.png">

**Comment by tomholub** [comment]
`aidSignatureDate`

**Comment by fcvakintos** [comment]
@tomholub do we need new ticket for this?

**Comment by fcvakintos** [comment]
@tomholub I get this error for all mock tests now
<img width="389" alt="Screenshot 2022-01-18 at 10 39 53" src="https://user-images.githubusercontent.com/91205853/149902247-0bfd6aec-3572-406c-909c-7d6ca929d005.png">

**Comment by fcvakintos** [comment]
@Kharchevskyi do you know why this error appears?^

**Comment by Kharchevskyi** [comment]
I think @tomholub can help you with it

aids added https://github.com/FlowCrypt/flowcrypt-ios/pull/1316

**Comment by fcvakintos** [comment]
@Kharchevskyi thanks

**Comment by fcvakintos** [comment]
@tomholub in stage 4 - `delete the public key by tapping the trash icon on that screen`
from what screen?
1st or 2nd?
<img width="413" alt="Screenshot 2022-01-19 at 15 30 56" src="https://user-images.githubusercontent.com/91205853/150140548-2f33bbc1-e15c-4901-b539-fa027af63777.png">
<img width="411" alt="Screenshot 2022-01-19 at 15 31 02" src="https://user-images.githubusercontent.com/91205853/150140556-070701cd-ed29-4c5e-be4e-9ef592a901c5.png">

if from 1st  -  it works correct(it removes contact from contact list), if from second it removes only pubkey - and I see contact in the list but it doesnt have pub key(check screen)
<img width="386" alt="Screenshot 2022-01-19 at 15 33 06" src="https://user-images.githubusercontent.com/91205853/150140947-8d170c59-5f43-427b-a695-bdbd32e40a83.png">

and if is compose new email with this recipient it shows me this message
<img width="388" alt="Screenshot 2022-01-19 at 15 35 22" src="https://user-images.githubusercontent.com/91205853/150141374-a9446290-c165-4f93-9322-7f386a6d8c1c.png">

**Comment by fcvakintos** [comment]
and I cant check fingerprint for this user -> it is empty

**Comment by tomholub** [comment]
This one is supposed to delete whole contact + pubkey, as you say:

![image](https://user-images.githubusercontent.com/6306961/150513550-d77a969f-02a6-460d-8f0b-5d9f8de896de.png)

This one is supposed to only delete pubkey but leave the contact in:

![image](https://user-images.githubusercontent.com/6306961/150513628-b04ebce3-55e6-41a7-9bca-2307914bee01.png)

You can tap either of the two. The result is that if you go back to compose screen, it should refetch the key and be green.

Did I understand it correctly that you are seeing it go gray in stage 4, when using `delete only pubkey` icon?

But it shows green when using `delete whole contact` icon?

That would be a bug, I think. Please confirm.
