### ISSUE TITLE
`MailServiceProviderFactory.services` not on main thread while generating a key during setup

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#1310]
First issue I faced now is that call to `MailServiceProviderFactory.services` executes not on main thread both for gmail and imap
<img width="400" alt="Screenshot 2022-01-14 at 22 01 39" src="https://user-images.githubusercontent.com/13693255/149577673-72f94f66-bd10-4ba0-a4ca-7f73786a7cbc.png">

Which cause issue with Main thread checker
<img width="400" alt="Screenshot 2022-01-14 at 22 03 07" src="https://user-images.githubusercontent.com/13693255/149577846-64f3c34d-92ef-42ff-ab7b-ee04e8196ece.png">

@sosnovsky probably would need assist with this issue. 
_Will fill a separate issue for that_

_Originally posted by @Kharchevskyi in https://github.com/FlowCrypt/flowcrypt-ios/issues/1303#issuecomment-1013441209_

**Comment by sosnovsky** [comment]
I checked it - looks like adding `@MainActor` to `setupAccount` method in `SetupGenerateKeyViewController.swift` (https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Controllers/Setup/SetupGenerateKeyViewController.swift#L91) fixes this issue.
