### ISSUE TITLE
iPad - fix layout for recipients

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#1315]
<img width="501" alt="Screenshot 2022-01-13 at 14 51 41" src="https://user-images.githubusercontent.com/13693255/149945920-b4ba89a3-6f7c-4559-ace7-ba1355d6e47e.png">

**Comment by tomholub** [comment]
There should also be an `X` next to each bad recipient so that the user can tap them to remove. Would that be a separate issue?
