### ISSUE TITLE
User is not able to login via Gmail 

### ISSUE THREAD

**Issue by fcvakintos** [FlowCrypt/flowcrypt-ios#1317]
Try to login to 'e2e.enterprise.test@flowcrypt.com' -> get error on set up pass phrase
<img width="389" alt="Screenshot 2022-01-18 at 10 39 53" src="https://user-images.githubusercontent.com/91205853/149959626-44544c5d-cdcd-4f2e-a724-2d1fd8b9c953.png">

**Comment by sosnovsky** [comment]
Same for me - can't login with `e2e.enterprise.test@flowcrypt.com` account

**Comment by tomholub** [comment]
sorry, working on this. EKM configuration issue

**Comment by tomholub** [comment]
it's fixed now
