### ISSUE TITLE
inconsistency between contact trash icon and public key trash icon result

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1327]
This one is supposed to delete whole contact + pubkey, as you say:

![image](https://user-images.githubusercontent.com/6306961/150513550-d77a969f-02a6-460d-8f0b-5d9f8de896de.png)

This one is supposed to only delete pubkey but leave the contact in:

![image](https://user-images.githubusercontent.com/6306961/150513628-b04ebce3-55e6-41a7-9bca-2307914bee01.png)

You can tap either of the two. The result is that if you go back to compose screen, it should refetch the key and be green.

Did I understand it correctly that you are seeing it go gray in stage 4, when using `delete only pubkey` icon?

But it shows green when using `delete whole contact` icon?

That would be a bug, I think. Please confirm. The two are supposed to work the same when you go to compose screen.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1301#issuecomment-1018392512_

**Comment by fcvakintos** [comment]
@tomholub i checked using my account and after deleting only pubkey - the account is displayed grey in compose and new pub key is present in contact details

https://user-images.githubusercontent.com/91205853/150751087-6a50e965-8f7a-4ba4-a5ae-abe487e025b5.mov

**Comment by tomholub** [comment]
Thank you for the video, this is a bug for sure. I'm glad you mentioned it.

**Comment by tomholub** [comment]
Interestingly, after you go back to Settings -> contacts, it seems that it did save the new public key. But it didn't render it. I think, if you went back to compose one more time and added that email one more time, it would likely be green.

The bug that needs to be fixed is that when the email is entered after deleting the public key, it's supposed to be gray at first but then it should turn green as soon as the public keys are re-fetched.

Similarly, if we only had an orange (expired) public key and we search for it again, it should be orange at first then turn gray once the pubkey is refetched.

**Comment by tomholub** [comment]
@sosnovsky once you're done with 0.7.0 issues, please look at this. You can test manually, and @fcvakintos will write an automated test for it.
