### ISSUE TITLE
set custom timezone for simulator in ui tests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1329]
Of course it is a timezone issue. Can you set in appium runner to run the iOS simulator on UTC timezone regardless of the timezone of the host? There must be settings for it.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1321#discussion_r789875899_

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/150575768-712bdabc-bcfa-4fa5-ae98-b448b4366d68.png)

**Comment by fcvakintos** [comment]
@tomholub, I tried to resolve this issue, i found 1 solution:
We need change timezone for semaphore CI when we run automation test( using "sudo ln -sf /usr/share/zoneinfo/UTC /etc/localtime"
and we will get UTC time for signature date 
<img width="629" alt="Screenshot 2022-01-25 at 11 30 40" src="https://user-images.githubusercontent.com/91205853/150950059-d5d685ab-71e4-471d-8ff5-0ec23c0d8f35.png">
but for local we get another time for my timezone it is UTC+2

**Comment by fcvakintos** [comment]
I found another way
we get date and convert it to UTC timezone, it works on local and for remote
<img width="937" alt="Screenshot 2022-01-27 at 10 07 36" src="https://user-images.githubusercontent.com/91205853/151317175-1415185e-e84b-4295-9ef0-55d43dd918b9.png">

**Comment by tomholub** [comment]
There you go.
