### ISSUE TITLE
Open attachments issues

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#1343]
When opening big attachments app freezes for quite a long and ui is not responsive, beside that it is possible to tap on the attachment multiple times which cause to opening screen multiple times

See attached video
https://user-images.githubusercontent.com/13693255/151363401-448a13af-018c-4128-add5-c02ce2a7cd90.MP4

* Check that file processing is not on main thread 
* Disable multiple taps
* Add activity indicator (maybe with possibility to cancel processing)

**Comment by Kharchevskyi** [comment]
```
"ℹ️[ThreadDetailsViewController] Start loading message"
"⚙️[AttachmentViewController] base64 encoding time is 0.297 ms"
"⚙️[AttachmentViewController] base64 encoding time is 0.277 ms"
"⚙️[AttachmentViewController] base64 encoding time is 0.285 ms"
```

**Comment by tomholub** [comment]
Do you want to look into this or do you think @ivan-ushakov should look into it?

**Comment by Kharchevskyi** [comment]
Sure. Will take a look
