### ISSUE TITLE
update OpenPGP.js to v5

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1362]
Likely, flowcrypt-ios uses an older version of OpenPGP.js than browser extension does.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1357#issuecomment-1028299363_

**Comment by IvanPizhenko** [comment]
@tomholub I'm stuck in typescript a bit.
v4:
```typescript
    class BasePacket {
      tag: enums.packet;
      read(bytes: Uint8Array): void;
      write(): Uint8Array;
    }
```

v5:
```typescript
abstract class BasePacket {
  static readonly tag: enums.packet;
  public read(bytes: Uint8Array): void;
  public write(): Uint8Array;
}
```
Then, our code:
```
  public static isPacketPrivate = (p: OpenPGP.AnyKeyPacket): p is PrvPacket => {
    return p.tag === openpgp.enums.packet.secretKey || p.tag === openpgp.enums.packet.secretSubkey;
  }
```

This works with v4, but with v5 it gives error:
```
Property 'tag' does not exist on type 'BasePublicKeyPacket'. Did you mean to access the static member 'BasePublicKeyPacket.tag'?
```
I don't understand how to rewrite this to preserve same functionality.

**Comment by tomholub** [comment]
When a method has a return type of `x is y`, in this case `p is PrvPacket`, it's a type-testing method.

Into the method goes an unknown, or too regeric type.

Out of the method goes boolean. If the boolean is true, then typescript knows that the value in the input (the x) is of type y.

It's our job, within that method, to safely establish if it's that wanted type or not.

In this particular case, if you have an input variable that may or may not have the `tag` on it, and wanted variable that you know does have the tag, then you would do this:

```
if (!p || typeof p !== 'object') {
  return false; // now we know it's an object so it's safe to test its properties
}
return (p as PrvPacket).tag === openpgp.enums.packet.secretKey || (p as PrvPacket).tag === openpgp.enums.packet.secretSubkey;
```

I suppose, in this particular case, you should not need the initial `if`, because the type coming in is already clarified as `AnyKeyPacket` which is an object?

This may not get you 100% there but should give you the idea.

**Comment by IvanPizhenko** [comment]
`(p as PrvPacket).tag === openpgp.enums.packet.secretKey` also doesn't work. It refuses to access static member on object, and if I access static member by class name, then what will be the sense of this function at all? Where those static members go in resulting JavaScript? Maybe I should try accessing it via prototype?

**Comment by IvanPizhenko** [comment]
it turns like correct solution is following:
```typescript
  public static isPacketPrivate = (p: OpenPGP.AnyKeyPacket): p is PrvPacket => {
    return p instanceof SecretKeyPacket || p instanceof SecretSubkeyPacket;
  }
```

**Comment by IvanPizhenko** [comment]
I'm stuck with following issue: openpgp v4 have had methods for reading whole stream content (`openpgp.streams.readToEnd()`). There is no equivalent in v5. I don't know how to implement it and I couldn't find anything suitable on the Internet so far.
Here is what it all about: some methods do return `MaybeStream<Data>`, where `Data = string | Uint8Array` and `MaybeStream<T> = T | Stream<T>`, where `Stream<T> = WebStream<T> | NodeStream<T>`, where:
```typescript
}
interface WebStream<T extends Data> extends BaseStream<T> { // copied+simplified version of ReadableStream from lib.dom.d.ts
  readonly locked: boolean; getReader: Function; pipeThrough: Function; pipeTo: Function; tee: Function;
  cancel(reason?: any): Promise<void>;
}

interface NodeStream<T extends Data> extends BaseStream<T> { // copied+simplified version of ReadableStream from @types/node/index.d.ts
  readable: boolean; pipe: Function; unpipe: Function; wrap: Function;
  read(size?: number): string | Uint8Array; setEncoding(encoding: string): this; pause(): this; resume(): this;
  isPaused(): boolean; unshift(chunk: string | Uint8Array): void;
}
```
where:
```typescript
interface BaseStream<T extends Data> extends AsyncIterable<T> { }
```

**Comment by IvanPizhenko** [comment]
Function `readToEnd()` seems to exist inside library, but it is missing in `openpgp.d.ts` and I am not sure if it is accessible outside at all.

**Comment by IvanPizhenko** [comment]
Added following to `openpgp.d.ts`:
```typescript
// ----- BEGIN ADDED BY FLOWCRYPT -----
export function readToEnd<T extends Data>(input: MaybeStream<T>, concat?: (list: T[]) => T): Promise<T>;
// ----- END ADDED BY FLOWCRYPT -----
```
If function like `readKey()` done similar way, with no special "exporting" in library source code, then this one should also work.

**Comment by IvanPizhenko** [comment]
Trying to run tests. Getting errors:
```shell
> ava build/ts/test.js --verbose


  Uncaught exception in build/ts/test.js

  build/ts/test.js:15

   14: const chai_1 = require("chai");                             
   15: const pgp_1 = require("./core/pgp");                        
   16: const endpoints_1 = require("./mobile-interface/endpoints");

  ReferenceError: OpenPGP is not defined
```
No ideas how to solve this. @tomholub @rrrooommmaaa Any ideas?

**Comment by tomholub** [comment]
> Added following to `openpgp.d.ts`:
> 
> ```ts
> // ----- BEGIN ADDED BY FLOWCRYPT -----
> export function readToEnd<T extends Data>(input: MaybeStream<T>, concat?: (list: T[]) => T): Promise<T>;
> // ----- END ADDED BY FLOWCRYPT -----
> ```
> 
> If function like `readKey()` done similar way, with no special "exporting" in library source code, then this one should also work.

You can file an issue with OpenPGP.js repo, not having this in types (or not having it accessible) may be a possible oversight.

**Comment by tomholub** [comment]
> Trying to run tests. Getting errors:
> 
> ```shell
> > ava build/ts/test.js --verbose
> 
> 
>   Uncaught exception in build/ts/test.js
> 
>   build/ts/test.js:15
> 
>    14: const chai_1 = require("chai");                             
>    15: const pgp_1 = require("./core/pgp");                        
>    16: const endpoints_1 = require("./mobile-interface/endpoints");
> 
>   ReferenceError: OpenPGP is not defined
> ```
> 
> No ideas how to solve this. @tomholub @rrrooommmaaa Any ideas?

OpenPGP.js 5 no longer does a one big import like to import everything, instead you are expected to be importing from individual modules of the library. It has been all decoupled. Not sure if that addresses the issue.

**Comment by tomholub** [comment]
To debug it, follow the path of how is OpenPGP.js imported in `endpoints`, and compare with how is v5 supposed to be imported in NodeJS.

**Comment by IvanPizhenko** [comment]
@tomholub I've rewored it, but now I'm getting build errors:
```
npm run build
...
ERROR in ./build/ts/core/pgp-msg.js
Module not found: Error: Can't resolve '../lib/openpgp' in '/home/ivan/pro/flowcrypt/flowcrypt-ios/Core/build/ts/core'
 @ ./build/ts/core/pgp-msg.js 14:18-43
 @ ./build/ts/mobile-interface/endpoints.js
 @ ./build/ts/entrypoint-bare.js

... and more errors like this ...
```

**Comment by tomholub** [comment]
I'd have to see a draft for this, this way it's just guesswork

**Comment by IvanPizhenko** [comment]
I'll try some more things and let you know if I have any progress

**Comment by IvanPizhenko** [comment]
I've tried but nothing worked. So I think I need help with this.

**Comment by IvanPizhenko** [comment]
Another problem is that some things used in the code are no longer exported from library. They've cleaned up interface, and that is good, but it doesn't make it easier to port to it. For example, hash calculation still inside library, but not exported.

**Comment by IvanPizhenko** [comment]
After some manipulations I've got it running test. However not all tests passing.

**Comment by IvanPizhenko** [comment]
Something strange happens. In this code (I've added few debug outputs):
```typescript
  public static lastSig = async (key: Key): Promise<number> => {
    console.log((Object as any).__oid(key));
    await key.getExpirationTime(); // will force all sigs to be verified
    const allSignatures: SignaturePacket[] = [];
    for (const user of key.users) {
      allSignatures.push(...user.selfCertifications);
      console.log(`selfcerts=${user.selfCertifications.length}`);
    }
    for (const subKey of key.subkeys) {
      allSignatures.push(...subKey.bindingSignatures);
      console.log(`sbb=${subKey.bindingSignatures.length}`);
    }
    allSignatures.sort((a, b) => (b.created ? b.created.getTime() : 0) - (a.created ? a.created.getTime() : 0));
    console.log(`nsig=${allSignatures.length}`);
    let i = 0;
    for (const sig of allSignatures) {
      console.log(`sig[${i++}]=${JSON.stringify(sig)}\n`);
    }
    for (const sig of allSignatures) console.log(`${(Object as any).__oid(sig)} => ${sig.verified}`);
    const newestSig = allSignatures.find(sig => sig.verified === true);
    if (newestSig) {
      return newestSig.created ? newestSig.created.getTime() : 0;
    }
    throw new Error('No valid signature found in key');
  }
```
`await key.getExpirationTime();` really forces verification and 1 signature is verified successfully and `verfied` set to true on it, but/ and it then gets included into `allSignatures`. However, in `allSignatures` it does not have `verified` set for some reason.
@tomholub @rrrooommmaaa any ideas?

**Comment by IvanPizhenko** [comment]
Update: It seems to be error in openpgp.js

**Comment by IvanPizhenko** [comment]
@tomholub Btw, we will anyway have to make our own custom modifications to openpgp.js, because from what I can see from current communication with openpgp.js maintainers, not all our modifications will be happily accepted into upstream. And so we have to comply with LGPL, which means we **MUST** distribute modified sources and do it under **exactly under LGPL** (so current "limitations apply" clause does not work for that). Therefore, I suggest to have separate public repo called like `flowcrypt-modified-gpl-thirdparty`, where we will put all modified GPL and LGPL stuff.

**Comment by IvanPizhenko** [comment]
Can't catch, what is wrong here, they look as equal:
```
AssertionError {
    actual: {
      algorithm: 'rsaEncryptSign',
      algorithmId: 1,
      bits: 2047,
    },
    expected: {
      algorithm: 'rsaEncryptSign',
      algorithmId: 1,
      bits: 2047,
    },
    message: 'expected { algorithm: \'rsaEncryptSign\', bits: 2047, algorithmId: 1 } to equal { algorithm: \'rsaEncryptSign\', bits: 2047, algorithmId: 1 }',
    operator: 'deepStrictEqual',
    showDiff: true,
  }
```

**Comment by IvanPizhenko** [comment]
Got all TS tests passing.

**Comment by IvanPizhenko** [comment]
Got all TS tests passing locally and on CI.
