### ISSUE TITLE
0.6.0 testflight feedback crashes

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1365]
These happened on 0.6.0 release

[testflight_feedback.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/8006564/testflight_feedback.zip)

[testflight_feedback2.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/8006565/testflight_feedback2.zip)

[testflight_feedback_3.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/8006563/testflight_feedback_3.zip)

**Comment by ivan-ushakov** [comment]
@tomholub 

All have the same crash point:
```
0   libswiftCore.dylib                  0x00000001865125a8 _assertionFailure(_:_:file:line:flags:) + 304 (AssertCommon.swift:132)
1   FlowCrypt                           0x0000000100c82c94 EncryptedStorage.storage.getter + 392 (EncryptedStorage.swift:74)
```

In code:
```
var storage: Realm {
    do {
        let configuration = try getConfiguration()
        Realm.Configuration.defaultConfiguration = configuration
        let realm = try Realm(configuration: configuration)
        return realm
    } catch {
        fatalError("failed to initiate realm: \(error)") // line 74 in tag 0.6.0
    }
}
```

Looks like app can not initialise Realm for some reason. Let's add Alert with error message.

**Comment by tomholub** [comment]
ok

**Comment by ivan-ushakov** [comment]
Looks like it is not possible with current approach to show alert because we must return Realm object anyway. We could store error and show it later.

**Comment by tomholub** [comment]
Couldn't it be thrown upwards and then display wherever we consume that property?

**Comment by ivan-ushakov** [comment]
> Couldn't it be thrown upwards and then display wherever we consume that property?

Let's try this approach. It will make code a bit verbose because of `throws` but one the other hand we will know what was wrong.
