### ISSUE TITLE
extract `getIdToken` methods from `SetupGenerateKeyViewController` and `EnterpriseServerApi`

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#1367]
`SetupGenerateKeyViewController` and `EnterpriseServerApi` have the same `getIdToken` method.
It should be extracted to remove code duplication

**Comment by tomholub** [comment]
I don't know a good place for it. If you don't know either, you can make a class `IdTokenUtils`
