### ISSUE TITLE
add new accessibility id for thread messages

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#1370]
__Originally posted by @fcvakintos in https://github.com/FlowCrypt/flowcrypt-ios/issues/959#issuecomment-1032448491__

**Comment by fcvakintos** [comment]
@Kharchevskyi any updates about this task?

**Comment by Kharchevskyi** [comment]
Got sick. 
Will get back to it this week

**Comment by fcvakintos** [comment]
thanks

**Comment by fcvakintos** [comment]
@Kharchevskyi hey, any updates?

**Comment by Kharchevskyi** [comment]
Sorry for delay. Will add in few hours

**Comment by fcvakintos** [comment]
can you ping me?
I will check on branch

**Comment by Kharchevskyi** [comment]
@fcvakintos can you please check `feature/issue-1370-aid` and let me know what other locators do you need?

**Comment by fcvakintos** [comment]
@Kharchevskyi I dont see any new aids, can you check pls?

**Comment by Kharchevskyi** [comment]
Can you please let me know what exact ids you need?

**Comment by fcvakintos** [comment]
1. for sender emails, for each one - should be like sender-0-aid, sender-1-aid
<img width="357" alt="Screenshot 2022-02-21 at 15 57 43" src="https://user-images.githubusercontent.com/91205853/154969110-b18a13f8-2781-4d18-bf0e-7e2fd91c83c2.png">
2. for each date - something like date-0-aid, date-1-aid
3. for each arrow 
<img width="429" alt="Screenshot 2022-02-21 at 16 25 32" src="https://user-images.githubusercontent.com/91205853/154974007-64a62c6c-3ff6-4681-815d-c778c8eba4a6.png">

4. for each message body
<img width="353" alt="Screenshot 2022-02-21 at 16 27 04" src="https://user-images.githubusercontent.com/91205853/154974222-c6449b86-0971-4390-9511-ea0714d87a8f.png">

**Comment by Kharchevskyi** [comment]
@fcvakintos Please let me know if this enough

<img width="1175" alt="Screenshot 2022-02-21 at 15 27 12" src="https://user-images.githubusercontent.com/13693255/154985129-5b0c10a8-3a37-47d0-a49a-e8623d769afa.png">
<img width="1173" alt="Screenshot 2022-02-21 at 15 28 32" src="https://user-images.githubusercontent.com/13693255/154985134-eb21c7e7-7ba3-4d4a-8a68-5364cb62b5a0.png">
<img width="1157" alt="Screenshot 2022-02-21 at 15 27 05" src="https://user-images.githubusercontent.com/13693255/154985135-ee147fc7-578d-4028-8e06-049b11b835a7.png">
<img width="1123" alt="Screenshot 2022-02-21 at 15 27 22" src="https://user-images.githubusercontent.com/13693255/154985138-097da966-012b-4ea1-8da9-1dd032943f13.png">
<img width="1119" alt="Screenshot 2022-02-21 at 15 27 30" src="https://user-images.githubusercontent.com/13693255/154985140-269bcffa-62d3-48a4-84ef-3578aab95c94.png">
<img width="1163" alt="Screenshot 2022-02-21 at 15 27 47" src="https://user-images.githubusercontent.com/13693255/154985142-cba838b4-561f-4825-8c9f-b740a8696e40.png">

**Comment by fcvakintos** [comment]
@Kharchevskyi , thank you
can we push it to my branch for test?

**Comment by Kharchevskyi** [comment]
Sure, you can merge my branch into yours. Let me know if you would need any help

**Comment by fcvakintos** [comment]
@Kharchevskyi can we put value for messages?
because i cant get value from this element
<img width="1272" alt="Screenshot 2022-02-22 at 14 30 04" src="https://user-images.githubusercontent.com/91205853/155132736-ca4de650-4202-4bb4-b789-eb35d4b49a4f.png">

**Comment by fcvakintos** [comment]
something like for Email(label or value)
<img width="1262" alt="Screenshot 2022-02-22 at 14 35 10" src="https://user-images.githubusercontent.com/91205853/155133541-eab8f793-6ffb-4f72-9688-5b659d3781f3.png">

**Comment by Kharchevskyi** [comment]
please check https://github.com/FlowCrypt/flowcrypt-ios/pull/1395/commits/e23ffa16bc470407456045c554f38ac088debc57
<img width="900" alt="Screenshot 2022-02-22 at 21 03 12" src="https://user-images.githubusercontent.com/13693255/155219037-058901af-b07a-4adc-951f-c831f3f4ab56.png">
