### ISSUE TITLE
storage corrupted - unable to open realm

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1373]
![image](https://user-images.githubusercontent.com/6306961/153182594-1a0a4024-f953-43d0-b8be-10f7a8c5a540.png)

**Comment by tomholub** [comment]
haven't experienced in a while. May have actually fixed this in last version.

**Comment by tomholub** [comment]
this is still a problem, unfortunately

**Comment by tomholub** [comment]
It just happened to me, simultaneously on both the Enterprise build and the Consumer build.

That suggests it's likely not a concurrency issue or a race condition as previously thought (wouldn't happen to both apps at once) but more likely, some of the information used to store the storage encryption key is not stable over the lifetime of the app. And it changed on both apps at once.

**Comment by tomholub** [comment]
Likely culprit could be our use of `UserDefaults` in the process of retrieving the storage encryption key index, combined with `NSFileProtectionComplete` which seems unpredictable.

https://developer.apple.com/forums/thread/667959

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/6306961/157652758-a7b37621-9ce8-4b4c-be3a-d8c4d6aef74c.png">

**Comment by tomholub** [comment]
This relates to `KeyChainService.getStorageEncryptionKey`. Currently, the encryption key is stored/retrieved as follows:

- encryption key is stored in OS key chain under a dynamic index
- the index under which the key is stored, is itself stored in UserDefaults
- when user first starts the app, these are empty. Therefore a new dynamic index is generated, stored in UserDefaults, and then this string is used as an index of a key stored in key chain
- when user restarts the app, the app checks UserDefaults. From there it retrieves the index. Uses the index to retrieve the encryption key from key chain, and uses that to decrypt the database

My hypothesis, from reading the above link/comment, is that we are seeing the following situation:
1) user sets up the app normally, with `SOME-INDEX` stored in `UserDefaults` and therefore with the encryption key stored in keychain at index `SOME-INDEX-indexStorageEncryptionKey`. The actual bytes of the encryption key could be anything, let's say `ABCD...`. With this it encrypts the database file at `Documents/encrypted.realm`
2) user uses the app normally for a while
3) at some point, ios pre-warms the app in the background, or maybe something else happens that causes `UserDefaults` to be empty during start. In this situation, the app will think that no key is set up and therefore it will make a new index like `ANOTHER-INDEX` and store that in `UserDefaults` instead. That makes the full index `ANOTHER-INDEX-indexStorageEncryptionKey`. App tries to get a key from there, but none is there. It makes a new one and now we have an encryption key like `1234...`, different from above. Then app proceeds to read existing `Documents/encrypted.realm` which of course fails with the above error.

**Comment by tomholub** [comment]
With that in mind, the possible fixes could be:

a) if app is starting and we detect it's in background eg `UIApplication.shared.applicationState == .background`, then don't initialize storage. This could be the simplest fix, if it works.

b) if a database file already exists at the target path, never initialize a new encryption key (index). If database file exists but there is no encryption key to be found, throw an error.

We could do both, actually.

@ioanmo226 do you have any thoughts?

**Comment by tomholub** [comment]
can't. It just sometimes happens.

**Comment by ioanmo226** [comment]
hmm... how did you reproduce it when it happened?

**Comment by tomholub** [comment]
simply opened the app

**Comment by ioanmo226** [comment]
I see

**Comment by ioanmo226** [comment]
@tomholub what happened when you tap `Reset` button?

**Comment by tomholub** [comment]
What do you think about the thoughts above - is it plausible?

**Comment by ioanmo226** [comment]
I still don't know much about how encryption & realm database works in current app.
Need to dig deep.

**Comment by ioanmo226** [comment]
@tomholub I checked deeply and I couldn't find anywhere which resets UserDefaults.
IMHO UserDefault is not a problem in this case.
Digging more now.

**Comment by ioanmo226** [comment]
@tomholub 
Error was thrown when initializing Realm so I think getting encryption key worked fine.
Otherwise, modal will show encryption key related error message.
 
So my suggestion is here.

When we catch Realm initialization error(due to decryption error as shown in above screen or something like that), we catch that event and delete current realm database file & re-initialize database using the encryption key we got above.

Let me know what you think.

**Comment by tomholub** [comment]
Have you read the conversation at https://developer.apple.com/forums/thread/667959 ?

**Comment by tomholub** [comment]
And also https://github.com/FlowCrypt/flowcrypt-ios/issues/1373#issuecomment-1063994757 ? My guess was not that we don't have an encryption key, but that empty user default due to the behavior described in above link cause us to get a new encryption key which would of course error with an already set up database.

We can't keep deleting user storage, that's not a solution.

**Comment by ioanmo226** [comment]
I think I now find why this issue happens. Your guess was right I think.
From what I've found, when user uses app & force-closes app and let device locked for 30+ min, then device will start to prewarm apps.

**Comment by ioanmo226** [comment]
@tomholub 
I think I now find why this issue happens. Your guess was right I think.
From what I've found, when user uses app & force-closes app and let device locked for 30+ min, then device will start to prewarm apps.
In this prewarm case, protected datas are not available as app is not fully active.
To fix this issue, we need to check `UIApplication.shared.isProtectedDataAvailable` and wait until this value gets true. (`UIApplication.shared.isProtectedDataAvailable` is false in prewarm case. As a result our app regenerated encryption key when app gets active and return above decrypt error).

Here's a link to full article.
https://sourcediving.com/solving-mysterious-logout-issues-on-ios-15-8b818c089466

**Comment by tomholub** [comment]
ok, now we're talking

**Comment by tomholub** [comment]
I''ll also put a last-resort guard/throw for `UIApplication.shared.isProtectedDataAvailable` in `KeyChainService`. In case we miss something in the future.

Hopefully that's the last time I've seen this issue - it's embarrassing.
