### ISSUE TITLE
Consistent code formatting

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-ios#1376]
Sure, it's well readable. I was just thinking for consistency. Let's file another issue to look into formatting across the TS code later.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1374#discussion_r805207497_

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa @tomholub Do we have any code style settings for JavaScript and TypeScript in another projects?

**Comment by tomholub** [comment]
Yes- you can copy settings from flowcrypt-browser vscode project. It includes vscode extensions for auto formatting. Additionally, should copy config files for both tslint and eslint from flowcrypt-browser, plus there are some custom rule implementations.

**Comment by IvanPizhenko** [comment]
@tomholub I've copied some settings from flowcrypt-browser, but I'd not say I found there something really related to typescript except enabling format-on-save in VS Code. Please look at #1431.
