### ISSUE TITLE
make OpenPGP.js v5 code work with iOS JavaScriptCore

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1379]
https://github.com/FlowCrypt/flowcrypt-ios/pull/1374/files#r805180770

<img width="831" alt="image" src="https://user-images.githubusercontent.com/6306961/153776588-cdef8ebb-0abc-4a57-bad1-9f8475a0f24f.png">

**Comment by tomholub** [comment]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/6306961/153776732-c99b0be6-b5d7-48b5-83e1-87aeb0857f70.png">

**Comment by tomholub** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/6306961/153776756-d27c1f58-e7bd-4907-8a18-3d7210687164.png">

**Comment by tomholub** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/6306961/153776885-38d63811-6612-44a6-b51e-a0e1a600c8b8.png">

**Comment by ivan-ushakov** [comment]
@tomholub

I tried to use new `flowcrypt-ios-prod.js.txt` and when I run application, I get
```
"❗️[Js][Core] SyntaxError: Unexpected token \',\'. Cannot declare a lexical variable twice: \'ReadableStream\'., 44400:undefined"
```

I want to continue with integration of OpenPGP library update in iOS, if you don't mind.

**Comment by ivan-ushakov** [comment]
After commenting that line out (because I found that such variables were already defines above), I got this error:
```
"⚙️ Can\'t find variable: exports\n -> js global code@"
"❗️[Js][Core] ReferenceError: Can\'t find variable: exports, 43914:30"
```
So it looks like merging (or generating) of JavaScript code produces wrong code for JavaScriptCore engine.

**Comment by ivan-ushakov** [comment]
Also I get error when I run `npm test`:
```
> flowcrypt-mobile-core@0.0.1 test /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/Core
> ava build/ts/test.js --verbose

internal/modules/cjs/loader.js:981
  throw new ERR_REQUIRE_ESM(filename);
  ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/Core/node_modules/ava/entrypoints/cli.mjs
    at Object.Module._extensions..mjs (internal/modules/cjs/loader.js:981:9)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
npm ERR! Test failed.  See above for more details.
```

**Comment by ivan-ushakov** [comment]
OK. I found that I need to use Node version 16. Now I can run test but still have several problems:
```
Error: Could not find signing key with key ID 06ca553ec2455d70
    at null.<anonymous> (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/Core/node_modules/openpgp/src/message.js:775:19)
```

```
PgpKey.lastSig: Skipping subkey d16ee86bdb129956 because there is no valid binding signature: Error: Subkey is expired
(node:11234) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by tomholub** [comment]
Ivan, I'll have to look into this myself. You have no real chance of getting this working, as it requires advanced TypeScript/JavaScrpt wizardry.

**Comment by tomholub** [comment]
Be careful self-assigning issues. If I thought you would be well suited to do this, I'd already have assigned it to you :-) are you low on issues to work on?

**Comment by ivan-ushakov** [comment]
> Be careful self-assigning issues. If I thought you would be well suited to do this, I'd already have assigned it to you :-) are you low on issues to work on?

I have several small issues
