### ISSUE TITLE
move compose layouting code to a separate file

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1393]
There's quite a bit of rendering or layouting code now in this VC, which makes business logic less obvious. Would it make sense to move it into some sort of decorator or rendering file (specific for this VC) instead of being here? Could be another PR, more of a maintenance task.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1381#discussion_r811120025_

**Comment by tomholub** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/6306961/154976316-99ac5f5d-33de-4e1d-bac8-ee7b1c988dde.png">

**Comment by sosnovsky** [comment]
Agree, we can move this part to `ComposeViewDecorator` as it's already contains code for styling compose screen.

**Comment by tomholub** [comment]
For clarity, the above quoted chunk of code is just one of many in that file that are purely rendering/layouting, and most of such code should ideally move to `ComposeViewDecorator`, leaving the business logic in the VC.

You can make exceptions when you feel when moving it elsewhere doesn't add to clarity in the VC.
