### ISSUE TITLE
extend ui tests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#14]
- [x] log in -> cancel
 - [x] log in -> approve -> bad pass phrase
 - [x] log in -> approve -> no backups -> switch email
 - [x] log in -> approve -> no backups -> generate pubkey -> weak pass phrase
 - [x] log in -> approve -> no backups -> generate pubkey -> good pass phrase -> wrong repeat
 - [x] log in -> approve -> no backups -> generate pubkey -> good pass phrase -> correct repeat -> create key
 - [x] log in -> approve -> no backups -> generate pubkey -> switch accounts
 - [x] log in -> approve -> loaded 1 backup -> good pass phrase -> inbox
 - [x] restart app -> loads inbox
 - [x] send new msg ->  inbox -> switch to sent -> open sent msg and verify content, recipient, subject
 - [x] send new msg -> no pubkey
 - [x] move msg to archive -> verify in archive
 - [x] move msg to Trash -> verify in trash -> verify no bin button on moved msg
 - [x] inbox -> open first msg -> to trash -> inbox -> open following first msg (to prevent crash as in #119)

**Comment by tomholub** [comment]
To do a bit later

**Comment by tomholub** [comment]
This should be the first priority after Texture

**Comment by tomholub** [comment]
@Kharchevskyi you should try to make a simple login test with Appium as a starting point

The goal is that we actually click around the app like a real user would. Not just integration tests. That way we know if basic functionality is broken or not.

https://www.youtube.com/watch?v=RagNvVuCvLI&list=PL-AJRKaxM-cb98PSYBpIQ9g_Vo1sn8L7f

**Comment by tomholub** [comment]
https://appium.io/

**Comment by tomholub** [comment]
@Kharchevskyi please have a look at this, at this stage it starts to be valuable to have some basic end-to-end tests for various user scenarios.

One typical problematic part is Google login. If it really turns our problematic, we could find a way how to log in manually, then recover storage of an app that was already logged in, for the tests.

**Comment by tomholub** [comment]
Another option would be to set up our own IMAP/SMTP mock server, and test against that. This means we would have to implement manual login (see Android app) - this is how we test Android.

**Comment by Kharchevskyi** [comment]
move msg to archive -> verify in archive

Do we support the archived folder?
