### ISSUE TITLE
a common way to report errors instead of ignoring them

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#140]
Actually here it would be better to get an error that shows to the user. Is there a way to do that easily? At this stage, email must be set, and if it's not, user should know about it. Such errors should not be ignored.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/135_

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/69329750-a1ef7100-0c8c-11ea-876d-41c503d4a779.png)

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/69329777-af0c6000-0c8c-11ea-8fb9-2da09b431683.png)

**Comment by tomholub** [comment]
There's many such places. It's not healthy to keep ignoring such errors, although seems to be (wrongly) a standard practice in Swift.

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/69330231-82a51380-0c8d-11ea-9745-9dd7856d546b.png)

**Comment by Kharchevskyi** [comment]
Actually you will never reach this screen if you don't have email stored in DataManager. 
Maybe it would be nice for user experience in case smth happens and you somehow get this screen to redirect user to login page - to get possibility to relogin again?

**Comment by tomholub** [comment]
Then we could just assert that the email is there with a `!`, and let the app crash if we are wrong.

Which is a bit extreme. I hope there could be some way to easily throw exception, like

```swift
let user = dataManager.email ?? throw new AppErr.NPE
```
Which is probably not valid swift. But we could have a method?
```swift
extension Optional {
   required(){
      if this == nil {
        throw new AppErr.NPE
      }
   }
}
```
Then use something like:
```swift
let user = dataManager.email.required()
// of if it's not possible to extend Optional, then just:
let user = requiredString(dataManager.email)
```
The advantage of throwing errors over doing `dataManager.email!` is that exceptions can be caught and handled.

Overall the goal is to clean up all of the "this should never happen" default values, and instead let the problems surface early.

**Comment by Kharchevskyi** [comment]
we can just use assertionFailure() with some message here. It will crash the app in develop but keep it safe in production. 
In production, we can somehow report this to us(to know that we have this problem) and just redirect the user to the initial screen with some message. Where he can log in again and not crash the app. It is safer if it's really our mistake and better for user experience.

**Comment by tomholub** [comment]
It's better. Logging out is a little extreme. I was thinking to throw an error, which should not crash the app. It should get caught by a default error handler which would then show alert to the user.

Let's say I download an email and it's supposed to have some value, like sender:

```swift

guard let sender = someEmail.sender.required() else { return }
```
It would be weird to log the user out for that, what you want is an error modal.

I see you really don't like throwing errors, and I wonder why - is this typical to avoid throwing errors in Kotlin? Why?

```swift
extension Optional {
    func required(_ message: String = "") -> Wrapped {
        switch self {
        case .some(let value):
            return value
        default:
            throw new AppErr.NPE
        }
    }
}

class A {
    func somethingWhereValueIsRequired() {
        let value = someValue.required()
    }
}
```
This is assuming that all functions bubble errors properly, and that at the root there is always an error handler that handles them.

**Comment by Kharchevskyi** [comment]
No. No. I' m okay with throwing error. Personaly I don't like `do{}catch{}` in swift. 
It was just a proposal

But, yes, I think that throwing an error and some default error handler is a good solution

**Comment by tomholub** [comment]
I just noticed I mentioned Kotlin above instead of Swift :laughing: 

Let's try the throw + common handler. If it becomes ugly, then we will reconsider. Thanks!

**Comment by Kharchevskyi** [comment]
Initial implementation for `CommonErrrorHandler` is in #261. 
Additional next possible solution marked as `// TODO: - ERROR HANDLING`

**Comment by tomholub** [comment]
this has now been done differently - by throwing and then a single catch for each Task.
