### ISSUE TITLE
[user concern] Does the "show encrypted messages" feature also comes with the iOS app?

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#1400]
Hello sir, @tomholub,

I received a concern about whether would the iOS app have the "show encrypted messages" feature planned?

Many thanks,

Reference: https://mail.google.com/mail/u/1/#inbox/FMfcgzGmvBpgHjcfCVDbXgcHvcLxvlKk

**Comment by tomholub** [comment]
It is a difficult feature to implement, and hard to get right, currently not planned for iOS.

**Comment by martgil** [comment]
Oh, okay, sir! I have updated the user about this. Thanks!
