### ISSUE TITLE
don't switch to main thread for ui changes?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#141]
Is it still necessary to push UI updates to main thread manually, even when using AsyncDisplayKit?

_Originally posted by @tomholub in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzIwNzM5MzMw/pull_request_reviews/more_threads_

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/69330144-5be6dd00-0c8d-11ea-9214-05e19ed512cd.png)

**Comment by Kharchevskyi** [comment]
From Texture documentation 
`This method must be called from the main thread. The asyncDataSource must be updated to reflect the changes before this method is called.`

Texture node can perform initialization, the calculation for layout and all preparation on the background thread but all "final" updates are on main thread.

**Comment by tomholub** [comment]
Ah, that's a pity. I thought I can completely avoid worrying about which thread I'm rendering from.
