### ISSUE TITLE
rewrite arguments of checkFilledComposeEmailInfo

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1413]
One day we'll probably rewrite the method to be clearer like accepting `{to: [...], cc: [...]}` and so on. But for this issue, this looks good.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1412#discussion_r823567225_

**Comment by tomholub** [comment]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/6306961/157646467-0804585f-d6b3-4c90-be62-79819b762e5e.png">

**Comment by ioanmo226** [comment]
@tomholub I think we can close this issue as it's already implemented in #1408 ?

**Comment by tomholub** [comment]
then you can update the PR description to indicate it closes this issue too. It will get auto closed once the PR is merged.

**Comment by ioanmo226** [comment]
Done
