### ISSUE TITLE
ComposeView doesn't hide search contacts view when user deletes whole email

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1414]
When user inputs email (inputs email in to recipients) and when user decides to not email and he deletes that email, user is not able to edit subject/message/can't click toggle button in screen.
Please check below recording.

https://watch.screencastify.com/v/FpZN0gWhjCk7PJiCXJtG

**Comment by ioanmo226** [comment]
@tomholub Please confirm this issue and I think this issue will be fixed in milestone 0.8.1 too.

**Comment by tomholub** [comment]
Sure, that looks like it needs fixing.
