### ISSUE TITLE
test for using local active contact if failed to fetch

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1420]
This will be a test case to write for @fcvakintos to write after this PR is merged:

1. open compose screen, search `robot@flowcrypt.com`, wait for it to load. Verify renders as valid. 
2. Search for `expired@flowcrypt.com` and wait for that to load. Verify renders as expired.
3. search for `revoked@flowcrypt.com` and wait to load. Verify renders as revoked.
4. Remove all recipients.
5. go offline
6. load `robot@flowcrypt.com` and verify it shows valid while offline (as if you were online)
7. load `expired@flowcrypt.com` and verify it shows an error while offline (could not load while offline)
8. load `revoked@flowcrypt.com` and verify it shows an error while offline (could not load while offline)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1419#issuecomment-1066749321_

**Comment by tomholub** [comment]
This can be written once #1419 merges

**Comment by fcvakintos** [comment]
@tomholub we cant turn on offline mode in our test, it is not working on IOS
https://appium.io/docs/en/writing-running-appium/other/network-connection/

**Comment by fcvakintos** [comment]
@tomholub what Attester API request should i use?

**Comment by tomholub** [comment]
It's the app that does the API requests. You just drive the UI and app makes requests to the mock.

**Comment by fcvakintos** [comment]
@tomholub can you provide steps for covering? Im not sure to understand you

**Comment by fcvakintos** [comment]
@tomholub could you provide revoked public key ?

**Comment by fcvakintos** [comment]
and how can i do this 'update attester mock to start returning an error'?

**Comment by tomholub** [comment]
Update attester mock code, similar to fes mock code. You'll want to copy and update method `throwErrorIfConfigSaysSo`. Then update attester config to include `returnError?: { code: number, message: string },` similar to fes config.

Then use that newly added config.

**Comment by fcvakintos** [comment]
@tomholub do you have revoked pubkey?

**Comment by tomholub** [comment]
see

> If available mock data for Attester API don't include expired and revoked samples, you can get them from the iOS app by searching the original three emails and then going to Settings -> Contacts -> eg revoked@flowcrypt.com and extract it from there.

**Comment by fcvakintos** [comment]
Hey @tomholub, I added new method for Attester Mock, and get this behavior 
`   mockApi.attesterConfig = {
              returnError: {
                  code: 400,
                  message: "some client err"
              }
          };
`
Is it correct in this case?
<img width="446" alt="Screenshot 2022-03-21 at 11 40 26" src="https://user-images.githubusercontent.com/91205853/159236741-cc7f995e-e88f-4a6f-9e39-8fc2d1ba08a5.png">

**Comment by tomholub** [comment]
That looks good to me 👍
