### ISSUE TITLE
Incorrect behavior when user wants to delete a contact in the Contacts screen

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1422]
After the user has deleted a contact on the "Contacts" screen, if user wants to delete another contact, app will start deleting the contact that is under the contact to be deleted.
For example, if there are 4 contacts (A, B, C, D) and the user deleted contact B first.
If the user wants to delete contact C, contact D will be deleted and if the user wants to delete contact A, contact C will be deleted.

**Comment by tomholub** [comment]
Thanks for noticing!

**Comment by ioanmo226** [comment]
@tomholub Got it
