### ISSUE TITLE
app crash on reply all of certain message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1437]
@tomholub I found issue
app crash when user click on "Reply all" this email "Message with cc and multiple recipients and attachment"

https://user-images.githubusercontent.com/91205853/159701293-6b0baff9-5e0e-4302-be73-ed3f10168495.mov

_Originally posted by @fcvakintos in https://github.com/FlowCrypt/flowcrypt-ios/issues/1432#issuecomment-1076331162_

**Comment by tomholub** [comment]
@ioanmo226 when you have a chance, please have a look. If you have any questions, ask @fcvakintos

**Comment by ioanmo226** [comment]
@tomholub I also faced this issue and it lets all CI tests fail.

**Comment by ioanmo226** [comment]
Let me include this fix in #1337

**Comment by tomholub** [comment]
Got it - please debug it. Thanks!

**Comment by tomholub** [comment]
> Let me include this fix in #1337

ok
