### ISSUE TITLE
request timed out when loading inbox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1442]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/6306961/159933590-de58a527-b421-4354-9aab-e09b18e4da6c.png">

We do a lot of requests at once when loading inbox, and it may sometimes time out.

When it times out, we seem to fail the whole loading and then we need to make all of the requests again.

I think it would be better if only the email messages that timed out had the failure showing on them, with a retry button.

Then retrying one of them would retry all of the failed ones. That's assuming that the "list of messages" API call succeeded, and it was some individual messages that failed. The initial list of messages (returned successfully) could result in "empty list" of messages already pre-rendered, and then individual message details could be rendered into that list as they become available. That way, the loading will become more interactive.

This way, at least, most of the inbox will be loaded when timeout happens on one or two messages.

After that, we can investigate in more detail how to make this happen less often. Maybe some automatic retry approach.

**Comment by tomholub** [comment]
Additionally, we could limit amount of messages we pull concurrently. So instead of pulling 20 at once, we could have a system with 10 concurrent messages maximum. Then, when one of the messages returns a successful result, we could start fetching the 11th one and so on. When second one returns success, we could begin fetching 12th one. This would be for a separate issue, as it's a big enough issue on its own.

**Comment by ioanmo226** [comment]
@tomholub I added retry logic for `Task` level.
Added retry logic for getting threads list and getting thread info calls.
Default retry `maxRetryCount` is 3 and we can change it by passing `maxRetryCount` param to `Task.retrying call`.
I think this eliminates above problem.
Let me know your thoughts
