### ISSUE TITLE
always use waitForContent when testing for presense of text

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1448]
- test content always with `element.waitForContent("expected content")`. This will keep checking for presense of expected content repeatedly for up to 15 seconds and then throw. That way, you avoid "testing too early" which is the cause of 95% of flakiness of UI tests. This is what we do on browser extension.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1056#issuecomment-974681036_

**Comment by tomholub** [comment]
Here is the implementation on browser extension

```ts
  public waitForContent = async (selector: string, needle: string | RegExp, timeoutSec = 20, testLoopLengthMs = 100) => {
    await this.waitAny(selector);
    const start = Date.now();
    const texts: string[] = [];
    while (Date.now() - start < timeoutSec * 1000) {
      const text = await this.read(selector, true);
      if (typeof needle === 'string') { // str
        if (text.includes(needle)) {
          return;
        }
      } else { // regex
        if (text.match(needle)) {
          return;
        }
      }
      texts.push(text);
      await Util.sleep(testLoopLengthMs / 1000);
    }
    throw new Error(`Selector ${selector} was found but did not match "${needle}" within ${timeoutSec}s. Last content: "${JSON.stringify(texts, undefined, 2)}"`);
  };
```

Anytime we test for text content, a method similar to this one should be used.

**Comment by fcvakintos** [comment]
@tomholub I added 2 methods - waitForText and waitForValue

**Comment by tomholub** [comment]
sounds good. What is the difference exactly? Please add comment to the methods to document it.

**Comment by fcvakintos** [comment]
sure
