### ISSUE TITLE
Display name in compose recipient list

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1473]
When user enters email in compose recipient input and tap `Enter` key, recipient name is not displayed. (Instead only email is displayed)
Let's say when there's a contact (test@example.com with `test user` name) and when user types test@example.com and tap `enter` key, `test@example.com` recipient is added.
Instead added recipient label should display as `test user` and email should be seen via recipient popup by clicking recipient name.

@tomholub Please confirm

**Comment by tomholub** [comment]
Agree

**Comment by tomholub** [comment]
I'm marking this for sometime later. Unless you are trying to bundle it with some other issue.

**Comment by ioanmo226** [comment]
I prefer to do this now. This is simple to fix and is blocking #1471.
Of course, we can search recipient by name in #1471 but I'd prefer to do this issue first because it's simple to fix and necessary.

**Comment by tomholub** [comment]
ok - makes sense
