### ISSUE TITLE
check password-protected recipient in cc with normal recipient in to

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1474]
Which means it should contain all of them. I just checked on browser extension, which works in this scenario: it sends all.

@martgil please check this scenario on iOS

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/1731#issuecomment-1088538696_

**Comment by martgil** [comment]
@tomholub I tested this scenario on iOS and here is what I've got:

the message gets sent even when adding a non-existing email to a password-protected message. Furthermore, this produces a notice that came from Gmail that message is not sent for the non-existing email which is expected (same behavior on browser extension).

**Comment by tomholub** [comment]
I'm mostly interested in scenario `to:existing email that has a public key` `cc:email without public key`. Does message get sent?

**Comment by martgil** [comment]
Yes, sir, message gets sent for both `cc/bcc` without pubkey + `to` with pubkey.

**Comment by tomholub** [comment]
great - thanks
