### ISSUE TITLE
add swift tests for how long it takes to do operations with rsa4096 key

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1478]
Also need to add a Swift test, that uses the `Core`, that measures it takes less than 1 second each to:
 - sign message with rsa4096
 - encrypt message with rsa4096
 - decrypt message with rsa4096
 - encrypt rsa4096 key
 - decrypt rsa4096 key

These will prevent regression once we do #1362 .

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1469#issuecomment-1087904833_

**Comment by tomholub** [comment]
Sample [rsa4096.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/8427393/rsa4096.zip)

Some of these operations may currently take much more than 1 second - especially signing. If true, then add maybe a 1 or 2 minutes limit for that one, until I fix it.

**Comment by tomholub** [comment]
Marking as priority - I'd need this by the end of the week. Please have a look at this after whichever task you're currently working on.

**Comment by mobilestar1** [comment]
OK

**Comment by ioanmo226** [comment]
OK
