### ISSUE TITLE
improve naming of compose message updateState

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1479]
I see. We can leave it as is for now. Later, maybe it needs some renaming to make it clearer what it does.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1477#discussion_r843931517_

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/161991761-c3707d19-3dd9-401a-956d-24ba2b9bc77a.png)

**Comment by tomholub** [comment]
could you propose a more fitting name?

**Comment by ioanmo226** [comment]
Maybe `updateNode(with newState: State)` or `updateView(with newState: State)`?

**Comment by tomholub** [comment]
I guess `updateView(with newState: State)` is a bit better, as it makes it clearer it's about rendering
