### ISSUE TITLE
use existing RSA key for 4096 bit test

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1484]
[rsa4096.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/8427393/rsa4096.zip)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1478#issuecomment-1090299132_

keygen too slow

**Comment by ioanmo226** [comment]
@tomholub It already does

**Comment by tomholub** [comment]
Ah - I somehow overlooked that. Thanks!
