### ISSUE TITLE
crash feedback from version 0.8.2

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1486]
[testflight_feedback-082.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/8450507/testflight_feedback-082.zip)

**Comment by ioanmo226** [comment]
By the way, @tomholub I think we should setup crashlytics once app goes live/stable.

**Comment by tomholub** [comment]
I'd need a solution that doesn't send data to a 3rd party. Something we can host, or something that's just a client lib we can point at our own server API, like ACRA.

**Comment by ioanmo226** [comment]
Hmm.. I see.
Maybe we need to research about this when we have time.
