### ISSUE TITLE
add GMP library to the project - priority

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1500]
@sosnovsky please pause your other work to look at this one

Roughly this:
1) please add a script that builds GMP into `Script/build-gmp.sh` that downloads https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz and builds it for iPhone arm64 . Even better if this was somehow done in `make dependencies`
2) do a reverse of https://github.com/FlowCrypt/flowcrypt-ios/pull/237/files which means adding  back gmplib to the project and removing Swift `BigInt`. Instead of Lib/Bignum please call it `Lib/GMP`
3) you'll want to copy `bignum.c` and `bignum.h` that was removed in that PR but call it `gmp-interface.c` and `gmp-interface.h` or similar.

Then update this method back to use the method from `gmp-interface` as you see it below:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/6306961/163387783-926113f3-12b8-40a9-bc91-675d68e34448.png">

Performance is the reason. It takes 30-90 seconds to do RSA 4096 sign in JavaScript. Swift BigInt is only marginally faster, because it's not optimized. This is causing issues to our customer who uses RSA 4096. GMP should have it near instant.

GMP was removed at the time because it was causing issues for our build, which may no longer be the case, or is likely something you'll know how to resolve.

Thanks!

**Comment by tomholub** [comment]
progress looks good

**Comment by sosnovsky** [comment]
> progress looks good

I was able to create `xcframework` with different architectures, so it can be used on both - simulator and device.
Now trying to implement `build-gmp.sh` which will automatically download, build and create framework from `gmp` source code.

**Comment by tomholub** [comment]
Very good. I will be out today. If on Thursday the automatic part is not ready, we should merge it with prebuilt binaries, while you continue work on the build procedure.
