### ISSUE TITLE
app store connect warnings

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#151]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/6306961/69342099-cb68c680-0ca5-11ea-83c4-7cc5eda8e1b0.png">

<img width="639" alt="image" src="https://user-images.githubusercontent.com/6306961/69342150-e3404a80-0ca5-11ea-802d-a7ef9171d29b.png">

**Comment by Kharchevskyi** [comment]
https://github.com/FlowCrypt/flowcrypt-ios/pull/152
