### ISSUE TITLE
check / update functionality of FORBID_STORING_PASS_PHRASE during EKM setup flow

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1513]
Simply removing flag `FORBID_STORING_PASS_PHRASE` should achieve the desired result (for EKM flow, at least). And if it doesn't, that's the fix that should be changed.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1512#discussion_r854904299_

**Comment by tomholub** [comment]
The behavior, during EKM setup flow, should be:
 - with `FORBID_STORING_PASS_PHRASE`, store pass phrase in `.memory`
 - without it, store pass phrase in `.permanent`

I think the second part may not be currently implemented - please have a look.

**Comment by tomholub** [comment]
related to testing https://github.com/FlowCrypt/flowcrypt-ios/pull/1510

**Comment by ioanmo226** [comment]
Currently `checkUsesEKM` functions returns incorrect configuration result if FORBID_STORING_PASS_PHRASE is passed.
Does it have to be changed?

![image](https://user-images.githubusercontent.com/77344191/164412065-1ba3d998-fa8f-49d5-a94c-ee1744772119.png)

**Comment by tomholub** [comment]
Yes - that was correct originally, because we didn't implement the functionality when it was omitted.

Together with implementing the functionality, that check should be removed.

**Comment by ioanmo226** [comment]
Ok, got it
