### ISSUE TITLE
screenshots for iOS app for various devices

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1518]
please help me take screenshots of:
 - splash screen
 - inbox
 - compose screen
 - read email screen

per each of the following device types (using various simulators):

<img width="640" alt="image" src="https://user-images.githubusercontent.com/6306961/164542289-5080a153-8694-406f-a5eb-674bcd477917.png">

That means 16 screenshots total. Apple wants screenshots to be in exact resolution for each device. I'll be copying the existing approved screenshots below so that you know the resolution for each.

**Comment by tomholub** [comment]
<img width="107" alt="image" src="https://user-images.githubusercontent.com/6306961/164542729-7b93ccda-c7e6-410b-b3ec-058d827e99cd.png">


![image](https://user-images.githubusercontent.com/6306961/164542625-9dd40a30-803f-4e4b-a1cd-07d9c2544540.png)

**Comment by tomholub** [comment]
<img width="107" alt="image" src="https://user-images.githubusercontent.com/6306961/164542845-97206a13-9f73-4108-b632-46a7893d14e1.png">

![image](https://user-images.githubusercontent.com/6306961/164542874-1d30cba8-3945-4550-ad91-50af2da09c73.png)

**Comment by tomholub** [comment]
<img width="151" alt="image" src="https://user-images.githubusercontent.com/6306961/164542999-30d93b11-8dbe-4d7a-a1e4-c7aa5164e8c9.png">

![image](https://user-images.githubusercontent.com/6306961/164543036-a69f0a6d-1ce2-41e5-bda5-89edb7b1dc66.png)

**Comment by tomholub** [comment]
<img width="151" alt="image" src="https://user-images.githubusercontent.com/6306961/164543098-52268576-85fa-42a0-ab82-6fab12d4a367.png">

![image](https://user-images.githubusercontent.com/6306961/164543120-cd92d786-384b-4831-a744-569658234e7a.png)

**Comment by tomholub** [comment]
Wait a sec - maybe I have some.

**Comment by tomholub** [comment]
Please replace all of these https://github.com/FlowCrypt/flowcrypt-design/tree/master/digital-assets/apple-app-store as they are dated. Please also use 4 folders, one per device type.

https://github.com/FlowCrypt/flowcrypt-design/invitations

**Comment by tomholub** [comment]
Be sure there is no personal info on these. I see on my previous screenshot, there was my email in it, which it shouldn't be there.

Use demo@flowcrypt.com or similar account.

**Comment by ioanmo226** [comment]
@tomholub I guess we may setup fastlane to generate screenshots for app store and upload build to app store. (CD solution).

**Comment by tomholub** [comment]
I do this kind of thing once in a few years (even browser extension screenshots are probably 5 years old) so probably not worth automating.

**Comment by ioanmo226** [comment]
I see

**Comment by martgil** [comment]
@tomholub May I ask for some hint here?
<img width="688" alt="Screen Shot 2022-04-22 at 4 04 19 PM" src="https://user-images.githubusercontent.com/46025304/164645222-a2999acf-22b5-4718-b201-0ab2cfa0f7e1.png">
I executed `make dependencies` and `bundler exec pod install` for the project dependency but i'm still getting these errors. I tried resetting package cache through `File -> Packages -> reset package caches & update to latest package versions but the error remains. 

I also had re-clone the flowcrypt-ios repo from the master branch but no avail.

**Comment by ioanmo226** [comment]
@martgil which Xcode version are you using?
If you are using v13.2 this might seem to be right answer.

https://stackoverflow.com/questions/70342174/xcode-13-2-internal-error-missing-package-description-module#:~:text=EDIT%3A%20Xcode%2013.2.1%20version%20fixes%20this%20issue%20and%20can%20be%20downloaded%20from%20the%20Mac%20App%20Store.

**Comment by martgil** [comment]
Hello @ioanmo226 - thank you for your response! I'm currently using v13, I'll try to update the Xcode.
<img width="523" alt="Screen Shot 2022-04-22 at 4 30 03 PM" src="https://user-images.githubusercontent.com/46025304/164650244-f59e3057-99a6-4157-9180-5a966438544e.png">

**Comment by sosnovsky** [comment]
@martgil yes, you should update to the latest Xcode 13.3, as it has some changes in Swift Package format.

**Comment by martgil** [comment]
Thank you @sosnovsky I'll follow your suggestions 🙏

**Comment by martgil** [comment]
This task has been finished on https://github.com/FlowCrypt/flowcrypt-design/issues/23 - thank you very much!
