### ISSUE TITLE
ensure to properly parse each received key from EKM

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1524]
> For `test 3: EKM key update errors handled gracefully`, when we want to parse broken key with `core.parseKeys` it doesn't return error but return 0 parsed keys.
> 
> > change EKM mock to start returning a broken key (for example, only return the first half of the armored key text)
> > restart the app
> > _observe that the app shows a modal during startup Could not update keys from EKM due to error: and followed by whatever error happened._

That's odd. In this situation, the parsing should fail. It should not swallow keys silently.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/841#issuecomment-1109067112_

**Comment by tomholub** [comment]
The solution would be to parse incoming keys from EKM one by one instead of contacting them into a single string to parse.

For each incoming `decryptedPrivateKey` we will expect to get exactly one key out. If not (either 0 or >1) then we throw an error.

With that, we can finalize the following test:

```
// stage 3 - error shown to user
change EKM mock to start returning a broken key (for example, only return the first half of the armored key text)
restart the app
observe that the app shows a modal during startup Could not update keys from EKM due to error: and followed by whatever error happened.
tap close on the modal and observe that inbox loads normally
go to app settings -> keys and observe they stayed the same
```

**Comment by ioanmo226** [comment]
Then if we want to parse 5 keys(2 valid keys and 3 broken keys), do we have to display 3 errors?

**Comment by tomholub** [comment]
One error would be enough, stating "One or more of keys received from EKM ..."
