### ISSUE TITLE
encrypt Realm?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#153]
> I meant maybe to separate storing some data to keychain storage or other please instead of Realm and UserDefaults. It's not really safe to save sensetive data in UserDefaults.

Definitely. We should be using whichever is the most secure method of storage.

Doesn't Realm support encryption? We could just store the Realm encryption password in keychain.

**Comment by Kharchevskyi** [comment]
https://github.com/FlowCrypt/flowcrypt-ios/pull/156
