### ISSUE TITLE
ui test for replying to my own email and changing recipient

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1531]
please write the following test, for functionality we are about to fix

1) navigate to any existing message from:me to:some recipient with public key
2) tap reply
3) observe and test the rendered recipients (currently it will include to:me which is wrong and instead should be to:the other recipient)
4) remove the existing recipient
5) replace it with some other recipient with public key (currently the app crashes)
6) finish filling out the message

**Comment by tomholub** [comment]
Please also confirm if you can also reproduce the crash

**Comment by fcvakintos** [comment]
@tomholub I can't build new app, I get many errors when I click on build
<img width="355" alt="Screenshot 2022-05-03 at 16 21 41" src="https://user-images.githubusercontent.com/91205853/166460655-909f5372-3a98-4051-9464-8ff9f5dc48cd.png">

**Comment by fcvakintos** [comment]
is it from Sent folder?

**Comment by tomholub** [comment]
You'll need latest xcode version to continue working on the project

**Comment by tomholub** [comment]
> is it from Sent folder?

In my case I tested it from inbox folder (original message was from them to me, second message from me to them, and that's the one I was replying to)

See if you can reproduce the issues from sent folder. If not, try the above scenario in inbox folder.

**Comment by fcvakintos** [comment]
@tomholub after changing the recipient - > app crashes

**Comment by fcvakintos** [comment]
it is actual for sent and inbox folder, i reproduced it

**Comment by fcvakintos** [comment]
It is actual for any email on reply

**Comment by tomholub** [comment]
Make a draft PR with the tests that reproduce this behavior, then I'll have someone fix the tests.

You can write the tests in a way that they will fail, since the intended behavior and the app implementation differs.

**Comment by fcvakintos** [comment]
@tomholub de we need 2 tests?
for sent folder and for inbox?

**Comment by tomholub** [comment]
Could be written as one test `chooses correct recipient on followup reply + doesnt crash when recipient changed`

**Comment by fcvakintos** [comment]
@tomholub I can't catch crash by autotest

**Comment by fcvakintos** [comment]
In autotest it works correct
