### ISSUE TITLE
extend CI linters to appium directory + discuss commit hook

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1533]
The way we solved this on other repos was with linters that run in CI. We did that here too, for TypeScript, but I suspect we didn't extend it to the /appium directory which we should.

With a commit hook, I'm worried it may become another thing that may break and need to be maintained, but maybe it's just my lack of experience. We could consider that for later, if it works well and if Roma agrees.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1526#issuecomment-1111169622_

**Comment by ioanmo226** [comment]
Moreover it doesn't need maintenance for several years.

**Comment by tomholub** [comment]
Were the dev machines cross platform (Linux / windows / mac) ? Curious in case we use it for our other projects.

**Comment by ioanmo226** [comment]
Yeah. it's cross platform

**Comment by sosnovsky** [comment]
I think commit hook will be a good solution for this case, and as @ioanmo226 said - probably it won't need any maintenance after initial setup.

**Comment by tomholub** [comment]
All good. Let's do this a few weeks from now
