### ISSUE TITLE
0.8.2 crash when trying to reply-all

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1534]
[testflight_feedback-082.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/8574836/testflight_feedback-082.zip)

this is on enterprise build

**Comment by ioanmo226** [comment]
Can't see correct error message but I think this is already fixed.
@tomholub Could you confirm with this customer if he still faces this issue?

**Comment by tomholub** [comment]
If you suspect it's fixed, I'll close this and we'll see if any other reports show.
