### ISSUE TITLE
reported vulnerabilities in npm packages

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1535]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/6306961/165581341-751d2c4f-3129-49c0-a08f-6d3675e983d3.png">

Edited by mart:
Additionally, I should have to break this task into smaller chunks as (1) I need to update webpack 5 on `/Core` path (2) I'm having difficulties on updating of most vulnerable npm packages on the `/appium` path but I'm still into it.

- [x] #1580
- [x] #1597 (may need to wait for appium 2.0 non-beta version)

**Comment by sosnovsky** [comment]
Currently `appium` and `Core` code uses the latest versions of npm packages without reported vulnerabilities.
