### ISSUE TITLE
0.8.2 another crash report

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1536]
[testflight_feedback-082-2.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/8574972/testflight_feedback-082-2.zip)

**Comment by ioanmo226** [comment]
@tomholub 
App crashed because of this line `fatalError`.
What should be done this case? maybe display error alert to user to sign out?

![image](https://user-images.githubusercontent.com/77344191/165912527-4e1593c3-0714-4537-a517-963b1d0309d4.png)

**Comment by ioanmo226** [comment]
ok

**Comment by ioanmo226** [comment]
what error message should i show
?
