### ISSUE TITLE
start using usableForSigning and usableForEncryption after v5

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1546]
This is not ideal, but I see our current js response is missing this. We have to improve this after #1379 

Since this is only a rough approximation

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1544#discussion_r860652244_

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/165723980-71ab3f79-f5bb-48c8-a08f-50e4eb49f984.png)

**Comment by tomholub** [comment]
after #1379

**Comment by ioanmo226** [comment]
This test needs to be updated after this issue.
Currently app only returns  `Your account keys are not usable for encryption` even though app is not ready for signing.

```
There are actually two separate concerns when sending a signed+encrypted message, as it relates to my own keys:

do I have any private key that is usable for signing? -> error Your account keys are not usable for signing
do I have any public key that is usable for encryption? -> error Your account keys are not usable for encryption
```
