### ISSUE TITLE
Store entered pass phrases in keychain

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#155]
Pass phrases cane be stored inside encrypted keychain on behalf of the user.
https://developer.apple.com/documentation/security/keychain_services/keychain_items/adding_a_password_to_the_keychain

**Comment by tomholub** [comment]
Please have a look at #153 - is it possible to just encrypt the whole realm database Realm with a password?

**Comment by tomholub** [comment]
closing as per discussion
