### ISSUE TITLE
public key update - better handling of revoked keys

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1560]
Currently, if we receive a newer version of the key (during compose or during signature verification), we will update our own older key with the newer version of the key.

We should update this mechanism to ensure that if the key in our own storage is revoked, it will never be updated anymore, even if we received a newer version of that key.

**Comment by tomholub** [comment]
You need private key to create a revoked public key.

That means, you need to start with a public-private key pair, not just the public part. Proceed as follows:

1) generate a keypair, and save two copies of it
2) original copy A - update the keypair to be revoked, then export public key
3) original copy B - update the keypair to add another user, then export public key

This sequence is important so that the "good" public key you exported has a newer `lastModified` on it compared to the revoked copy. Only then are we actually testing if the app rejects it, else it may just ignore it because of older `lastModified` which is not what we're wanting to test here.

Also keep the private keys (original, revoked, updated valid), they will be needed for #1559

**Comment by tomholub** [comment]
Could post the private keys here for future use

**Comment by ioanmo226** [comment]
Keys can be found in appium/api-mocks/apis/ekm/ekm-endpoint.ts.

By the way, Here's my question.
Let's say I have revoked key for test@example.com (This key contains 1 user named `Test1`).
Then attester returns updated key(which is not revoked and has 2 users named `Test1-Updated` and `Test1`).
For this case in compose recipient input view when user enters test@example.com, do we have to display `Test1` with red background(which means revoked) or display `Test1-Updated` with green background[This is how app currently works though](which means correct key)?

Of course I know for both cases, we should not update local keys as we have revoked key in local.

![image](https://user-images.githubusercontent.com/77344191/169889794-45e8635f-d06e-477b-a99d-2c52f1286f2b.png)

**Comment by tomholub** [comment]
>  Then attester returns updated key(which is not revoked and has 2 users named Test1-Updated and Test1).
> For this case in compose recipient input view when user enters [test@example.com](mailto:test@example.com), do we have to display Test1 with red background(which means revoked) or display Test1-Updated with green background[This is how app currently works though](which means correct key)?

That's the core of this issue. Currently, it is wrong.

If the app has ever observed a key (of a certain primary fingerprint) that was ever revoked, then the app can never update that key again.

> Test1 with red background(which means revoked) 

This is the answer, which should reflect the fact that the revoked key wasn't replaced with the un-revoked one.

**Comment by tomholub** [comment]
However, if you supply another key for the same user (different primary fingerprint) that is valid, the app should use that key and it should turn from red to green - which should be the case before as well after the update.
