### ISSUE TITLE
avoid test-specific delays in prod code

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1568]
There must be a more reasonable way to fix the issue. It could be a change to test code or production code (maybe the flow would have to be changed to be easier to test, idk).

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1510#discussion_r864162554_

**Comment by tomholub** [comment]
Please see if a more gracious fix can be done if you remove the workaround above

**Comment by sosnovsky** [comment]
> @sosnovsky I think if we fix this issue, #1532 build failure issue will also be fixed.

Probably, but we'll need to re-check once this fix is implemented.

**Comment by ioanmo226** [comment]
Yeah. sure

**Comment by ioanmo226** [comment]
I don't think pass phrase popup will appear on every app startup.
Even if users store passpharse in memory, once user enters passphrase it will update saved keys.
Therefore, app will ask user passphrase only when there are updated keys available.
When there are no keys to update, app won't ask pass phrase

> but now users who store passphrase only in memory will see modal asking for passphrase on every app start. It can be annoying, I think

**Comment by ioanmo226** [comment]
By the way @sosnovsky, semaphoreci ui test failure issue is because of refreshKeysFromEKMIfNeeded called in SideMenuNavigationControll init method instead of viewDidAppear?

**Comment by ioanmo226** [comment]
I see. Thanks
