### ISSUE TITLE
approval / merging procedure

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1573]
@sosnovsky @ioanmo226 going forward you may approve / merge each other's PRs, except when:
 - the PR is complicated or wide-reaching
 - the PR involves encryption / security
 - the PR involves product changes that are ambiguous / not obvious
 - one of you is unsure about intended result or want my input on implementation

In the excepted cases you please tag me to have a look.

**Comment by ioanmo226** [comment]
Ok, got it

**Comment by sosnovsky** [comment]
Sounds good 👍

**Comment by tomholub** [comment]
Also pls involve me anytime the PR concerns key lifecycle: key import, update, sync etc. Thanks!

**Comment by tomholub** [comment]
I just added you
