### ISSUE TITLE
enable and integrate Gmail API mocks + switch one simple test to run on mock Gmail

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1576]
The Gmail API mock should already be included in test sources (maybe disabled). Can also copy chunks from browser extension. The Mock API is easy since it's a solved problem.

The more interesting part is, can we convince Gmail API client library to use mock domain (localhots:8001 or similar) instead of the live domain? Any configuration for that?

**Comment by tomholub** [comment]
Does this look doable so far?

**Comment by sosnovsky** [comment]
Yes, I was able to mock google auth and fetching inbox items locally. It's needed switching mock server from `http` to `https`, as Google REST library doesn't allow requests to `http` because of security reasons.

Today will try to make it work on semaphore, as `https` mock needs to use locally generated certificates. I used https://github.com/FiloSottile/mkcert for my local setup, probably it should work on CI too.

**Comment by tomholub** [comment]
You create it once and check the cert/key into the git repo - that's what we did on browser extension repo. Then we just reuse it on each test run.

**Comment by sosnovsky** [comment]
We also need to add it into simulator, to make it trusted.

Locally it's added just by dragging certificate file to simulator, but on Semaphore we'll need to open certificate file by url in Safari and then enable it in iOS settings.

**Comment by tomholub** [comment]
Noted. That is a bit annoying - is there no command line or simulator setup mechanism that would make the cert trusted?

If the only way to do it is to load it from url in Safari, you could load it from git url so you don't need to serve it locally. Like this https://raw.githubusercontent.com/FlowCrypt/flowcrypt-ios/master/appium/babel.config.js

**Comment by sosnovsky** [comment]
Currently looking for simpler solution, maybe it's possible to do with some terminal command.

**Comment by sosnovsky** [comment]
Should be possible with `xcrun simctl keychain booted add-root-cert ./cert.pem` command, will try to use it.
