### ISSUE TITLE
reconsider recipients of "reply" as opposed to "reply-all" when replying to sent message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1599]
@tomholub 

message:
<img width="402" alt="Screenshot 2022-05-11 at 18 41 48" src="https://user-images.githubusercontent.com/91205853/167891172-d121739f-57e0-4b5a-ac9b-f6a5798fd635.png">

if i click on reply all button i see all recipients
<img width="436" alt="Screenshot 2022-05-11 at 18 39 41" src="https://user-images.githubusercontent.com/91205853/167890780-d043c4a9-2e6b-40a9-aba3-459dbf7ef5e0.png">

but if i click on "Reply" icon of the last thread message -> I see e2e account only, is it wrong?
<img width="426" alt="Screenshot 2022-05-11 at 18 41 18" src="https://user-images.githubusercontent.com/91205853/167891078-61d36721-05a7-4cb9-8520-0d439d1426bc.png">

_Originally posted by @fcvakintos in https://github.com/FlowCrypt/flowcrypt-ios/pull/1582#discussion_r870477081_

**Comment by tomholub** [comment]
> but if i click on "Reply" icon of the last thread message -> I see e2e account only, is it wrong?

Maybe it's correct, maybe not. It would be good to know what Gmail does here.

@fcvakintos what does Gmail app itself do when you attempt to reply to that email?

**Comment by ioanmo226** [comment]
With #1590 fix when user replies to sent email, it sets correct recipient.
Like when I (a@test.net) send email to b@test.net and I want to reply that email, recipient is set to `b@test.net`.

In gmail app, it works same.

**Comment by tomholub** [comment]
To avoid triggering the bot, you can use email addresses on test tld. `a@domain.test` 

1) Does reply-all also behave the same as Gmail? on such email?
2) how about from:me to:recipient1 cc:recipient2 - then reply - what does it do? and is it same as gmail?
3) how about from:me to:recipient1 cc:recipient2 - then reply all - what does it do? and is it same as gmail?

**Comment by ioanmo226** [comment]
Yeah, For all cases, it works same as gmail

**Comment by tomholub** [comment]
sounds good. Once that PR #1582 is merged to master and ready, please review it to ensure it's testing one of the scenarios - either scenario 2 or 3 - appropriately, and then you can approve it. Thanks :+1:
