### ISSUE TITLE
Add UUID to email subject which is composed during UI tests.

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1603]
When we compose email in UI tests with below code, we delete sent email after email compose.
`await NewMessageScreen.composeEmail(recipient, emailSubject, emailText);`

The problem is when for some reason, ui tests fail after compose email but before deleting sent email, there might be multiple `emailSubject` emails.
And after that happens, UI tests will treat like sent email is not deleted even after successful deletion and tests will fail after that (As there are multiple emails with same subject).

So my suggestion is to add UUID to email subject when composing email.
If we do like this, even if specific UI test fails and composed email remains, further tests will not fail because of previous test.

Like this.

```
const uniqueId = Date.now().toString(36) + Math.random().toString(36).substring(2);
const testEmailSubject = `${emailSubject}-${uniqueId}`;
await NewMessageScreen.composeEmail(recipient, testEmailSubject, emailText);

```

**Comment by ioanmo226** [comment]
@tomholub , @sosnovsky

**Comment by sosnovsky** [comment]
I like this idea 👍 

We can use default Swift UUID generator `UUID().uuidString` here

**Comment by sosnovsky** [comment]
Ah, that's what happens when jumping between Swift and TS issues here 🙂

**Comment by tomholub** [comment]
agree

In the future we will use Gmail mock for sending emails. https://github.com/FlowCrypt/flowcrypt-ios/issues/1576 then it will no longer be issue

**Comment by ioanmo226** [comment]
Let me handle this task now.
I experienced above issue 5 times for last 2 days.
