### ISSUE TITLE
`Create a new key` doesn't work with gmail account which doesn't have backups

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1644]
Here are steps to reproduce. (Tried with 1.0.2 testflight version)

1. Click `Continue with Gmail` in splash screen.
2. Select any gmail account which doesn't have key backups and not using EKM.
3. Tap `Create a new key` button in setup flowcrypt screen
4. Enter passphrase and confirm passphrase.
5. Now this error will be shown

![setup_error](https://user-images.githubusercontent.com/77344191/170055898-c4c62438-d39b-4f30-b122-0da2c90ee1e1.jpeg)

**Comment by ioanmo226** [comment]
@tomholub

**Comment by tomholub** [comment]
Attester is misconfigured.

Please try both on enterprise app and on consumer - see if there is any difference.

Then please parse the JWT that the app is providing (both on consumer and enterprise) and find out what audience (`aud` claim) does it contain, and print both aud claims below. Then I can update attester config.

**Comment by tomholub** [comment]
It's updated now. Any better?

**Comment by ioanmo226** [comment]
Yeah, it works perfectly fine now

**Comment by ioanmo226** [comment]
We may close this issue

**Comment by tomholub** [comment]
Feel free to close issues that are due to be closed
