### ISSUE TITLE
Change email read bevavior

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1660]
There are 2 things I want to propose for email read logic.

1. When we open thread/email, automatically read all threads/emails. (currently if i open thread, 1 message is marked as read) 
2. Do not wait for email read/unread api to finish. Just display read/unread status immediately after user opens thread/message or tap `unread button`(in navigation bar)

FYI those are all same exactly Gmail app works.

**Comment by ioanmo226** [comment]
@tom

**Comment by tomholub** [comment]
sounds good
