### ISSUE TITLE
Everytime Xcode project is built 2 times in semaphoreci

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1667]
Xcode project is built 2 times in `Appium UI tests` and `TypeScript + Swift tests`.
I think this seems not necessary and messy.

We may split test into `Swift Tests + Appium UI tests` and `Typescript tests` and build Xcode project 1 time only in `Swift Tests + Appium UI tests`.

**Comment by ioanmo226** [comment]
@tomholub

**Comment by tomholub** [comment]
It's building them one time for Swift tests context (plus it includes the swift tests that need to be built) and one time for Appium context. Is it actually the same build?

**Comment by tomholub** [comment]
Eventually we'll be parallelizing Appium runners in CI like it's done on browser extension. At that point there will be single build for all Appium runners which will then be distributed for individual machines to run in parallel.

At that point, we could have a second look to see if maybe building Swift tests on that same shared machine may allow the swift tests to be built faster.

**Comment by tomholub** [comment]
Yup :-) it should be achievable here to, to some extent.
