### ISSUE TITLE
Client configuration option to not search on any Attester domains except a whitelist

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1668]
See https://flowcrypt.com/docs/business/org-rules.html 

One of our customer has the following rule set up: `disallow_attester_search_for_domains: ["*"]` meaning don't use Attester to search public keys for any recipient domain. They would like to be able to add an exception to this for some domains, to be able to say "don't search anywhere except do use attester to search for public keys of users on domain example1.com and example2.com" which we don't currently support.

There are a few ways to approach this:

### option 1 - add a way to define negative items

eg `disallow_attester_search_for_domains: ["*", "!example1.com", "!example2.com"]`

or  `disallow_attester_search_for_domains: ["*", "^example1.com", "^example2.com"]`

or `disallow_attester_search_for_domains: ["*", "-example1.com", "-example2.com"]`

advantage - I find it clearer what is going on, all related config in one place

disadvantage - `^`, `!` or `-` are quire arbitrary choices. A minor form of string parsing involved

could be more explicit like 

or `disallow_attester_search_for_domains: ["*", "allow:example1.com", "allow:example2.com"]`

## option 2 - add another configuration

```
disallow_attester_search_for_domains: ["*"], 
always_allow_attester_search_for_domains: ["example1.com", "example2.com"]
```

where `always_allow_attester_search_for_domains` overrides the wildcard in `disallow_attester_search_for_domains`

advantage - more explicit, no string parsing

disadvantage - one more  client configuration which is not meaningful on its own, and is only meaningful when `*` is used in `disallow_attester_search_for_domains` - seems too narrow scope to have another client configuration

**Comment by tomholub** [comment]
what do you think about these choices? @sosnovsky @ioanmo226 @DenBond7

**Comment by DenBond7** [comment]
@tomholub using `regex` on the customer side sounds difficult? Do customers have a special person for managing that or do it themselves?

**Comment by ioanmo226** [comment]
If I were you, I would choose 2nd because

1. It makes clear user to which domains are always allowed
2. No `&`, `^`, `-` which is uncomfortable for non coders.

By the way, IMHO `force_allow_attester_search_for_domains` name seems more declarative (as this setting forces attester to search for domains)  than  `always_allow_attester_search_for_domains`

**Comment by sosnovsky** [comment]
What about having `allow_attester_search_only_for_domains` option?

If it's set then app will ignore `disallow_attester_search_for_domains` option and search only in listed domains.

So we don't need to set `disallow_attester_search_for_domains: ["*"]`, which fixes disadvantage of `option 2 - add another configuration`

**Comment by tomholub** [comment]
Regex would probably be the most flexible but also complicated.

Let's go with what Roman suggests.

> What about adding `allow_attester_search_only_for_domains` option?
> 
> If it's set then app will ignore `disallow_attester_search_for_domains` option and search only in listed domains.

Plus add an appropriate test.

**Comment by ioanmo226** [comment]
@tomholub Yeah, I think so.
Problem is that I don't have any idea about browser extension codebase and may take more time though

**Comment by ioanmo226** [comment]
By the way FlowCrypt/flowcrypt-browser#447 issue doesn't seem like related issue and also it's closed issue

**Comment by tomholub** [comment]
Yes :-)

**Comment by tomholub** [comment]
> @tomholub Yeah, I think so. Problem is that I don't have any idea about browser extension codebase and may take more time though

No worries, when unsure, you can ask. I may have you start contributing sometimes there as well, if that is ok with you.

**Comment by ioanmo226** [comment]
ok, sure
