### ISSUE TITLE
linter: any breakpoint statement should fail tests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#168]
We need code linting to run in our CI, this could be the first linter

**Comment by Kharchevskyi** [comment]
Will add https://github.com/realm/SwiftLint and also https://github.com/nicklockwood/SwiftFormat
And also will create a prebuild script to run SwiftFormat rules. 

But breakpoints should be a part of gitignore. Will take a look

**Comment by Kharchevskyi** [comment]
https://github.com/FlowCrypt/flowcrypt-ios/pull/169
