### ISSUE TITLE
Show avatar images in email/thread list/detail, compose recipient list/recipient popup.

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1690]
I think it will be better if we display recipient avatar image in those places.

- Email/Thread list/detail page
- Compose screen (added recipient, recipient info popup)

If we can't get recipient info image/image is empty, we may display recipient name first letter in circle like below

![image](https://user-images.githubusercontent.com/77344191/173594873-846838ca-6c1d-4533-860e-3e5f51d506ce.png)

**Comment by tomholub** [comment]
I think it would be good to do this sometime after we implement Drafts. So I'm setting it to Later milestone. Once we are closer to getting Drafts done, we'll schedule it for a specific milestone at that time.

**Comment by ioanmo226** [comment]
Yeah, but for IMAP, I think they won't provide `circle letter`. So need to implement `circle letter` feature manually i guess
> Gmail provides that "circle letter" as the alias of the user by default, I think. So every user will end up having some alias.

**Comment by tomholub** [comment]
Our IMAP implementation is almost certainly broken, with no users on it and no customers needing it, at the moment. We'll of course be fixing that, but IMAP is a low priority functionality at the moment. I'd make the avatars a Gmail-only feature.

**Comment by sosnovsky** [comment]
@tomholub Should be good task for `1.2.1: Maintenance` milestone

**Comment by ioanmo226** [comment]
@sosnovsky

**Comment by ioanmo226** [comment]
How about avatar image for message/threads?
Thread api only returns email addresses information about sender, to, etc

**Comment by ioanmo226** [comment]
I'm talking about this one though
![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/77344191/e734f2d7-3c95-462b-99be-4ffc0e952ec4)

**Comment by sosnovsky** [comment]
> How about avatar image for message/threads?
> Thread api only returns email addresses information about sender, to, etc

But we can get sender of the last thread message and then run `searchContacts` query with this sender email?
If sender is in current user's contacts then we probably can get sender's profile image from `searchContacts` response

**Comment by sosnovsky** [comment]
> How about avatar image for message/threads?
> Thread api only returns email addresses information about sender, to, etc

But we can get sender of the last thread message and then run `searchContacts` query with this sender email?
If sender is in current user's contacts then we probably can get sender's profile image from `searchContacts` response

**Comment by ioanmo226** [comment]
Got it

**Comment by ioanmo226** [comment]
Hmm.. search contacts api don't actually return user avatar. Instead it returns `user name` letter image like below one.

https://lh3.googleusercontent.com/cm/AJSPFBy-XX8kBK2gBR-OgdhuOO8pBwsgCB-UCcT8HQbPoZjgoUh7HsOcvJAIWW0vKSp1=s100

**Comment by ioanmo226** [comment]
Instead people.get api returns actual `avatar`. But problem is that it only accepts google user id instead of email address.

**Comment by tomholub** [comment]
We can't be using 3rd party API. Data leak

**Comment by ioanmo226** [comment]
Yep, I guessed so. But not sure how they managed to get correct profile information(avatar image)

**Comment by sosnovsky** [comment]
Then for now we can just render first letter of sender name in messages list:

<img width="87" alt="Screenshot 2023-08-11 at 13 14 24" src="https://github.com/FlowCrypt/flowcrypt-ios/assets/1062093/4dd98fd3-6108-4f34-9013-b9ef1674218a">
