### ISSUE TITLE
bring all except one live gmail tests to mock gmail

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1693]
after #1692 

we will leave one live gmail test there - something simple like "log in and read some message". All other tests will be mocked.

**Comment by tomholub** [comment]
How is this looking so far?

When creating exported messages for API mock - just to be sure you know - you don't have to create them manually. You can use the browser extension export functionality:

```ts
export class GoogleData {

  /**
   * This is the proper way to add messages to mock api for testing:
   *   1) log into flowcrypt.compatibility@gmail.com
   *   2) go to Settings -> Inbox and find your message
   *   3) click "download api export"
   *   4) save the json file to exported-messages folder
   */
  private static exportedMsgsPath = './test/source/mock/google/exported-messages/';

```

You could modify the browser extension to also offer this export functionality for `e2e.enterprise.test@flowcrypt.com` and then export them more or less with one click. Making it easier to port messages from live to mock tests.

**Comment by sosnovsky** [comment]
@tomholub looking good - 5-6 tests from 'Inbox` group left to migrate to mock. Currently implementing some message actions for the mock backend, like adding/removing labels, deleting messages etc.

> You could modify the browser extension to also offer this export functionality for `e2e.enterprise.test` flowcrypt.com account

Yes, I enabled message export for `e2e.enterprise.test` account locally, will create PR as it'll be useful in the future for new tests.

I have a question about encrypting messages for mock tests - should I use `.env` file for storing private key of `e2e.enterprise.test`? I thought about generating new mock private key and store it in mock constants, but then it won't be possible to decrypt messages exported from our real `e2e.enterprise.test` account.

**Comment by sosnovsky** [comment]
@tomholub I don't have write access to https://github.com/FlowCrypt/flowcrypt-browser for creating PR

**Comment by tomholub** [comment]
here https://github.com/FlowCrypt/flowcrypt-browser/invitations
