### ISSUE TITLE
speed up project build in ci with prebuilt dependency - Texture

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1702]
It take 28 minutes to build the project, and I seem to recall that Texture took a good chunk of that. Is that true? If yes, could the build times be sped up by making a prebuilt swift package?

![image](https://user-images.githubusercontent.com/6306961/174353087-d7a0fb27-a875-4465-aee4-3d0779f83b88.png)

**Comment by ioanmo226** [comment]
@sosnovsky , @tomholub FYI here's XCLogParser log
![y79s1yj5](https://user-images.githubusercontent.com/77344191/182345700-e9f87030-5274-41e7-8740-2e34db6536df.png)
![g3w1wutk](https://user-images.githubusercontent.com/77344191/182345916-686a6cd4-5b11-47eb-ae5b-873df31983b5.png)

**Comment by sosnovsky** [comment]
As expected Cocoapods build time is the longest one, possible improvements:
- create `Texture` fork with SPM support (example - https://github.com/shimastripe/Texture/releases/tag/3.1.1)
- just manually copy library files for `ENSwiftSideMenu` instead of using pod (https://github.com/evnaz/ENSwiftSideMenu/tree/master/Library)

**Comment by sosnovsky** [comment]
@tomholub I think this issue can be added to [1.2.1: Maintenance](https://github.com/FlowCrypt/flowcrypt-ios/milestone/45) milestone too, as it should improve project build time.

We just need to create our own forked repository for https://github.com/texturegroup/texture as we did for [mailcore2](https://github.com/FlowCrypt/mailcore2)

**Comment by tomholub** [comment]
:+1: good addition

**Comment by tomholub** [comment]
You can also file issues for other maintenance tasks that you'd like to do, in that milestone. Or move the issues there.

**Comment by sosnovsky** [comment]
@tomholub can you please create fork repository for https://github.com/texturegroup/texture on FlowCrypt organization?
So I'll be able to use it for adding SPM support

**Comment by tomholub** [comment]
Yes, will do. Later when I'm gone, @DenBond7 has these type of permissions

**Comment by tomholub** [comment]
Here https://github.com/FlowCrypt/Texture/
