### ISSUE TITLE
Set `isHeadless` to `true` in appium only in semaphoreci

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1719]
I think it might speed up CI speed(Maybe 1.5x-2x) if we set `isHeadless` to `true` only in semaphoreci. (I think we still need to see ui results in local as that's useful for debugging).
Let me know your thoughts.

https://appium.io/docs/en/writing-running-appium/caps/#:~:text=true%20or%20false-,isHeadless,-Set%20this%20capability

![image](https://user-images.githubusercontent.com/77344191/175057200-a003d91d-2c7c-460d-822b-4c60a2eaba4a.png)

**Comment by ioanmo226** [comment]
@tomholub , @sosnovsky

**Comment by ioanmo226** [comment]
@sosnovsky As I checked from local, I tested 10 tests and those all passed with `isHeadless: true` flag and speed indeed increased (1.5x i think)

We don't need to worry about this. App generates failed screenshots even though we have `isHeadless: true` flag
> The only downside I see for know - we won't be able to see screenshots of failed tests (but in this case we can temporarily remove isHeadless flag for getting screenshots)

**Comment by sosnovsky** [comment]
> We don't need to worry about this. App generates failed screenshots even though we have `isHeadless: true` flag

Oh, great! Then we definitely should try it on Semaphore

**Comment by tomholub** [comment]
For these kind of improvements, if you two agree, you don't need my opinion :-)
