### ISSUE TITLE
openpgpjs v5 improvements

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1788]
This looks good, the other things could be settled, per comments.

Also now that the build process is fixed and modernized, we should copy the built result into resources folder each time the js code is built. It no longer has to be a separate step.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1786#pullrequestreview-1070844282_

**Comment by sosnovsky** [comment]
> Also now that the build process is fixed and modernized, we should copy the built result into resources folder each time the js code is built. It no longer has to be a separate step.

We already have `npm run deploy` command which builds current js code and then copies result into `Resources` folder (https://github.com/FlowCrypt/flowcrypt-ios/blob/master/Core/package.json#L32), is it enough?

**Comment by tomholub** [comment]
I'd recommend to do that on every `npm run build` also. So could add `postbuild` command for example that points to deploy, or could add `&& npm run deploy` to build.

**Comment by sosnovsky** [comment]
from https://github.com/FlowCrypt/flowcrypt-ios/pull/1786#discussion_r944302037

@tomholub I ran performance tests with old and updated `core` code, performance improved for all cases:
```
decrypt key - 54ms -> 31ms
encrypt key - 359ms -> 95ms
verify key - 12ms -> 5ms
encrypt message - 25ms -> 7ms
decrypt message - 3ms -> 3ms
sign message - 836ms -> 138ms
```

also `flowcrypt-ios-prod.js.txt` file size decreased from 7.3mb to 4.4mb (probably because of build optimizations in webpack 5)

**Comment by tomholub** [comment]
looks good. Thanks!
