### ISSUE TITLE
support of http redirects when looking up on WKD

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1804]
When searching for a public key of a particular user, the WKD endpoint may respond with a HTTP redirect pointing to another URL.

Such redirects should be followed to the new url, where the public key ultimately is. From customer testing, it may be that today these redirects are not supported when calling WKD from iOS.

**Comment by sosnovsky** [comment]
@tomholub I tested urls with redirects and they all work well - requests follow redirect and return data from redirect url (it's default behavior for `URLRequest` which we're using for api calls)

Do you have specific url with redirect which fails for WKD lookup?

**Comment by tomholub** [comment]
You're right. It does work. I'll let the customer know, maybe their issue is elsewhere.
