### ISSUE TITLE
Add ability to hide quote text in thread message 

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#1830]
Currently each thread message shows quote of all previous messages in the end of text.
It makes each message cell very long in thread view and more scrolling is needed for finding specific message.

I propose to add `Show history` button instead of thread quote text, so all previous messages texts will be shown only after button tap.

**Comment by tomholub** [comment]
The `...` button similar to what browser extension does?

**Comment by sosnovsky** [comment]
> The `...` button similar to what browser extension does?

Yes, we can call it `...` on ios too, for consistency.

**Comment by tomholub** [comment]
This would be good to have
