### ISSUE TITLE
drop `uuid`, use id_token

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1841]
Also should drop `uuid` mechanism from iOS and Android, and use id_token there too.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4686#issuecomment-1262505327_

**Comment by sosnovsky** [comment]
@tomholub Currently `BackendApi` isn't implemented on iOS - https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Functionality/Api/Account%20Server%20Apis/BackendApi.swift#L7

So no changes needed for now.
