### ISSUE TITLE
Appium UI test doesn't work with iOS 16(Xcode 14)

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1842]
UI test doesn't start application when we want to run ui tests.
Seems like appium v1 doesn't support iOS 16 and need to upgrade several packages

https://github.com/appium/appium/issues/17498

**Comment by sosnovsky** [comment]
@ioanmo226 did you caught such error during live ui test on Semaphore? Currently it causes live test to fail on each run, but works well locally.

<img width="400" src="https://user-images.githubusercontent.com/1062093/193803996-a2bd49f7-c5e4-43ae-baad-61b588cc3b95.png">

**Comment by ioanmo226** [comment]
No. but I got several emails from Google.
![image](https://user-images.githubusercontent.com/77344191/193812192-744f4332-4c37-4507-a8cc-0ed8ed81e624.png)

**Comment by sosnovsky** [comment]
Got it, then probably we'll need to temporary disable live test (as it passes locally), merge this PR and later check if this sign in warning  went away.

**Comment by ioanmo226** [comment]
ok
