### ISSUE TITLE
FlowCrypt ios app crash when trying to decrypt a very large message

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#1877]
Description:
I have recently tested the ios app regarding the security report we received and found out that the app crashed when trying to decrypt an encrypted message with 100Mb lengths of text. 

Such payload can be created through python: `python3 -c 'print("A"*100000000)' > 100_million_A.txt` and encrypt the plain text message using `gpg`

Steps to reproduce:

1. Create a file containing a large input. eg. python3 -c 'print("A"*100000000)' > 100_million_A.txt
2. Encrypt it with `gpg` and send it yourself using Gmail's built-in message composer.
3. Open the message on the FlowCrypt iOS and it will crash the app.

The android app has a limit of cutting 50Kb of decrypted messages to prevent this (though the android app is not working as expected yet since it cuts the encrypted content, not the decrypted content) - https://github.com/FlowCrypt/flowcrypt-android/blob/c5d8e4b841c784a0101f20a3854a84f406b89987/FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt#L1744

Please see https://github.com/FlowCrypt/flowcrypt-security/issues/215 for more details.

**Comment by sosnovsky** [comment]
@martgil unfortunately I don't have access to https://github.com/FlowCrypt/flowcrypt-security/ repository, do you have permissions to add me there?

**Comment by martgil** [comment]
Sorry, i dont have permissions to add you there but I think @tomholub can
add you there to see some other iOS related issues.

**Comment by sosnovsky** [comment]
@DenBond7 do you have permissions to add new users to https://github.com/FlowCrypt/flowcrypt-security/ ?

**Comment by DenBond7** [comment]
> @DenBond7 do you have permissions to add new users to https://github.com/FlowCrypt/flowcrypt-security/ ?

Yes, I do. But there are no free members.

@tomholub Can we have more members for that private repository?

**Comment by tomholub** [comment]
yes, you can when needed. Just added him https://github.com/FlowCrypt/flowcrypt-security/invitations
