### ISSUE TITLE
Possible draft management issue when deleting draft message

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#1880]
Description:
During my testing, I noticed that when deleting a draft message from the FlowCrypt iOS app, it deletes the draft message completely without it being transferred to the trash folder. 

In comparison, Gmail first transfers the delete draft messages to the trash folder  -- the FlowCrypt android app does the same so I think we should follow this kind of flow for the iOS app.

**Comment by sosnovsky** [comment]
@martgil Strange, I just re-checked iOS Gmail app and Gmail web version - after deleting drafts don't appear in `Trash` folder, they're deleted completely.
Can you please tell me how I can reproduce it - does it happens for new drafts or for draft replies for existing threads?

**Comment by martgil** [comment]
Thank you, Roma - I understand.

What you describe is exactly what happened. The message discarded when
deleting it from the compose message screen.

**Comment by sosnovsky** [comment]
Mentioned functionality will be implemented in https://github.com/FlowCrypt/flowcrypt-ios/issues/1543
