### ISSUE TITLE
cannot download attachment when empty message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1906]
send message with no body, and one attachment, from browser extension

restart app

open in ios, download it

it will not ask for pass phrase, and will fail

**Comment by tomholub** [comment]
@sosnovsky

**Comment by sosnovsky** [comment]
@tomholub I tried to reproduce this bug on `master` branch, but it works well for me - app asks for passphrase after app restart and I'm able to download attachment. Are you using the latest `master` code?

**Comment by tomholub** [comment]
I was using the last enterprise release, not master. If you can reproduce on that one, but not on master, then we can close it as fixed.

**Comment by sosnovsky** [comment]
@tomholub is this the latest enterprise release?
<img width="800" alt="Screenshot 2022-11-09 at 14 32 56" src="https://user-images.githubusercontent.com/1062093/200831358-54fcf8f9-77b9-45b1-821e-7cede426167f.png">

**Comment by sosnovsky** [comment]
I checked this issue with code from September 2, and it still works well for me.
Maybe it happens only with specific conditions - can you please tell your attachment extension and size (I tried small text file and 10mb file, no issues with them)
