### ISSUE TITLE
Use native swift functions in WKWebView

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#1909]
With `JavaScriptCore` we used some native swift functions for increased performance (like `getSecureRandomByteNumberArray`, `decryptAesCfbNoPadding` etc).

Need to find way how to use them in `WKWebView` and check if they'll increase performance of `Core` functions.

**Comment by tomholub** [comment]
If web view performance is this much better, we would no longer need the core Swift functions. So you can remove them.

**Comment by sosnovsky** [comment]
`WKWebView` seems to be faster because it has native implementation for `crypto` functions and also `openpgp` can use some native optimisations for better performance there.
