### ISSUE TITLE
tapping trash icon on an email does nothing

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1913]
on version 1.1.1. It just shows loader for a second, but nothing changes.

**Comment by sosnovsky** [comment]
@tomholub I checked it - this bug occurs for me in `sent` folder, but messages are deleted after tap in `inbox`, same for you?

**Comment by tomholub** [comment]
for me on 1.1.1 also doesn't work in inbox folder
