### ISSUE TITLE
ability to view list of attachments

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#193]
part of  #275

When I open a message, currently it doesn't show a list of attachments on that message.

Please list attachments in message view, and their sizes. Downloading or decrypting doesn't need to be implemented yet (clicking each attachment will produce a toast "Downloading attachments not implemented yet".

 The `Core.parseDecryptMsg` returns an array of MsgBlock of various types, and one textual representation of the message body. Currently we only look at textual representation of the message body `text` but not actual individual blocks.

You'll want to look at `decrypted.blocks` to find the ones of the following types:  `plainAtt`, `encryptedAtt`, `decryptedAtt` and render them below. Use our Android app for rough visual guidance. Attachments that are encrypted (encryptedAtt, decryptedAtt) should be styled in green similar to how encrypted text is green. `plainAtt` should be styled in a neutral color.

When opening a (draft) PR please add a screenshot to the description as well.

The functionality should be accompanied with meaningful tests - for guidance you can ask me (general approach) and @Kharchevskyi (specific code questions).

**Comment by qsdemir** [comment]
@tomholub @Kharchevskyi 

`Core.parseDecryptMsg` returns an array of MsgBlock, but that array always consists of only one element.  

`decrypted.blocks` always has one block, and its type is `plainHtml`, which means that blocks of `plainAtt`, `encryptedAtt`,  `decryptedAtt` types don't exist. This might be an issue with js code, most likely `parseDecryptMsg`.

Can you please take a look into this? I didn't want to fiddle around js, and Core too much, because I didn't want to break something else unknowingly.

**Comment by tomholub** [comment]
Hello, that should be the case if source message contains no attachments. But if there are any attachments, they should show up as `MsgBlock`s. 

I'll share a test account with you (over email) where you will find a few sample messages in various formats to test with to confirm.

**Comment by tomholub** [comment]
@qsdemir I've sent you email with credentials to access a test account.

There, please test the following messages:
 - `file preview - RICH TEXT PGP/MIME - open txt file, image, pdf, unknown`
 - `file preview - open txt file, image, pdf, unknown`
 - `[enigmail] signed message inline + attachment`
 - `[enigmail] signed message + attachment + PGP/MIME`

There are various types of attachments represented there:
1) plain
2) encrypted separately from message ("inline")
3) encrypted together with message ("pgp/mime")
4) inside pgp/mime signed message

We may have varying compatibility on iOS for those. If none of them work, I'll have to take a second look. Please let me know.

**Comment by tomholub** [comment]
Hello - do you have any update on this? Do you need any help? Were you able to log in, were you able to find the emails I listed? Are you seeing any attachment related MsgBlocks on these emails?

**Comment by qsdemir** [comment]
Hi Tom. I was able to log in and find those emails. Attachments are retrieved in MsgBlocks, but I have some troubles displaying it, still getting used to Texture framework. I will ask Anton today if he could check just too see if I have the right approach

**Comment by tomholub** [comment]
Got it - thank you. Feel free to create a Draft PR, and self-review on GitHub to highlight code that you are unsure about or where you need guidance.

**Comment by qsdemir** [comment]
Just a quick status update - there has been progress on UI part as well, but still I'd like to hear your feedback whether or not this is right. You can expect Draft PR on Monday.

**Comment by Kharchevskyi** [comment]
> Hello, that should be the case if source message contains no attachments. But if there are any attachments, they should show up as `MsgBlock`s.
> 
> I'll share a test account with you (over email) where you will find a few sample messages in various formats to test with to confirm.

Can you please share it with me as well for testing purposes?

**Comment by tomholub** [comment]
Definitely - I'll send it over email.

**Comment by qsdemir** [comment]
Hi, there are still some things unclear. For example, how to get actual data from MsgBlocks. I assumed that it would be inside `content`, but on test account, all blocks have empty content field. I've just updated PR, maybe @Kharchevskyi can take a look into it

**Comment by tomholub** [comment]
In this issue we are only rendering list of attachments - we don't concern ourselves with data yet.

But you should already be able to get file names, at least. Is it not giving you those either?

**Comment by qsdemir** [comment]
No, I'm not getting file names, nor size of the files. Name and size are still hardcoded, just to show something so the node isn't empty. We would like to hear your feedback on the rest.

**Comment by tomholub** [comment]
I'll take a look.

**Comment by tomholub** [comment]
The JavaScript object that this comes from has the following properties (not always all of them):

```ts
class MsgBlock {
    constructor(type, content, complete, signature, keyDetails, // only in publicKey when returned to Android (could eventually be made mandatory, done straight in detectBlocks?)
    attMeta, // only in plainAtt, encryptedAtt, decryptedAtt, encryptedAttLink (not sure if always)
    decryptErr, // only in decryptErr block, always
    verifyRes) {
        this.type = type;
        this.content = content;
        this.complete = complete;
        this.signature = signature;
        this.keyDetails = keyDetails;
        this.attMeta = attMeta;
        this.decryptErr = decryptErr;
        this.verifyRes = verifyRes;
    }
}
```

The interesting property here is `attMeta`. But the struct on the Swift side is missing this property, therefore when decoding from JSON, these get lost.

```swift
struct MsgBlock: Decodable {
    static func blockParseErr(with content: String) -> MsgBlock {
        MsgBlock(type: .blockParseErr, content: content, decryptErr: nil, keyDetails: nil)
    }

    let type: BlockType
    let content: String
    let decryptErr: DecryptErr? // always present in decryptErr BlockType
    let keyDetails: KeyDetails? // always present in publicKey BlockType
    // let verifyRes: VerifyRes?,
    // let attMeta: AttMeta?; // always present in plainAtt, encryptedAtt, decryptedAtt, encryptedAttLink

    // let signature: String? // possibly not neded in Swift

    struct DecryptErr: Decodable {
        let error: Error
        let longids: Longids
        let content: String?
        let isEncrypted: Bool?

        struct Error: Decodable {
            let type: ErrorType
            let message: String
        }

        struct Longids: Decodable {
            let message: [String]
            let matching: [String]
            let chosen: [String]
            let needPassphrase: [String]
        }

        enum ErrorType: String, Decodable {
            case keyMismatch = "key_mismatch"
            case usePassword = "use_password"
            case wrongPwd = "wrong_password"
            case noMdc = "no_mdc"
            case badMdc = "bad_mdc"
            case needPassphrase = "need_passphrase"
            case format
            case other
        }
    }

    enum BlockType: String, Decodable {
        case plainHtml // all content blocks, regardless if encrypted or not, formatted as a plainHtml (todo - rename this one day to formattedHtml)
        case publicKey
        case privateKey
        case encryptedMsgLink
        case plainAtt
        case encryptedAtt
        case decryptedAtt
        case encryptedAttLink
        case decryptErr
        case blockParseErr // block type for situations where block json could not be parsed out
        // case cryptupVerification; // not sure if Swift code will ever encounter this
    }
}
```

Please inspect the JSON coming in before it gets parsed to become a Swift struct, and update the Swift struct type appropriately to contain the name / size which should be present in `attMeta`.

**Comment by qsdemir** [comment]
Thanks, I got it. Found in js code that `attMeta` has `name`, `data` and `length` in its structure and I can display name and size of the attached file. Any other fields that I should be aware of?

**Comment by tomholub** [comment]
These will be enough for this issue. Thanks
