### ISSUE TITLE
Fix drafts test

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#1930]
`check drafts functionality` test occasionally fails on semaphoreci.
Needs to be fixed

**Comment by ioanmo226** [comment]
@sosnovsky

**Comment by sosnovsky** [comment]
@ioanmo226 `webdriverio` driver which is used by `appium` for ui tests was recently updated from 7 to 8 version and tests seems to be more stable. And I think drafts test was fixed too, so if there won't be any fails with it in the next week then we can close this issue.

**Comment by ioanmo226** [comment]
I can see that test failed again after webdriverio update.
I pushed fix and let's see if it passes
https://flowcrypt.semaphoreci.com/jobs/93860042-0d07-4112-aa1b-80f9e1063a6a/summary?report_id=4ae71336-e44b-39bf-b9d2-752e234818a5

**Comment by sosnovsky** [comment]
> I can see that test failed again after webdriverio update.

Ah, I see.

> I pushed fix and let's see if it passes

It should pass with your fix, as you've changed test logic by adding manual reload, but test should test if emails list is automatically updated even without manual reload.
