### ISSUE TITLE
The iOS beta app is expired/no longer accepting new testers

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#1949]
The FlowCrypt Testflight link in https://flowcrypt.com/download no longer accepts new testers. Beta testers reported that the FlowCrypt ios app is unusable. They're interested to know when it will become available again. (Enterprise customers may be affected)

Reference:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGrbRPkfjVXjjFbSSBwtmTnqfTl
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwHNqLVgqtkjkDJbPdjQxJPXzDx

**Comment by tomholub** [comment]
@sosnovsky do you have the necessary permissions to increment the version number, build and sign the app and upload a new TestFlight build to app store connect?

**Comment by sosnovsky** [comment]
@tomholub I tried to upload new build to Testflight, but got these errors:

<img width="689" alt="Screenshot 2022-12-02 at 11 46 02" src="https://user-images.githubusercontent.com/1062093/205264496-7e04787a-324d-4e4e-a24a-6863a250a839.png">

Here are steps needed for giving `cloud signing permission`:
- Go to https://appstoreconnect.apple.com/access/users
- Select the correct person and under "Additional Resources" check both `Access to Certificates, Identifiers & Profiles` and `Cloud Managed Distribution Certificate Access`

**Comment by tomholub** [comment]
They were already there, anything else?

<img width="918" alt="image" src="https://user-images.githubusercontent.com/6306961/205303457-6ba7e007-33d3-46e2-83ca-1d3589517db5.png">

**Comment by tomholub** [comment]
All the TestFlight stuff says "read only" not sure why

**Comment by sosnovsky** [comment]
Probably it happens because we don't have any `distribution` certificate at https://developer.apple.com/account/resources/certificates/list

I'll need `App Manager` role to create new distribution certificate (https://developer.apple.com/support/roles)

You can temporarily assign me this role, so I'll create new certificate and then you'll set it back to `Developer`

**Comment by tomholub** [comment]
I just added a distribution certificate - please retry

**Comment by tomholub** [comment]
The second one. When done, it just downloaded to my file system.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/6306961/205309399-44c3f6b5-a3fb-4253-ad6f-ecc43c2274ed.png">

**Comment by sosnovsky** [comment]
Probably we're also missing provisioning profile for the app - https://developer.apple.com/account/resources/profiles/list

**Comment by sosnovsky** [comment]
And here is a manual of how you can export distribution certificate so I can use it on my machine - https://sarunw.com/posts/how-to-share-ios-distribution-certificate/#exporting-a-certificate

**Comment by tomholub** [comment]
Provisioning profile is tied to particular devices

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/6306961/205338199-a67b6796-1044-4285-bf5a-4741c1566255.png">

ok I'll make you a manager temporarily

**Comment by tomholub** [comment]
Please list all steps you took with that.

**Comment by sosnovsky** [comment]
> Please list all steps you took with that.

I just re-tried to upload build to App Store and Xcode automatically created `Distribution Managed` certificate.

New `1.2.0` build is now processing at https://appstoreconnect.apple.com/apps/1591754995/testflight/ios

**Comment by martgil** [comment]
The reporting users are now informed. I can now install and use the latest build too. Thank you!
