### ISSUE TITLE
decrypt encrypted attachments during download

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#195]
part of  #275, after #194

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/118121654-516c5600-b3e1-11eb-89c2-409c054ce344.png)

**Comment by ekievsky** [comment]
To check if attachment is encrypted we just use a RegEx, right?

How do we check if attachment is armored? Seems that in context of Keys it's handled by JS code

**Comment by tomholub** [comment]
> How do we check if attachment is armored? Seems that in context of Keys it's handled by JS code

Yes, on iOS this part is done in JS code as you say - decryptFile will transparently handle armored or binary attachments.

> To check if attachment is encrypted we just use a RegEx, right?

For now you can go by the attachment ending with `.pgp` -> encrypted, else plain. I would probably not use RegEx if there is a simpler String method like `.endsWith(".pgp")`. If Swift doesn't have that, then regex.

**Comment by ekievsky** [comment]
It does, got you, thanks!

**Comment by ekievsky** [comment]
One more question, are the listed errors thrown by JS code? is there a way I may simulate these errors using JS code?

**Comment by tomholub** [comment]
> btw, error with Could not fetch keys reproduces for me really often

Could you try to debug it as well? I'd really like to resolve this. Actually - if you could look into it before continuing on the decryption, that would be great.

**Comment by tomholub** [comment]
> One more question, are the listed errors thrown by JS code?

Yes, returned from js

> is there a way I may simulate these errors using JS code?

`key_mismatch` - give it a file that was encrypted for public key that does not match private key you are using for decription

`need_passphrase` - omit pass phrase in PrvKeyInfo

`wrong_passphrase` - give it wrong pass phrase in PrvKeyInfo

`format` - remove some chunk of the encrypted data from the middle, which should screw up the message enough that when you try to decrypt it, you'll get a format error.

Unit tests for these would be good.
