### ISSUE TITLE
documentation - steps when creating a new release

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1953]
I'll take 1.2.0 as an example, and list the steps here. For 1.2.0 I've done the steps described below.

1) move all finished issues that we took action on to the current milestone from other milestones except the "discussion" milestone (after this step, discussion milestone is the only one that is expected to have any finished issues other than the current milestone). Example:

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/6306961/205424091-a22b7e3c-695e-4c7d-ae27-939327cd9126.png">

2) compose release notes, by copying all issue names from the milestone to the milestone description and editorializing them as follows:
  - all refactoring issues with no change of functionality should be as one item called "internal improvements"
  - group of related issue that together are for a single goal should be together (in 1.2.0 it was "added drafts functionality")
  - if the milestone includes "add feature X" and then "fix a bug for the same feature X" then only "add feature X" should be on the list. We care about the difference between last released milestone and this one, not each step we took
  - editorialize remaining issues to describe them from the point of view of the user and customer, what do the changes mean for them. So for example issue called "app crashes when we do X" should be editorialized as "fixed a crash when doing X" in release notes. The issue title can also completely differ from release notes if the issue title was very technical or internal-focused, and it wouldn't be clear to users what the difference is.
  - change order of release notes from most impactful on top, to least impactful on the bottom
3) increment version, build + publish, submit version increase PR
4) go to https://appstoreconnect.apple.com/ -> FlowCrypt -> TestFlight -> iOS, where the app is showing `Ready to submit`. In `Groups` column click `+` and choose `Public Beta`

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/6306961/205424525-f66c76df-6442-43c4-a5fa-afb35f687660.png">

5) `What to test` modal will pop up. Paste the release notes there.

6) You should see it `Waiting for review` on TestFlight now

<img width="736" alt="image" src="https://user-images.githubusercontent.com/6306961/205424612-af5f28cd-49ae-443e-85a6-f3e92d5aa6a5.png">

7) go to `FlowCrypt` -> `App Store` -> `Add Build` -> `1.2.0`. Save, ensure version on the page matches the build version.

8) `Add for Review`, ensuring that `Version Release` on the bottom of the page is set to `manually` (for now)

**Comment by tomholub** [comment]
For the public release it's missing some s

**Comment by tomholub** [comment]
@sosnovsky this is for you for future releases. We could target releasing approximately monthly, unless there's an important bugfix release to do in which case it could be done anytime.

When choosing what to add to each milestone, for myself I prefer the following approach: if a PR is tied to some issue (as 99% of them are), then the issue should be added to the milestone, and PR should be without milestone. If the PR has no associated issue, then I add it to the milestone. That way there are no duplicates in milestone (issue + related PR) and I find it easier to compose release notes. But if it will be you composing the notes, then it's up to you how exactly you organize it. In that case, please share here your preferred approach, so I can follow it when you are away from work.

Finally, when doing releases, it's good to check "issues with no milestone", both completed and open, to move them to the right milestones. https://github.com/FlowCrypt/flowcrypt-ios/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone if any show up

**Comment by tomholub** [comment]
Forgot to add, for enterprise release:

10) build/release enterprise app
11) Add for enterprise TestFlight with same steps, except add group "Enterprise Testers"
12) Add for Enterprise App Store release with an automatic release +2 calendar weeks
13) write emails to our enterprise customers that a new iOS version is ready for them to test, and that it will be auto-released on X date. Add release notes. (copy me in the email)

For now I'll be doing steps 10-13 but at some point in the future it would be done by you as well.

**Comment by sosnovsky** [comment]
> When choosing what to add to each milestone, for myself I prefer the following approach: if a PR is tied to some issue (as 99% of them are), then the issue should be added to the milestone, and PR should be without milestone. If the PR has no associated issue, then I add it to the milestone. That way there are no duplicates in milestone (issue + related PR) and I find it easier to compose release notes. I've noticed you like to add both issues and PRs to that milestones. In either case, if it will be you composing the notes, then it's up to you how exactly you organize it - in that case, please share here your preferred approach, so I can follow it when you are away from work (eg all issues + PRs should be in milestone, or whatever other system you prefer).

Your approach looks cleaner, I'll use it for the next PRs, so there will be no more duplicates for issues and PRs.

@tomholub what about moving these release documentation to repository [wiki](https://github.com/FlowCrypt/flowcrypt-ios/wiki), so it'll be easier to find?

**Comment by tomholub** [comment]
yes, feel free to move it to wiki

**Comment by sosnovsky** [comment]
✅ done - https://github.com/FlowCrypt/flowcrypt-ios/wiki/Release-process
