### ISSUE TITLE
add missing screenshots + prepare public App Store page

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1954]
I didn't complete step 8 from #1953 because of missing screenshots:

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/6306961/205424925-ff60ac2c-d617-4582-b8d1-799c9c566c5d.png">

Please help me spend some time on the release details + screenshots of the app on various devices / various screens.

App description is also lacking, please have a look at the Chrome extension and Android app to create description for the iOS app as well, preparing it for public release.

**Comment by sosnovsky** [comment]
@tomholub I uploaded all needed screenshots and updated app description to highlight FlowCrypt features

**Comment by sosnovsky** [comment]
@tomholub should I send current build to App Store review?

**Comment by tomholub** [comment]
yes, you may go ahead and send it for review, with manual release after that. thanks!

**Comment by sosnovsky** [comment]
@tomholub `1.2.0` was approved by App Store review, now it's ready to be released.

**Comment by tomholub** [comment]
let's release it. about time i think 👍

**Comment by sosnovsky** [comment]
Released, should be available on App Store in a few minutes - https://apps.apple.com/app/flowcrypt-encrypted-email/id1591754995

**Comment by tomholub** [comment]
Excellent. Please monitor the crashes/screenshots once in a while (weekly, especially after updates), on all of the builds (2x testflight + 2x prod). Are you able to sign up for email notifications when there is a new crash or screenshot? That would be best.

**Comment by sosnovsky** [comment]
It seems there is no way to have email notification on new crash or screenshot, but I'll check crash reports in the beginning of each work day.

**Comment by tomholub** [comment]
They don't show up that often, you'll notice, so weekly should do, except post-release good to check a bit more.

I'll generally see one a month these days, used to be many more initially.
