### ISSUE TITLE
Missing backup query

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#1955]
App setup fails with error
```
Missing backup query:
JavaScript execution returned a result of an unsupported type
```

<img src="https://user-images.githubusercontent.com/1062093/205650624-2a627560-d6a6-4c64-a92c-0da424243d32.png" width="300">

**Comment by tomholub** [comment]
could it be that the web view wasn't available immediately after starting, for that user, maybe it would work if they retried?

is that message defined by us? maybe we can include more details that was actually returned?

**Comment by sosnovsky** [comment]
> could it be that the web view wasn't available immediately after starting, for that user, maybe it would work if they retried?

Currently web view is initialized as `lazy var`, so `Core` code should wait for its initialisation, it shouldn't cause such issue

> is that message defined by us? maybe we can include more details that was actually returned?

It's error message from iOS `WKWebView`, I'll check if it's possible to add more details to it

**Comment by ioanmo226** [comment]
@sosnovsky Please confirm if you are working/worked on this task.

**Comment by sosnovsky** [comment]
@ioanmo226 this bug is from user feedback - I was able to reproduce it only once on device, when trying to login.
All next login attempts passed well for me, without any errors. May be you'll be able to find what leads to this error

**Comment by tomholub** [comment]
We don't have to have the backup query in javascript anymore, for one thing.

**Comment by ioanmo226** [comment]
@sosnovsky I think we can move this task to `Later` or `Can't reproduce` milestone and revisit once when this error happens?
I haven't been able to reproduce it though

**Comment by tomholub** [comment]
https://github.com/FlowCrypt/flowcrypt-ios/issues/1955#issuecomment-1597006845

**Comment by ioanmo226** [comment]
Yes?

**Comment by tomholub** [comment]
If you do that, this issue will for sure not happen again.

**Comment by ioanmo226** [comment]
Aha, I see

**Comment by ioanmo226** [comment]
Can anyone clarify why we're initiating the `fetch backup query` from the JavaScript side?
Is there a particular reason we can't execute this directly in Swift?
I'm concerned that shifting this logic to Swift could potentially cause issues.

@sosnovsky , @tomholub 

https://github.com/FlowCrypt/flowcrypt-ios/blob/2cfa95b762a86aae88104d6303e003ac5f449aee/Core/source/core/const.ts#L29

**Comment by sosnovsky** [comment]
I think we've used JavaScript code for it because earlier this code was reused in iOS, Android and web extension, so it was easier to maintain 1 codebase. But currently we're using different code on these platforms, so it should be ok to move this functionality to Swift

**Comment by ioanmo226** [comment]
Got it. Thank you
