### ISSUE TITLE
option to keep pass phrase only in memory

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#197]
During setup (of new key or when importing key or when loading from backup - whenever I'm creating or entering pass phrase), the user should see two radio buttons:

> **o**   store pass phrase locally
> o   keep pass phrase in memory

Default is to store.

If the user switches it, then we do not store pass phrase with the key (or at all). We only keep it in memory for up to 4 hours from the moment it was stored - then it needs to be forgotten. During those 4 hours, the key will be used for actions (eg decrypt messages). After those 4 hours, the user will be prompted for a pass phrase with a modal / alert to re-enter it, at which point it will be again remembered for 4 hours.

If app gets killed, pass phrase gets forgotten.

**Comment by DenBond7** [comment]
how it looks on Android

![image](https://user-images.githubusercontent.com/2863246/119663556-1f281300-be3b-11eb-81ea-d3be1aac5c64.png)

**Comment by Kharchevskyi** [comment]
@DenBond7 thank you. Is it the same on a screen where you enter a new pasha phrase in case there are no backups?

**Comment by DenBond7** [comment]
I think it will be very similar. We don't have such a realization for the option `"Create a new key"` yet.

**Comment by tomholub** [comment]
To all import screens, we'll be adding the two radio buttons
