### ISSUE TITLE
enteprise release 1.2.0 [Monday]

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#1991]
Please follows steps 10-13 for enterprise release at: https://github.com/FlowCrypt/flowcrypt-ios/wiki/Release-process so they can test 1.2.0 in test flight, and so that 1.2.0 enterprise release is submitted as well.

**except please choose manual release for the enterprise release this time instead of scheduled date**, as customer is still testing a particular problem they had with previous versions. we want to make sure they give us a green light before scheduling.

So at this moment, after your actions, only TestFlight 1.2.0 will be available to them, and they'll still continue using previous version on prod this time.

**Comment by sosnovsky** [comment]
@tomholub I checked App Store Connect of enterprise app and there we have `1.0.6` build which is currently available on App Store and also `1.1.0` build which is approved by App Store review, but not released to App Store.

For sending new `1.2.0` build to review we need to release approved `1.1.0` build to App Store or cancel `1.1.0` release. Should I cancel it and replace with the new `1.2.0` build?

**Comment by tomholub** [comment]
If they will be testing 1.2.0 i testflight, then it makes sense to cancel previous pending prod build and re-submit 1.2.0 for manual release later.

Just make sure that it's possible to update directly from their currently live prod version to 1.2.0. Like, that we didn't remove some migration that is needed for direct update between these two somewhat distant versions.

**Comment by sosnovsky** [comment]
Okay, I'll test migrating from the previous released enterprise build to the `1.2.0`

**Comment by sosnovsky** [comment]
Tested updating from previous `1.0.6` build to `1.2.0` - works well. Sent new build to Testflight review.

**Comment by tomholub** [comment]
👍 and also to prod review, manual release

**Comment by sosnovsky** [comment]
> 👍 and also to prod review, manual release

done ✅

**Comment by sosnovsky** [comment]
> 13. write emails to our enterprise customers that a new iOS version is ready for them to test

@tomholub do we have list of enterprise customers emails? Or I can just copy all emails of enterprise testers from Testflight?

**Comment by tomholub** [comment]
for ios,  only the biggest customer on top of the list. the one we were already in communication with. you may follow the particular contact (plus cc email) that is highlighted in the list for that customer

it won't hurt to also cc other people from the previous conversation about ios update

but other enterprise customers don't use ios (yet)
