### ISSUE TITLE
a way to enter several recipients

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#200]
Currently, the recipients field is just a simple text field. But instead we should have a way to enter recipient emails.

Have a look at FlowCrypt Android App or Browser Extension. 

**Within scope for this PR:** ability to enter several recipients, and these recipients should show as distinct "chips". Ability to remove each recipient (by putting carrot to the right of them and hitting backspace? take a look at other email apps, particularly Gmail, and do something similar).

**Out of scope:** evaluating recipients and coloring them (which will be in issue #201 separately). But please choose UI elements that will be easy to color, select, copy, paste and otherwise manipulate, similar to what Android does (or any other email app).

**Comment by tomholub** [comment]
Please ask questions to clarify this issue if it needs clarification

**Comment by tomholub** [comment]
Also, if I'm typing an email and hit any of the following keys, that should signify I finished typing one email (which should be made into a recipient ui element) and want to continue writing another one:
 - space
 - comma
 - return

Just like Browser Extension does it.

**Comment by Kharchevskyi** [comment]
Should we add rules for email validation? Or it can be a separate ticket?

**Comment by tomholub** [comment]
For now, just has to has an @ in it. If it's a bad email, Gmail will return error. Than tome other time we could do validation.
