### ISSUE TITLE
Problems with draft error handling

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#2012]
1) should not lose focus and keyboard  when error toast displays - disruptive to user workflow
2) what does that particular error mean? should think of how to address it in particular
3) should not keep trying forever for any of these errors. eg if it tried 20 times then could just drop it
4) use exponential backoff. currently keeps trying every 3 seconds
5) another issue. it suddenly showed many drafts after i sent the last one. when i go back to all conversations and open again, they are gone. so it’s just some rendering issue maybe, too many times and didn’t go away when actually sent?

![image](https://user-images.githubusercontent.com/77344191/209345841-96c113a1-7e8f-4066-9789-87815a97f0a3.png)

**Comment by tomholub** [comment]
@ioanmo226 after this issue, I would like to ask for your help on flowcrypt-browser again, for 1-2 months. I'll assign you issues there. Thanks!

**Comment by ioanmo226** [comment]
Ok, got it

**Comment by ioanmo226** [comment]
But does this mean iOS app won't be maintained for 1-2 months?

**Comment by tomholub** [comment]
Good question. Let's call it a "feature freeze" on iOS.

If a bug comes through that needs fixing, it would be assigned to you on iOS, and then you'd work on it after finishing whichever issue you started on browser extension at the time (unless it's an urgent bug, in which case it would be right away) and then Roma will release the bugfix with a new iOS version.

But meanwhile no new features and not much other maintenance on iOS for the next 1-2 months.

**Comment by tomholub** [comment]
@sosnovsky fyi

**Comment by ioanmo226** [comment]
Makes sense
