### ISSUE TITLE
Javascript exception after app was in background for long time

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2013]
reported by Tom:
```
happens after the app was running in background for a day
during that day, the app was on conversation view screen
happened when opening existing draft in that conversation
error shows again if i go back and reopen the draft
error goes away when i kill the app

likely related to the webview change. maybe something in the webview gets garbage collected or otherwise disposed to free memory after longer time
```

<img src="https://user-images.githubusercontent.com/1062093/209347008-c6f2c00b-3929-48e3-8f73-d880168ab2c7.png" width="300">

**Comment by tomholub** [comment]
just happened again, after same circumstances

**Comment by tomholub** [comment]
need to kill app to fix it

**Comment by sosnovsky** [comment]
@ioanmo226 maybe it happens because our `Core` js code is injected using [evaluateJavaScript](https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Core/Core.swift#L68) and it's result is removed from memory when app is in background for a long time.

There is another method for loading custom js code into `WKWebView` - using `WKUserScript` (https://developer.apple.com/documentation/webkit/wkuserscript), we can try it to see if it fixes this issue.

It's just 1 possible case, may be you'll find another fix. Please let me know if you'll have any questions about current `WKWebView` integration, as I worked on migration from `JavascriptCore` to current implementation.

**Comment by tomholub** [comment]
@sosnovsky provided live tests are passing (at least locally) you can release 1.2.1 and inform our customer that there was this bug in 1.2.0 and that they should resume testing 1.2.1 instead for potential release to prod.

In the future, when we fix an important bug, you can take initiative to take these steps.

As a part of the process, all still open issues in current milestone should go to newly created milestone 1.2.2

Also can re-enable public release with 1.2.1

**Comment by tomholub** [comment]
if there is a recurring error, do we have an infinite recursion? if yes, that would also be something to address, to only retry once per call.

**Comment by ioanmo226** [comment]
Hmm... let me chekc

**Comment by sosnovsky** [comment]
> if there is a recurring error, do we have an infinite recursion? if yes, that would also be something to address, to only retry once per call.

yes, currently we don't have check if webview was already re-initialized. will need to add it and show some error message in the case when reinitialization didn't fix issue
