### ISSUE TITLE
Fix semaphoreci test

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#2034]
The new year has started and SemaphoreCI tests are failing.
Need to be fixed.

**Comment by sosnovsky** [comment]
Is it because of some wrong date comparison? Can we fix tests so they won't fail on year change?

**Comment by ioanmo226** [comment]
Yes, it's because of date format `MMM DD` for same year (2022) and now it changed to `MMM DD, YYYY` (for different year)
And some pub keys expired at Dec 31
