### ISSUE TITLE
Attachment is double-encrypted in forwarded message

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2063]
While forwarding an email (with attachment) the attachment becomes "over" encrypted and has a .pgp.pgp extension, which makes it impossible to decrypt by recipient.

**Comment by ioanmo226** [comment]
Is this urgent one which needs to be fixed soon?

**Comment by sosnovsky** [comment]
It's not extra-urgent, you can work on it after finishing your current task.
