### ISSUE TITLE
deprecated UIWebView

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#208]
still happening, will open another issue to investigate

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "FlowCrypt TestFlight" 0.1.7 (1). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.
> 
> Best regards,
> 
> The App Store Team

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/108#issuecomment-587521179_

**Comment by tomholub** [comment]
I know we're not sure which dependency is triggering this, hopefully there's a way to find out somehow.

**Comment by Kharchevskyi** [comment]
https://github.com/ReactiveX/RxSwift/issues/2055

**Comment by Kharchevskyi** [comment]
Currently, we use RXSwift only for Keyboard notifications. So I think  there is no need for RXSwift  at all. Will remove it in a scope of this ticket

**Comment by tomholub** [comment]
Got it, thanks for looking into it
