### ISSUE TITLE
Can't forward message with attached public key

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2095]
Steps to reproduce:
1. compose encrypted email in browser extension and click `Include your public key` button in the bottom right corner of compose box
2. send this message with attached pubkey
3. open message in iOS app and try to forward it
4. app shows error message `Error during parsing. This message / key probably does not conform to a valid OpenPGP format.`

Issue appeared in 1.2.2, worked well in 1.2.1

UI test should also be added for this case

**Comment by tomholub** [comment]
@ioanmo226 please have a look here after the issue you currently work on, and then return back to browser extension, like before. Thanks :+1: 

@sosnovsky it's better to be explicit in situations when customer may be waiting on an issue to be fixed, that way Ioan will be sure in how to prioritize

**Comment by ioanmo226** [comment]
Ok, got it

**Comment by tomholub** [comment]
browser extension "treatAs" method addresses this and should be reused imo

**Comment by ioanmo226** [comment]
I think we already use browse extension `treatAs` method.
isEncrypted becomes true when treatAs == enryptedFile or name contains asc suffix.
I think we can safely remove `name.hasSuffix(".asc")` condition?

**Comment by tomholub** [comment]
There should only be `treatAs == "encryptedFile"` and the other `||` should be removed. If that doesn't behave as it should then `treatAs` should be updated, and not ad-hoc side-stepped this way.

**Comment by ioanmo226** [comment]
I agree. 
@sosnovsky What's your opinion?

**Comment by sosnovsky** [comment]
I agree with Tom - other `||` can be removed, initially `.asc` was used for detecting encrypted rich text messages (as they usually named `encrypted.asc`). And it's not needed anymore as we've started using `treatAs` value from backend, not sure why I left it there, but if all tests pass - should be ok to remove.
