### ISSUE TITLE
consistent ui design / layout / spacing spec

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#21]
There are lot of broken layouts around the app, especially when viewed on different size devices.

No thought was given to responsive design so far, and this needs to be fixed.

Here's an example of a broken layout, but there are many, and many of them are subtle.

As a part of this issue:
 - [x] fix any obvious brokenness like the one on the screenshots below
 - [x] fix any more subtle broken ui, and document what was fixed
 - [x] establish common padding and margins around text and buttons, and consistently apply it throughout the app
 - [x] document here your choices for common element padding sizes, distance between buttons, line item sizes, text sizes, etc
 - [x] test and fix design for devices starting with iPod touch all the way up to iPhone X
 - [x] test the app on at least one iPad and fix any obviously broken parts
 - [x] test the app in landscape iPhone view and fix where necessary
 - [x] provide screenshots of what was fixed and how the result looks
 - [x] fix or propose ui / design improvements
 - [x] fix xcode layout warnings
 - [x] when all done, please provide a screenshots of what the app looks on several screens on small iPhone, large iPhone and any tablet.

**Comment by tomholub** [comment]
Eg here the gray box was supposed to be just a thin line (bottom border under the pass phrase)

![image](https://user-images.githubusercontent.com/6306961/61993520-6c9c9300-b09f-11e9-92f0-1448d91a5402.png)

Or here it's way too broken:

![image](https://user-images.githubusercontent.com/6306961/61993524-850cad80-b09f-11e9-99fc-134659fce50b.png)

Or here the title text does not even fit on screen

![image](https://user-images.githubusercontent.com/6306961/61993528-9950aa80-b09f-11e9-87ad-740e24f17fac.png)

etc etc

**Comment by tomholub** [comment]
Unexpected gray block in compose, was probably supposed to be a line just like between recipient and subject.

![image](https://user-images.githubusercontent.com/6306961/62066318-7b5e8380-b220-11e9-8859-924d64b4138a.png)

**Comment by RomanKovalchuk2019** [comment]
Fixed in pr #32

**Comment by tomholub** [comment]
@RomanKovalchuk2019 did you also look at these three?

* [ ]  document here your choices for common element padding sizes, distance between buttons, line item sizes, text sizes, etc
* [ ]  test the app on at least one iPad and fix any obviously broken parts
* [ ]  fix xcode layout warnings

Let me know.

**Comment by RomanKovalchuk2019** [comment]
I have a look at first item of the list. I will share with you document
where I describe padding, other sizes when it would be completed. This
layout was tested on iPad, but I think some improvements are needed. I
don’t fix only two or three layout warning about localization

**Comment by tomholub** [comment]
> I have a look at first item of the list. I will share with you document where I describe padding, other sizes when it would be completed.

Sounds good

> This layout was tested on iPad, but I think some improvements are needed.

Please create github issues for things that you notice. You can put them into the "not anytime soon" milestone.

> I don’t fix only two or three layout warning about localization

It would be good to look into the warnings. Maybe we could make another issue for this?

**Comment by RomanKovalchuk2019** [comment]
Ok, I will create issue for configuring layout on iPad and take a look on
layout warnings.

**Comment by RomanKovalchuk2019** [comment]
Spacing that I used through the app. Button height - 50, leading and trailing space 20, height of separator view - 1, font size - 17. Space between navigation item is 15. Bar button size is 44x44. Distance between buttons on sign in- 30
