### ISSUE TITLE
are revoked uids recognized as such?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#2126]
I wonder if iOS has the same problem, sharing some parts of the codebase?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4588#issuecomment-1445117643_

**Comment by ioanmo226** [comment]
We don't have a "Compatibility Page" like the browser extension does. In the iOS app, trying to import an invalid key (as per [this browser extension issue](https://github.com/FlowCrypt/flowcrypt-browser/issues/4588)) shows a "No public keys found" error, which is accurate.

@sosnovsky, could you look into this issue and list what needs to be done?

**Comment by sosnovsky** [comment]
I think all good on iOS here - in browser extension mentioned check is used only in `diagnose` method from compatibility page, but there is no similar functionality on iOS, no fix needed.
