### ISSUE TITLE
Temporary skip search contacts functionality

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#217]
For having search functionality we need to add another permission to the google permission scope. 
Because the application is still on beta - we will see an error screen from Google, which will not be shown on the live app. 
To prevent this we need temporarily disable recipients search functionality.

- disable search functionality
- remove contacts scope 
- remove "renew token" alert

**Comment by tomholub** [comment]
You can just uncomment/disable the relevant code instead of removing, so it's easy to add back later.

**Comment by Kharchevskyi** [comment]
will just comment out with the comment message
// temporary disable search contacts - https://github.com/FlowCrypt/flowcrypt-ios/issues/217

**Comment by tomholub** [comment]
perfect

**Comment by tomholub** [comment]
Need to create another issue for me to re-enable it
