### ISSUE TITLE
Blind carbon copy leak

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#2183]
for more information, please see: https://github.com/FlowCrypt/flowcrypt-security/issues/223

**Comment by ioanmo226** [comment]
In iOS, the `bcc` is set correctly on my side. Let's say I send an email with to: `a@test.com` and `bcc: b@test.com, c@test.com`. Then on the `b` user's side, `bcc` is set correctly only to `b@test.com`, and on the `c` user's side, `bcc` is set correctly only to `c@test.com`.

@sosnovsky, @martgil, could you please check again with the master branch and see if you can reproduce this issue on your end?

**Comment by sosnovsky** [comment]
I think for fixing of original issue we need to just remove `BCC` recipients from PGP/MIME messages uploaded to the web portal. Currently they're listed in recipients list which is encrypted at https://github.com/FlowCrypt/flowcrypt-ios/blob/31352f250f6a58f6a107eac18d4a136587cef13d/FlowCrypt/Functionality/Services/Compose%20Message%20Helper/ComposeMessageHelper.swift#L409 (the same is done in Android fix)

I didn't fully understand steps for reproducing at https://github.com/FlowCrypt/flowcrypt-security/issues/223#issue-1425229826, maybe @martgil can describe them more detailed. But for me original issue means that recipient at web portal can download encrypted PGP/MIME message, decrypt it locally (using openpgp.js) and there will be list of BCC recipients, which shouldn't be visible for him.

**Comment by martgil** [comment]
I'm able to reproduce the issue on the FlowCrypt iOS app version 1.2.3.

Here is how I do it.

1. Open the FlowCrypt iOS app version 1.2.3.
2. Login with your corporate account.
3. Add a recipient in the `To` Field, and other two recipients in the `Bcc`.
4. Set a password to the email and send it.
5. Download the copy of the session-key encrypted message and decrypt it with `gpg`.
6. Enter the password and find the `Bcc` header where it specifies all the bcc'ed recipients.


![bcc_leakage](https://github.com/FlowCrypt/flowcrypt-ios/assets/46025304/095953e6-61a9-4ad2-8583-ede9987602e8)

**Comment by martgil** [comment]
For reference, here is the password-protected message I created:

https://fes.flowcrypt.com/api/v1/message/1ea70ec6-a00f-407a-a380-5a2f91cfeecb/download 

I will send the password thru email. It is composed by the FlowCrypt iOS app version 1.2.3

**Comment by ioanmo226** [comment]
@martgil Thank you for your brief introduction.

**Comment by martgil** [comment]
You're welcome - thank you, too.

**Comment by ioanmo226** [comment]
@sosnovsky I think we can now release 1.2.5 version to App store?
By the way, keep in mind that we need to update app screenshots in App Store as we added avatar and home screen looks different

**Comment by sosnovsky** [comment]
let's also work on https://github.com/FlowCrypt/flowcrypt-ios/issues/2252 in this milestone, as it's from customer's security audi

**Comment by ioanmo226** [comment]
ok
