### ISSUE TITLE
Update repo README

### ISSUE THREAD

**Issue by vahram-papazyan** [FlowCrypt/flowcrypt-ios#2240]
Do grammar/formatting corrections.

**Comment by sosnovsky** [comment]
@DenBond7 do you have permissions to add Vahram to this repository?

**Comment by DenBond7** [comment]
> @DenBond7 do you have permissions to add Vahram to this repository?

Of course. I have the access to all repos. I've updated settings. @vahram-papazyan please check.

**Comment by sosnovsky** [comment]
thanks!
