### ISSUE TITLE
Request: iPhone Screen Shots

### ISSUE THREAD

**Issue by prep-gh** [FlowCrypt/flowcrypt-ios#227]
### iPhone Screen Shots 

Can I please get some iPhone (*not iPOD*) screens shots of the very latest app?  

(Anything from the "iOS pentest group" from their testing, would be nice as well)

These would be multi-use (blog posts, web pages, etc).

* Having an iPhone skin around the display would be good.
* PNG if possible?
* Transparent background behind the skin, if possible.
* The larger the better. (But don't resize them bigger, after the capture).
 
The procedure to do so should be repeatable, 
so that we can easily get updated ones in the future.

April 2020
@prep-gh

**Comment by tomholub** [comment]
@Kharchevskyi when you're done with the current issue (IMAP), please have a look at this. You could add screenshot-taking as a part of the tests if that's possible. If not, you could just take the screenshots manually.

Here are the screenshots to be taken: https://github.com/FlowCrypt/flowcrypt-docs/tree/master/assets/images/screenshots/ios/showcase

@prep-gh could you please come up with which English text should be on the screens? What should be in the composed or decrypted email, for example.

**Comment by prep-gh** [comment]
@Kharchevskyi  Anton, when you get to this, can I see a new screeshot, 
blank-text-area, 
to start?

@tomholub -- what would you like the topics on the screens to be about?

Discussion between users about office stuff?
Discussions between developers about FlowCrypt?
A few sales notes about FlowCrypt being shared?
Discussion about the lack of Hockey?
Financial results on Jaromir Jagr's team?
(...please nothing about Covid-19)

Just give me a topic preference.

**Comment by prep-gh** [comment]
"to create new screenshots and add iPhone frame run make snapshots in root of the project"

@tomholub

This seems to be a few steps above "provide English text for screenshots".
What exactly are the set up steps to get to the top line?

How much effort do you want me to expend on this? 
Time parameters please.

Do I need an iPhone here?

I think I see the top line as a prep to closing this (?)
I'd prefer it if I close items that I open.

Thank you

**Comment by tomholub** [comment]
@Kharchevskyi please export the screenshots for @prep-gh to use. He does not have a way to run our iOS stack himself, and he needs the screen shots for the documentation he is writing.

**Comment by Kharchevskyi** [comment]
[Archive.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/4509174/Archive.zip)
@prep-gh or contact me directly will share them with you.

**Comment by tomholub** [comment]
Thank you, these look workable.

@prep-gh let us know if this is what you wanted. For the texts, you could just edit them in Gimp - when necessary - unless it seems too much work, in which case you could ask @Kharchevskyi to provide a way to share screenshots that have certain texts natively.

> Discussion between users about office stuff?

I think this style is appropriate. Thanks!

**Comment by tomholub** [comment]
If you will be editting the texts, please also check the texts into https://github.com/FlowCrypt/flowcrypt-docs/ repo as an internal document, so that we can copy and paste them again later, and reuse on Android etc.

**Comment by prep-gh** [comment]
@Kharchevskyi 
@tomholub

Yes -- this is the kind of thing that I wanted.
Thank you both.

I do see some **Serif fonts**, 
like on **iPhone 11-recover.png**

Should we stick to sans-serif, like the FlowCrypt logo, for consistency?

When you can, let me know the exact Font and sizes that you use. 

Thanks

**Comment by prep-gh** [comment]
@tomholub

*Are there* instructions to set up the iOS stack?
I'd like to give it a go, if you ever want me trying out, or even testing things.

Or, 
Maybe to write up the instructions for others, if they need some filling out.

**Comment by tomholub** [comment]
@prep-gh you'd need a mac. Apple is apple, they suck.

Fonts - good eye. Actually we will be fixing the fonts to be sans serif for sure. We have an open issue for it at https://github.com/FlowCrypt/flowcrypt-ios/issues/222 so feel free to use sans fonts.

**Comment by prep-gh** [comment]
@Kharchevskyi

Please don't forget to send me the exact fonts and sizes being used on iOS currently.

I'll close this issue.

**Comment by tomholub** [comment]
I would go ahead and use not the current fonts, which are serif, but the planned ones, which are sans.

Either that, or wait until we have fixed the fonts to make screenshots.

@Kharchevskyi what is the standard Sans-Serif font used on iOS? Can it be downloaded somewhere?

**Comment by Kharchevskyi** [comment]
https://developer.apple.com/fonts/

> This sans-serif typeface is the system font for iOS, macOS, and tvOS, and includes a rounded variant. It provides a consistent, legible, and friendly typographic voice.

**Comment by prep-gh** [comment]
OK, I'll go with **SF Pro** (San Francisco Pro) for mockups
outside of a mac system. (Or find a similar free font). 

SF-Font-Pro.dmg

```html
@font-face {
  font-family: "San Francisco";
  font-weight: 400;
  src: url("https://applesocial.s3.amazonaws.com/assets/styles/fonts/sanfrancisco/sanfranciscodisplay-regular-webfont.woff");
}
```


**Apple's license of the font**: 

"You may use the Apple Font solely for creating mock-ups of user interfaces to be used in software products running on Apple’s iOS, iPadOS, macOS or tvOS operating systems, as applicable".

**Comment by tomholub** [comment]
Sounds good, thanks
