### ISSUE TITLE
Request: Fully Country-Specific Screen Shots

### ISSUE THREAD

**Issue by prep-gh** [FlowCrypt/flowcrypt-ios#228]
Request: Fully Country-Specific Screen Shots

Currently, the iOS screen shots are from an iPOD 
and are mixed language, German and English.

Can we get screen shots and all in the same language?

English first?

As with the iPhone skin request, 
the process to do this should be repeatable; 
so that we can have similar size, resolutions, things-on-the-screen, etc 
across different Flowcrypt versions and different languages 
over time.  A consistency-thing :-)

Thanks
@prep-gh

**Comment by tomholub** [comment]
I'll close this issue because for now we do not plan to internationalize the apps - it's a lot of work. We could re-open this one when the apps are internationalized. For now, let's focus on English only. Thanks!
