### ISSUE TITLE
1.2.4 release

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2336]
- [x] update screenshots
- [x] release notes
- [x] upload build
- [x] send to review (on Sep 18)

**Comment by sosnovsky** [comment]
@tomholub @martgil @ioanmo226 new build 1.2.4 (1) is available on Testflight.
Let's test it on this week, and if all good - I'll send it to App Store review next Monday.

**Comment by martgil** [comment]
Hello Roma, thank you for sending me the TestFlight invitation. I will let you know how my testing for SSL Pinning implementation goes. Thanks again.

**Comment by martgil** [comment]
@sosnovsky It looks like the SSL certificate pinning works very well. The tool I use has an SSL bypass feature which does not work against the FlowCrypt iOS app. Is it okay if I send you a short video clip demonstrating that?

**Comment by sosnovsky** [comment]
> @sosnovsky It looks like the SSL certificate pinning works very well. The tool I use has an SSL bypass feature which does not work against the FlowCrypt iOS app. Is it okay if I send you a short video clip demonstrating that?

Great! Yes, please send this video

**Comment by sosnovsky** [comment]
@martgil I checked video - pinning works well, however we implemented it only for flowcrypt.com, but it seems to work also for gmail domains too. Can you please also check it on current App Store version and send me the video? thanks

@ioanmo226 I just found that from iOS 14 it's possible to pin certificates just by using `NSPinnedDomains` config property - https://blogs.sap.com/2021/05/28/certificate-pinning-on-ios-14/, it looks much simpler that our current implementation. It also makes pinning additional domains easier. What do you think about using it?

**Comment by ioanmo226** [comment]
@sosnovsky, just wrapped up my review.
I think `NSPinnedDomains` is kinda rigid—lacks customization and is a not easy to debug.

On the flip side, `URLSessionDelegate` is way more flexible and easier to debug(a bit hard to implement though).
But yeah, `NSPinnedDomains` is quick to set up and is declarative.

What do you think?

**Comment by ioanmo226** [comment]
@martgil Please send me video as well(old one and new one too)

**Comment by sosnovsky** [comment]
> I think NSPinnedDomains is kinda rigid—lacks customization and is a not easy to debug.

For debugging you still need to use some 3rd-party tools, as you can't check SSL pinning implementation directly in Xcode. So I think it's not a big disadvantage.

I was able to test it on Mac using [Proxyman](https://proxyman.io) (guide about SSL Proxying - https://tanaschita.com/20220704-quick-guide-on-proxyman/). Current implementation works well, but error message is just `cancelled` instead of `SSL certificate mismatch`

<img src="https://github.com/FlowCrypt/flowcrypt-ios/assets/1062093/e4533b9e-4ad1-46fd-af20-c629a5df9f4b" width="300">

<img src="https://github.com/FlowCrypt/flowcrypt-ios/assets/1062093/2438e278-3b16-49c8-ae22-c72e18667640" width="300">

Let's try to use `NSPinnedDomains` and fix this error message, maybe it'll be even easier with `NSPinnedDomains`

**Comment by ioanmo226** [comment]
OK

**Comment by sosnovsky** [comment]
Build 1.2.4 was published to App Store
