### ISSUE TITLE
Build on Xcode 11.4

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#235]
> Can you please have a look at the tests? They are failing lately, but master looks ok

It looks like Semaphore use Xcode 11.4 
https://docs.semaphoreci.com/examples/ios-continuous-integration-with-xcode/

and probably the problem with `libgmp-6.1.2-iPhoneOS-arm64`
https://forums.developer.apple.com/thread/117346#364519

Can we replace this library with any other? For what do we use it?

_Originally posted by @Kharchevskyi in https://github.com/FlowCrypt/flowcrypt-ios/pull/231#issuecomment-629824622_

**Comment by tomholub** [comment]
We use these for cryptography, I cannot easily replace it.
I built it myself, but I could not reproduce the building procedure easily.

You could add a script to rebuild it from source. It's this library: https://gmplib.org/
Best would be to build and set it up for dynamic linking if iOS allows this.

**Comment by Kharchevskyi** [comment]
I see that we use it only here 
```swift
func verifyRsaModPow(_ base: String, _ exponent: String, _ modulo: String) -> String { 
        return String(cString: c_gmp_mod_pow(base, exponent, modulo))
}
```
Can you please give some context what this `c_gmp_mod_pow` returns? Maybe we can have some native solution without this library?

**Comment by tomholub** [comment]
This is modular exponentiation, or mod_pow: https://en.wikipedia.org/wiki/Modular_exponentiation

A native library would be nice if it's as well maintained as GMP and comparably fast. Could not find anything decent in Swift/ObjC that time. Here is a java example: https://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html#modPow(java.math.BigInteger,%20java.math.BigInteger)

**Comment by Kharchevskyi** [comment]
I did some investigation and found https://github.com/attaswift/BigInt

I also did some measurements with the previous and new library. Made some screenshots to compare differences
<img width="300" alt="Screenshot 2020-05-27 at 18 22 05" src="https://user-images.githubusercontent.com/13693255/83047189-4f7e7b00-a048-11ea-9392-916bbf5085b8.png">
<img width="300" alt="Screenshot 2020-05-27 at 18 29 51" src="https://user-images.githubusercontent.com/13693255/83047199-52796b80-a048-11ea-94ae-bbcba07bebe3.png">
<img width="300" alt="Screenshot 2020-05-27 at 18 27 25" src="https://user-images.githubusercontent.com/13693255/83047202-53120200-a048-11ea-9596-ac9bb8ab8a3e.png">
<img width="300" alt="Screenshot 2020-05-27 at 18 22 22" src="https://user-images.githubusercontent.com/13693255/83047203-53aa9880-a048-11ea-8212-3674b3c05742.png">

On average BigInt is about 0.0007 seconds slower than GMP. But it's well maintained and I think we can use it with Xcode 11.4.1 and future Xcode versions.

**Comment by tomholub** [comment]
Native would be nice. Please give it some REAL big numbers. Have it run with a test 4096bit key, and have it print out the `n, e, m` of a real key. Then use these for testing, and let me know how did it do. Thanks!

**Comment by tomholub** [comment]
It has to be an RSA 4096 bit key, not the ECC key it typically creates. You can create one in the browser extension.
