### ISSUE TITLE
Add Encrypted & Attachment Icon  to Thread List View on iOS

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-ios#2350]
The Android app currently displays an encrypted icon next to threads that are encrypted.
This is a nice UI feature that helps users quickly identify secure threads.
It would be beneficial to implement this feature on the iOS app as well.

Android app screenshot
![Screenshot_2](https://github.com/FlowCrypt/flowcrypt-ios/assets/77344191/96297915-f7dd-468f-ada9-cad38cd9de62)

**Comment by ioanmo226** [comment]
PS: It would be better if we include attachment icon too

**Comment by sosnovsky** [comment]
Looks good, it'll be a nice addition to UI 👍
