### ISSUE TITLE
[ask user retry] unexpected - error while fetching messages

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#236]
Ideally errors would be more specific - that way we can debug them easier.

![image](https://user-images.githubusercontent.com/6306961/83685300-f9757e80-a5d7-11ea-8a70-eefb35758d21.png)

In case I need to contact the customer - https://mail.google.com/mail/u/8/#inbox/FMfcgxwHNMRZTkZCmQLTgqpksXbLtcXt

**Comment by Kharchevskyi** [comment]
This error occurs in case there are no messages in user folders which was sent to his email when we try to `searchBackups` with IMAP (mailcore) implementation.
```swift 
let messageContexts = try uidsForFolders.flatMap { uidsContext -> [MsgContext] in
    let msgs = try await(self.fetchMessagesIn(folder: uidsContext.path, uids: uidsContext.uids))
    return msgs.map { msg in MsgContext(path: uidsContext.path, msg: msg) }
}

guard messageContexts.isNotEmpty else {
    throw BackupError.missedMessages
}
```
Is this bug reproduced in latest app version(with Gmail API)?

**Comment by tomholub** [comment]
I don't know - haven't made a release in a long time. If you suspect it may be fixed, then we can tell user to retry once we release.

**Comment by Kharchevskyi** [comment]
👍 This should be fixed or at least we can get some more specific error with Gmail API
