### ISSUE TITLE
mail in All Mail (archived) cannot be moved back to inbox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#2367]
most can, but sometimes it can't, missing icon

example here

![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/6306961/15a21197-4115-493f-a73e-bab5be8b8905)

**Comment by tomholub** [comment]
my bad, the screenshots are equal. not sure what was I seeing.

**Comment by ioanmo226** [comment]
@sosnovsky Only this task is left for me and also for [1.3.0 ](https://github.com/FlowCrypt/flowcrypt-ios/milestone/1) milestone.
Please assign new tasks.

**Comment by tomholub** [comment]
btw if ios is starting to look decent these days, could do some on browser extension. I haven't looked at either so will leave it on roma

**Comment by sosnovsky** [comment]
@ioanmo226 this one will be the last for iOS for now, I'll create new 1.3.0 release after it's completed.

I assigned you a couple tasks on browser extension repo, will add more later
