### ISSUE TITLE
inconsistent archive vs move to inbox icons

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#2368]
these two icons will display differently based on which label i clicked on the email from

eg click from all mail or inbox

it should depend on the email itself, not how I opened it

example screenshots 

![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/6306961/85990454-a4d2-49ee-a638-e294d57c9ce7)

![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/6306961/cadb7ed2-0d6d-460c-ba1d-3765fe98bede)

**Comment by sosnovsky** [comment]
@tomholub these screenshots look same for me

**Comment by tomholub** [comment]
yeah I was meaning to close this. I don't know what was I seeing, these are the same. my bad
