### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2388]
- [x] release notes
- [x] upload customer build
- [ ] upload enterprise build
- [ ] notify customers

**Comment by web2brain** [comment]
Are there any news on this release? I'd really like to add keys per contact and from emails. These features have been merged quite some time ago and I'm looking forward them!

**Comment by sosnovsky** [comment]
> Are there any news on this release? I'd really like to add keys per contact and from emails. These features have been merged quite some time ago and I'm looking forward them!

Hi @web2brain, thanks for your interest! 1.3.0 release is scheduled to be published to App Store in the current month 🚀

**Comment by web2brain** [comment]
Hi @sosnovsky 
Thanks for the heads up! Looking forward to it

**Comment by sosnovsky** [comment]
hi @web2brain, new release was published to App Store

**Comment by web2brain** [comment]
Thanks @sosnovsky, already installed and imported the first public keys :)
