### ISSUE TITLE
Fix choosing correct key for message encryption

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2396]
When WKD returns multiple keys for recipient, app should choose valid ~key~ **keys** for encrypting message.
Currently when there are multiple keys app seems to use just the first one.

Example:
Recipient has 2 public keys - one which can be used only for signing, and second one which can be used for encryption too. App fetches both these keys, but when trying to encrypt message it shows error `could not find valid encryption key`, so looks like it tries to use `only for signing` key to encrypt message, but it should choose key which can be used for encryption.

**Comment by tomholub** [comment]
Another example - recipient has 3 public keys, 1 valid, one only for signing, and 1 more valid. (2 valid, one sign-only)

The two valid keys must be used in that case.

**Comment by tomholub** [comment]
Also the error message that kept popping up when encrypting draft was rendered incomplete. There should be more space for it.

**Comment by sosnovsky** [comment]
@ioanmo226 let's work on remaining tasks from [1.3.0 milestone](https://github.com/FlowCrypt/flowcrypt-ios/milestone/1) on the next week, so we can release a new build to the App Store.

**Comment by ioanmo226** [comment]
ok

**Comment by DenBond7** [comment]
> Another example - recipient has 3 public keys, 1 valid, one only for signing, and 1 more valid. (2 valid, one sign-only)
> 
> The two valid keys must be used in that case.

@sosnovsky or @ioanmo226 Do we allow to import all fetched pub keys from WKD?

**Comment by sosnovsky** [comment]
@DenBond7 yes, currently we import all keys fetched from WKD, even if key is sign-only
