### ISSUE TITLE
the consumer app should allow me to send unencrypted messages if I choose so

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#2397]
but the enterprise app should continue behaving exactly like now

can use Android for inspiration, for switching to plain compose or reply. I haven't used the Android app in a while, @DenBond7 could you please share some screenshots of what it looks like these days to do that? Then I'll confirm whether that's what I'd like to see on iOS.

**Comment by DenBond7** [comment]
![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/2863246/a93aac40-bdd5-42f9-abd6-4487b28913c6)
![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/2863246/d594b4da-e149-4217-a798-567cb7acb7ae)
![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/2863246/d7500a33-b711-4553-955b-7f60e6b7df58)

**Comment by tomholub** [comment]
that looks good to me

**Comment by ioanmo226** [comment]
iOS app also lets users send unencrypted message if they choose to do so.
@sosnovsky, @tomholub  Could you check again and let me know if you want to change something here?

![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/77344191/7b1bf75f-9171-4dce-b1d6-bdf768eaf07e)

**Comment by tomholub** [comment]
I forgot /overlooked it. Thanks! Works as expected

**Comment by sosnovsky** [comment]
Difference here is that on iOS we can send unencrypted message only to recipients who don't have encryption set up, while on Android unencrypted message can be sent to anyone, is it ok?

**Comment by tomholub** [comment]
I think that's ok for now
