### ISSUE TITLE
open side menu button - does not work immediately after recovery

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#24]
to reproduce:
1) delete app -> install -> log in -> recover by adding pass phrase -> inbox shows
2) click side menu - nothing happens (bug)
3) restart app - > click side menu - menu opens

**Comment by RomanKovalchuk2019** [comment]
Fixed

**Comment by tomholub** [comment]
Hello, where can I take a look at the fix? Best is to open a PR for each issue that I can review.

**Comment by RomanKovalchuk2019** [comment]
I just want to ask you if it needed to open a pull request for each issue or I can combine a few issues in one pull request? Because I want to finish some layout fixes and create pull later if it suits you

**Comment by tomholub** [comment]
For layout fixes, you can combine many in one PR. 

For functionality fixes, best is to keep them separate, one pr per issue, when possible.

**Comment by RomanKovalchuk2019** [comment]
Ok, I will create pull request. Please, give me permission to push on this
repo. As for now I have only access to read repo

**Comment by tomholub** [comment]
I'm on my mobile today. For now, you can create a fork, then make a new branch there, and make a PR from your feature branch to our master.
