### ISSUE TITLE
Show links to remote images

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2414]
Was not sure where to post this - but on IOS Mobile Flowcrypt App there is no button for "Show Remote Images" - it just says in text "Remote content blocked for your privacy" and I cant find any settings to allow loading of remote images (which in case of some email I am getting is essential to approve security requests (they come as image with link and flowcrypt mobile does not load neither the image nor the link - while in gmail on desktop it loads images and links fine)

_Originally posted by @kubadoki in https://github.com/FlowCrypt/flowcrypt-browser/issues/4759#issuecomment-1780933675_

**Comment by sosnovsky** [comment]
let's handle it the same way as on Android:
- add `remote content blocked for your privacy` label
- show link to remote image

<img src="https://github.com/FlowCrypt/flowcrypt-ios/assets/1062093/893475c9-e8a1-4a91-9ced-b8c7f6aa7987" width="300">

**Comment by ioanmo226** [comment]
@sosnovsky Could you tell me reproduce steps?
Currently iOS app shows links to image whether message is encrypted or not.

![image](https://github.com/FlowCrypt/flowcrypt-ios/assets/77344191/b8684d45-1947-43f2-b05b-58fc5698a6e4)

**Comment by sosnovsky** [comment]
@ioanmo226 I sent you email message with such image.
To reproduce you should add image to non-encrypted message using Gmail's `Insert photo` -> `Web Address (URL)`

**Comment by ioanmo226** [comment]
Got it. Thank you
