### ISSUE TITLE
Add ability to message recipient without valid public key

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2421]
I also think it'll be useful to have ability to send unencrypted message to recipient without valid keys, but it'll be for another issue.

For example, user tries to send message to recipient with expired key (or sign-only key) - currently we just show modal saying `recipient has expired key, please contact him`. But to message this recipient user will need to use another email client.

Here we can add button `Send unencrypted message` to error modal, tapping on it will open another compose screen with predefined text:
```
Hi,

I tried to compose encrypted message to you, but your public key is expired|revoked|sign-only.
Can you please share your valid public key.

Thanks
```

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-ios/issues/2413#issuecomment-1785075870_

**Comment by tomholub** [comment]
could be treated like no keys, after the error, offer password message or plain

**Comment by ioanmo226** [comment]
@sosnovsky Is this also 1.3.0 milestone?

**Comment by sosnovsky** [comment]
Yes, let's include it in 1.3.0
