### ISSUE TITLE
Hide quote text in plain messages

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2448]
For hiding quote texts in non-encrypted messages we need to parse text from `<div class="gmail_quote">` and hide it below 3-dots button, like it's currently done for encrypted messages.

reference - https://github.com/FlowCrypt/flowcrypt-ios/pull/2422#issuecomment-1792502315

**Comment by ioanmo226** [comment]
Do you agree with html parser like [SwiftSoup](https://github.com/scinfu/SwiftSoup)?

**Comment by sosnovsky** [comment]
> Do you agree with html parser like [SwiftSoup](https://github.com/scinfu/SwiftSoup)?

Yes, let's use it
