### ISSUE TITLE
ios testflight invitation doesn't arrive

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-ios#249]
Support email: https://mail.google.com/mail/u/5/#inbox/FMfcgxwJXCFxTbCllqVWFmxdTvJKcNPB

> Can not install iOS app after TestFlight installation
> No any invitations...

FlowCrypt TestFlight link: https://testflight.apple.com/join/PNblgSUL

Apparently, the invitation to use FlowCrypt Beta via TestFlight is not making it to the user. I have never used TestFlight, and I don't have an ios device to test this.

**Comment by tomholub** [comment]
Many iOS beta apps require that they get an invitation - closed beta.

Ours is open beta. There is no invitation needed, they can just follow the link on their ios device, and if they have TestFlight installed, they will be able to install FlowCrypt.

**Comment by seisvelas** [comment]
Cool! I informed the user.
