### ISSUE TITLE
Add warning for suspicious messages

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#2548]
Suspicious messages has `Received-SPF: softfail` header, for such messages we need to show warning before message body:

```
Potentially suspicious message

It wasn't properly verified by the sender, so its authenticity can't be confirmed.
Be careful - avoid clicking links and downloading attachments, or sharing personal info.
```

ref: https://github.com/FlowCrypt/flowcrypt-security/issues/270
android: https://github.com/FlowCrypt/flowcrypt-android/issues/2670

**Comment by ioanmo226** [comment]
@sosnovsky Current implementation looks like below(Gmail app style).
Let me know if you want our Android app style which has yellow left border instead of background.

![image](https://github.com/user-attachments/assets/e196b35f-b31d-4754-a49d-59cf051ffdf7)

**Comment by sosnovsky** [comment]
Current implementation looks great, let's use it 👍
