### ISSUE TITLE
Decryption error for message sent via Encrypted Contact Page

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#2614]
Descrption:

Encrypted messages sent with attachment via [FlowCrypt's Encrypted Contact Page ](https://flowcrypt.com/docs/getting-started/send-and-receive/encrypted-contact-page.html) cannot be decrypted correctly. The JSON object were rendered into the message view instead of decrypting and rendering the decrypted message and its attachment.

Screenshot:

![image](https://github.com/user-attachments/assets/39d12db9-bba7-468a-a156-a4119b8ea017)

Reference:

https://mail.google.com/mail/u/human@flowcrypt.com/#archive/FMfcgzQVxtmgFdMvXxLQkxdRzcFvXtlh

**Comment by martgil** [comment]
Some other user experienced the reported issue: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzQVzNpjsjmVRcSnQKKctlClBxvZ

**Comment by ioanmo226** [comment]
![image](https://github.com/user-attachments/assets/9102cd30-1aaa-4053-a3ea-17b3bfa76a28)

Hmm.. I can't even send encrypted message via Encrypted Contact page.

**Comment by sosnovsky** [comment]
It works for me, was able to send encrypted message with attachment at https://flowcrypt.com/me/sosnovsky
Did you get any error in console?

**Comment by ioanmo226** [comment]
Your encrypted contact page works fine but not mine.
Don't get any errors in console.
Seems like my contact page has some errors. Could you check my contact page?
https://flowcrypt.com/me/ioanflowcrypt

**Comment by martgil** [comment]
Hi @ioanmo226 - sorry for the interruption of your conversation. I've checked the issue you are having and it seemed like the error lies down to your expired keys:

```
(1) Primary keys found: 1  
(2) ----- Testing key 0 -----  
(3) PK 0 > Key type: openpgp  
(4) PK 0 > Is Private?: [-] false  
(5) PK 0 > User id 0: Ioan at FlowCrypt <ioan@flowcrypt.com>  
(6) PK 0 > Primary User: Ioan at FlowCrypt <ioan@flowcrypt.com>  
(7) PK 0 > Fingerprint: F781 99EC 3D3F E74B 7C89 7AA7 9B39 0120 D7FB 8D51  
(8) PK 0 > Subkeys: [-] 1  
(9) PK 0 > Primary key algo: [-] eddsa  
(10) PK 0 > Usage flags: [-] [sign_data, certify_keys]  
(11) PK 0 > Primary key verify: [Error: Primary key is expired]  
(12) PK 0 > Primary key creation?: [-] 1646732938 or 2022-03-08T09:48:58.000Z  
(13) PK 0 > Primary key expiration?: [-] 1672531199 or 2022-12-31T23:59:59.000Z  
(14) PK 0 > Primary key getBitSize?: [-] undefined  
(15) PK 0 > Encrypt/Decrypt test: Got error performing encryption/decryption test: Error: Error encrypting message: Primary key is expired:   
(16) PK 0 > SK 0 > LongId: [-] 8A599FAD4FA4A68F  
(17) PK 0 > SK 0 > Created: [-] 1646732938 or 2022-03-08T09:48:58.000Z  
(18) PK 0 > SK 0 > Algo: [-] ecdh  
(19) PK 0 > SK 0 > Usage flags: [-] [encrypt_communication, encrypt_storage]  
(20) PK 0 > SK 0 > Verify: [-] OK  
(21) PK 0 > SK 0 > Subkey object type: [-] PublicSubkeyPacket  
(22) PK 0 > SK 0 > Subkey getBitSize: [-] undefined  
(23) PK 0 > SK 0 > Subkey decrypted: [-] null  
(24) PK 0 > SK 0 > Binding signature length: [-] 1  
(25) PK 0 > SK 0 > SIG 0 > Key flags: [-] 12  
(26) PK 0 > SK 0 > SIG 0 > Version: [-] 4  
(27) PK 0 > SK 0 > SIG 0 > Public key algorithm: [-] 22  
(28) PK 0 > SK 0 > SIG 0 > Sig creation time: [-] 1646732938 or 2022-03-08T09:48:58.000Z  
(29) PK 0 > SK 0 > SIG 0 > Sig expiration time: [-] -  
(30) PK 0 > SK 0 > SIG 0 > Verify: [-] valid  
(31) PK 0 > expiration: [-] 1672531199000  
(32) PK 0 > internal dateBeforeExpiration: [-] Sun Jan 01 2023 07:59:58 GMT+0800 (Philippine Standard Time)  
(33) PK 0 > internal usableForEncryption: [-] false  
(34) PK 0 > internal usableForSigning: [-] false  
(35) PK 0 > internal usableForEncryptionButExpired: [-] true  
(36) PK 0 > internal usableForSigningButExpired: [-] true  
```

The public key I've checked is the returned pubkey from https://flowcrypt.com/attester/pub/ioan@flowcrypt.com.

You may update your primary key's expiry using gpg. I can assist you with that in case you haven't done it before.

**Comment by martgil** [comment]
You may follow some guide here regarding extending key's expiration - https://gist.github.com/krisleech/760213ed287ea9da85521c7c9aac1df0. Then once its done, you may update your keypair record in the extension as well as submitting the updated public key to https://flowcrypt.com/attester/update-public-keys. Your EC page should work afterward.

**Comment by ioanmo226** [comment]
@martgil Thank you for your answer.
I think we should show appropriate error message though instaed of `Encountered an error with unknown cause` generic error message.
I/user have no idea what's happening/wrong behind this scene.

**Comment by ioanmo226** [comment]
FYI, after I updated my public key, it works fine.

**Comment by martgil** [comment]
You're right @ioanmo226 - that particular case seemed not handled very well. I have created a GitHub issue for it in the web repo - https://github.com/FlowCrypt/flowcrypt-web/issues/1805
