### ISSUE TITLE
How to generate .ipa from this source code?

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-ios#271]
From a bug bounty reporter:

>I am planning to test for your IOS Flowcrypt but unfortunately I dont own a mac for testing. May I ask for the team to generate a .ipa file so I could able to install it on my device? Any feedback would be appreciated :)

I tried loading the project into Xcode and doing this myself but I have no idea what I'm doing, so I was hoping for tips in how to make this happen

**Comment by seisvelas** [comment]
Here is what Xcode looks like when I clone this repo into it:

<img width="728" alt="Screen Shot 2021-02-28 at 22 10 34" src="https://user-images.githubusercontent.com/44826516/109454598-d1edfe00-7a11-11eb-9f84-fbcd8181f333.png">

I think the 'archive' option is what I'd normally use but it's greyed out, so I can't click it.

**Comment by tomholub** [comment]
Anton may have an idea of what this means, if it's possible or how to do it.

**Comment by seisvelas** [comment]
Hopefully! I think I should also be able to run the FlowCrypt iOS app on my Mac, since it has an m1 chip. If so I can try to find some bugs here as well!

**Comment by Kharchevskyi** [comment]
If you want to distribute an .ipa file to a device first of all you need to register it 
https://help.apple.com/xcode/mac/current/#/dev7ccaf4d3c

> Users don’t need to be on your team or App Store Connect users to run the app, but their devices need to be registered in your developer account.

If you want, you can run it locally on a simulator.
For this you need
*  install all dependencies  `bundle install --path vendor/bundle`
* install pods `bundle exec pod install`
Then you can open `.xcworkspace` and run it for simulator. 
(@tomholub will add Readme to the project) 

@tomholub  In case we want to distribute app for testing I recommend using Firebase AppDistribution or TestFlight for that.

**Comment by tomholub** [comment]
I imagine, for security testing, the researchers may need an .ipa directly to be able to probe it easier.

Similar to when we did a security review with Cure53 last year.

Therefore @seisvelas would need to find out the id of the target device, and I could register it and then give them a release to test.

**Comment by Kharchevskyi** [comment]
Got it. I can archive and share .ipa archive with @seisvelas if needed. 
Or just try install all dependencies and do it by your own. 
Probably you will need also to create an empty `test-ci-secrets.json` file in the root of the project. 

To find an UDID of the device 
* Connect your iOS device to your computer using USB
* Select your iOS device in the Finder (Mac)
* Tab 'General' and  Click on the text that is shown below your device name

**Comment by seisvelas** [comment]
Thanks for all the info!

So, in order to generate a .ipa that the security researcher can install on their device, I'd need to have their device's UDID registered as a test device in my Apple Developer account, correct? (I've requested their UDID because this is how I've interpreted your instructions, but let me know if I've err'd).

**Comment by seisvelas** [comment]
Darn, I have to pay to enroll as an Apple Developer. I'll do it tomorrow (I want to anyway for other reasons), then I should be able to make a .ipa for his device :)

**Comment by tomholub** [comment]
I don't think you should have to do that. That is something either Anton or me should be able to do.

**Comment by seisvelas** [comment]
Sure, I sent the UDID to tom@flowcrypt.com and anton@flowcrypt.com so one of you can make the .ipa for that device :)

**Comment by tomholub** [comment]
I've built the ipa and sent it to them for testing.
