### ISSUE TITLE
set up a Custom App for deployment to specific customer

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#272]
We'd like to deploy the app to our customer without a public listing. So that only one customer organization's users can download it and nobody else. Is that possible?

**Comment by Kharchevskyi** [comment]
As discussed in #271 you should add this specific devices UDID to developer program and archive the build. 
Unfortunately I do not have correct account role. 
<img width="707" alt="Screenshot 2021-03-16 at 11 02 45" src="https://user-images.githubusercontent.com/13693255/111282999-47c7ab80-8647-11eb-81cc-29ec917e41bd.png"> 

@tomholub you can try to generate it by your own, steps are almost the same as distributing app to TestFlight. 
- https://stackoverflow.com/questions/5499125/how-to-create-ipa-file-using-xcode
- https://help.apple.com/xcode/mac/current/#/devf37a1db04
- https://help.apple.com/xcode/mac/current/#/dev37441e273

**Comment by Kharchevskyi** [comment]
Unfortunately it's not possible for me to archive the app for distributing purposes.
<img width="685" alt="Screenshot 2021-05-05 at 21 14 13" src="https://user-images.githubusercontent.com/13693255/117189422-db675e00-ade6-11eb-86b5-44bf4c14c938.png">
Same will be for issue #287

**Comment by tomholub** [comment]
I don't want to allow specific devices, this should be managed by the customer. I want to be able to add their organization ID and distribute to them that way. They themselves should manage which devices they include.

Here's a mechanism for it: https://coletiv.com/blog/distribute-custom-b2b-ios-app/
A blog describing it: https://coletiv.com/blog/distribute-custom-b2b-ios-app/

I'll take a look into it.

**Comment by tomholub** [comment]
Here info also https://help.apple.com/app-store-connect/#/dev275598f16

note for me: email `Integration of Flowcrypt Mobile App for Android and iOS`

**Comment by tomholub** [comment]
It's pretty straight forward on the app store side: we need a second app with a new app id, and I'll submit that to app store as a separate app. I'll need to get a separate review. I'll choose `private` distribution instead of `public`, and then I'll add the org id of our customer, so I can distribute directly to them. Then they can deploy it to their business using `Apple Business Manager`.

@Kharchevskyi Could you please add another build type (or is it called target?). The name of the app should be `Enterprise FlowCrypt` and the id should be same as the regular app except add `.enterprise` at the end. Thanks!

**Comment by tomholub** [comment]
Also with some guidance on how to build one type of app versus the other. Or can I build both at the same time with one command? That's how we do it on other platforms.

**Comment by Kharchevskyi** [comment]
<img width="117" alt="Screenshot 2021-09-13 at 16 25 12" src="https://user-images.githubusercontent.com/13693255/133091609-6552047d-c512-45c4-a031-0eca2a0e05d0.png">
@tomholub which scheme would be used to test flight? Do we need this 3 configurations? Or for example we can have enterprise + release + debug. Or just release + enterprise?

**Comment by tomholub** [comment]
I'm not sure. What are schemes for? Is it a way to have different builds of the same app ids? Or is it a way to have different apps that each have a different app id?

**Comment by Kharchevskyi** [comment]
This configurations can be used exactly for described case, for example we have 1 code base, but they should be distributed separately for example for testflight and for enterprise(private) distribution. Also it's possible to have different set of environment, urls, etc. 
Each configuration can have different app name, capabilities, bundle identifier and so on. Even some code can be specifically for configuration. (For example we can disable in app logging for enterprise configuration)
I propose to have just release configuration and enterprise configuration and in case we need more we will add them later (YAGNI).
> Also with some guidance on how to build one type of app versus the other. Or can I build both at the same time with one command? That's how we do it on other platforms.
Based on that I will create 2 different apps/schemas to have possibility to run them separately

**Comment by tomholub** [comment]
I see. At a minimum, I need the following types of release tracks:
 - enterprise (for customers where we deploy to them directly privately)
 - consumer release (will become standard public app on the app store)
 - test flight (for early releases)

I'm unsure if I need the debug release or not.

The first track to be released will be the enterprise, privately. Followed by TestFlight, public beta. I don't want to release consumer release publicly on the app store because the app is not feature complete enough for that, and I don't want to accumulate bad reviews because of missing features. But sometime next year I'll publish the consumer release too.

This looks like we'll need three schemas? Maybe four, if you need debug for something as well (eg for development - I suppose we usually build the debug version?)

**Comment by Kharchevskyi** [comment]
For developing purposes there is no differences in this configurations for now. 
Because we already have debug, release and testflight configuration I would suggest to just add enterprise configuration, to not break already managed Provisioning Profiles/certificates and etc

**Comment by tomholub** [comment]
Correct.

**Comment by Kharchevskyi** [comment]
Having some problems with app name with space. 
Would it be ok with `EnterpriseFlowCrypt`?

**Comment by Kharchevskyi** [comment]
![Simulator Screen Shot - iPhone 8 - 2021-09-15 at 14 32 02](https://user-images.githubusercontent.com/13693255/133425761-b5ffb3c3-31e7-4099-9a8d-4d392fdf4ae2.png)
Having some problems with space in app name. 
Would it be ok to call `EnterpriseFlowCrypt`?

**Comment by tomholub** [comment]
If iOS doesn't print the whole name anyway, we should call both just `FlowCrypt`.

Later we will differentiate the icon.

**Comment by Kharchevskyi** [comment]
<img width="200" alt="Screenshot 2021-09-15 at 16 46 02" src="https://user-images.githubusercontent.com/13693255/133445136-4878158d-f096-49d8-86a2-19c1b9874454.png">
Maybe let's have some separate task to add label here or in settings?

**Comment by tomholub** [comment]
agree - let's make a separate issue for the future
