### ISSUE TITLE
follow OrgRule to forbid backing up keys

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#277]
as a part of #275 , but after #276 more context https://flowcrypt.com/docs/business/org-rules.html

-----------------------------

### whenever orgRules.canBackupKeys() == false:

Disable all forms of private key backup (except storing the key on Email Key Manager which is not implemented yet)

 - [ ] during setup, do not check for backups in inbox at all. Account recovery option from backups is forbidden. Do not allow to create a new key either. This means the only possible way to proceed is to manually import a key.
 - [ ] hide the `Backups` option in settings view
 - [ ] disable (by throwing error / crashing the app) the backups view in settings, in case we accidentally link to it from elsewhere in the app in the future
 - [ ] disable (by throwing error / clashing the app) the recovery view in setup, in case we accidentally link it in the future

Since OrgRules are supposed to be fetched immediately following sign in, then you can enforce this right at the time the app is choosing which setup flow to use, and always use manual import for that user.

**Comment by tomholub** [comment]
@ekievsky when will you be able to get to this? Thanks

**Comment by ekievsky** [comment]
hi @tomholub , I plan to finish with that by the end of Sunday
