### ISSUE TITLE
verify signed messages

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#278]
This is part of #275. Sister issues on Android: https://github.com/FlowCrypt/flowcrypt-android/issues/1096 and https://github.com/FlowCrypt/flowcrypt-android/issues/1097. First need to do #609

**Comment by tomholub** [comment]
Here, before loading the message, we'd pull public keys from local contacts that are recorded for the email that we received the message from (the sender email). Then offer these to the verification method as possible public keys it was signed with, into `Core.parseDecryptMsg`. 

Then render the result, similar to what browser does.

**Comment by tomholub** [comment]
As an overview, there can be three states that you get back:
 - valid signature - `Signed by \(signingPubkey.primaryUserIdEmail)`
 - invalid signature or expired public key or something like that `Bad signature - cannot trust authenticity of this message`
 - missing public key - `Signature not verified because key $longid is unknown`

I don't know where to render it. Maybe above the message. It has to look different than the message itself, so that I can't send someone an email where I type out `Singed by ...` on top in a way that could confuse the recipient.

**Comment by sosnovsky** [comment]
@tomholub how should `Core.parseDecryptMsg` respond if app sends invalid pub keys in `verificationPubkeys` array?
I tried to send test array `["0000"]` and thought it would return error, but I got successfully decrypted message.

**Comment by tomholub** [comment]
Best would be for it to still decrypt (as it does now) but show some error on the signature verification result of the response.

**Comment by sosnovsky** [comment]
@tomholub should we show any warning text if mail message isn't encrypted? Like `This message isn't encrypted`

**Comment by tomholub** [comment]
Did you mean signed?

If you meant encrypted, for now we differentiate by text color. But in the future, we'll do something like what you suggested.

**Comment by sosnovsky** [comment]
Yes, I mean non-encrypted mails (received from users without Flowcrypt), so for now I'll just leave color differentiation.

Also I noticed we have 2 very similar view controllers:
`ThreadDetailsViewController.swift` https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
`MessageViewController.swift` https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Controllers/Msg/MessageViewController.swift

They have many code duplications, so when fix or update will be needed on messages screen then we'll need to implement it in 2 places - for each controller.
By the way, for me `ThreadDetailsViewController.swift` is used for every message in mailbox (even when there is only 1 message, and it's not thread).
So I think it'll be more convenient to create 1 base view controller - it'll remove code duplication and will make implementing new features easier. Or maybe we even don't need `MessageViewController.swift` anymore and can just update `ThreadDetailsViewController.swift` to render single message too.

@tomholub what do you think?

**Comment by tomholub** [comment]
Absolutely agree

**Comment by tomholub** [comment]
In this issue, you can start by only implementing it in ThreadDetailsViewController.

Then later, we'll deprecate MessageViewController and join the functionality in another issue.
