### ISSUE TITLE
tests broken on CI - test with mock Gmail API instead

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#286]
We'll have to do something about these tests.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/281#issuecomment-816906462_

**Comment by tomholub** [comment]
On flowcrypt-browser repo we use this mock of Google oauth2 / Gmail API:
https://github.com/FlowCrypt/flowcrypt-browser/blob/master/test/source/mock/google/google-endpoints.ts

@DenBond7 what approach do we use on Android? Could you point us to some source files for inspiration?

**Comment by DenBond7** [comment]
@tomholub we use Gmail API recently. Before we had only IMAP realization. That's why we don't have any tests for Gmail API yet.

**Comment by tomholub** [comment]
Not good. That means on Android, we only test all of this functionality with IMAP server, we don't actually test the Gmail API functionality. But the difference should generally only be the IMAP/API layer, hopefully not so error prone.

**Comment by DenBond7** [comment]
Agree. But the code made to support Gmail API and IMAP at the same time. It means we have the same code. Just in some place we call Gmail API or IMAP. The behavior should be the same. UI tests will be the same. There is only one difference - error messages.

But anyway we should add mock realization for Gmail API to be sure that all works as expected.

**Comment by DenBond7** [comment]
> But the difference should generally only be the IMAP/API layer, hopefully not so error prone.

You are totally correct

**Comment by tomholub** [comment]
I'll close this for now, we haven't encountered many Gmail specific bugs.
