### ISSUE TITLE
Fix showSpinner()

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#291]
showSpinner() is an extension method to show MBProgressHUD on a view. 
Spinner dispatched on main queue with animation and without any completion on when animation ends. 
This can lead to a bug that HUD is not showed if any other operation scheduled

see `// TODO: - fix for spinner`

**Comment by Kharchevskyi** [comment]
@tomholub there is one more question/issue which can be related to this task. Should we disable user interactions while spinner is shown? 
Can I use some other solution instead of MBProgressHud for this? are you ok with that?

**Comment by tomholub** [comment]
You can choose some other solution.

Disabling user interactions while spinning is generally ok as a default, but there may be situations where maybe you may want to specifically enable it later.

**Comment by tomholub** [comment]
May or may not be outdated, use your discretion.

**Comment by ioanmo226** [comment]
@sosnovsky, I'm leaning towards this one. It's more maintainable than MBProgressHUD and it's developed in Swift. What do you think?
https://github.com/relatedcode/ProgressHUD

**Comment by sosnovsky** [comment]
> @sosnovsky, I'm leaning towards this one. It's more maintainable than MBProgressHUD and it's developed in Swift. What do you think?
> 
> https://github.com/relatedcode/ProgressHUD

This one looks good, let's try to use it
