### ISSUE TITLE
clicking Load Account while still loading causes crash

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#293]
My backup screen was showing loader for a long time, enough to enter pass phrase and click `Load Account`. The click crashes the app.

**Comment by tomholub** [comment]
This is a good first issue for a new contributor to have a look

**Comment by tomholub** [comment]
(clicking Load Account on an empty pass phrase shows alert and removes the loader)

Actually there are two issues:
1) the loader stays up forever (unless I click load account with empty pass phrase)
2) meanwhile filling pass phrase and clicking load account crashes the app

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/115622132-ffa34500-a2e6-11eb-9a6e-c58cdcbf1d86.png)

**Comment by tomholub** [comment]
@Kharchevskyi exact same behavior on iOS 14 / iPhone 12 Mini. Loader stays up forever. If I give it empty pass phrase, it shows alert, which I click away. If I then enter pass phrase and click load account, it crashes.

**Comment by Kharchevskyi** [comment]
should I pickup this bug or it's better for @qsoftdevelopment ?

**Comment by tomholub** [comment]
Please have a look Anton - it's preventing me from using the app.
