### ISSUE TITLE
a way to import Public Keys in Settings -> Contacts

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#298]
follow Android functionality

**Comment by ivan-ushakov** [comment]
I don't have Android device so could you please provide some details and screenshots how this function should work?

**Comment by tomholub** [comment]
Would it be ok for you to use the Android Studio to run a simulator? (there will be more than one functionality to port over time - it would simplify my work).

https://github.com/FlowCrypt/flowcrypt-android#running-the-app-in-emulator-first-time

If not, we'd postpone this issue until I can give you better instructions. (or I'll get help from someone to specify the issue.)

As an overview, currently public keys are auto-imported when composing messages. This issue would add a and "add" (or "+" icon) to the Contacts screen, which leads you to a view where you can import public key from file or by copy-pasting. After confirming by user, the public key would get parsed with `Core.parseKeys` to verify it's valid, and then imported for a certain recipient email address like is done on the compose screen. After that, the updated public key defails should be visible when you go back to Contacts screen and tap on that contact.

**Comment by martgil** [comment]
Some users would like to import public keys for their contacts within in FlowCrypt iOS app.

User interest(s):

https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGsmWvfgdqzdDhXjBRmTxNFBCQh

**Comment by ioanmo226** [comment]
@sosnovsky After this task, do you wanna me to continue `1.3.0` milestone tasks(left tasks were not assigned to me though) or continue browser extension?

**Comment by sosnovsky** [comment]
@ioanmo226 I assigned you remaining tasks which should be done in the current milestone. After them you can switch to the browser extension
