### ISSUE TITLE
update setup screen labels

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#325]
I did roughly this:
1) already had account A signed in
2) added another account B
3) recovered from inbox, and then setup done -> render inbox
4) switch to account A
5) something went wrong: noInbox
6) clicked retry and it worked

both Gmail accounts. Setting for future milestone

**Comment by tomholub** [comment]
happens again if I switch back to B and to A again. So far happened every time I switch to A.

**Comment by tomholub** [comment]
@ekievsky please have a look if you are able to reproduce this. Thanks!

**Comment by ekievsky** [comment]
how to "recovered from inbox, and then setup done -> render inbox"?

**Comment by tomholub** [comment]
"recover from inbox" here means that that account was already set up before, with key backups sent to inbox during previous setup of that account. Then you logged out or deleted the app. If you try to set up again now, you are prompted with an "enter pass phrase" prompt which cross-checks the pass phrase the users enters against the keys from inbox, and recover your account - that's what the "recovered from inbox" means

**Comment by tomholub** [comment]
"and then setup done -> render inbox" means it will render that setup is done and send to user to inbox view, which is what normally happens after setup

**Comment by ekievsky** [comment]
> "recover from inbox" here means that that account was already set up before, with key backups sent to inbox during previous setup of that account. Then you logged out or deleted the app. If you try to set up again now, you are prompted with an "enter pass phrase" prompt which cross-checks the pass phrase the users enters against the keys from inbox, and recover your account - that's what the "recovered from inbox" means

It asks me to enter passphrase and there is no option to recover. Am I missing something?

![Simulator Screen Shot - iPhone 12 - 2021-07-08 at 01 38 20](https://user-images.githubusercontent.com/38130577/124837295-3d7e4400-df8d-11eb-89e2-6a2fb719070c.png)

**Comment by tomholub** [comment]
What happens if you enter "abcd" for pass phrase? Does it say it's wrong? If yes, then this is the recovery screen, but it's just not clearly labeled.

**Comment by ekievsky** [comment]
It just says that passphrase is wrong and keep challenging me.
![Simulator Screen Shot - iPhone 12 - 2021-07-08 at 12 14 52](https://user-images.githubusercontent.com/38130577/124896680-536c2300-dfe6-11eb-9c6c-744cb99c8283.png)

**Comment by tomholub** [comment]
Ok - in that case this is the recovery screen that I meant. You're in the right place, it just doesn't make it very clear. I'll make another issue for improving the UI to make it clear this is recovery.

**Comment by ekievsky** [comment]
But it doesn't allow me to import back up key from clipboard or file.

**Comment by tomholub** [comment]
@ekievsky what screen does the browser extension show after login on that account? Please share screenshot - let's see the difference. Anton's comment here https://github.com/FlowCrypt/flowcrypt-ios/issues/382#issuecomment-876294589 suggests there is something else going on.

**Comment by Kharchevskyi** [comment]
@tomholub, just spoke to @ekievsky with regards to this issue. Was just a miscommunication.  

This issue is probably already fixed, unfortunately do not remember in which commit exactly, is it possible for you to merge #355 and try to reproduce it once again?

**Comment by tomholub** [comment]
Yes, but there is still something wrong with the above screen nevertheless.

The above screen seems to be creating a new key, where you are free to choose your own pass phrase. But it's saying `wrong pass phrase` as if it's checking it against something, like during a recovery flow. 

That's why I'd like to see what does the browser extension show, as that is the reference implementation.

**Comment by Kharchevskyi** [comment]
It was a recovery screen, just without a label. 
@ekievsky was entering wrong pass phrase - that's why it showed `wrong pass phrase`

**Comment by tomholub** [comment]
Why was the label missing - is that also true on current master right now that I merged that PR #355 ?

**Comment by tomholub** [comment]
Btw I can no longer reproduce the noInbox issue

**Comment by Kharchevskyi** [comment]
<img width="1040" alt="Screenshot 2021-07-08 at 13 49 27" src="https://user-images.githubusercontent.com/13693255/124910111-e2336c80-dff3-11eb-9e8f-00e98e0d0377.png">
Was a bug which was fixed in `ef8a552`

**Comment by tomholub** [comment]
got it - thank you. I'll close this issue but will open another one for a bit clearer labeling.

**Comment by tomholub** [comment]
Actually, no need - it seems it will be fine as is. Thanks again
