### ISSUE TITLE
add a modal with hint about how to choose pass phrase

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#327]
There should be a little question mark icon at the end of pass phrase creation prompt texts like `Choose your pass phrase (?)`. When clicked, this shows:

![1](https://user-images.githubusercontent.com/13693255/119661711-3d8d0f00-be39-11eb-96ef-9b5e751aff77.png)

**Comment by tomholub** [comment]
@ekievsky do you have any android device handy? Our Android app is further along in implementation, and a lot of iOS functionality can be copied from there. It will be helpful to you to be able to use the app as an inspiration when implementing issues.

**Comment by Kharchevskyi** [comment]
@ekievsky please make sure that #197 is merged or checkout from `feature/issue-197-pass-phrase-memory`.

**Comment by tomholub** [comment]
I've put this issue into 0.2.1 milestone which is to be done after all issues in 0.2.0 are done - therefore the above should already be merged by then.
