### ISSUE TITLE
SwiftFormat: failed to format any files

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#331]
I'm getting this error when re-building the project. Currently need to `git reset --hard` between each run to make it build successfully.

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/6306961/120664632-acafd680-c4bd-11eb-9495-5095e0c77efe.png">

**Comment by Kharchevskyi** [comment]
can you please show output for `which swiftformat` and `swiftformat --version`?
is it the same for you @ekievsky?

**Comment by ekievsky** [comment]
Project works for me well.

**Comment by tomholub** [comment]
Thanks - I'll check next time I build the app for a review.

**Comment by tomholub** [comment]
Still happening. It modifies OrganizationalRule.swift and then second time I run it, it doesn't want to process the file anymore, so I have to reset it before it works.

```
which swiftformat
/usr/local/bin/swiftformat

swiftformat --version
0.40.12
```

**Comment by tomholub** [comment]
fixed for now in https://github.com/FlowCrypt/flowcrypt-ios/pull/323/commits/52e14d610a4f666769b1bcb69a7be3c215bbecac
