### ISSUE TITLE
prepwork for retrieving client configuration (OrgRules) from FES

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#339]
part of #275
after this, you may do #340
after that can do #276 

FES = FlowCrypt Enterprise Server https://flowcrypt.com/docs/technical/enterprise-server/latest/enterprise-server.html

Flow:
1) parse out user domain: `user@example.com` -> `example.com`
2) skip all following steps if user is on public email domain (@ gmail, @ outlook)
3) call `GET https://fes.$domain/api/` (no authentication) for example `GET https://fes.corp.com/api/`. If it returns a 404 or the server cannot be reached within 4 seconds, skip following steps (similar failure handling to WKD policy call)
4) make sure that the response contains json parameter `service` which must equal `enterprise-server`. If it shows something else or this is not contained, show an error.
5) show a toast message that says `FES at $url not supported on iOS yet`

The class that does steps 1-4 should be `EnterpriseServerApiClient` eg a method `func getActiveFesUrl(for email: String): Promise<String?>` (nil if no FES runs there, else url of the server). 

Do the above during setup immediately after authentication (once you know user email address)

You can test this flow using your Google account at flowcrypt.com domain which I'll send you. Here is the API that you will be calling in that case: https://fes.flowcrypt.com/api/ but of course the domain is dynamic, so you may be calling another URL if you used account on another domain.

**Comment by tomholub** [comment]
> There were 1 email addresses found in the above comment. Please:
> 
>     1. click `three dots` -> `edit` to remove the email addresses
> 
>     2. click `edited` in the comment header, and click on the previous revision of the comment
> 
>     3. when viewing the old revision with an email in it, click `options` -> `delete this revision from history`

@seisvelas it seems to be getting triggered but not sure why. The emails are @ example.com

**Comment by seisvelas** [comment]
>@seisvelas it seems to be getting triggered but not sure why. 

I neglected to update this repo when I updated all the others to have exemptions. Right now I'll review all the public repos in our org to make sure I didn't miss any others. Sorry!

**Comment by ekievsky** [comment]
@tomholub now the API returns `{"v": 4}`, is there a way to get a complete JSON?
what should be passed as a result of `String?`?

P.S. I was using flowcrypt.com domain for test

**Comment by tomholub** [comment]
Are you sure? See this particular URL: https://fes.flowcrypt.com/api/

**Comment by tomholub** [comment]
notice the pattern `GET https://fes.<domain>/api/`

**Comment by ekievsky** [comment]
<img width="676" alt="Screenshot 2021-06-05 at 23 20 11" src="https://user-images.githubusercontent.com/38130577/120904360-95572180-c654-11eb-9854-a350aaeece06.png">

**Comment by tomholub** [comment]
could you try with curl to compare?

```
curl https://fes.flowcrypt.com/api/
{"vendor":"FlowCrypt","service":"enterprise-server","orgId":"flowcrypt.com","version":"2021-02-RC","endUserApiVersion":"v1","adminApiVersion":"v1"}
```

Also DNS:

``
$ systemd-resolve fes.flowcrypt.com
fes.flowcrypt.com: 45.77.52.9

-- Information acquired via protocol DNS in 1.1ms.
-- Data is authenticated: yes
```

**Comment by ekievsky** [comment]
here is what curl returns me 
`curl https://fes.flowcrypt.com/api/
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>`

**Comment by tomholub** [comment]
try with `-I`

```
$ curl -I https://fes.flowcrypt.com/api/
HTTP/1.1 200 OK
Server: nginx/1.14.0
Date: Sat, 05 Jun 2021 20:34:36 GMT
Content-Type: text/plain
Content-Length: 0
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Security-Policy: frame-ancestors 'none'; default-src 'self';
```

**Comment by ekievsky** [comment]
`curl -I https://fes.flowcrypt.com/api/
HTTP/1.1 301 Moved Permanently
Date: Sat, 05 Jun 2021 20:35:29 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://flowcrypt.com/api/
Content-Security-Policy: frame-ancestors 'self'
Cache-Control: max-age=0, must-revalidate
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-XSS-Protection: 1; mode=block`

**Comment by tomholub** [comment]
could you find out which IP does fes.flowcrypt.com resolve to on your system?

**Comment by tomholub** [comment]
Separately, also try this:

```
curl -I https://fes.flowcrypt.com/api/ --resolve 'fes.flowcrypt.com:443:45.77.52.9'
```

**Comment by ekievsky** [comment]
45.76.85.121

**Comment by ekievsky** [comment]
> curl -I https://fes.flowcrypt.com/api/ --resolve 'fes.flowcrypt.com:443:45.77.52.9'

it returns 200 OK

**Comment by tomholub** [comment]
I had that IP only in my hosts file as I just fount out. Missing DNS record - I just fixed it. Hopefully, in a few minutes it should work normally for you too.

**Comment by tomholub** [comment]
Seems to show correctly now https://dns-lookup.com/fes.flowcrypt.com

**Comment by ekievsky** [comment]
so the curl returns right JSON now, but the iOS client is not

**Comment by tomholub** [comment]
probably dns cache. You could work around it by setting the hosts file on it if it lets you.

**Comment by ekievsky** [comment]
the iOS client resolves `45.76.92.47` 🤷‍♂️

**Comment by tomholub** [comment]
Or try tomorrow :-) or restart your device, maybe.

**Comment by ekievsky** [comment]
well, I've reset Simulator and got the right JSON.
Thanks for help!

**Comment by ekievsky** [comment]
what should be returned as a result of String??

**Comment by tomholub** [comment]
The URL of the FES (eg `https://fes.flowcrypt.com/` without the `/api/`), if there is any running.

**Comment by ekievsky** [comment]
The toast should say "FES at $url not supported on iOS yet", so the method should return `https://fes.flowcrypt.com/` if FES is not supported. Am I wrong?

**Comment by tomholub** [comment]
Sorry for the confusion. The correct way is:
 - if it returns nil, don't toast anything. Because there is no FES running, nothing to tell the user.
 - if FES is available and it returns URL, then toast `FES at $url not supported on iOS yet`. This is because there is FES running, but we have not implemented any functionality on the iOS app that utilizes the FES (meaning it's not supported, even if we know that it exists).

Thanks for asking.

**Comment by ekievsky** [comment]
got it, thanks!

**Comment by ekievsky** [comment]
@tomholub  `curl -I https://fes.flowcrypt.com/api/` started timing out. Could you help with that?

**Comment by tomholub** [comment]
indeed - sorry about that. Will take a look

**Comment by tomholub** [comment]
fixed now
