### ISSUE TITLE
call FES in background after startup

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#340]
part of #295 right after #339

In addition to checking FES presense during setup / after authentication, also do the same on app startup for all logged in users. 

Do it after app started (asynchronously - don't hold up the user), immediately after all other network requests were idle for at least 1 second. If this is difficult to do, then do it 5 seconds after the app has started (so we don't hog up internet capacity during app startup when it needs to grab emails quickly to render to user)

In this case, instead of showing toast, you can just log that message.

**Comment by ekievsky** [comment]
It's been handled in https://github.com/FlowCrypt/flowcrypt-ios/pull/349
