### ISSUE TITLE
Core decryptFile + encryptFile methods

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#341]
part of #275, do before #195 or #196

 need to add the following method to Core. Roughly:

```swift
    public func decryptFile(encrypted: Data, keys: [PrvKeyInfo], msgPwd: String?) throws -> CoreRes.DecryptFile {
                let json: [String : Any?]? = ["keys": try keys.map { try $0.toDict() }, "msgPwd": msgPwd]
                let decrypted = try call("decryptFile", jsonDict: json, data: encrypted)
                let meta = try decrypted.json.decodeJson(as: CoreRes.DecryptFileMeta.self)
                return CoreRes.DecryptFile(...) 
     }
```

here is the code of the typescript handler:

```ts
  public decryptFile = async (uncheckedReq: any, data: Buffers): Promise<Buffers> => {
    const { keys: kisWithPp, msgPwd } = ValidateInput.decryptFile(uncheckedReq);
    const decryptedMeta = await PgpMsg.decrypt({ kisWithPp, encryptedData: Buf.concat(data), msgPwd });
    if (!decryptedMeta.success) {
      decryptedMeta.message = undefined;
      return fmtRes(decryptedMeta);
    }
    return fmtRes({ success: true, name: decryptedMeta.filename || '' }, decryptedMeta.content);
  }
```

need to be mindful of ability to handle the error scenario.

-----------------

similarly for encryptFile:

```
  public encryptFile = async (uncheckedReq: any, data: Buffers): Promise<Buffers> => {
    const req = ValidateInput.encryptFile(uncheckedReq);
    const encrypted = await PgpMsg.encrypt({ pubkeys: req.pubKeys, data: Buf.concat(data), filename: req.name, armor: false }) as OpenPGP.EncryptBinaryResult;
    return fmtRes({}, encrypted.message.packets.write());
  }
```

**Comment by tomholub** [comment]
@ekievsky please get started on sending/downloading encrypted messages.

Please ensure that it's done the same way browser extension does it, and is compatible. Ask questions if unsure.

**Comment by tomholub** [comment]
To test these methods, you can write a unit test that encrypts some file, then decrypts it, then compares content.

**Comment by ekievsky** [comment]
How do I update `.js` file with decryptFile and encryptFile methods?

**Comment by ekievsky** [comment]
How may mock this case:
```
if (!decryptedMeta.success) {
      decryptedMeta.message = undefined;
      return fmtRes(decryptedMeta);
}
```

**Comment by tomholub** [comment]
You could try giving it a bogus message like "blahblah" and try decrypting that.

**Comment by ekievsky** [comment]
what do you mean by `message`? File(MessageAttachement) contains `name`, `size` and `content`

**Comment by tomholub** [comment]
The file to decrypt is supposed to be an encrypted file. You can give it a file that has bogus content, which should result in an error.

**Comment by ekievsky** [comment]
ah, right, thanks!

**Comment by ekievsky** [comment]
In case of not encrypted content, method `call("decryptFile",....)` throws an error with description, so it seems that this case handled by js script.

**Comment by tomholub** [comment]
Yes, it's supposed to be. Just need to make sure we can understand these errors on the Swift side too (we should already have all the various error situations from `parseDecryptMsg`. Another one you could try is to give it correct encrypted message, but wrong (mismatching) private keys. That's a common problem. Swift should recognize that situation too.

**Comment by ekievsky** [comment]
got that, thanks
