### ISSUE TITLE
@testable import instead of adding files to. the test target

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#348]
In current implementation in case we want to cover some functionality with unit test, whole file with all related dependencies should be added to test target which lead to compiling each file 2 times, besides that for now not all files are added to both targets which makes testing quite complicated. 
For example `DataService` can't be easily add to test target, so it's hard to use it as default parameter and it should be "hidden" by some protocol to not include whole file.
Investigate is it possible to use `@testable import FlowCrypt` instead of adding files to test target.

**Comment by Kharchevskyi** [comment]
@ekievsky what do you think about it?

**Comment by ekievsky** [comment]
Agree, that's a good approach to avoid compiling the same file twice.

I'll try not to forget about it in new tests 😅

**Comment by Kharchevskyi** [comment]
@ekievsky Not sure we are ready for that) 
I think we need to update Podfile and probably some frameworks can be an issue. 
Do you have any experience with migrating from "adding to test target" to "testable import"?

**Comment by Kharchevskyi** [comment]
new tests - 😍

**Comment by ekievsky** [comment]
I had no experience with migration, but I had worked on a project where we were using @testable and we just set up all the pods for both targets(main and tests).

**Comment by tomholub** [comment]
I see
