### ISSUE TITLE
add libs as pods not as source files

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#35]
> add libs as pods not as source files. Easier to maintain, improve compile time

**Comment by Kharchevskyi** [comment]
Fixed in pr https://github.com/FlowCrypt/flowcrypt-ios/pull/41

**Comment by tomholub** [comment]
Thanks! I like to keep issues open until I've merged the PR and reviewed/tested the code, so I'll re-open it for a little longer

**Comment by tomholub** [comment]
There's the menu closing bug which will be addressed in #38
