### ISSUE TITLE
Secret flowcrypt-ios-ci-secrets not found

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#378]
@tomholub The build fails on CI and if I open SemaphoreCI it shows me empty screen with `Secret flowcrypt-ios-ci-secrets not found` message, is it internal Semaphore issue?

_Originally posted by @ekievsky in https://github.com/FlowCrypt/flowcrypt-ios/issues/376#issuecomment-873427670_

**Comment by Kharchevskyi** [comment]
Same for all active PRs. 
@tomholub we do not run UI tests currently on CI. Is it ok to disable this task on Semaphore?

**Comment by Kharchevskyi** [comment]
Looks like indeed problem with `test-ci-secrets.json` on CI
please check #379

**Comment by tomholub** [comment]
I'll look into it and revert #379 once fixed

**Comment by tomholub** [comment]
I suppose this was now fixed? I'm closing this unless still a problem.
