### ISSUE TITLE
Compare keys by fingerprint

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#384]
Later this should be compared by `primaryFingerprint` vs `$0.fingerprint` - it's ok to do it in a followup PR

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/375#discussion_r666438234_

**Comment by Kharchevskyi** [comment]
https://github.com/FlowCrypt/flowcrypt-ios/pull/375#discussion_r666438349

**Comment by Kharchevskyi** [comment]
@tomholub this is already compared by `primaryFingerprint`. Can you please check is logic correct?
And what in addition should be done for this issue?

**Comment by tomholub** [comment]
Review every single usage of longid and use fingerprint instead if possible.

Here is one example:

![image](https://user-images.githubusercontent.com/6306961/125280787-00a3ab80-e305-11eb-9a5b-9de7c4dab0e0.png)

**Comment by Kharchevskyi** [comment]
We use KeyDetails to recover account 
`private func recoverAccount(with backups: [KeyDetails], and passPhrase: String)`
Does this mean we need to add `primaryFingerprint` to `KeyDetails` as well?

**Comment by tomholub** [comment]
Likely yes - whenever today longid is used, fingerprint should be used instead.

**Comment by tomholub** [comment]
Longid can still be present in objects like `KeyDetails` but basically never used, except when circumstances somehow require it, in which case we'll discuss it case by case and add a comment next to it why we used longid and not fingerprint in a particular scenario.

**Comment by Kharchevskyi** [comment]
Got it, thanks

**Comment by Kharchevskyi** [comment]
Does order for fingerprints always the same? 
Should we compare by primaryFingerprint (first one from array of fingerprints)? or it's better to compare sets of fingerprints?
