### ISSUE TITLE
replace all fatalError with throw

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#387]

**Comment by tomholub** [comment]
If yes, then we can close this. If no, then we should instead use a way to assert things that will also function in production - I don't want wrong assumptions in code in particular in production.

**Comment by ekievsky** [comment]
`assertionFailure` will only crash on debug builds, it won't crash on production. We can change to `fatalError` so it will crash in production.

**Comment by tomholub** [comment]
Ok, we should use `fatalError` in situations that must never happen, meaning if they do happen, it's our own code fault (like user with missing ClientConfiguration after setup). This will crash the app and then we'll see it in reports and can fix the code.

We will use Promise rejections with an appropriate error for situations that can happen (badly parsed external input, network error, unexpected API input etc) so that these don't crash the app.

**Comment by ekievsky** [comment]
So in scope of this PR I am just going to replace `assertionFailure` with `fatalError`, Promises rejections should be refactored partly, right?

**Comment by tomholub** [comment]
In the scope of this issue, for every `assertionFailure` you have to make a decision. Ask this question:

**Does this error scenario seem "impossible" on a well written, bug-free codebase?** 

- **Yes, it feels impossible unless there's a hidden bug**: Then it's a `fatalError`. Examples: a nil check when we've already nil-checked before, `account?.email` nil check when we are in a flow where the user already must have been logged in, state of the app that should never happen and so on. We want to crash the app, because something is quite wrong.

- **No, this could happen and it's not a code bug:** for example wrong user input, wrong response format from API, server down, server timeout, connection timeout, HTTP 4xx or 5xx and so on. These are errors which would be rendered to user. Then we need to produce an error that will be somehow shown to the user, and stop what we are doing.
    - if we are in a Promise, then this is a promise rejection with an error
    - if we are in view controller code and it makes sense to render error directly, then we render error
    - if we are in other code that does not have promises, I'm not too sure what to do here. Probably throw an error and catch it somewhere where you can render an error to the user (like VC).

**Comment by tomholub** [comment]
You don't have to address every single `assertionFailure` in one PR, you can do one part of the app in one PR and then next one later - but make it clear which parts are there to do and which ones does the PR address.

Thanks!

**Comment by ekievsky** [comment]
got you, thanks for explanation!

**Comment by tomholub** [comment]
Should not be closed yet - I think not every assertionFailure was replaced yet.

**Comment by ekievsky** [comment]
You're right, I didn't replaced every assertion, I just replace the ones that I am really confident.

**Comment by tomholub** [comment]
For the remaining `assertionFailure` usages, please highlight them here or make a PR where you add a todo comment next to each one of them, so that we can discuss how to address them.

**Comment by tomholub** [comment]
I guess, with the exception of `fatalError("init(coder:) has not been implemented")`, all of the fatal errors should be replaced.

I seem to recall there were some in the storage code too that were hard to deal with? Those could be skipped too for now.

But things like:

```swift
        guard let fingerPrint = fingerprints.first else {
            fatalError("primaryFingerprint for KeyDetail is missing")
        }

        guard let service = services.first(where: { $0.mailServiceProviderType == authType.mailServiceProviderType }) as? T else {
            fatalError("Email Provider should support this functionality. Can't resolve dependency for \(type)")
        }

          guard case let .byNextPage(token) = pagination else {
                fatalError("Pagination \(String(describing: context.pagination)) is not supported for this provider")
            }

        guard case let .byNumber(from) = context.pagination else {
            fatalError("Pagination \(String(describing: context.pagination)) is not supported for this provider")
        }
        guard let folderPath = context.folderPath else {
            fatalError("Folder path should not be nil for IMAP")
        }
        guard let expression = helper.createSearchExpressions(from: expressions) else {
            fatalError("could not create search expression")
        }

```

etc have to be replaced.
