### ISSUE TITLE
upgrade addressable dependency

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#391]
![image](https://user-images.githubusercontent.com/6306961/125582003-13cd910b-5f96-413d-8463-6a9c84a898e0.png)

**Comment by tomholub** [comment]
Unsure if this issue was already addressed. If yes, please close.

**Comment by sosnovsky** [comment]
Yes, we're currently using the latest 2.8.0 version.

<img width="391" alt="Screenshot 2021-10-04 at 13 33 12" src="https://user-images.githubusercontent.com/1062093/135836623-717b823a-f79d-43b6-9607-374edaac3320.png">
