### ISSUE TITLE
Improve send message checks

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#399]
Unsure how was this handled before, looks like we should improve it, but that would be for another PR.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/306#r669354549_

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/126501824-afd3cd5d-9ed2-4afb-a131-899a77a3a2d0.png)
