### ISSUE TITLE
make sure id token does not get printed in production build

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#401]
@ekievsky by "should not be printing" did you mean it does not print any in production build, or that it would be bad if it printed?

We'll have to be very clear about this - I'm making an issue to verify that it in fact does not print it in a production build.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/395#discussion_r672923094_

**Comment by ekievsky** [comment]
I mean we have to avoid printing any sensitive data on prod builds.
Let me check if the app prints anything on production build.

**Comment by tomholub** [comment]
duplicate issue #440
