### ISSUE TITLE
handling of core.composeEmail errors

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#411]
It's possible for this to fail for various reasons. For example, try to run this with an invalid public key. It will produce an error, and this should be handled gratiously - by showing a modal alert to the user that there was an error sending message, and what it said. After the taps clicks the modal away, they should still be on the compose screen where they can click send again to retry.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/410#discussion_r677428684_

```
    private func encryptMessage(with msg: SendableMsg) -> Data {
        do {
            return try core.composeEmail(msg: msg, fmt: MsgFmt.encryptInline, pubKeys: msg.pubKeys).mimeEncoded
        } catch {
            fatalError()
        }
    }
```

**Comment by ivan-ushakov** [comment]
Looks like this was changed a lot because now it uses Compose to provide future object:
```
func composeEmail(msg: SendableMsg, fmt: MsgFmt, pubKeys: [String]?) -> Future<CoreRes.ComposeEmail, Error>
```

and in `ComposeMessageService`:
```
private func encryptMessage(with msg: SendableMsg) -> AnyPublisher<Data, Error>
```

**Comment by tomholub** [comment]
I see it now - could you check what happens when you give it some bogus pubkey to trigger an error?

```diff
    private func encryptMessage(with msg: SendableMsg) -> AnyPublisher<Data, Error> {
        return core.composeEmail(
            msg: msg,
            fmt: MsgFmt.encryptInline,
-           pubKeys: msg.pubKeys
+          pubKeys: ["This is bogus!"]
        )
        .map(\.mimeEncoded)
        .eraseToAnyPublisher()
    }
```

It should surface the error to the user as a modal in a generic manner.

**Comment by ivan-ushakov** [comment]
Do you have any test user for the app? Maybe some kind of test account?

**Comment by tomholub** [comment]
> Do you have any test user for the app? Maybe some kind of test account?

Yes, I'll just need an NDA signed if that is ok with you. You'll get your own account on `flowcrypt.com` domain that you can test with, and also some general test accounts. Also test secrets to run UI tests.

**Comment by ivan-ushakov** [comment]
OK, I will contact you tomorrow about NDA.

**Comment by ivan-ushakov** [comment]
Here is how it looks:

![Simulator Screen Shot - iPhone 11 Pro - 2021-09-30 at 18 38 08](https://user-images.githubusercontent.com/1408366/135486899-3a20ce1f-9b32-4782-91fb-6cce53cae04b.png)

but I found that error handling happens off the main thread:
```
Main Thread Checker: UI API called on a background thread: -[UIViewController navigationItem]
PID: 71426, TID: 8735387, Thread name: (none), Queue name: com.flowcrypt.core, QoS: 9
Backtrace:
4   FlowCrypt                           0x000000010c4320dd $s9FlowCrypt21ComposeViewControllerC6handle33_7A1ECDF8A8586BF8F0F21A8909AD61B9LL5erroryAA0C12MessageErrorO_tF + 157
5   FlowCrypt                           0x000000010c432028 $s9FlowCrypt21ComposeViewControllerC11sendMessage33_7A1ECDF8A8586BF8F0F21A8909AD61B9LLyyFyAA0cG5ErrorOcfU0_ + 232
6   FlowCrypt                           0x000000010c43231c $s9FlowCrypt19ComposeMessageErrorOIegg_ACIegn_TR + 28
7   FlowCrypt                           0x000000010c2f4fe3 $s7Combine9PublisherP9FlowCryptE10sinkFuture12receiveValue0G5ErrorAA14AnyCancellableCy6OutputQzc_y7FailureQzctFyAA11SubscribersO10CompletionOy_AMGcfU_ + 435
8   Combine                             0x00007fff4e90e216 $s7Combine11SubscribersO4SinkC7receive10completionyAC10CompletionOy_q_G_tF + 422
```
I will fix this.

**Comment by ivan-ushakov** [comment]
Also I found that something happens with navigation bar and buttons (see screenshot above).
