### ISSUE TITLE
All Mail folder on Gmail doesn't work

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#429]
![image](https://user-images.githubusercontent.com/6306961/127878923-068d02b9-85c0-4577-9c00-59f8884d47f4.png)

**Comment by tomholub** [comment]
The error message is wrong, too. That should be fixed before the issue is resolved.

**Comment by ekievsky** [comment]
What is correct error message?

**Comment by tomholub** [comment]
I'm not sure. The folder was failing to load repeatedly, when other folders worked. Doesn't seem like offline issue, therefore it must be showing a wrong error. Can you reproduce this?

**Comment by ekievsky** [comment]
@tomholub it reproduces all the time, what is the difference between `all mail` and `inbox` should `all mail` show the emails from all active accounts?

**Comment by tomholub** [comment]
If you log into any Gmail account through webmail, you should see an All Mail section. You have to click `More` on the left menu, then `All Mail`. It's just an email folder like any other. On Gmail, these are emails that are in inbox plus emails that were archived.

However, before you fix it, you should also investigate why it's showing "no internet" error message, which is clearly wrong. There is something wrong with our error handling, the real error is getting masked. It would be good to know what the real error is before you attempt to fix it.

**Comment by ekievsky** [comment]
got it

The issue with errors is that we don't handle GmailServiceError and take that as unexpected. I would fix the issue with `All mail` in scope of this issue and create another to fix error handling on Inbox screen.

**Comment by tomholub** [comment]
Best would be other way around, if you can: fix error handling first, so that it starts printing some proper error. Then fix that error specifically after.
