### ISSUE TITLE
Rework usage of EncryptedStorage().activeUser

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#438]
Should be addressed in a separate ticket.

_Originally posted by @Kharchevskyi in https://github.com/FlowCrypt/flowcrypt-ios/pull/437#discussion_r686974745_

Consider possible solutions:
- Injecting encrypted storage
- Pass user as a parameter to `fetchFolders`

 make the user object required

**Comment by tomholub** [comment]
This is probably outdated? You may close if so.

**Comment by sosnovsky** [comment]
Yes, we already have `FoldersService` with injected `EncryptedStorageType`
