### ISSUE TITLE
UX - add activity indicator on Login screen

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#447]
Sometimes gmail sign in popup will not appear
1. Log out from the app
2. Tap on the `continue in with gmail` multiple times

Add activity indicator or disable tapping on login buttons after first tap on sign in with gmail
#442

**Comment by paragdulam** [comment]
I tried reproducing this issue on a very slow internet on my phone expecting to see some UI glitch, may be multiple gmail login modal screens but no such thing happened. Additionally, it shows an alert initially to avoid multiple hits on the button. I think we can close this issue. @tomholub @Kharchevskyi please let me know if I am missing something here.
