### ISSUE TITLE
UX - dark status bar

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#448]
![Simulator Screen Shot - iPhone 8 - 2021-08-16 at 17 22 24](https://user-images.githubusercontent.com/13693255/129578962-53c22ad8-77d2-468d-bb1b-7187b4e8a141.png)
#442

**Comment by tomholub** [comment]
Are you thinking of the elements in the status bar? Maybe use white instead?

**Comment by paragdulam** [comment]
The status bar is white. We can close this issue @tomholub. your thoughts?

**Comment by tomholub** [comment]
Please show a screenshot of what it looks like now.

**Comment by paragdulam** [comment]
![image](https://user-images.githubusercontent.com/307000/140177248-e3700e33-1821-42f2-bcea-1970cde45d5b.png)

**Comment by tomholub** [comment]
looks good
