### ISSUE TITLE
UX - wrong colour for button in dark mode

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#449]
![Simulator Screen Shot - iPhone 8 - 2021-08-16 at 17 23 04](https://user-images.githubusercontent.com/13693255/129579095-4ebd2d78-2523-438c-8f61-bc7f8555e487.png)
#442

**Comment by tomholub** [comment]
Also the size looks wrong

**Comment by Kharchevskyi** [comment]
it should use `clear` color to be transparent

**Comment by paragdulam** [comment]
![image](https://user-images.githubusercontent.com/307000/139945467-092d393e-80ca-49c7-9616-eff72198a99d.png)

Have we removed the "Use Another Account" button from current master?

**Comment by Kharchevskyi** [comment]
fixed in scope of #1258
