### ISSUE TITLE
menu - connection error in inbox

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#453]
Screen with emails of the folder will be pushed once more even if you already in it.
1. Tap on menu
2. Tap on inbox folder
3. With until emails list is loaded 
4. Tap on inbox once more

![Simulator Screen Shot - iPhone 8 - 2021-08-16 at 17 39 49](https://user-images.githubusercontent.com/13693255/129581661-90e0c4a1-a4b0-458d-8cab-9ebc313834b0.png)

#442

**Comment by tomholub** [comment]
Thank you! This looks very broken indeed.

**Comment by ekievsky** [comment]
Should we refresh the messages list when user taps on the same folder type or just hide a side menu?
