### ISSUE TITLE
send information about testing to Dmitry

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#454]
Per Anton's suggestion - this makes sense.

It would be best if the QA person could also help us write tests to test for the problems they uncover.

**Comment by ekievsky** [comment]
I truly support this point, it would be really helpful if we could have a QA person that will verify the tasks and help testing the app.

**Comment by tomholub** [comment]
I started looking for a testing automation person, to help with ui tests.

I don't think developer responsibility and QA responsibility should be separated - that leads to careless developers. Plus adds manual labor for what should be automated.

However we do need help from someone to help us lay foundation for automated ui tests, so that it becomes easier for us to write these.

**Comment by tomholub** [comment]
Found someone - they will be starting next week.
