### ISSUE TITLE
UX - adopt to ipad/mac

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#457]

**Comment by paragdulam** [comment]
![Simulator Screen Shot - iPad (9th generation) - 2021-11-04 at 01 45 52](https://user-images.githubusercontent.com/307000/140186055-1610623e-2d12-4f81-9578-a92e14a70d3b.png)

Are we thinking of implementing a UISplitViewController like UI/UX on ipad here?

**Comment by tomholub** [comment]
For now, for simplicity, I'd like mobile and ipad app have the same/similar layout.

If we can a lot of interest from ipad users, we'll consider layout changes for them.

**Comment by tomholub** [comment]
One obvious thing to fix is the splash screen - looks horrible on ipad. The buttons should not have full length (please set some maximum) and the logo is stretched too big as well.

Other will probably be setup screen - check if pass phrase entries are too wide (probably are) and similarly buttons during setup procedure.

After that please look at other screens for similar issues.

**Comment by Kharchevskyi** [comment]
<img src="https://user-images.githubusercontent.com/13693255/147952864-b4695631-b73b-4dc2-bd98-5874ca667730.png" width="400" />
<img src="https://user-images.githubusercontent.com/13693255/147953004-8633a9ed-baac-4e50-9c28-5f526c93ce8a.png" width="400" />
<img src="https://user-images.githubusercontent.com/13693255/147953046-9a4eaf36-10e4-4357-8d08-33a68b9d56e5.png" width="400" />
<img src="https://user-images.githubusercontent.com/13693255/147953051-f79b0903-59b5-4064-bfa2-cbaff3b23b40.png" width="400" />

@tomholub is this adoption looks ok for you? Or what design is more preferable?

**Comment by tomholub** [comment]
Yes, it's a definite improvement.

**Comment by Kharchevskyi** [comment]
#1270 - text insets
#1269 - crash
