### ISSUE TITLE
UI Tests for EKM integration

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#469]

**Comment by Kharchevskyi** [comment]
@DenBond7 I assume you do have this tests. Would it be possible for you to explain how is it set up on Android?

**Comment by DenBond7** [comment]
Please look at this issue https://github.com/FlowCrypt/flowcrypt-android/issues/1168 for more details. And for example this https://github.com/FlowCrypt/flowcrypt-android/commit/b1a0b64de4bae649bd380d95b83db3428e1a6262 commit.

If shortly, we use a mock web server to generate needed responses.

**Comment by tomholub** [comment]
This will be for @fcvakintos next week. I'd like to write an end-to-end UI test that tests login, setup and reading one message successfully with a user at `flowcrypt.com` domain - where keys are managed with Email Key Manager (EKM). For context here is relevant documentation https://flowcrypt.com/docs/technical/enterprise/email-deployment-overview.html but for the purposes of testing this, you don't need to know the details yet except that it has to be some user at `@flowcrypt.com` where we have this EKM integration in place which we are not properly testing yet.

I suppose we should give Appium a try for this test. Our current UI tests have trouble running on CI. Either that, or you could see if you can manage to get our current UI tests to run on CI reasonably, and then continue writing them as we were doing it before. I'll leave it up to you to explore options.

We were using SemaphoreCI with a mac instance. I don't know if that is the cause of the trouble or not - we could try other mac CI services per your recommendation instead. I'm flexible. (having an actual mac running somewhere would be last resort)

UI tests for our app involve Gmail oAuth2 login and permission grant. Is this something that Appium offers ready-made tooling for? We hacked around the login for our own UI tests and it seems to work ok so far - how is this usually done with Appium?

Before running the test, we'll need to add another account into secrets file - a `@flowcrypt.com` account which we will set up together. I'll help update the secrets file in SemaphoreCI or upload it to some other CI we use. For now, you can just add it locally to your git folder (where the file is gitignored)

Here are the steps for the actual test:

1) click `Continue with Gmail` and sign-in with this flowcrypt.com account on google, grant access
2) you will see pass phrase screen, enter any sufficiently strong pass phrase
3) repeat pass phrase to confirm
4) proceed with setup, which will bring you to inbox
5) open an encrypted email which you earlier sent to that account
6) email contents should be readable

I think that covers the basics, enough to evaluate if Appium or our current mechanism is the better way to go.

I'll do a followup issue with other test steps to do after we evaluate that.

**Comment by tomholub** [comment]
> Please look at this issue [FlowCrypt/flowcrypt-android#1168](https://github.com/FlowCrypt/flowcrypt-android/issues/1168) for more details. And for example this [FlowCrypt/flowcrypt-android@b1a0b64](https://github.com/FlowCrypt/flowcrypt-android/commit/b1a0b64de4bae649bd380d95b83db3428e1a6262) commit.
> 
> If shortly, we use a mock web server to generate needed responses.

To clarify, so that this doesn't confuse Dmitry: for simplicity, I expect here on iOS we will initially use a real Google account and do an end-to-end test that way, not mocking anything.

However, in the long term, we may use the approach Den suggested - to have more control over the test environment and be able to test some scenarios that are difficult to reproduce with real live services.
