### ISSUE TITLE
UI Tests - multiple accounts

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#484]

**Comment by fcvakintos** [comment]
@tomholub please provide second account

**Comment by fcvakintos** [comment]
@tomholub please provide second account

**Comment by tomholub** [comment]
Sorry, didn't get to this yet. Please look at #913 first

**Comment by fcvakintos** [comment]
@tomholub ok

**Comment by tomholub** [comment]
Also before you do this issue, I'd like the env file reduced. I've mentioned it a few times but didn't see any issue filed. Here: https://github.com/FlowCrypt/flowcrypt-ios/issues/914

**Comment by fcvakintos** [comment]
913 and 914 were done

**Comment by tomholub** [comment]
Thank you. This one is on me now, I'll be giving you another account once I have a chance to create and set up one.

**Comment by fcvakintos** [comment]
@tomholub ok, let me know

**Comment by tomholub** [comment]
We'll later use an Outlook account for this. But that's probably broken now due to #989 so we'll have to fix that one first

**Comment by tomholub** [comment]
@fcvakintos I have sent you an updated env file with this structure. Also updated it on semaphore.

```
ACCOUNT_PASSWORD=
E2E_ENTERPRISE_TESTS_GOOGLE_PASSWORD=
E2E_CONSUMER_TESTS_OUTLOOK_PASSWORD=
```

`ACCOUNT_PASSWORD` and  `E2E_ENTERPRISE_TESTS_GOOGLE_PASSWORD` have the same content. Please stop using `ACCOUNT_PASSWORD` in the codebase (name too generic) and use the other one. Eventually we'll remove `ACCOUNT_PASSWORD` from env file

Also added `E2E_CONSUMER_TESTS_OUTLOOK_PASSWORD`. This is for outlook account `e2e.consumer.tests@outlook.com`. This account has a key set up with pass phrase `flowcrypt compatibility accounts o`.

pre-setup:
1) make a special label/folder/category on outlook email like `outlook consumer folder`
2) make a special labe/folder/category on gmail like `gmail enterprise folder`
3) send a plain email to outlook with subject `outlook account inbox email`

Test case:
1) log into outlook use the `Other email provider` button on settings (not the Outlook option - not implemented) and then enter the email into `email` field and password into `password` filed. All other fields, including the `account` field will be auto-filled correctly. Scroll down to continue
2) you will see pass phrase prompt, enter a wrong pass phrase. Should get rejected right away. Then enter the good pass phrase. Should not get re-prompted for it, and then you should see inbox.  
3) Confirm that there is an outlook-related email in inbox - "outlook account inbox email" to easily distinguish it pulls the right inbox.
4) go to menu. Confirm there is the outlook email address. Confirm that there is expected category `outlook consumer folder`
5) click chevron next to account
6) you'll see add account, click it
7) choose continue with gmail
7) login with the enterprise gmail account as you normally do
8) now you should see enterprise gmail inbox. search for some known email on gmail.
9) Go to menu. Confirm there is `gmail enterprise folder` and also the gmail account email
10) switch back to outlook using the menu. Confirm again there is the right email address, folder, and inbox item for outlook after the switch

For now, opening actual emails in outlook cause crashes, this is known: #1145 so for now don't open any messages in outlook tests.

**Comment by fcvakintos** [comment]
I tried to login to outlook account and get error(I use E2e.consumer.tests@outlook.com)
![Simulator Screen Shot - iPhone 13 - 2021-12-06 at 13 05 44](https://user-images.githubusercontent.com/91205853/144835633-850da0de-7043-45e8-a713-f5c945a895f1.png)

If I set "e2e.consumer.tests@outlook.com"  and correct password, the app is crashed

https://user-images.githubusercontent.com/91205853/144836086-f5d70d61-b2c9-4d4b-a964-820f500a78e4.mov

**Comment by tomholub** [comment]
Please share the crash report that it generated. (didn't crash when I tested it 4 days ago)

**Comment by fcvakintos** [comment]
@tomholub 
[appium-server-logs.txt](https://github.com/FlowCrypt/flowcrypt-ios/files/7660412/appium-server-logs.txt)

**Comment by tomholub** [comment]
I meant the app crash report. Haven't you yourself implemented retrieving it last time? https://github.com/FlowCrypt/flowcrypt-ios/issues/890

**Comment by fcvakintos** [comment]
@tomholub ^

**Comment by tomholub** [comment]
Assigned, moving this to later until fixed.

**Comment by fcvakintos** [comment]
thanks

**Comment by tomholub** [comment]
@fcvakintos this should now be actionable again

**Comment by fcvakintos** [comment]
@tomholub I tried to login to outlook account and get the error
<img width="433" alt="Screenshot 2022-01-05 at 16 26 49" src="https://user-images.githubusercontent.com/91205853/148233876-72fa68e5-7900-4bc8-93ed-f198bc3bce26.png">
can you check pls?

**Comment by tomholub** [comment]
Will take a look

**Comment by sosnovsky** [comment]
I got this error with my `gmail.com` account too, will push fix in a few minutes

**Comment by fcvakintos** [comment]
@tomholub I cant login this this pass phrase 'flowcrypt compatibility accounts o' too outlook account
could you provide correct pass phrase?

**Comment by tomholub** [comment]
Try `flowcrypt compatibility account o`

**Comment by fcvakintos** [comment]
@tomholub the same error, wrong pass phrase

**Comment by fcvakintos** [comment]
@tomholub  any news about pass phrase?

**Comment by Kharchevskyi** [comment]
Had the same issue. 
Just created a new account in Outlook and set it up with our iOS app

**Comment by fcvakintos** [comment]
cool, can you share credentials?

**Comment by fcvakintos** [comment]
@Kharchevskyi ^

**Comment by Kharchevskyi** [comment]
Will try to find them or you can create a new one

**Comment by fcvakintos** [comment]
@Kharchevskyi Thanks, i need use it for automation test

**Comment by Kharchevskyi** [comment]
can share over email. Please text me on anton@flowcrypt.com

**Comment by fcvakintos** [comment]
@Kharchevskyi done

**Comment by tomholub** [comment]
I recommend to enumerate them as `aid-account-email-0`, `aid-account-email-1` and so on. @Kharchevskyi can help.

Btw that email can be used for your local testing but not for CI tests. I'll check the credentials your were missing.

**Comment by tomholub** [comment]
@fcvakintos I can't find the record of what was the pass phrase supposed to be, other than the one above. You can remove the backup email from the inbox / trash it / delete it. Then go through setup and choose to make a new key, and give it a pass phrase of `flowcrypt compatibility accounts o` once. After that you'll be able to enter this pass phrase during ci tests.

**Comment by fcvakintos** [comment]
@tomholub I dont know how to set up new key 
can you explain to do this?

**Comment by tomholub** [comment]
1) You can remove the backup email from the inbox / trash it / delete it
2) reinstall app or log out
3) Then go through setup and choose to make a new key, and give it a pass phrase of `flowcrypt compatibility accounts o`

After that you'll be able to enter this pass phrase during ci tests.

**Comment by Kharchevskyi** [comment]
@fcvakintos 
Will add AIDs today

**Comment by fcvakintos** [comment]
@tomholub The key is not saved, I tried your steps, but after logout and login again i need to create new key

**Comment by fcvakintos** [comment]
@Kharchevskyi  do you need ticket for this ?

**Comment by Kharchevskyi** [comment]
https://github.com/FlowCrypt/flowcrypt-ios/issues/1302

**Comment by tomholub** [comment]
> @tomholub The key is not saved, I tried your steps, but after logout and login again i need to create new key

That would be a bug. You can file that separately as a bug for someone to investigate, and meanwhile you can use the browser extension or Android app to go through the setup and have it save the backup.

**Comment by Kharchevskyi** [comment]
Was also tried to reproduce. Had this error. Can you please add to this issue as well
<img width="299" alt="Screenshot 2022-01-13 at 11 53 46" src="https://user-images.githubusercontent.com/13693255/149307467-e3114753-320d-485f-a7c8-5c2887868f7d.png">

**Comment by Kharchevskyi** [comment]
not sure but looks like this functionality doesn't work for gmail accounts as well

**Comment by fcvakintos** [comment]
ok, will create new issue

**Comment by tomholub** [comment]
Ok, so there are three issues when creating a key during setup:
 - missing / unclear details of that error message. It should be showing clearly the URL and http code like other API errors do. This will need an appium test as well. The Attester mock will be set to return a 400 on submission with some error message, and the above modal must show that error message (we had a mechanism for this that was supposed to work across modals)
 - the fact that there is an error submitting to attester
 - per Dmitry's account, whenever there isn't the above error, backup doesn't get sent to inbox

**Comment by fcvakintos** [comment]
https://github.com/FlowCrypt/flowcrypt-ios/issues/1304

**Comment by fcvakintos** [comment]
@tomholub how can i create key using web version?

**Comment by tomholub** [comment]
Exact same procedure I described earlier, except you use our browser extension for it.

**Comment by fcvakintos** [comment]
@tomholub I dont know how to set up key for outlook account
can you help me?

**Comment by tomholub** [comment]
I see - browser extension doesn't support outlook - forgot about that. Try the android app, and if you get stuck, share a screenshot to understand the issue.

**Comment by fcvakintos** [comment]
@tomholub I dont have Android device

**Comment by tomholub** [comment]
Are you able to run it on a simulator? (I was under impression that you also write appium tests for android app at times)

**Comment by fcvakintos** [comment]
@tomholub no

**Comment by fcvakintos** [comment]
@tomholub I get this error
<img width="393" alt="Screenshot 2022-01-13 at 15 27 42" src="https://user-images.githubusercontent.com/91205853/149338842-6c068447-a8a4-477b-b21a-a435ed53bcf3.png">

**Comment by tomholub** [comment]
Did you do this?

> 1. You can remove the backup email from the inbox / trash it / delete it

**Comment by fcvakintos** [comment]
yes

**Comment by tomholub** [comment]
If you really fully removed the backup from the inbox, and also from thrash, reinstalled the app and then went through setup, then you would not be looking at that screen - no backup to recover. Do you confirm you have done that?

**Comment by tomholub** [comment]
@DenBond7 please have a look whether you see the same behavior. I'm sending the creds by email

**Comment by fcvakintos** [comment]
@tomholub on iOS app I get this screen after login to outlook account
<img width="389" alt="Screenshot 2022-01-13 at 17 04 25" src="https://user-images.githubusercontent.com/91205853/149354997-42e10c4d-1e03-4417-95d7-5d771848bf4e.png">

but on Android after reinstall - "we found a backup of your key"
<img width="393" alt="Screenshot 2022-01-13 at 15 27 42" src="https://user-images.githubusercontent.com/91205853/149355077-84a840c2-c304-469a-ba98-45e199cb2a56.png">

**Comment by tomholub** [comment]
ok. Den will check it. Thanks for the screenshots

**Comment by DenBond7** [comment]
> please have a look whether you see the same behavior. I'm sending the creds by email

@fcvakintos Please look at the `Sent` folder. You have a backup there.

**Comment by fcvakintos** [comment]
@DenBond7 yes, found in Sent

**Comment by fcvakintos** [comment]
@tomholub  done, I setup new key

**Comment by tomholub** [comment]
Good. With that, you should be able to write tests for iOS.
