### ISSUE TITLE
join or rename OrganisationalRules with ClientConfiguration

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#504]
In another PR, we should refactor the naming. It's not clear what's the benefit of having an `OrganisationalRules` object that only wraps `ClientConfiguration` object. We should just have a single `ClientConfiguration` object and that's all. If we do need a wrapper for some justified reason, then we can call that `ClientConfigurationWrapper` and add a comment on why it's needed. If it's to match it to a http response, then we should call it `ClientConfigurationResponse` that contains `ClientConfiguration`.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/499#discussion_r711189057_

**Comment by ekievsky** [comment]
In JS code you have `DomainRules` object that's the same as `ClientConfiguration` in Swift code, so maybe I should just rename `ClientConfiguration`?

**Comment by tomholub** [comment]
JS code needs to be renamed too.

Where in Swift code do we need a separate object that wraps the `ClientConfiguration`? Is it to match http response, or is it some other reason?

**Comment by ekievsky** [comment]
It's just raw data model that keeps data from API.

**Comment by tomholub** [comment]
The call the wrapper `ClientConfigurationWrapper`, having a separate name is confusing

**Comment by ekievsky** [comment]
Okay, I will.
