### ISSUE TITLE
is iOS ATS enabled?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#509]
no reason not to enable it. Is it done in code?

**Comment by Kharchevskyi** [comment]
Yes. Enabled by default. No ` NSExceptionDomains` specified in `info.plist`

From https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity
`ATS operates by default for apps linked against the iOS 9.0 or macOS 10.11 SDKs or later.`

**Comment by tomholub** [comment]
excellent, thanks
