### ISSUE TITLE
The folder name `Functionallity` is misspelled, it should be `Functionality`

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#511]
The folder name `Functionallity` is misspelled, it should be `Functionality`

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/499#discussion_r713398389_

**Comment by ivan-ushakov** [comment]
Looks like this is [already fixed](https://github.com/FlowCrypt/flowcrypt-ios/tree/master/FlowCrypt/Functionality)

**Comment by ivan-ushakov** [comment]
Ah, I found that in unit tests it is still wrong
