### ISSUE TITLE
notReady - could not fetch keys

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#516]
Another severe regression - this shows how lacking our tests are.

Can be tested on any account with EKM set up.

Reproduce:
1) set up account managed by EKM
2) open any encrypted message

![image](https://user-images.githubusercontent.com/6306961/134329811-c9dce7d6-b264-48c8-bcca-a802af43e43e.png)

**Comment by ekievsky** [comment]
@tomholub while logging in to my flowcrypt gmail account receiving 502 on `https://fes.flowcrypt.com/api/`, no issues with usual gmail account

**Comment by tomholub** [comment]
Yes, that is unrelated issue that I just caused minutes ago - I'm fixing it and will let you know once fixed.

**Comment by ekievsky** [comment]
got you, just letting you know, thank you!

**Comment by tomholub** [comment]
it should be ok now

**Comment by tomholub** [comment]
This turns out to be an intermittent issue. It went away when I logged out and set up again. I'm moving to 0.2.1, but we have to investigate this thoroughly, it suggests we are either using Realm wrongly or not checking errors properly during setup.

**Comment by tomholub** [comment]
Interestingly, when this was happening, it was showing 3 keys in Settings -> Keys without issue.

**Comment by tomholub** [comment]
> [Roman] After app restart it works well - seems like something isn't fully configured after sign up

**Comment by tomholub** [comment]
(I removed some comments that were not related to this particular issue, for clarity)

**Comment by tomholub** [comment]
At least this seems to be quite reliably reproducible.

**Comment by tomholub** [comment]
Also adding @ekievsky to have a look in parallel - this issue is becoming annoying.

**Comment by sosnovsky** [comment]
@tomholub is there any way to simulate new user setup? As this bug happens only for new users, but isn't reproduced for existing users.

**Comment by sosnovsky** [comment]
Yeah, I finally reproduced it by resetting Xcode simulator content, as after app uninstall-install it worked well without "fetch keys" error. Thanks!

**Comment by sosnovsky** [comment]
I'm reproducing it with my `flowcrypt.com` mail, but I think it happens for other accounts too.

I found where this bug happens - https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Functionality/Services/Key%20Services/KeyService.swift#L84

Stored passphrase has 2 fingerprints, but app compares only `primaryFingerprint`(which is the first one).
On first app launch first fingerprint isn't equal to `keyInfo.primaryFingerprint` and fetch fails, but on the next app launches fingerprints order is changed and `storedPassPhrase.primaryFingerprint` is equal to `keyInfo.primaryFingerprint`

I can update code to compare not only `primaryFingerprint` but all available fingerprints. Is it good solution or only `primaryFingerprint` should be checked there?

**Comment by sosnovsky** [comment]
Got it, I'll check why order is wrong on the first app launch

**Comment by sosnovsky** [comment]
Issue is reproduced only after resetting simulator, so if you installed app in simulator before running ui tests then "fetch keys" alert won't be shown. Possibly app stores some data in keychain which is deleted only on device reset.

I think it should be possible to automatically reset simulator before running ui tests to make this issue reproducible there too.

**Comment by ekievsky** [comment]
@tomholub should I still work on it?

**Comment by tomholub** [comment]
@ekievsky it seems Roma is pretty close - in that case it would be better for you to continue on other issue. Thanks for asking.

**Comment by ekievsky** [comment]
good, thanks!
