### ISSUE TITLE
test for not needing pass phrase for plain message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#520]
Test steps:
1) set up with pass phrase in session, restart app (to clear the pass phrase)
2) open plain message

expected result: message renders without asking for pass phrase

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/519#issuecomment-925572274_

**Comment by fcvakintos** [comment]
hi @tomholub please review https://github.com/FlowCrypt/flowcrypt-ios/pull/698
