### ISSUE TITLE
TypeScript core build should update iOS js respource + build scripts

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#527]
following from https://github.com/FlowCrypt/flowcrypt-ios/issues/506

Please update package.json to add `postbuild` which copies the iOS artifact (may be called `-bare`?) to https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Resources/flowcrypt-ios-prod.js.txt

Then after the .js.txt file is updated, please check the updated version into git (I expect it to be the same, or mostly same - it's possible the built file could be identical - in which case the only change on the PR would be the postbuild).

**Comment by IvanPizhenko** [comment]
@tomholub There is already "deploy" task which does the job, just need to edit it a bit, because it copies stuff to the both Android and iOS, while now we only need iOS.

**Comment by tomholub** [comment]
that sounds good - thanks
