### ISSUE TITLE
don't add .pgp to file list when attaching files on compose screen

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#538]
(when composing a message and adding attachment)

the .pgp filename should not be visible in that list. So you don't have to alter the filename, after all (the encryption method should be already transparently renaming them)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/505#pullrequestreview-763195500_

**Comment by tomholub** [comment]
notice browser extension:

![image](https://user-images.githubusercontent.com/6306961/134698993-64e6ac53-71ca-4683-b60c-827127958264.png)

**Comment by tomholub** [comment]
I suppose this causes a bug when sending emails to browser extension. The `.pgp` gets passed into `composeEmail` which is also wrong - the original filename should go there.

**Comment by ekievsky** [comment]
If I don't add `.pgp` into name for `composeEmail` neither app or extension will decrypt the file.
All the files sent by extension have `.pgp` extension in received email
<img width="447" alt="Screenshot 2021-10-05 at 21 19 11" src="https://user-images.githubusercontent.com/38130577/136080275-64bd2c33-21eb-4762-b9a3-3196985f6158.png">
.

**Comment by tomholub** [comment]
> If I don't add `.pgp` into name for `composeEmail` neither app or extension will decrypt the file. All the files sent by extension have `.pgp` extension in received email <img alt="Screenshot 2021-10-05 at 21 19 11" width="447" src="https://user-images.githubusercontent.com/38130577/136080275-64bd2c33-21eb-4762-b9a3-3196985f6158.png"> .

Doesn't `composeEmail` add the `.pgp` to attachments automatically?

**Comment by ekievsky** [comment]
it doesn't
