### ISSUE TITLE
attaching a screenshot (instead of a photo) causes error

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#563]

**Comment by ekievsky** [comment]
This issue is not reproducing for me now.

**Comment by tomholub** [comment]
What would be the fix? Since it lets me choose a particular object (a screenshot), I'd expect it should be able to process it too.

**Comment by ekievsky** [comment]
That's the thing. I working on resolving it

**Comment by tomholub** [comment]
got it :-)
