### ISSUE TITLE
cocoapods-core-1.11.2 requires ruby version >= 2.6, which is incompatible with the current version, ruby 2.5.1p57

### ISSUE THREAD

**Issue by newuser4github** [FlowCrypt/flowcrypt-ios#572]
Hi @sosnovsky I tried to follow the instructions from the README.md to set up the app's environment and failed after the command

> make dependencies

with output

> cocoapods-core-1.11.2 requires ruby version >= 2.6, which is incompatible with the current version, ruby 2.5.1p57

Please tell me exactly what I have to do to be guaranteed to overcome this, thank you!

**Comment by sosnovsky** [comment]
Hi @newuser4github, I forgot to update README.md after upgrading CocoaPods to the latest version.
The quick fix is to use these commands:
```
rvm install 3.0.2
rvm --default use 3.0.2
```

instead of 
```
rvm install 2.5.1
rvm --default use 2.5.1
```
