### ISSUE TITLE
migrate to Texture, declare ui in code

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#58]
My biggest worry is that if we do all UI in code, there will be too much code, or code readability will suffer by mixing UI and logic.

Hopefully you can find a way to minimize that.

**Comment by Kharchevskyi** [comment]
Can share you some code examples with texture. 
Basically you declare all your ui in views and all your business logic contains in services to handle this. 

Also all calculations to draw ui are calculated not on main thread so we can reach about 60fps with Texture. 

Will add Texture in separate branch.

**Comment by tomholub** [comment]
Yes I have researched Texture. Actually the thing I like the most is that you can access your UI elements from any thread, so you don't have to always go to main thread to operate on UI. Is this correct? If yes, that could already clean up some code.

This issue is marked in the "**Later**" milestone, that means we will wait until issues in First and Second priority milestones are done.
