### ISSUE TITLE
see if we can avoid both .map and force unwrapping when dealing with non-array nullables

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#593]
I know this is probably my problem not coming from a Swift background, but to me a `.map` implies that `keyDetail.expiration` is some sort of an iterable, and you're applying a method over it to return something iterable again.

But that's not the case here - `keyDetail.expiration` is an `Int?` and so the `.map` on values like this will never stop confusing me :-( seems to be a common practice in Swift.

Is there a pattern possible in Swift that's a bit more obvious for a non-Swifter? A ternary operator maybe? Like `keyDetail.expiration != nil ? Date(timeIntervalSince1970: Double(keyDetail.expiration)) : nil` ?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/566#discussion_r717843388_

**Comment by tomholub** [comment]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/6306961/135732120-d3e5e923-f454-4a62-b60a-e42366ebf256.png">

**Comment by ivan-ushakov** [comment]
> Is there a pattern possible in Swift that's a bit more obvious for a non-Swifter? A ternary operator maybe? Like `keyDetail.expiration != nil ? Date(timeIntervalSince1970: Double(keyDetail.expiration)) : nil` ?

No, you should unwrap variable even if you tested it to be not null. The only way I see here is to have special method like [XCTUnwrap](https://developer.apple.com/documentation/xctest/3380195-xctunwrap).

**Comment by tomholub** [comment]
I can see now that it's using this .map for Optionals: https://developer.apple.com/documentation/swift/optional/1539476-map

That looks good but the name is really unfortunate. Can it be aliased, or can we write our own? To call it something sane like `.ifNotNil` ?

```swift
expiration = keyDetail.expiration.ifNotNil { Date(timeIntervalSince1970: Double($0))  }
```

The goal is that `.map` should be reserved for array-like situations, so that data structures are more obvious during code reviews.
