### ISSUE TITLE
support conversation view in inbox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#608]
The app has two methods to access email provider: Gmail API and IMAP/SMTP.

I'd like to update the app as follows: app stays the same when IMAP is used. When we use Gmail API, I'd like to view a list of conversations instead of list of emails when I open any folder in inbox.

Specifically, with Gmail, at the moment we:
 - use messages.list to get a list of messages in inbox: https://developers.google.com/gmail/api/reference/rest/v1/users.messages/list
 - user clicks on a message, and we use https://developers.google.com/gmail/api/reference/rest/v1/users.messages/get to download and display it

After update, with Gmail, we will:
- [x] use threads.list https://developers.google.com/gmail/api/reference/rest/v1/users.threads/list to get a list of threads. Choose them using `labelIds` for a particular folder. Maybe you'll have to threads.get the individual threads to show the details: https://developers.google.com/gmail/api/reference/rest/v1/users.threads/get (like subject etc of each thread in the list)
- [x] also render amount of messages in each thread with a `(1)` or `(3)` or similar under the date.
- [x] when user clicks on one of the threads, then on message view we'll use threads.get for this particular selected thread. The threads will be rendered as a list, a bit similar to the inbox list except that we only show the sender and the time, not subject next to each item (since subjects in a thread are all the same).
- [x] to the right side of each thread item (that is, individual email) on the message view, there should be a chevron. Clicking the chevron will expand the message, which will download the actual message from server with messages.get https://developers.google.com/gmail/api/reference/rest/v1/users.messages/get , then decrypt it with `parseProcessMsg` like we do now
- [x] clicking the chevron again will make that message collapse
- [x] emails on message view should be from oldest in thread on top to newest on bottom 
- [x] when I render the message view by transitioning from inbox view, only one message should be expanded - the first **unread** message from the top.

The technical details above, eg regarding Gmail API usage, may not be 100% precise but it should give you the idea.

The unfortunate part is that somewhere in controller code (both inbox and message view) you'll have to decide if we are using IMAP or Gmail API and branch accordingly. Or do you think it would be better to have completely different controllers, maybe with shared bases? One for IMAP and one for Gmail API?

**Comment by Kharchevskyi** [comment]
Yes, it shows in "thread" view. 
Can I fully remove previous implementation for gmail inbox view or it will be still used?

**Comment by Kharchevskyi** [comment]
![IMAGE 2021-10-10 22:52:54](https://user-images.githubusercontent.com/13693255/136711151-67d0862e-7e81-4c13-8a95-9aafe16f580a.jpg)

**Comment by tomholub** [comment]
Let's remove it the previous code. Less code to maintain.

**Comment by tomholub** [comment]
@Kharchevskyi please before self-assigning, see if there is an open issue that is already assigned to you: https://github.com/FlowCrypt/flowcrypt-ios/issues/assigned/Kharchevskyi

Since you already started working on this, ok to finish. But after, please do https://github.com/FlowCrypt/flowcrypt-ios/issues/287

**Comment by tomholub** [comment]
> What in case there are no unread messages? should we expand latest message in thread?

Yes

> Would this mean we need to scroll to bottom in case of there are a lot of messages in the thread?

Once the view loads, always auto-scroll so that the top of the expanded message is visible (if the message spans more than the screen, then scroll so that the top of the expanded message and it's header is visible on top of the screen. if the message spans less than the screen, simply scroll to the bottom)

**Comment by Kharchevskyi** [comment]
Can we create a separate ticket to support threads view in search controller?

**Comment by Kharchevskyi** [comment]
having some issues with rendering message in thread. 
Is it ok to just render message text in scope of this ticket and all other functionality, like showing attachments, mark as read and functionality split to another ticket?

**Comment by tomholub** [comment]
Got it. You're the most experienced with our rendering code here :-) so you'll have to tackle it either way
