### ISSUE TITLE
composeEmail TS code should add `.pgp` to enncrypted attachment names

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#619]
> If I don't add `.pgp` into name for `composeEmail` neither app or extension will decrypt the file. All the files sent by extension have `.pgp` extension in received email <img alt="Screenshot 2021-10-05 at 21 19 11" width="447" src="https://user-images.githubusercontent.com/38130577/136080275-64bd2c33-21eb-4762-b9a3-3196985f6158.png"> .

Doesn't `composeEmail` add the `.pgp` to attachments automatically?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/538#issuecomment-934656535_

That way, in Swift code, we can pass the original attachment name into `composeEmail`.

Then composeEmail can use the original name to pass into encryption method, but use altered name with `.pgp` to encode the mime email.

**Comment by IvanPizhenko** [comment]
reassigned to @ekievsky since my part is done
