### ISSUE TITLE
ios-android differences: attachments

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#627]
This will contain multiple issues if there's any, related to attachments

**Comment by tomholub** [comment]
please retest

**Comment by martgil** [comment]
Retesting case no.1 (opening message with an attachment larger than 5MB)

<img width="1440" alt="Screen Shot 2022-05-26 at 4 55 34 PM" src="https://user-images.githubusercontent.com/46025304/170454977-14e35234-a82e-4d43-b354-0e598c7ac48b.png">
The message decrypted without any problems -- viewing the attachment preview on the ios works well as well as the download function.
