### ISSUE TITLE
Increase icon tappable area?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#63]
I use an iPod touch as my debugging device.

Sometimes I have to tap an icon 2 or 3 times before it registers the tap (often I notice this when trying to open the side menu).

My guess is that maybe the tappable icon area is too small, maybe something like this:

![image](https://user-images.githubusercontent.com/6306961/63510357-e3c21d00-c4cd-11e9-952a-92b24448a99f.png)

It would be better to increase it to take up as much space around the icon as possible, for all icons, maybe like this:

![image](https://user-images.githubusercontent.com/6306961/63510478-33a0e400-c4ce-11e9-958d-690d3119e33d.png)

**Comment by RomanKovalchuk2019** [comment]
Ok, I will do this today with finishing infinite scrolling on inbox
