### ISSUE TITLE
test for opening message with attachment when pass phrase is set to be in memory but not currently there

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#641]
>     Difficult to test (explain why) - currently we don't have tests for MessageService, so test for this functionalityprobably will be added once we'll cover MessageService with tests.

@fcvakintos will be later covering this with UI tests. I'll make an issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/640#issuecomment-937662094_

**Comment by fcvakintos** [comment]
@tomholub I started working on this ticket and have a question
In my message with attachment(image) I see only name of image. Is it ok? or I should see image?
And could you provide test steps for this scenario?

<img width="416" alt="Screenshot 2021-11-02 at 11 22 35" src="https://user-images.githubusercontent.com/91205853/139820171-b6a68f2e-2cdd-4b19-b551-0404d1ba876a.png">

**Comment by tomholub** [comment]
@fcvakintos could you please, before continuing on this issue, help with:

https://github.com/FlowCrypt/flowcrypt-ios/issues/892 - Ivan is having trouble running test
https://github.com/FlowCrypt/flowcrypt-ios/issues/891 - exporting app logs
https://github.com/FlowCrypt/flowcrypt-ios/issues/890 - getting app crash log
This is all to help us debug what we broke in https://github.com/FlowCrypt/flowcrypt-ios/pull/854 which we'd like to merge but the appium tests are failing.

I'll provide answer shortly, but please look into the above first - it's blocking us.

**Comment by tomholub** [comment]
> @tomholub I started working on this ticket and have a question
In my message with attachment(image) I see only name of image. Is it ok? or I should see image?

How was the message sent? Was it from the iOS app or from the browser extension (chome or firefox)?

Details depend on how was the message structured. What do you see when you open it on browser extension?

> And could you provide test steps for this scenario?

1) don't have any pass phrase in memory (for now it's with app restart)
2) open an encrypted message that has an attachment on it
3) enter a wrong pass phrase, you should be re-prompted
4) enter a correct pass phrase, and you should see the message and attachment (but not the way you are seeing it - attachment should be tappable)
5) tap the attachment
6) it should offer to download without further prompting pass phrase
7) go back to inbox
8) open the message again, and it should decrypt without prompting pass phrase
9) tap the download one more time, still should not ask for pass phrase

**Comment by fcvakintos** [comment]
@tomholub in chrome I see image

<img width="495" alt="Screenshot 2021-11-02 at 12 07 02" src="https://user-images.githubusercontent.com/91205853/139827010-c578ef51-ba89-4a38-abdb-9f0033bb8253.png">

**Comment by tomholub** [comment]
Please look into the other issues first

**Comment by tomholub** [comment]
> @fcvakintos could you please, before continuing on this issue, help with:
> 
> #892 - Ivan is having trouble running test #891 - exporting app logs #890 - getting app crash log This is all to help us debug what we broke in #854 which we'd like to merge but the appium tests are failing.
> 
> I'll provide answer shortly, but please look into the above first - it's blocking us.

**Comment by fcvakintos** [comment]
@tomholub what about image?
should i see it in email?

**Comment by tomholub** [comment]
How was the message sent? Was it from the iOS app or from the browser extension (chome or firefox)?

**Comment by fcvakintos** [comment]
@tomholub sorry, it is actual only for simple email, not for encrypted
for encrypted email attachment is displayed

**Comment by tomholub** [comment]
I see. The original email had an inline image, which is not supported in the iOS app yet.

**Comment by fcvakintos** [comment]
ok, got it

**Comment by fcvakintos** [comment]
@tomholub is it correct the pop opens when I tap only on download button from attachment (not on attachment name)?
<img width="421" alt="Screenshot 2021-11-03 at 10 12 42" src="https://user-images.githubusercontent.com/91205853/140027317-297885c2-44e2-4b80-92e9-c0d39f9cdf5e.png">

**Comment by tomholub** [comment]
With current implementation yes, but you're right it should be improved. Well noticed! I'll file an issue.

**Comment by fcvakintos** [comment]
ok, thanks)

**Comment by fcvakintos** [comment]
@tomholub should the file format be displayed? because in download pop-up the .png is not displayed.
And what is attachment type should I user for this? .png - is it ok?
<img width="408" alt="Screenshot 2021-11-03 at 12 31 33" src="https://user-images.githubusercontent.com/91205853/140045339-c03a0aec-4263-4c9a-a90e-2fa069659050.png">
<img width="399" alt="Screenshot 2021-11-03 at 12 31 26" src="https://user-images.githubusercontent.com/91205853/140045343-b3ce0740-878c-46a8-b23f-f36323f42e52.png">
?

**Comment by tomholub** [comment]
yes, can use png for the test

**Comment by tomholub** [comment]
Agree that it would be better if the app could show the attachment name too - I'll file a ticket

**Comment by fcvakintos** [comment]
@tomholub did you create ticket for attachment name?^

**Comment by tomholub** [comment]
here https://github.com/FlowCrypt/flowcrypt-ios/issues/901

**Comment by fcvakintos** [comment]
@tomholub created draft PR for this issue, could you check?
https://github.com/FlowCrypt/flowcrypt-ios/pull/911

**Comment by tomholub** [comment]
I already have notifications for all newly opened PRs - no need to tag me separately here. As long as that PR links this issue (it did), it's all good & I'll know about it.
