### ISSUE TITLE
create unit tests for composeEmail with signing key

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#659]
When signature verification issue will be ready we need to add unit tests for the `Endpoints.composeEmail` method when we provide signing key.

**Comment by tomholub** [comment]
comes from https://github.com/FlowCrypt/flowcrypt-ios/pull/650#issuecomment-939542068 - now we have signature verification code, and therefore signing should be testable / verifiable.
