### ISSUE TITLE
FlowCrypt ipa for penetration tester installtion failed

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#660]
I tried to install the IPA executable to my device but it says:

`
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/FlowCrypt.app/SC_Info/FlowCrypt.sinf in archive!
Copying 'FlowCrypt.enterprise.020.for.pentest.ipa' to device... DONE.
Installing 'com.flowcrypt.as.ios.enterprise'
Install: CreatingStagingDirectory (5%)
Install: ExtractingPackage (15%)
Install: InspectingPackage (20%)
Install: TakingInstallLock (20%)
Install: PreflightingApplication (30%)
Install: InstallingEmbeddedProfile (30%)
Install: VerifyingApplication (40%)ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008015: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.SsTltI/extracted/Payload/FlowCrypt.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)
`

I use the following command in installing the ipa:
`ideviceinstaller -i FlowCrypt.enterprise.020.for.pentest.ipa -u <my udid>`

<img width="699" alt="flowcrypt_ipa_installation_error" src="https://user-images.githubusercontent.com/46025304/136923416-80b1b759-09f8-4495-a078-b6a59461f73b.png">

**Comment by tomholub** [comment]
Please share your apple device UUID, I'll add you.

**Comment by tomholub** [comment]
uuid of the ios device

**Comment by tomholub** [comment]
I don't know if it still helps to add you retroactively - may not necessarily work. Let's see

**Comment by martgil** [comment]
My device UUID is `00008030-000665AE3685802E`. Thank you, sir!

**Comment by martgil** [comment]
It still doesn't work, but it's okay, sir. You may request a pentest for the ios anytime. 

Thank you!

**Comment by tomholub** [comment]
How about ability to build the app straight into the phone? It doesn't allow you now?

**Comment by tomholub** [comment]
I suppose this is now resolved - if it's not, please file another issue.
