### ISSUE TITLE
Broken style for header

### ISSUE THREAD

**Issue by fcvakintos** [FlowCrypt/flowcrypt-ios#665]
Steps:
- Login
- Set pass phrase
- Observe Inbox screen

Actual: Header is transparent and header buttons are not visible
Expected: Header should be green and buttons should be visible
<img width="434" alt="Screenshot 2021-10-13 at 12 44 37" src="https://user-images.githubusercontent.com/91205853/137109490-43377b52-461b-44a9-a37a-cb8a081eb9e8.png">

**Comment by tomholub** [comment]
@fcvakintos can you reproduce on current master? (in case you were using code before #533 )
