### ISSUE TITLE
Can't download MailCore2

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#667]
MailCore2 package can't be downloaded 

`
Showing All Messages
failed downloading 'https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip' which is required by binary target 'MailCore2': downloadError("Error Domain=NSURLErrorDomain Code=-1202 \"The certificate for this server is invalid. You might be connecting to a server that is pretending to be “downloads.maddux.cloud” which could put your confidential information at risk.\" UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(\n    \"<cert(0x7fa1eeec1600) s: progress.hub.agwmafrica.org i: R3>\",\n    \"<cert(0x7fa1eeac0600) s: R3 i: ISRG Root X1>\",\n    \"<cert(0x7fa1eeacd600) s: ISRG Root X1 i: DST Root CA X3>\"\n), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip, NSErrorFailingURLStringKey=https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore2-2020-09-24.xcframework.zip, NSUnderlyingError=0x7fa1f0a65790 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 \"(null)\" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x7fa1f9acbbf0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9843, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9843, kCFStreamPropertySSLPeerCertificates=(\n    \"<cert(0x7fa1eeec1600) s: progress.hub.agwmafrica.org i: R3>\",\n    \"<cert(0x7fa1eeac0600) s: R3 i: ISRG Root X1>\",\n    \"<cert(0x7fa1eeacd600) s: ISRG Root X1 i: DST Root CA X3>\"\n)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalDownloadTask <742C6AA5-DA02-43AB-B356-FDFCEE5E564B>.<1>\"\n), _kCFStreamErrorCodeKey=-9843, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <742C6AA5-DA02-43AB-B356-FDFCEE5E564B>.<1>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x7fa1f9acbbf0>, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “downloads.maddux.cloud” which could put your confidential information at risk.}")
`

**Comment by Kharchevskyi** [comment]
I think for now we are blocked with further development, until this issue resolved.

**Comment by ekievsky** [comment]
just have seen that. thank you @tomholub 

@sosnovsky that worked for me. its strange because I was deleting entire derived data several times before.
anyway - now I am good, thanks!
