### ISSUE TITLE
threads in search view

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#669]
Can we create a separate ticket to support threads view in search controller?

_Originally posted by @Kharchevskyi in https://github.com/FlowCrypt/flowcrypt-ios/issues/608#issuecomment-942442660_

At the moment the search results are rendered using a custom view, but instead we should use the same view that we use for all other folders.

**Comment by ioanmo226** [comment]
@tomholub What does `thread` mean here?

**Comment by tomholub** [comment]
It means a "conversation", a sequence of emails treated as one email thread.

**Comment by ioanmo226** [comment]
Aha, Got it
