### ISSUE TITLE
share secrets file with ivan

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#671]
Yes, I get error when I try to run unit tests because Xcode tries to copy this file and file does not exist. Maybe I forgot to run some script during project setup.

_Originally posted by @ivan-ushakov in https://github.com/FlowCrypt/flowcrypt-ios/pull/590#discussion_r727422019_

I just need to share the secrets file with you. I'll check if you have the NDA signed yet.

**Comment by ivan-ushakov** [comment]
@tomholub 
Sorry, I forgot to check my FlowCrypt mail. I found secret file.
