### ISSUE TITLE
ios webView controller allows redirection to third-party unknown website.

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#673]
Description: 
ios webView is used to display most of the static pages of the website listed in the `SignInViewDecorator.swift` and `LegalViewControllersProvider.swift`. this webView configuration by default follows a redirection on a click. This can somehow be used for phishing after taking the user into the malicious website through several clicks.

Any third-party user is unable to add their malicious link to www.flowcrypt.com. This became possible because there is a link to github.com under > Settings > Legal > Sources tab. And as we all know, this is now a bit different because controllable links can be added in various places in Github to redirect a user (can be used for phishing).

Here I have the a quick demonstration (non-harmful, showcasing the redirect through github):

https://user-images.githubusercontent.com/46025304/137302797-9b64011c-3c6d-451e-a96d-c82e3940e8e7.mov

Suggested improvement: 
I honestly haven't tried coding in swift but I think it can be accomplished by preventing/overriding a redirect? Similar to android webView wherein the webView following redirect can be disabled. 

Also If I remember it correctly, webView in the android version was disabled through configuration. If it wasn't used really much, maybe we could disable it here as well? This will prevent ios webView be affected by cross-site scripting. 

Apology for my bad english grammar.

Reference: 
https://newbedev.com/capture-redirect-url-in-wkwebview-in-ios
https://stackoverflow.com/questions/33828064/ios-web-view-javascript-disable

**Comment by tomholub** [comment]
Instead of 4 tabs that show webviews, we could have 4 menu items. Clicking each of them would open the link in a browser app instead of opening a webview.
