### ISSUE TITLE
appium login debugging

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#694]
I tried to run Appium tests, but it failed on `GmailLogin` tests with such error
```
[iPhone 12 iOS 15.0 #0-0] 1) LOGIN:  user is able to login via gmail
[iPhone 12 iOS 15.0 #0-0] Error: Can't call click on element with selector "~Enter your password" because element wasn't found
[iPhone 12 iOS 15.0 #0-0] Error: Can't call click on element with selector "~Enter your password" because element wasn't found
```

And here is screenshot of login screen, probably we need to click on "Next" button here

![Simulator Screen Shot - iPhone 12 - 2021-10-18 at 09 34 07](https://user-images.githubusercontent.com/1062093/137681690-8ae5ec54-f00e-4d1b-8670-c8e77482543b.png)

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-ios/issues/692#issuecomment-945414446_

**Comment by fcvakintos** [comment]
@tomholub try with https://github.com/FlowCrypt/flowcrypt-ios/tree/hotfix/appium and let me know if helped
