### ISSUE TITLE
Decryption error reasons that should be handled

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#704]
Description:
the ios version currently throws a generic alert box when the message can't be decrypted that says:
"Could not open message".

<img src=https://user-images.githubusercontent.com/46025304/136903672-3dc2bdf4-1f54-4079-bb43-9be80166b0cf.png>

There are many reasons that cause the decryption error of an encrypted message needs to be handled. 
Here are some of them:

1. Current key cannot open the message - often happens when the user is using the wrong private key or the sender uses an old public key to encrypt the message. 
<img width="330" alt="wrong key" src="https://user-images.githubusercontent.com/46025304/137849774-7582909c-1225-48a7-8b33-343154e55fca.png">
2. Missing MDC integrity checks
<img width="330" alt="no_mdc_error" src="https://user-images.githubusercontent.com/46025304/137849846-72f8cbe6-beac-459b-9f3e-10282b64c0e3.png">
3. Modified MDC hash.
<img width="330" alt="modified_mdc" src="https://user-images.githubusercontent.com/46025304/137849913-8142fc3c-25f8-47be-a6a8-4f56bd2020e2.png">
4. Message with the wrong checksum.
<img width="330" alt="wrong checksum" src="https://user-images.githubusercontent.com/46025304/137849993-71783eac-80fc-4b30-a443-cde787051de4.png">
5. Unexpected end-of-steam (partially/incomplete PGP message).
<img width="330" alt="unexpected end-of-steam" src="https://user-images.githubusercontent.com/46025304/137850084-81d2b00e-b69a-46de-be21-266c41b55923.png">
6. Check if for a bogus PGP message that starts with `-----BEGIN PGP MESSAGE -----`.
<img src=https://user-images.githubusercontent.com/46025304/136903672-3dc2bdf4-1f54-4079-bb43-9be80166b0cf.png>

Reference:
can be found under the "decrypt error" label
https://gpgtools.tenderapp.com/kb/faq/modification-detection-code-mdc-errors

**Comment by tomholub** [comment]
@martgil please retest. Does it look better now?

**Comment by martgil** [comment]
@tomholub, I have retested the latest master branch and there is only one that is not working properly at the moment.

This message has no description at all, where it should be flagged as NO_MDC - Missing integrity checks 
![263035028_427045735587244_8435958667037311091_n](https://user-images.githubusercontent.com/46025304/144381257-582a2492-82c4-400d-a715-5bd93a199219.png)

Other than that, we can confirm that the decrypt errors are defined respectively.

MDC hash mismatch error
![262386646_2261232780842655_145907191713791408_n](https://user-images.githubusercontent.com/46025304/144381203-3099bd41-2d0c-4b8b-adb7-ad7066fb8c01.png)

Key mismatch error
![262501111_613773743095584_5469301273504672701_n](https://user-images.githubusercontent.com/46025304/144381217-7ce7ec72-c7fa-4168-93e8-54854e002e39.png)

Invalid pgp message starting with `-----BEGIN PGP MESSAGE-----`
![image](https://user-images.githubusercontent.com/46025304/144383105-e3214885-67c7-4391-aac4-b34f4ca889d6.png)

Unexpected end of stream error
![262985293_231467232432894_4356978699489178473_n](https://user-images.githubusercontent.com/46025304/144381230-da00a477-d541-4775-afcd-23fa5951ded5.png)

wrong checksum error
![262990483_749881079301578_2097267183349993823_n](https://user-images.githubusercontent.com/46025304/144381250-2fd2678f-be8f-49da-897f-ad3a750714af.png)

**Comment by martgil** [comment]
Hi @tomholub,

I just noticed that first key mismatch was actually an error for a public key mismatch (I think)

In case you are wondering, here is what it looks like for mismatch (private key)
![image](https://user-images.githubusercontent.com/46025304/144388763-ee7a0f12-ed11-441b-b475-754b3ef210fa.png)

**Comment by tomholub** [comment]
Great - thank you. I've filed two issues from these.
