### ISSUE TITLE
Infinity spinner on Inbox screen after login with e2e.enterprise.test@flowcrypt.com 

### ISSUE THREAD

**Issue by fcvakintos** [FlowCrypt/flowcrypt-ios#706]
Steps:

1. Login with gmail using  e2e.enterprise.test@flowcrypt.com 
2. Set pass phrase
3. Observe Inbox screen

Actual: Infinity spinner appears and inbox messages are not displayed 
Expected: Inbox messages should be displayed
<img width="402" alt="Screenshot 2021-10-19 at 13 36 56" src="https://user-images.githubusercontent.com/91205853/137893384-2eb8f534-baa7-4b2b-aa8d-1f8080ab14ff.png">

Notes: Tried with another user and get 403 error
<img width="420" alt="Screenshot 2021-10-19 at 13 41 32" src="https://user-images.githubusercontent.com/91205853/137894221-f654bedb-8c38-4c2b-bc2d-c1d11cebbbbb.png">

**Comment by sosnovsky** [comment]
I think infinity spinner is shown because of https://github.com/FlowCrypt/flowcrypt-ios/issues/703
