### ISSUE TITLE
[WKD mock needed] write UI test for updating keys from WKD

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#711]
Works well. I tested the following scenario:
1) loaded demo@flowcrypt.com in compose
2) checked Contacts in app
3) updated EKM to change expiration of the key
4) loaded demo@flowcrypt.com in compose
5) checked contacts - correctly showed new expiration :+1: 
6) went to EKM to add one more key to demo@flowcrypt.com user
7) went to compose again and added demo@flowcrypt.com
8) went to contacts - now showing two keys for demo@flowcrypt.com :+1: 

We'll write a UI test for this later. For the UI test to be viable, the WKD has to be mocked.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/710#issuecomment-946957052_

**Comment by tomholub** [comment]
I suppose you'll need the WKD mocks prepared in advance to work on this, so I'm un-assigning.

**Comment by tomholub** [comment]
I suppose we already have a WKD mock? If not, it can be brought from browser extension tests. This is a worthwhile test to write.

**Comment by ioanmo226** [comment]
@tomholub I believe you meant `updated WKD` instead of `updated EKM`?

> 3. updated EKM to change expiration of the key
> 4. loaded [demo@flowcrypt.com](mailto:demo@flowcrypt.com) in compose

**Comment by sosnovsky** [comment]
Tom meant that he used EKM to update key expiration, as WKD is used only for serving public keys, while EKM performs all actions with keys.

But for test we need to just mock WKD response - it should have different key expiration on the second request.

**Comment by ioanmo226** [comment]
Aha, got it
