### ISSUE TITLE
color recipient bubble based on public key status

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#712]
For this evaluation, we will use the first public key in `RecipientWithPubKeys`. In a separate issue I'm about to file, we'll do ordering on these keys to make sure the first key is the most appropriate, but for now, we just blindly choose the first, to use as a base for coloring the recipient.

Here is the logic, based on that chosen key:
 - valid pubkey: green (RecipientStatus.HAS_PGP)
 - expired pubkey: orange `c27e23` (RecipientStatus.EXPIRED)
 - revoked pubkey: red `d14836` (RecipientStatus.REVOKED)
 - no pubkey: gray (RecipientStatus.NO_PGP)
 - email not valid: red (RecipientStatus.WRONG)
 - could not look up due to error: gray with red border (RecipientStatus.ERROR)

**Comment by sosnovsky** [comment]
@tomholub do we need capitalized statuses (`RecipientStatus.EXPIRED`) for similar names across platforms?
Or we can use more common for iOS code lowercase like `RecipientStatus.expired`?
