### ISSUE TITLE
[UX] Add 3 dots button for gmail thread message

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-ios#723]
or add similar 3 dots button which will show popup with options to choose option(mark as unread, delete message, archive) for  selected message. And buttons on top will acts on whole threads

_Originally posted by @Kharchevskyi in https://github.com/FlowCrypt/flowcrypt-ios/issues/608#issuecomment-948845791_

**Comment by tomholub** [comment]
closing as a dupplicate the top icons that act on whole thread are already present, three dots will be added in PR #1066 and Gmail app doesn't have a way to modify individual messages anyway.

**Comment by tomholub** [comment]
There's still three dots that act on whole thread (in Gmail app) but we don't need any of that functionality yet.
