### ISSUE TITLE
missing orientations for iPad, missing icons?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#724]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/6306961/138333447-5ad4e692-7431-41a2-bb40-78008428e983.png">

**Comment by tomholub** [comment]
<img width="200" alt="image" src="https://user-images.githubusercontent.com/6306961/141155304-06b04587-ff00-47f0-9f26-5508c29afc64.png">

Could try to re-submit it without multitasking support

**Comment by tomholub** [comment]
iPad turns out to be very important for our customer. Could you please check that all icons are available - even the ones for iPad. If not, please update the icons script in Scripts and re-generate them.

Then please check the `iPad` checkbox so that it gets build next time.

For the orientations and multi-tasking, I guess we could enable them (without necessarily fixing any ui issues, since there is #457

**Comment by ivan-ushakov** [comment]
@tomholub 
Here is how multitasking looks like:

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-11-22 at 18 52 09](https://user-images.githubusercontent.com/1408366/142892806-c3ff1cc6-62a3-456c-bd9b-911b2a78b58e.png)

**Comment by tomholub** [comment]
That looks good. At least on that screen :-)
