### ISSUE TITLE
testing that Attester search is disabled on some domains

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#736]
test that attester search is disabled for some domains + test that WKD is used for looking up public keys

details tbd

**Comment by tomholub** [comment]
For this, will need a way to mock FES responses. Similar to #711 - need our own FES instance for UI tests and need the app to listen to it. I suppose it would be easier to start with FES since the API is simple and obvious.

**Comment by tomholub** [comment]
After #1158 lands, this will be actionable.

Relevant documentation https://flowcrypt.com/docs/business/org-rules.html

Test case 1: `can find email on attester`
1) set FES mock clientConfiguration to `{flags: ["NO_PRV_CREATE", "NO_PRV_BACKUP", "NO_ATTESTER_SUBMIT", "PRV_AUTOIMPORT_OR_AUTOGEN", "FORBID_STORING_PASS_PHRASE"], key_manager_url: "https://ekm.flowcrypt.com"}` and start mock
2) search `flowcrypt.compatibility@gmail.com` recipient
3) it should find a public key (green)

Test case 2: `cannot find email on attester with disallow_attester_search_for_domains=*`
1) set FES mock clientConfiguration to `{flags: ["NO_PRV_CREATE", "NO_PRV_BACKUP", "NO_ATTESTER_SUBMIT", "PRV_AUTOIMPORT_OR_AUTOGEN", "FORBID_STORING_PASS_PHRASE"], key_manager_url: "https://ekm.flowcrypt.com", disallow_attester_search_for_domains: ["*"]}` and start mock
2) search `flowcrypt.compatibility@gmail.com` recipient
3) it should NOT find any result

Test case 3:`respects disallow_attester_search_for_domains on a per-domain basis`
1) set FES mock clientConfiguration to `{flags: ["NO_PRV_CREATE", "NO_PRV_BACKUP", "NO_ATTESTER_SUBMIT", "PRV_AUTOIMPORT_OR_AUTOGEN", "FORBID_STORING_PASS_PHRASE"], key_manager_url: "https://ekm.flowcrypt.com", disallow_attester_search_for_domains: ["gmail.com"]}` and start mock
2) search `flowcrypt.compatibility@gmail.com` recipient
3) it should NOT find any result
4) search `flowcrypt.compatibility@outlook.com` recipient
5) it should find a result

**Comment by fcvakintos** [comment]
@tomholub what is the attester mock?
can you share example how it calls?

**Comment by tomholub** [comment]
> @tomholub what is the attester mock?

Mock API of the Attester service. https://flowcrypt.com/attester/

>  can you share example how it calls?

You configure it the same as fes mock, except in addition to `fesConfig` you also set `attesterConfig`. The config objects have TypeScript types on them, and will guide you.

**Comment by fcvakintos** [comment]
@tomholub 
is it ok?
`    mockApi.attesterConfig = {servedPubkeys: {'attester@disabled.test': attesterPublicKeySamples.valid, attester@enabled.test': attesterPublicKeySamples.valid}};
`

**Comment by tomholub** [comment]
For test case 3, yes.

**Comment by fcvakintos** [comment]
we cant check color

**Comment by tomholub** [comment]
Ok, then we need updated accessibility identifiers to include the color for the recipient bubbles.

`to1orange` - first recipient has orange color (or `to1green` - first recipient has green color)
`to2red` - second recipient has red color

And so on.

**Comment by fcvakintos** [comment]
@tomholub it will be great

**Comment by fcvakintos** [comment]
i will create new method like "checkRecipientBadgeColor"

**Comment by tomholub** [comment]
Let's do `checkRecipientBadge` which will take 3 arguments: expected index, expected color, expected text (email).
