### ISSUE TITLE
PubKey type should have emails and uids type on it

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#812]
```swift
struct PubKey {
    let armored: String
    /// will be provided later
    let lastSig: Date?
    /// the date when key was retrieved from a public key server, or nil
    let lastChecked: Date?
    /// expiration date
    let expiresOn: Date?
    /// all key longids
    let longids: [String]
    /// all key fingerprints
    let fingerprints: [String]
    /// key created date
    let created: Date?
    /// key algo
    let algo: KeyAlgo?
    /// is key revoked
    let isRevoked: Bool
}
```

When parsing a key, the pgp user ids are available, and so are pgp user id emails once parsed. These should be included in this type.

Then all usages of `armored` should be investigated, to see if it's being used solely for parsing out the emails. Such usages should be replaced directly with the newly added property.

**Comment by sosnovsky** [comment]
@tomholub I added user emails to `PubKey` in https://github.com/FlowCrypt/flowcrypt-ios/commit/0b99faa62e7258513cb8c0b5deaef5b84db05546, but haven't found any usage of `armored` for parsing emails. Usually we already have recipient email and `armored` is used for parsing `KeyDetails` data, for example:
1️⃣ https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Functionality/Services/Compose%20Message%20Service/ComposeMessageService.swift#L121
2️⃣ https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Functionality/Services/Local%20Pub%20Key%20Services/LocalContactsProvider.swift#L117

**Comment by tomholub** [comment]
Thanks. After your changes merge, I'll have another look so see if it can be streamlined.
