### ISSUE TITLE
pass phrase not remembered when sending email

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#819]
> Hi Tom,
> 
> When I initially set up my FlowCrypt on my iPhone and
> iPad I set the password to be saved temporarily. Everytime
> I encrypt or decrypt a message I''m required to reenter my
> password. I thought that setting the password to temporary
> would be per session and when I quit FlowCrypt IOS the
> password would then be deleted.
> 
> Thanks,

my response

> thanks for the feedback! You're right - the pass phrase gets remembered when you enter it to view an encrypted message, but it doesn't get remembered when you enter it to send a message. That's a bug - thank you for reporting it. We'll get it fixed.

**Comment by tomholub** [comment]
Still seeing a problem on 0.3.2 - will add details

**Comment by ekievsky** [comment]
I don't see that issue. If you entered once a passphrase, its saved.
what I am missing?

**Comment by tomholub** [comment]
I'm not sure what the detail of the problem was anymore - but I've rewritten it to be more alike to what we do on other platforms, and will retest once I'm done.
