### ISSUE TITLE
crash/assertionFailure when typing recipient

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#832]
I did roughly this:
1) entered `something@hel.com` which failed looking up (red color)
2) clicked reload icon that showed
3) tapped the recipient and removed it
4) started typing another recipient. After two letters, got a crash

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/6306961/139318680-ce00bf27-b7f4-40fd-82f2-9d26f048a07d.png">

**Comment by ivan-ushakov** [comment]
This happens because `evaluate(recipient: ComposeMessageRecipient)` is still working and we removed recipient from list. When we get response and invoke `handleEvaluation()` we get that assert.

One of possible solutions could be just ignore that update if we can not find recipient.
