### ISSUE TITLE
request time out should print shorter error + show length of time it took

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#836]
```
"ℹ️[WkdApi] Failed to load https://openpgpkey.flowcrypt.com/.well-known/openpgpkey/flowcrypt.com/policy with error HttpErr(status: -1, data: nil, error: Optional(Error Domain=NSURLErrorDomain Code=-1001 \"The request timed out.\" UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x2829dc480 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 \"(null)\" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <BE848CCC-6001-46D4-BFD6-0327B00C4C6A>.<9>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"LocalDataTask <BE848CCC-6001-46D4-BFD6-0327B00C4C6A>.<9>\"\n), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://openpgpkey.flowcrypt.com/.well-known/openpgpkey/flowcrypt.com/policy, NSErrorFailingURLKey=https://openpgpkey.flowcrypt.com/.well-known/openpgpkey/flowcrypt.com/policy, _kCFStreamErrorDomainKey=4}))"
```

should just be

```
[URLSession] URLSession.asyncCall status:-1001 "The request timed out." ms:0.485 ms GET https://openpgpkey.flowcrypt.com/.well-known/openpgpkey/flowcrypt.com/policy, headers: [:] 
```

Similar to successful calls. In particular interested in the time it took as measured by our own wall clock, as I think I got a much longer than 4 seconds timeout.

**Comment by ivan-ushakov** [comment]
@tomholub 
Do you want this fix only for `WkdApi`?

**Comment by ivan-ushakov** [comment]
Also this error is just wrapped in `HttpErr` like we do for all `URLSession` errors. Do you want to have special handling for timeout error? I just don't understand how we could do this: we throw `HttpErr` and we don't know how it will be handled on upper level so all we could do here is just add that message to log.

**Comment by tomholub** [comment]
I'd like to fix it for all timeout situations. Logging of all http requests should be consistent regardless of api

> Also this error is just wrapped in HttpErr like we do for all URLSession errors. Do you want to have special handling for timeout error? I just don't understand how we could do this: we throw HttpErr and we don't know how it will be handled on upper level so all we could do here is just add that message to log.

I guess you could:
 -  log first in a controlled manner (for all http requests)
 - then make sure on upper level to handle without logging (for this WKD situation)
