### ISSUE TITLE
[to triage] I should be able to switch input while recipient is loading

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#837]
reproduce

1) enter recipient on a slow connection, wait for it to slowly fetch. Or try some recipient that won't load like `nobody@there.com`
2) while recipient has a spinner, try to switch to subject to start typing subject

actual: the app doesn't recognize my taps

expected: I should be able to swtich to subject/body and start typing my message while recipient is still loading

maybe the main thread is blocked while recipient is loading, or there is some other issue

**Comment by ivan-ushakov** [comment]
@tomholub 
Are you testing this on device or simulator? On simulator it works while recipient has spinner.

**Comment by tomholub** [comment]
It was on a device - 12 mini

**Comment by ivan-ushakov** [comment]
Not in progress because I can not reproduce it in my environment

**Comment by tomholub** [comment]
Got it. Later I'll see if I can reproduce it again.

**Comment by tomholub** [comment]
@Kharchevskyi please see if you can reproduce. If not, please close.

**Comment by ioanmo226** [comment]
@tomholub I also can't reproduce this issue

**Comment by tomholub** [comment]
ok
