### ISSUE TITLE
use login hint for second sign-in if we already know the user email

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#840]
It can be improved further: on the second sign-in attempt, supply `login hint` into the google sign-in request. That way, I don't have to choose my email again, instead my email will be pre-chosen based on the first sign-in.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/663#issuecomment-954246152_

**Comment by tomholub** [comment]
Follow browser extension behavior. To understand this issue:

1) go to accounts.google.com on your account -> 3rd party apps -> flowcrypt ios -> revoke
2) login on ios app with that account, but don't tick Gmail permission during the grant screen
3) you will be prompted to login / grant again

current behavior: the user has to select their email account address again, especially if you are logged into more than one account

expected behavior: since user already signed in once (even though without granting permission), we should already know user email. The second login prompt should use that email address in a `login_hint` so that user doens't have to choose their email address again.

The very same thing applies when user then goes to compose screen and wants to grant contacts permission - `login_hint` should always be used there since user is already logged in.

**Comment by ioanmo226** [comment]
@tomholub I agree that we need to provide `login_hint` in compose screen for grant contacts permission.

But for login screen, let's say user logged in with `a@gmail.com` google account(without ticking Gmail permission during the grant screen)
If we pass login_hint as `a@gmail.com` in this case, there will be no way for user to log out this `a@gmail.com` account.
Please check below screenshot.
I think we should not pass `login_hint` for login screen.

![image](https://user-images.githubusercontent.com/77344191/159523344-6935a811-b157-45c3-acdc-7a85718b4bae.png)

**Comment by ioanmo226** [comment]
@tomholub

**Comment by ioanmo226** [comment]
If user taps `Cancel` it will return to login screen and when user taps `continue with gmail`, above screen will appear again.
So IMHO it's better we should not set `login_hint` for login screen.

**Comment by tomholub** [comment]
Ok, for now, let's only add login_hint on the contacts prompt. Let's leave this issue open though. I'd like to discuss the login flow again sometime later.

**Comment by ioanmo226** [comment]
OK
