### ISSUE TITLE
crash feedback version 0.3.2

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#849]
[testflight_feedback 032.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/7444601/testflight_feedback.032.zip)

**Comment by ivan-ushakov** [comment]
Crash happens here:
```
@objc func callJsCb(_ timer: Timer) {
    let callback = (timer.userInfo as! JSValue)
    callback.call(withArguments: nil)
    // todo - remove from timers by uuid, could cause possible memory leak
}
```
No ideas yet

**Comment by tomholub** [comment]
Does `Thread 0` mean the main thread? Or not necessarily?

**Comment by ivan-ushakov** [comment]
> Does `Thread 0` mean the main thread? Or not necessarily?

Yes, main thread

**Comment by ivan-ushakov** [comment]
So maybe this is wrong to lock on main thread and some kind of assert happens

**Comment by tomholub** [comment]
Is that something we do or something that JavaScriptCore does? I don't think it's us.

Unless we can run everything related to JavaScriptCore always on non-main thread? A dedicated one?

**Comment by ivan-ushakov** [comment]
Lock happens inside `JavaScriptCore` but maybe my assumption about lock on main thread is wrong. I need to investigate this.

**Comment by tomholub** [comment]
I think this could have been solved by synchronizing the calls. We'll see.
