### ISSUE TITLE
cannot find recipient public key when reply

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#851]
when I write a new email to @sosnovsky then it finds public key. Saves it in contacts.

When I reply to @sosnovsky it cannot find it (gray). Even though already in contacts.

**Comment by tomholub** [comment]
See if you can reproduce

**Comment by sosnovsky** [comment]
I can send both (new emails and replies to you), but when I go to `Sent` section and try to open sent mail - "No matched key found" error appears.
And I can't read our emails with browser extension - I enter the same passphrase as on iOS app, but it doesn't accepted.

**Comment by tomholub** [comment]
My issue above, as well as your first issue could be related to https://github.com/FlowCrypt/flowcrypt-ios/issues/852

>  And I can't read our emails with browser extension - I enter the same passphrase as on iOS app, but it doesn't accepted.

On enterprise installations (like the one on flowcrypt.com, and also some of our customers) the client fetches decrypted private keys from EKM during setup. Then the user chooses their pass phrase and encrypts the received keys locally.

That means you can have a different pass phrase for each client. That's what you probably have, but have forgotten that you've set up the one on browser extension different than the iOS app.

You can uninstall/reinstall the browser extension plugin, and choose the same passphrase as ios this time. That will make it work going forward.

**Comment by sosnovsky** [comment]
Reinstalling browser extension helped me - now I can read mail there, but still seeing key errors on my older replies from iOS app. But it's probably #852
