### ISSUE TITLE
crash when showing request time out

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#864]
I was browsing the inbox and moving in/out of messages (I think) when I saw:

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/6306961/139559030-278cb465-0056-43eb-be94-05781e407310.png">

<img width="315" alt="image" src="https://user-images.githubusercontent.com/6306961/139559068-ce07f087-9e56-4ce8-aafa-6fabfa21e558.png">

**Comment by ivan-ushakov** [comment]
Looks like problem happens here:
```
func msgListUpdateReadFlag(message: Message, at index: Int) {
    messages[index] = message
    DispatchQueue.main.asyncAfter(deadline: .now() + 0.4) { [weak self] in
        guard let self = self else { return }
        self.tableNode.reloadRows(at: [IndexPath(row: index, section: 0)], with: .fade)
    }
}
```
because we capture `index` inside closure, but at the moment we run closure it is possible that `messages` was changed and captured `index` is not actual.
