### ISSUE TITLE
ComposeMessageService.getDraft seems to do nothing

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#868]
Todo - file an issue to discuss this

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/854#r739864071_

**Comment by tomholub** [comment]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/6306961/139600752-4bc40e7b-4673-4523-8bb3-7f6e3ba226df.png">

**Comment by ekievsky** [comment]
this was done to be used to fetch draft by me, but after all explorations and investigations looks unneeded so we can remove this code.
