### ISSUE TITLE
render recipients instead of sender in list of drafts

### ISSUE THREAD

**Issue by fcvakintos** [FlowCrypt/flowcrypt-ios#873]
**Steps:**

1. Login as "e2e.enterprise.test@flowcrypt.com"
2. Set compose email with Recipient email('dmitry@flowcrypt.com')
2. Open Drafts screen
3. Observe screen

**Actual:** Recipient email is "e2e.enterprise.test@flowcrypt.com"
**Expected:** Recipient email should be "dmitry@flowcrypt.com"

**Notes:** Incorrect email is displayed opening draft too

https://user-images.githubusercontent.com/91205853/139641102-842eb1e3-b9d1-40ac-a55e-1f179164648e.mp4

**Comment by tomholub** [comment]
Thank you - drafts functionality is still rough. This can later turn into a test case 👍

**Comment by tomholub** [comment]
Should be done similarly to how inbox threads are rendered.

Let's say I make a draft `to:joe@example.com` - the item on the drafts screen should show `joe draft` where the `draft` is red.

Let's say I make a draft `to:joe@example.com,bill@example.com` and `cc:jane@example.com` then the item on the drafts screen should show `joe,bill,jane draft` where `draft` is red.

Currently it just shows sender's email.

**Comment by tomholub** [comment]
can be fixed without having to re-enable saving drafts
