### ISSUE TITLE
separate Realm models and app logic models

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#877]
Since we use `async/await` now, it is hard to predict which thread will use `Realm` object and this leads to crashes

**Comment by tomholub** [comment]
Should realm be made an actor then, which would synchronize it? Or does it have to be strictly one thread for Realm (and can that be achieved with actors?)

**Comment by ivan-ushakov** [comment]
In Realm is it not possible to pass objects across threads so we have to convert object to app model

**Comment by tomholub** [comment]
I see.

**Comment by tomholub** [comment]
First, we should rename all realm objects to end with `RealmObject`, eg `PrivateKeyRealmObject`. That will make them stand out.

**Comment by tomholub** [comment]
Btw I keep getting the fatal error on startup caused by Realm about once a week. I hope, after we refactor Realm and have all actions synchronized (maybe on single theread), it will go away. Else we'll have to debug it further.

![image](https://user-images.githubusercontent.com/6306961/141736856-bfb921a2-9097-4325-81c5-8805ccf931be.png)

**Comment by tomholub** [comment]
@ivan-ushakov I'm thinking whether I should wait for this issue to merge before doing 0.5.0 release, or move it to the release after that. Either is fine with me. Approximately how long do you think this may take?

**Comment by ivan-ushakov** [comment]
> @ivan-ushakov I'm thinking whether I should wait for this issue to merge before doing 0.5.0 release, or move it to the release after that. Either is fine with me. Approximately how long do you think this may take?

I hope to have something working today. If no - feel free to do release
