### ISSUE TITLE
tests that need many cores to reproduce issues - how to run

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#880]
Is there a way to run this code on simulator that actually uses many OS threads for the simulator?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/854#discussion_r739864405_

The test reproduces issues on real device but not simulator.

**Comment by tomholub** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/6306961/139683955-c8e57d86-be09-4cfe-a9cd-a1a83858a397.png">

**Comment by ivan-ushakov** [comment]
@tomholub 
You did it right and test helped me to catch concurrency bug

**Comment by tomholub** [comment]
> @tomholub You did it right and test helped me to catch concurrency bug

But did you run it on real iPhone or on your mac/simulator?

**Comment by ivan-ushakov** [comment]
> But did you run the test on real iPhone or on your mac/simulator?

On simulator

**Comment by tomholub** [comment]
My mac has only two cores - `1.2 GHz Dual-Core Intel Core m3`, and doesn't reproduce such problem when I run it. I've added updated comment in PR review.
