### ISSUE TITLE
draft wrongly saved before any field is edited

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#887]
Drafts should only be saved if the user edited any fields in this session.

can branch from #854 or wait

**Comment by tomholub** [comment]
```
    private func shouldSaveDraft() -> Bool {
        // todo - that draft should only be saved when one of the fields are dirty (edited by user). Right now, a draft may get saved right after rendering compose (or reply), which is annoying.
        let newDraft = ComposedDraft(email: email, input: input, contextToSend: contextToSend)
        guard let oldDraft = composedLatestDraft else {
            composedLatestDraft = newDraft
            return true
        }
        let result = newDraft != oldDraft
        composedLatestDraft = newDraft
        return result
    }
```

**Comment by ekievsky** [comment]
Do we really need to fix this?

Actually, as far as I see, we don't have any error handling for drafts save. It is kinda background work that should just be done, and user cannot do something in case of error.

Also, even if user changes fields ( and they will be dirty ) we will get validation error ( because composed email that we can save should be valid ) during editing.

As for me - removing toast as error handle, will solve all this problems.
@tomholub  what do you think about it?

**Comment by tomholub** [comment]
> As for me - removing toast as error handle, will solve all this problems.

Not quite.

When I open a reply, a draft gets immeiately saved which is wrong. It should only get saved if I start changing the content.

When I open either compose or reply, I get asked for a pass phrase even though it's not needed yet (I didn't type anything)

**Comment by ekievsky** [comment]
> When I open a reply, a draft gets immeiately saved which is wrong. It should only get saved if I start changing the content.

agree, should be fixed

> When I open a reply, a draft gets immeiately saved which is wrong. It should only get saved if I start changing the content.

do you prefer being interrupted in process of typing? I thought it would be much more annoying than initial popup

**Comment by tomholub** [comment]
> >    When I open a reply, a draft gets immeiately saved which is wrong. It should only get saved if I start changing the content.
> do you prefer being interrupted in process of typing? I thought it would be much more annoying than initial popup

Good point, see here: https://github.com/FlowCrypt/flowcrypt-ios/issues/888

**Comment by ekievsky** [comment]
cool. so @tomholub this issue stays for: 
> When I open a reply, a draft gets immeiately saved which is wrong. It should only get saved if I start changing the content.

correct?

**Comment by tomholub** [comment]
yup

**Comment by tomholub** [comment]
@ekievsky please do this before continuing on the sharing extension

**Comment by tomholub** [comment]
This can still be addressed, as follows: temporarily enable drafts (from #975), then add your fix, then disable the drafts as before, and submit a PR.
