### ISSUE TITLE
appium: failed to run UI tests locally because of Russian Google interface

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#889]
I can not run tests locally because Google web page has Russian interface

![Simulator Screen Shot - appiumTest-9D7CBD23-6790-436E-926D-CA189C5C5DAC-iPhone X - 2021-11-02 at 10 13 54](https://user-images.githubusercontent.com/1408366/139802149-e10c68af-8b03-4715-9042-ccfbfc12a4ac.png)

Looks like Google determine locale somehow

**Comment by tomholub** [comment]
The appium tests normally recognize this and tap change language on the bottom left. Normally, that should be working.

As a work-around, before this gets fixed for you, you can tap change-language and change to us-english while the test is running. That should help the test continue running.

**Comment by tomholub** [comment]
@ivan-ushakov have you been able to run them smoothly since? Anything changed?

**Comment by ivan-ushakov** [comment]
> @ivan-ushakov have you been able to run them smoothly since? Anything changed?


It works fine after your advice

**Comment by tomholub** [comment]
Do you still have to manually interact with it each time? Or did it start working automatically after that?

**Comment by ivan-ushakov** [comment]
Yes, now it works automatically. Only first time it requires to manually change language

**Comment by tomholub** [comment]
I think I encountered the same one time, interestingly. Let's close for now.
