### ISSUE TITLE
HIDE_ARMOR_META client configuration support

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#897]
https://flowcrypt.com/docs/business/org-rules.html

**Comment by tomholub** [comment]
When above client configuration is present, please not show Comment and Version on outgoing pgp messages, or when armoring keys.

**Comment by tomholub** [comment]
I'd like to prioritize this issue after currently worked on issue, following a customer request.

**Comment by sosnovsky** [comment]
Okay, I think I'll be able to work on it today
