### ISSUE TITLE
preview (or directly open) attachments instead of downloading

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#902]
would it be difficult / possible to view attachments, if some app allows to open it, instead of downloading it first?

**Comment by ekievsky** [comment]
is it same as #436 ?

**Comment by tomholub** [comment]
This one is for opening messages from inbox. That one is for the compose screen.

**Comment by tomholub** [comment]
@ekievsky another change - please do this one first, before continuing on other issues.

It's important that the app opens the attachment itself, not sending it to another app.

The flow is like this
1) remove the download icon from attachments that I received. The whole attachment card should be tappable
2) when I tap the attachment, I will see a view attachment view
 - if the attachment is supported by webview (pdf, doc, docx, xls, xlsx, jpeg, ...) then open the attachment in webview and display it to user. Make sure it can be scrolled if it's long.
 - if the attachment is not supported by webview, show "No preview available"
3) there should be a `Download` text with the download icon next to it. The two together should be tappable. That will download the attachment to device as before.

See https://developer.apple.com/library/archive/qa/qa1630/_index.html

**Comment by tomholub** [comment]
But first please finalize this PR https://github.com/FlowCrypt/flowcrypt-ios/pull/942 per the review so it doesn't get stale. Thanks!

**Comment by ekievsky** [comment]
The app downloads the attachments when you open the email. So once you see the list of attachment they are downloaded already.

The rest is clear, will do

**Comment by ekievsky** [comment]
@tomholub should we open the attachment on received message view or on compose as well?

**Comment by tomholub** [comment]
wherever opening is already implemented. I think not implemented yet on compose view
