### ISSUE TITLE
see if messageSizeLimit is still useful / needed

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#908]
In another issue - figure out where this is still used, may not be relevant

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/657#discussion_r742653008_

**Comment by ivan-ushakov** [comment]
@tomholub 
We don't have this constant in `master` branch anymore. You could close this one

**Comment by tomholub** [comment]
@ivan-ushakov when this is the case, feel free to close the issue yourself - no need to ask me. Thanks!
