### ISSUE TITLE
database migration from 0.3.2 to 0.4.0? or revert schema

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#912]
I think I caused a database schema update (unintended) in #854 with the pass phrase object update. I'll review it and see if we need a migration or if I should revert that change.

**Comment by tomholub** [comment]
@ivan-ushakov if you still have time today, could you confirm I broke it? And what exactly did I do to break the database schema between the versions? (so I can be more careful next time)

**Comment by ivan-ushakov** [comment]
@tomholub 
I don't see any changes in Realm objects. You changed `PassPhrase`, but we don't persist it.

**Comment by tomholub** [comment]
Please try building https://github.com/FlowCrypt/flowcrypt-ios/commit/491a5e8de8f5a84a3d76cc577a687f4c668e7787 , set up the app and then build master. See if anything breaks. I just want to be sure, because I've had a realm-related error that went away after I deleted the app and reinstalled it, which made me suspicious.

**Comment by ivan-ushakov** [comment]
@tomholub 
I checked `491a5e8` and current branch. No crashes.

**Comment by tomholub** [comment]
excellent, thank you!
