### ISSUE TITLE
Wrong error message when sending email

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#918]
App shows such generic error message (on screenshot) instead of `ComposeMessageError` message:
```
One or more of your recipients are missing a public key (marked in gray).

Please ask them to share it with you, or ask them to also set up FlowCrypt.
```

![Simulator Screen Shot - iPhone 12 - 2021-11-04 at 17 11 24](https://user-images.githubusercontent.com/1062093/140342378-498ec5d4-ce9e-498f-98d3-bd50e46ed5a4.png)

**Comment by tomholub** [comment]
This situation needs to be tested with a UI test:

1) compose a message to someone that doesn't have any public key
2) send
3) observe that it shows the text that Roma quoted above

**Comment by tomholub** [comment]
I probably broke this in my async Core refactor #852 ?

**Comment by sosnovsky** [comment]
> I probably broke this in my async Core refactor #852 ?

Checking it now, maybe app receives another error type while expects `ComposeMessageError`, so can't parse real error message

**Comment by tomholub** [comment]
I exactly thought I improved that:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/6306961/140422321-2e0bb759-521e-4eda-9334-90783ccb3a3b.png">

**Comment by tomholub** [comment]
Ah! I must have changed it to `MessageValidationError` (which I thought was more appropriate) but didn't adjust the handler. My bad. Could you update the handler to also understand that one?

**Comment by tomholub** [comment]
Later a test in #919 will prevent this in the future.

**Comment by sosnovsky** [comment]
I fixed this issue in https://github.com/FlowCrypt/flowcrypt-ios/commit/f061845824042db153f8196d5aac6dec8126c075, but noticed the same one for draft saving error message, will check it tomorrow

![Simulator Screen Shot - iPhone 12 - 2021-11-04 at 23 59 25](https://user-images.githubusercontent.com/1062093/140426346-ffdc0108-575c-4751-9a9f-81746f3786f5.png)
