### ISSUE TITLE
PR review feedback for threads - fix download loader, n. of threads render

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#920]
Thank you Ivan for getting it up to master!

I'll merge it but there will still be some fixes to do after:
 - [ ] download percentage is not getting rendered anymore - I think
 - [ ] with a very long subject, the number of messages in thread gets hidden because it's at the end

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/657#pullrequestreview-798021944_

**Comment by ivan-ushakov** [comment]
@tomholub

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-05 at 12 47 02](https://user-images.githubusercontent.com/1408366/140491505-2bb91f4a-7a88-45ac-871a-5fcf6b53756e.png)

We keep number of messages in thread at sender's level

**Comment by ivan-ushakov** [comment]
It is still possible that number of people in thread is too big and in this case number of messages in thread will be hidden.  Like this:

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-05 at 12 56 36](https://user-images.githubusercontent.com/1408366/140492671-866ff5cf-c775-4afd-a092-086fb40ec24a.png)

It is possible to solve with independent label for this number.

**Comment by tomholub** [comment]
You're right - it's the senders that can get too long. Yes - independent label would be great. Thanks!

**Comment by ivan-ushakov** [comment]
@tomholub 
What do you think?

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-05 at 13 25 18](https://user-images.githubusercontent.com/1408366/140496394-ea0fead3-c988-4c13-9e14-f76d726d859f.png)
