### ISSUE TITLE
thread view of encrypted conversation - sometimes displays the same message over and over

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#923]
I had an encrypted conversation that had 5 back and forth emails in it.

The first email correctly showed the right contents.

But all of the other 4 emails contained just a quote of the first email and nothing else.

Can you see if you can reproduce this? Can compare to browser extension when wanting to know the right behavior.

**Comment by ivan-ushakov** [comment]
@tomholub 
Can not reproduce this one, but on the other hand I can reply only from Gmail now. Let's wait for reply function from the app

**Comment by tomholub** [comment]
This was actually #962 combined with #963 

I thought I was looking at a conversation, but it was just one message on top and 5 empty drafts that quoted the first message.
