### ISSUE TITLE
Private key error prompt can be dismissed and continue to send the message

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-ios#926]
Description:
A user can skip the private key prompt when replying to an encrypted message and proceed to send the message.

As the respondent shared, he has to click the "cancel" button to skip the private key prompt to proceed and send the message.

The respondent also mentioned that this happens occasionally in some of the other messages.
![image](https://user-images.githubusercontent.com/46025304/140483272-68920a7d-e25f-43dd-9e77-35d28bc136e1.png)

Reference:
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkjbQnGbxvxFDbpZtmlqXjlbW
https://mail.google.com/mail/u/2/#archive/FMfcgzGlkjWzVWSgKGJzpsQBJVlLhQCL

**Comment by tomholub** [comment]
Thank you for reporting this!

**Comment by tomholub** [comment]
@martgil could you please include exact steps to reproduce this?

**Comment by martgil** [comment]
Hello @tomholub - sorry for the late reply. The user confirms that it is now working properly. thanks!

reference:
https://mail.google.com/mail/u/6/#inbox/FMfcgzGlkjbQnGbxvxFDbpZtmlqXjlbW
