### ISSUE TITLE
Attachment is not displayed in encrypted email

### ISSUE THREAD

**Issue by fcvakintos** [FlowCrypt/flowcrypt-ios#929]
Steps:

1. Open email with attachment
2. Observe email

**Actual:** Attachment is not displayed
**Expected:**  Attachment should be displayed

**Comment by tomholub** [comment]
@fcvakintos could you please add the screenshot? Thanks!

**Comment by fcvakintos** [comment]
<img width="392" alt="Screenshot 2021-11-05 at 13 16 06" src="https://user-images.githubusercontent.com/91205853/140503310-8e120a98-d1ad-4299-b36c-5bc70db361ee.png">

**Comment by fcvakintos** [comment]
on old version it is displayed
<img width="910" alt="Screenshot 2021-11-05 at 13 24 09" src="https://user-images.githubusercontent.com/91205853/140503441-23ec46aa-d757-44a4-85c2-ea2bf45a99c1.png">

**Comment by tomholub** [comment]
Got it - thank you. The ui test from https://github.com/FlowCrypt/flowcrypt-ios/pull/911 would have prevented this.

@ivan-ushakov can you please look into re-enabling this functionality? It got lost in the gmail conversations PR.

**Comment by ivan-ushakov** [comment]
Looks like attachment support not implemented in `ThreadDetailsViewController` at all and since we use threads mail provider by default for Gmail, we don't have attachments now

**Comment by ivan-ushakov** [comment]
I could try to add `AttachmentNode` to current implementation and see what happens
