### ISSUE TITLE
expand/close icon is white on white background

### ISSUE THREAD

**Issue by ivan-ushakov** [FlowCrypt/flowcrypt-ios#940]
Minor UI issue but could confuse user:

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-06 at 20 28 57](https://user-images.githubusercontent.com/1408366/140618591-a91d01e2-9367-46f5-82c6-7e5f7dd59aae.png)

with red color:

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-06 at 20 30 52](https://user-images.githubusercontent.com/1408366/140618601-ba72888e-aca1-43b1-adb6-411853112a94.png)

**Comment by sosnovsky** [comment]
@tomholub I can work on this issue along with https://github.com/FlowCrypt/flowcrypt-ios/issues/936, as it's the same cell

**Comment by tomholub** [comment]
Ivan - well noticed. Roma - assigned. Thank you both!

**Comment by tomholub** [comment]
Btw this issue is not minor - it could be very confusing
