### ISSUE TITLE
use accessibility identifiers for appium tests?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#944]
Could you give these elements accessibility identifiers in the source code? Then here you can refer to them by the accessibility identifiers. This way, even the smallest change on that screen (adding an element that wasn't there before) would break these tests.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/943#discussion_r744549315_

**Comment by fcvakintos** [comment]
Need to update lot's of elements. Want to complete a few other tickets first

**Comment by tomholub** [comment]
Ok. It will be worthwhile to do this. Else the more tests we write without doing this, the more brittle the test may be overall to implementation changes that should normally not break tests.

**Comment by tomholub** [comment]
No need to do the selectors that use text, those are good.

But selectors like this really ought to use accessibility ids instead.

> `ADDED_RECIPIENT: '-ios class chain:**/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther' +
    '/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeTable' +
    '/XCUIElementTypeCell[1]/XCUIElementTypeOther/XCUIElementTypeCollectionView/XCUIElementTypeCell' +
    '/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeStaticText', //it works only with this selector`
