### ISSUE TITLE
remove expand icon when message expanded

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#952]
> Works well. Maybe we should move the reply icon a tiny bit further from the chevron icon? Seem like they are a bit too close together. For spacing, can follow the space between the header icons which are comfortably apart. (people with fat fingers etc)

Agree, looks quite close. I was also thinking about removing `expand` icon when message is expanded, so it'll be only `reply` button, as currently `expand` icon looks too repetitive, as for me. What do you think?

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-ios/issues/947#issuecomment-963527437_

**Comment by tomholub** [comment]
Agree. I'm setting it for later milestone. I think it will require even more design work - the individual messages in a thread should be somehow "compartmentalized" into their own boxes so it's visually more obvious what is being expanded or collapsed.

**Comment by ekievsky** [comment]
to clarify: 

as far as I understand, expand is working only in one direction - we can expand only, but cannot collapse?

![Simulator Screen Shot - iPhone 12 - 2021-11-18 at 22 41 28](https://user-images.githubusercontent.com/38130577/142493424-30391a95-951f-45d5-9698-f668485615cc.png)

so, in scope of this task:
- remove expand/collapse icon if message is expanded ( user wont be able to collapse it? double checking )

another part, about  
> "compartmentalized" into their own boxes

I think it would be done in scope of #921 

am I correct @tomholub ?

**Comment by tomholub** [comment]
I'm actually not too sure anymore. Sorry, I think this issue is a mistake.

**Comment by tomholub** [comment]
Reopening. I think I wanted something like this:
 - the chevron is only visible when message is collapsed, and is used to expand it
 - expanded messages can be collapsed again by tapping around their header area? (it think this is what Gmail app does - please confirm)
 - each message is visually separated from other messages, a bit similar to how gmail does it.

**Comment by ekievsky** [comment]
> each message is visually separated from other messages, a bit similar to how gmail does it.

clear.

> expanded messages can be collapsed again by tapping around their header area? (it think this is what Gmail app does - please confirm)

Gmail app is not using chevron as button, but only as visual representation of message state. it is visible when message is expanded and hidden when message is collapsed. We can make same behavior. The use full message for tap zone to expand/collapse.

please confirm if we want same behavior

**Comment by ekievsky** [comment]
in general, they have double expand/collapse ( you tap to expand to see message, and one more tap will open some other details of email)  but I think we will be good with single one.

**Comment by tomholub** [comment]
> @tomholub
> 
> > each message is visually separated from other messages, a bit similar to how gmail does it.
> 
> clear.
> 
> > expanded messages can be collapsed again by tapping around their header area? (it think this is what Gmail app does - please confirm)
> 
> Gmail app is not using chevron as button, but only as visual representation of message state. it is visible when message is expanded and hidden when message is collapsed. We can make same behavior. The use full message for tap zone to expand/collapse.
> 
> please confirm if we want same behavior

yes, I'd do the same

**Comment by tomholub** [comment]
> in general, they have double expand/collapse ( you tap to expand to see message, and one more tap will open some other details of email) but I think we will be good with single one.

should start with single as you say

**Comment by tomholub** [comment]
but first please finalize #1031

**Comment by ekievsky** [comment]
@tomholub sure. I am asking questions in multiple tasks to make them clarified before I start :)

thank you

**Comment by tomholub** [comment]
Assigning to Roma as he's working on related functionality.
