### ISSUE TITLE
reply all functionality

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#953]
currently, we have a reply button. should also add reply all, and differentiate the two.

**Comment by tomholub** [comment]
please follow Gmail: add reply-all under the menu for all messages in thread, and then add the three reply/reply-all/forward buttons on the very bottom. Thanks!

**Comment by sosnovsky** [comment]
I think this task should include #921 too, as currently users don't see when mail has multiple recipients.

Also Gmail app by default triggers `reply all`, and I didn't find way to reply only for message sender (only by removing other recipients). I think it's because `reply all` is used more often than just `reply`, maybe we should use `reply` button for `reply all` and add `Reply` option to message menu?

**Comment by tomholub** [comment]
Assigned that one. Looking into reply/reply all. For me, the default on Gmail app is reply-to-one-person.

I think in Gmail this is configurable.

**Comment by sosnovsky** [comment]
Interesting, I haven't changed any settings in Gmail app after installing, maybe they take `reply` settings from Google account. Okay, let's do `Reply all` in message menu, and `Reply to one` as button

**Comment by tomholub** [comment]
https://mail.google.com/mail/u/0/#settings/general

![image](https://user-images.githubusercontent.com/6306961/143444946-9ed6bd87-aafd-4912-a90e-4b26695a3c71.png)

But interestingly, after changing this (on desktop) it has no affect on the mobile app. Still the default is reply to one even if I reply to a conversation.

To be fair, I would expect the same as you - that default is reply all. On the other hand, our main customer seems to like reply-to-one as default (recently they submitted a bug to browser extension: https://github.com/FlowCrypt/flowcrypt-browser/issues/4077 )

On top of all of this, it defaults to reply-all for you and reply for me :shrug: 

Let's start with reply to one, based on customer feedback above. Then when we are wiser, we may adjust it.
