### ISSUE TITLE
all texts to be in separate strings files

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#956]
currently most are, but I think there were some alerts that still had hardcoded texts

we may need to do a language translation, this will help

**Comment by Kharchevskyi** [comment]
What do you think about using SwiftGen in the project?
This tool will automatically generate swfit type safe code for strings.

https://github.com/SwiftGen/SwiftGen
```
* Avoid any risk of typo when using a String
* Free auto-completion
* Avoid the risk of using a non-existing asset name
* All this will be ensured by the compiler and thus avoid the risk of crashing at runtime.
```

Besides that it would be easier during code review to make sure all strings are localized.
@sosnovsky

**Comment by sosnovsky** [comment]
`SwiftGen` looks good for me - we can start with using it for strings, and later add support for assets, colors etc
