### ISSUE TITLE
ui tests for thread rendering

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#959]
- test that date of last message in the thread is displayed on each inbox item
 - make sure that messages are ordered by this date in inbox, with threads that have the most recent message on top

**Comment by fcvakintos** [comment]
@tomholub is it correct?
email with date 22 Nov is displayed under email with date Nov 03, 2017
<img width="389" alt="Screenshot 2021-11-30 at 12 47 43" src="https://user-images.githubusercontent.com/91205853/144033968-332c8633-ba15-4172-97d7-f60446081d3a.png">
<img width="389" alt="Screenshot 2021-11-30 at 12 48 03" src="https://user-images.githubusercontent.com/91205853/144034048-3ad043b7-dfb4-4317-bad4-46d1089c7d49.png">

**Comment by tomholub** [comment]
Well noticed btw

**Comment by fcvakintos** [comment]
@tomholub login to e2e.enterprise.test@flowcrypt.com
and check inbox screen

**Comment by fcvakintos** [comment]
@tomholub check this pls
<img width="403" alt="Screenshot 2021-11-30 at 13 30 03" src="https://user-images.githubusercontent.com/91205853/144039725-2d2ff265-fd19-4504-a00c-97ef5920b1b1.png">

**Comment by tomholub** [comment]
Looks wrong indeed

**Comment by tomholub** [comment]
@fcvakintos in this issue you can at least check order of messages within a particular email thread, instead of the inbox where we're still looking into potentially fixing it.

**Comment by fcvakintos** [comment]
@tomholub can you confirm is it correct thread?
 I'm not sure to understand the task
 
<img width="433" alt="Screenshot 2022-02-04 at 10 52 05" src="https://user-images.githubusercontent.com/91205853/152499727-77fde7cb-72fe-4424-9d56-56a0231d1190.png">

**Comment by tomholub** [comment]
Yes, this is an example of one email thread. There are several messages in it. You want to make sure they start from oldest to newest, and that the `to` and `from` make it clear who sent each message to whom.

**Comment by fcvakintos** [comment]
ok, thanks

**Comment by fcvakintos** [comment]
@tomholub we need to add new accessibility id for thread messages
something like we did for recipients
who from devs can do this?

**Comment by fcvakintos** [comment]
and we need to add accessibility id for message body(text)
<img width="1269" alt="Screenshot 2022-02-08 at 12 25 59" src="https://user-images.githubusercontent.com/91205853/152968669-95673545-3fa0-42e8-9d65-d8e81b1754fb.png">

**Comment by tomholub** [comment]
please ask @Kharchevskyi for accessibility ids going forward

**Comment by fcvakintos** [comment]
@Kharchevskyi can you help me this ?

**Comment by Kharchevskyi** [comment]
Sure, will do

**Comment by tomholub** [comment]
Possible. You can test for either of the two values to be present.

**Comment by fcvakintos** [comment]
I added function for convert date to UTC time zone

**Comment by tomholub** [comment]
ok
