### ISSUE TITLE
localizable strings

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#96]
To make it easier to translate to other languages

Does iOS have any mechanism for keeping track of language snippets and translations?

**Comment by Kharchevskyi** [comment]
I will add Localization to app. 
You will have `localizable.string `file with all keys for _labels_
Which you will need to translate to supportable languages. 

There is not necessary to have all texts in one file.

**Comment by tomholub** [comment]
Ok, understood

**Comment by tomholub** [comment]
This would be somewhat for later - depending on the effort needed. None of our other apps were localized yet, and while we have some requests for it, it's not too many.
