### ISSUE TITLE
mark drafts in conversation with a red "draft" label

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#963]
Message in the red rectangle is draft, but it looks the same as other received or sent messages.
So for user it's not clear that this message is draft and wasn't sent yet.

![Simulator Screen Shot - iPhone 13 - 2021-11-09 at 13 13 46](https://user-images.githubusercontent.com/1062093/140914331-d9adb8f6-5eb4-4a22-8667-919f2f9060fc.png)

**Comment by tomholub** [comment]
agree, that needs to change

**Comment by tomholub** [comment]
I could literally just say "draft" in red color next to the time. That would be enough for this issue for now.

**Comment by tomholub** [comment]
@ekievsky please do this before continuing on the sharing extension. That one was a bigger issue than I thought.

**Comment by tomholub** [comment]
can be tested with drafts made in browser extension - creating drafts in iOS will remain disabled
