### ISSUE TITLE
App should use existing draft when creating new message in thread

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-ios#965]
New draft is created each time when I try to compose new message from thread screen.
App should check if there is existing draft for this thread and use it, instead of creating new one.

**Comment by tomholub** [comment]
This could be the same as #834 ?

**Comment by sosnovsky** [comment]
Yes, it looks similar to `opening from Drafts screen doesn't allow to edit text`, but I think we can leave this issue for second part - `use existing draft when composing new message on thread screen`, as currently new draft is created on each `reply` button tap.

**Comment by tomholub** [comment]
New draft creation should remain disabled even after this PR
