### ISSUE TITLE
frequency of draft save timer to 5 seconds, ensure it runs when tapping back

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#972]
We shouldn't actually be encrypting the draft every second. We should only be encrypting a draft if the content changed from last second to the next.

And even then, we should probably change it to check once in 5 seconds, and one last time when we tap the back icon. I'll file a separate issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/970#issuecomment-964360732_

**Comment by ivan-ushakov** [comment]
Maybe we don't need to encrypt draft until we leave compose screen?

**Comment by tomholub** [comment]
That's not ideal - maybe internet is available in the beginning but not at the end - it would be better to have at least something saved. But if we ensure to save the draft when leaving the screen, then we can do a higher timer, say 10 seconds.

**Comment by ivan-ushakov** [comment]
Well, since we have local DB, this should not be a problem. We could always restore draft from DB

**Comment by ivan-ushakov** [comment]
You are right, looks like we encrypt draw only when message text is changed. So if I type 100 symbols, I will have 100 encrypt calls

**Comment by tomholub** [comment]
Hopefully not? If you typed it in 10 seconds, then you should have 10 encrypt calls max.

**Comment by ivan-ushakov** [comment]
We have draft check each second:
```
@objc private func startTimer() {
    saveDraftTimer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true) { [weak self] _ in
        self?.saveDraftIfNeeded()
    }
    saveDraftTimer?.fire()
}
```

Inside this check we just compare new and old messages (not only text, but also subject and recipients). So if I type new symbol each second, this check will return true and encrypt new message

**Comment by tomholub** [comment]
Yes, that's it currently. In this issue it will be changed to once in 10 seconds, and on more run on back tap.

But first, I'll probably disable all draft functionality and do a release. It's giving us too much trouble.

**Comment by tomholub** [comment]
I've already done the 10 seconds. Left to do is to ensure it gets triggered when leaving view.

**Comment by tomholub** [comment]
Even after this PR, drafts should remain disabled.

**Comment by tomholub** [comment]
> I've already done 10 seconds. Left to do is to ensure it gets triggered when leaving view.

That was a year ago - let's check what the status is, and lower it to 5 if I've really done that.
