### ISSUE TITLE
ui test failing because waiting for pass phrase when it should be authenticating

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#973]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/6306961/140972747-26fadf1e-9464-40d9-a341-0851d9813290.png">

**Comment by fcvakintos** [comment]
Hm, I feel like it was issue on google side that user was not logged in

**Comment by tomholub** [comment]
If we assumed the user is already logged in, we would not need the env file with the password, right? :-)

We should evaluate the screen to see if it's asking for login password or not. Then if it's asking for it, supply it.
