### ISSUE TITLE
there are swift files which are not part of the project

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#990]
I just deleted some in #404 - what is the way to find the rest?

**Comment by sosnovsky** [comment]
There is a tool for finding unused Swift code - https://github.com/peripheryapp/periphery

**Comment by Kharchevskyi** [comment]
@tomholub Do we want to just remove unused code?
Or to add some build phase to detect unused code as well? 
any objections of using https://github.com/PaulTaykalo/swift-scripts instead?

@sosnovsky Also, out of curiosity why we are not using `Package.swift` manifest file for package dependencies? 
As far as I see  https://github.com/peripheryapp/periphery would not work without manifest file if it would be added as SP.

**Comment by tomholub** [comment]
I think once a year cleanup of unused code would be enough, don't necessarily need to script it. (notice the issue is assigned to Ivan atm)

**Comment by sosnovsky** [comment]
> @sosnovsky Also, out of curiosity why we are not using `Package.swift` manifest file for package dependencies? As far as I see https://github.com/peripheryapp/periphery would not work without manifest file if it would be added as SP.

`Package.swift` was mandatory in earlier versions of Xcode, now you can just add packages by the URL
