### ISSUE TITLE
key mismatch in ThreadDetailsViewController not rendered

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#991]
when tapping on the inbox item, it brings me to the thread and then right back to inbox. This gets logged:

```
"ℹ️[ThreadDetailsViewController] Start loading message"
"ℹ️[ThreadDetailsViewController] Error keyMismatch(9959 bytes)"
```

We'll need to render something sensible (into the message text, with red color), and a UI test for this too.

**Comment by tomholub** [comment]
To reproduce, please send an email from account A to account B, both unrelated to our e2e testing account. Then, manually copy the message content (the PGP block) from account B to our e2e testing account, and send it from e2e to e2e account in regular Gmail window (make sure to choose plain text mode). Give it an obvious subject like `encrypted message with keyMismatch`

<img width="623" alt="image" src="https://user-images.githubusercontent.com/6306961/141738574-6a5033e1-cb0c-4503-90d6-37720872cd92.png">

Then open that message in iOS app. It's supposed to render the key mismatch error inside the message, but instead it bumps me back to inbox.

Because this:

```
        case let .keyMismatch(rawMimeData):
            handleKeyMismatch(for: rawMimeData)
```

Is only in `MessageViewController` and missing in `ThreadDetailsViewController`. It's ok to duplicate it, because later in #994 we will remove `MessageViewController` anyway.

**Comment by tomholub** [comment]
Please then write a UI test, with the message that you put in the e2e account.

**Comment by tomholub** [comment]
Recommend to not start writing the test before I finish #1010

**Comment by ivan-ushakov** [comment]
@tomholub 
What kind of signature we use for this message? `error` or `bad`?

**Comment by ivan-ushakov** [comment]
@tomholub 

Here is how it looks with code from `MessageViewController`:

![Simulator Screen Shot - iPhone 11 Pro - 2021-11-18 at 19 39 47](https://user-images.githubusercontent.com/1408366/142458072-16bbe3c3-ce29-4254-a844-ff5e3e9ecb78.png)

**Comment by ivan-ushakov** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2021-11-18 at 19 40 39](https://user-images.githubusercontent.com/1408366/142458165-5d55a530-3212-4b23-88b4-d803de651572.png)
