### ISSUE TITLE
ui test for logging out

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#992]
In case we don't have any. The log-in test can be updated to also go to log out.

**Comment by fcvakintos** [comment]
@tomholub we already have test for this, in Login spec we have clickLogout method, and checking login page after logout
<img width="415" alt="Screenshot 2021-11-11 at 17 05 17" src="https://user-images.githubusercontent.com/91205853/141320761-972c2ae5-047d-4aee-9148-921090be7f8f.png">

**Comment by fcvakintos** [comment]
I think we can close this task

**Comment by tomholub** [comment]
very good - thanks
