### ISSUE TITLE
menu folder items unnecessarily capitalized + slow load each time

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#995]
(small) regression:
 - menu items (folders) now take visibly longer to load
 - it says `INBOX` instead of `Inbox` etc (had to adjust appium test for it)
Will file another issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/985#issuecomment-966301292_

**Comment by tomholub** [comment]
There used to be caching mechanism for the folder names showing in the menu (stored in local db?). There still probably is, but one of our refactors must have broken it. Need to investigate why the menu items are not cached, currently seem to load from API on each menu open.

**Comment by ioanmo226** [comment]
> There used to be caching mechanism for the folder names showing in the menu
Do you have any idea why force reloading folders every time user opens menu?

![image](https://user-images.githubusercontent.com/77344191/159867256-e7cebbd5-5ad4-46ba-8d0d-f758f155f896.png)
