### ISSUE TITLE
can use Google client library for userinfo call

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-ios#996]
Google library supports this request - https://github.com/google/google-api-objectivec-client-for-rest/blob/main/Source/GeneratedServices/Oauth2/GTLROauth2Query.m#L46

The only difference is that it uses `oauth2/v2/userinfo` instead of `oauth2/v3/userinfo`, but response looks similar.

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-ios/pull/985#discussion_r747482947_

**Comment by ivan-ushakov** [comment]
@tomholub May I start with `0.9.0: Post-EIS maintenance` tasks?

**Comment by tomholub** [comment]
thanks for checking - yes you can go ahead and work on these
